### PR TITLE
Use defaulted special member functions for View and ViewMapping

### PR DESCRIPTION
**Pull request by masterleinad**
Extracted from #3231.

### CODE REVIEW

**Review by jeffmiles63 — APPROVED** [review]
Looks Good

**Review by dalg24 — CHANGES_REQUESTED** [review]
Blocking until we get a rational for this change

**Comment by masterleinad** [comment]
It would be good to hear @nliber's reasoning for changing it in #3231 but I think it's a good idea regardless.

**Comment by dalg24** [comment]
Ping @nliber

**Review by nliber — COMMENTED** [review]
Working on making things trivially copyable for SYCL, which requires that these functions be defaulted instead of body which does the same thing.

**Review by dalg24 — COMMENTED** [review]
Please drop the `/*rhs*/` and make Nevin a co-author on the change

**Comment by masterleinad** [comment]
@dalg24 Here you go.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
