### PR TITLE
Define minimum compiler versions for C++20 support 

### PR DESCRIPTION
**Pull request by masterleinad**
We discussed in the meeting that we already want to define minimum compiler versions for C++20 support.

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]

**Comment by masterleinad** [comment]
The new error looks like
```bash
CMake Error at cmake/kokkos_compiler_id.cmake:198 (MESSAGE):
  Compiler not supported by Kokkos for C++17.  Required minimum compiler
  versions:

      Clang(CPU)          19.0.0
      Clang(CUDA)         10.0.0
      Clang(OpenMPTarget) 15.0.0
      GCC                 8.2.0
      Intel               19.0.5
      IntelLLVM(CPU)      2021.1.1
      IntelLLVM(SYCL)     2023.0.0
      NVCC                11.0.0
      HIPCC               5.2.0
      NVHPC/PGI           22.3
      MSVC                19.29
      XL/XLClang          not supported

  Compiler: Clang 18.1.5
```

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
The error log in https://github.com/kokkos/kokkos/pull/7128#issuecomment-2223058234 is clearly made up.  Would you please update it with what is currently proposed.

**Comment by dalg24** [comment]
Also is this ready or still a draft?

**Comment by masterleinad** [comment]
> The error log in [#7128 (comment)](https://github.com/kokkos/kokkos/pull/7128#issuecomment-2223058234) is clearly made up. Would you please update it with what is currently proposed.

The only thing that is made up is changing the minimum `clang++` requirement to `19` so that I can trigger the compile-time error.
For `g++-7.5.0`, I am getting
```
CMake Error at cmake/kokkos_compiler_id.cmake:206 (MESSAGE):
  Compiler not supported by Kokkos for C++17.  Required minimum compiler
  versions:

      Clang(CPU)          8.0.0
      Clang(CUDA)         10.0.0
      Clang(OpenMPTarget) 15.0.0
      GCC                 8.2.0
      Intel               19.0.5
      IntelLLVM(CPU)      2021.1.1
      IntelLLVM(SYCL)     2023.0.0
      NVCC                11.0.0
      HIPCC               5.2.0
      NVHPC/PGI           22.3
      MSVC                19.29
      XL/XLClang          not supported

  Compiler: GNU 7.5.0
```
and
```
CMake Error at cmake/kokkos_compiler_id.cmake:206 (MESSAGE):
  Compiler not supported by Kokkos for C++20.  Required minimum compiler
  versions:

      Clang(CPU)          14.0.0
      Clang(CUDA)         14.0.0
      Clang(OpenMPTarget) 15.0.0
      GCC                 10.1.0
      Intel               not supported
      IntelLLVM(CPU)      2022.0.0
      IntelLLVM(SYCL)     2023.0.0
      NVCC                12.0.0
      HIPCC               5.2.0
      NVHPC/PGI           22.3
      MSVC                19.30
      XL/XLClang          not supported

  Compiler: GNU 7.5.0
```

**Comment by dalg24** [comment]
The point was that your PR defines new compiler minimum requirement for C++20 and that therefore if reporting anything in this discussion then, what should be printed are these new requirement.

**Pull request merged**
