### PR TITLE
Fix -Werror=pedantic

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Fix for errors showing up in gcc nightly builds with -Werror

**Review by masterleinad — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]

**Comment by ndellingwood** [comment]
Is this error expected from the hpx ci test?
```
FAILED: core/unit_test/CMakeFiles/KokkosCore_UnitTest_HPX.dir/hpx/TestHPX_MathematicalFunctions.cpp.o 
/usr/bin/clang++ -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME_DEFAULT=KokkosCore_UnitTest_HPX -DHPX_DEBUG -DHPX_PREFIX_DEFAULT=\"/home/runner/work/kokkos/kokkos/hpx/install\" -DKOKKOS_DEPENDENCE -I/home/runner/work/kokkos/kokkos/kokkos/tpls/gtest -I/home/runner/work/kokkos/kokkos/kokkos/build/core/unit_test -I/home/runner/work/kokkos/kokkos/kokkos/core/unit_test -I/home/runner/work/kokkos/kokkos/kokkos/core/unit_test/category_files -I/home/runner/work/kokkos/kokkos/kokkos/build -I/home/runner/work/kokkos/kokkos/kokkos/build/core/src -I/home/runner/work/kokkos/kokkos/kokkos/core/src -I/home/runner/work/kokkos/kokkos/kokkos/build/containers/src -I/home/runner/work/kokkos/kokkos/kokkos/containers/src -I/home/runner/work/kokkos/kokkos/kokkos/build/algorithms/src -I/home/runner/work/kokkos/kokkos/kokkos/algorithms/src -isystem /home/runner/work/kokkos/kokkos/hpx/install/include -Werror -g -pthread -Wall -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized -std=gnu++14 -MD -MT core/unit_test/CMakeFiles/KokkosCore_UnitTest_HPX.dir/hpx/TestHPX_MathematicalFunctions.cpp.o -MF core/unit_test/CMakeFiles/KokkosCore_UnitTest_HPX.dir/hpx/TestHPX_MathematicalFunctions.cpp.o.d -o core/unit_test/CMakeFiles/KokkosCore_UnitTest_HPX.dir/hpx/TestHPX_MathematicalFunctions.cpp.o -c /home/runner/work/kokkos/kokkos/kokkos/build/core/unit_test/hpx/TestHPX_MathematicalFunctions.cpp
Killed
[85/584] Building CXX object core/unit_test/CMakeFiles/KokkosCore_UnitTest_HPX.dir/hpx/TestHPX_TeamBasic.cpp.o
[86/584] Building CXX object core/unit_test/CMakeFiles/KokkosCore_UnitTest_HPX.dir/hpx/TestHPX_TeamScratch.cpp.o
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

**Comment by masterleinad** [comment]
> Is this error expected from the hpx ci test?

Looks like extending the `MathematicalFunctions` test makes the HPX CI run out of memory...

**Comment by msimberg** [comment]
> > Is this error expected from the hpx ci test?
> 
> Looks like extending the `MathematicalFunctions` test makes the HPX CI run out of memory...

So restricting the number of jobs may be needed after all :disappointed: `ninja -j2` may help.

**Pull request merged**
