### PR TITLE
Workaround to ice with icpc when using -no-ip

### PR DESCRIPTION
**Pull request by ndellingwood**
Remove the ViewCopy_c test when compiling with icpc See issue: https://github.com/kokkos/kokkos/issues/7084

### CODE REVIEW

**Comment by ndellingwood** [comment]
I was able compile several Trilinos packages that have been sensitive to ICE without the kokkos tests; removing this test with intel classic compilers is sufficient to allow the rest of the Kokkos tests to compile and avoids wasting time on clunky workarounds for a deprecated compiler

**Review by crtrott — CHANGES_REQUESTED** [review]
can't we just add a "remove from list thing"?

**Comment by ndellingwood** [comment]
> can't we just add a "remove from list thing"?

@crtrott the change I added skips `ViewCopy_c` in the for loop when intel compilers are used; I can try removing the generated file from the list L285 `list(APPEND ${Tag}_SOURCES2A ${file})`, but will that leave behind some generated file cruft from the configuration file write/configuration L280-284?

**Comment by crtrott** [comment]
One sec I am pushing an alternative.

**Comment by crtrott** [comment]
Can you try this? It mirrors how we do things for the sources 1B

**Comment by ndellingwood** [comment]
@crtrott yeah I like that better, I'll test it out

**Comment by ndellingwood** [comment]
@crtrott that worked, thanks!

**Review by crtrott — APPROVED** [review]

**Review by nmm0 — APPROVED** [review]
Looks good to me though I'm really curious as to what exactly is causing the ICE

**Comment by crtrott** [comment]
Bunch of issues with container bringup. I will merge this.

**Pull request merged**
