### PR TITLE
CMakeLists.txt: Bracket CUDA-Trilinos flags with ENABLE_CUDA

### PR DESCRIPTION
**Pull request by ndellingwood**
Matching PR to #2714 (to develop) by @jjwilke

### CODE REVIEW

**Comment by ndellingwood** [comment]
For consideration of merge into develop, depending on how copyright 3.0.00 updates are supposed to work.
Without this PR, any snapshot of master in Trilinos will clobber the matching Trilinos hot-fix.

**Comment by jjwilke** [comment]
This is in develop. I'm not familiar with our usual processes. Do we usually just merge develop into master at regular intervals? Or do we want to propagate the fix to master instead of waiting to merge develop?

**Comment by ndellingwood** [comment]
@jjwilke usually this would just come in during the next integration, but it's not clear to me how 3.0.00 is going to be handled - it may be a snapshot of master back into Trilinos with the updated copyright info, if that is the case this fix is needed to prevent clobbering the hot-fix to Trilinos.
Adding @crtrott to clarify how 3.0.00 is to be handled.

**Comment by ndellingwood** [comment]
Retest this please.

**Comment by dalg24** [comment]
Retest this please

**Comment by crtrott** [comment]
We are just applying the script on Trilinos as a hot fix to change the copyright notice ...

**Comment by crtrott** [comment]
This is not needed.

**Pull request closed without merging**
