### PR TITLE
kokkos_tpls.cmake: update default option to enable rocthrust

### PR DESCRIPTION
**Pull request by ndellingwood**
Avoid configuration issues with Trilinos of the form: 
CMake Error at kokkos/cmake/kokkos_tpls.cmake:29 (MESSAGE):
 Enabled TPL ROCTHRUST inside TriBITS build, but this can only be enabled in
 a standalone build

### CODE REVIEW

**Comment by ndellingwood** [comment]
This is a workaround option to resolve configuration issues with Trilinos with Hip builds. Mostly opening for discussion, it would be nice to have rocthrust available for performance like @dalg24 mentioned, but I'm not certain at the moment what is needed to make that work

**Comment by ndellingwood** [comment]
Rocthrust isn't listed on the supported TPLsList https://github.com/trilinos/Trilinos/blob/master/TPLsList.cmake . I don't think Trilinos will work with Rocthrust until a find module is added to support the usage, then we can add rocthrust as an option to the [`LIB_OPTIONAL_TPLS`](https://github.com/kokkos/kokkos/blob/5931cbd296519c9ed7746f4c8c6e78411c1e3144/cmake/Dependencies.cmake#L2C3-L2C20)

**Comment by ndellingwood** [comment]
Potential alternative PR https://github.com/kokkos/kokkos/pull/6880 , but that relies on acceptance and merge of some form of https://github.com/trilinos/Trilinos/pull/12826

**Comment by masterleinad** [comment]
I would prefer this as a temporary solution since it doesn't depend on the question of how to handle Kokkos TPLs in Trilinos going forward. Of course, that would mean that `sort[_by_key]` with `HIP` would not get a performance improvement before we refactor the TPL system in  #6871. The same is true for `oneDPL`.

**Review by masterleinad — APPROVED** [review]

**Comment by Rombur** [comment]
@ndellingwood am I correct that if a user builds its own Kokkos with rocthrust, Trilinos can still use the user-installed Kokkos as a TPL? In this case, it shouldn't matter to Trilinos that rocthrust is not a TPL in Trilinos, right?

**Comment by ndellingwood** [comment]
@Rombur I haven't tested pulling in Kokkos as a TPL in Trilinos to see if the issue is present (need to try). But in any case, without a similar change to this PR or #6880 with Trilinos changes, the snapshot of Kokkos into Trilinos (as a package) will break Hip builds of Trilinos

**Comment by Rombur** [comment]
Right but it's less of a problem to disable rocthrust when compiling with Trilinos if there is a way for users to use their own Kokkos with rocthrust enabled.

**Comment by ndellingwood** [comment]
To clarify, by "achieve compatibility as a snapshot in Trilinos" I mean resolve configuration issues that come up with rocthrust, https://github.com/kokkos/kokkos/pull/6871#issuecomment-1996263156

**Comment by ndellingwood** [comment]
@Rombur ah, thanks, I misunderstood. I'll test as a TPL in a Hip build to confirm with you that the change works as hoped for

**Comment by ndellingwood** [comment]
Hip CI failed in `Kokkos_AlgorithmsUnitTest_StdSet_Team_P`:
```
50: [  FAILED  ] 2 tests, listed below:
50: [  FAILED  ] std_algorithms_exclusive_scan_team_test.test
50: [  FAILED  ] std_algorithms_transform_exclusive_scan_team_test.test
```

That shouldn't be related to changes in this PR I don't think, are these known issues?

**Comment by ndellingwood** [comment]
The ubuntu clang++ GA checks are failing several checks but those are unrelated to changes in this PR

**Comment by Rombur** [comment]
I don't why you get errors but it should not be related to this PR.

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
```
50: Test command: /var/jenkins/workspace/Kokkos_PR-6879/build/algorithms/unit_tests/Kokkos_AlgorithmsUnitTest_StdSet_Team_P
50: Test timeout computed to be: 1500
50: [==========] Running 2 tests from 2 test suites.
50: [----------] Global test environment set-up.
50: [----------] 1 test from std_algorithms_exclusive_scan_team_test
50: [ RUN      ] std_algorithms_exclusive_scan_team_test.test
50: /var/jenkins/workspace/Kokkos_PR-6879/algorithms/unit_tests/TestStdAlgorithmsCommon.hpp:628: Failure
50: Expected equality of these values:
50:   A(i, j)
50:     Which is: 1493366
50:   B(i, j)
50:     Which is: 1492878
50: [  FAILED  ] std_algorithms_exclusive_scan_team_test.test (3066 ms)
50: [----------] 1 test from std_algorithms_exclusive_scan_team_test (3067 ms total)
50: 
50: [----------] 1 test from std_algorithms_transform_exclusive_scan_team_test
50: [ RUN      ] std_algorithms_transform_exclusive_scan_team_test.test
50: /var/jenkins/workspace/Kokkos_PR-6879/algorithms/unit_tests/TestStdAlgorithmsCommon.hpp:628: Failure
50: Expected equality of these values:
50:   A(i, j)
50:     Which is: 4317188
50:   B(i, j)
50:     Which is: 4124587
50: [  FAILED  ] std_algorithms_transform_exclusive_scan_team_test.test (1521 ms)
50: [----------] 1 test from std_algorithms_transform_exclusive_scan_team_test (1521 ms total)
50: 
50: [----------] Global test environment tear-down
50: [==========] 2 tests from 2 test suites ran. (4588 ms total)
50: [  PASSED  ] 0 tests.
50: [  FAILED  ] 2 tests, listed below:
50: [  FAILED  ] std_algorithms_exclusive_scan_team_test.test
50: [  FAILED  ] std_algorithms_transform_exclusive_scan_team_test.test
50: 
50:  2 FAILED TESTS
50/52 Test #50: Kokkos_AlgorithmsUnitTest_StdSet_Team_P .....***Failed  Error regular expression found in output. Regex=[  FAILED  ]  5.05 sec
```
@Rombur OK to ignore in the ROCm 5.6 C++20 build?

**Comment by Rombur** [comment]
@dalg24 yes, that's fine to merge as-is

**Pull request merged**
