### PR TITLE
Issue 1064

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Address issue #1064

**Comment by hcedwar** [comment]
Tested across platforms?

**Comment by ndellingwood** [comment]
kokkos-dev: `test_all_sandia` with intel/14.0.4 OpenMP, clang/3.9.0 Pthread, cuda/7.5.18 Cuda_Serial, gcc/4.8.4 Serial; development testing with cuda/8.0.44 and gcc/5.3.0

No testing on white or bowman, will run spot checks now

**Comment by ndellingwood** [comment]
white: 
```
ndellin@white30:~/kokkos/testing/TestAllSandia$ ../../config/test_all_sandia ibm/13.1.3 --build-list=OpenMP
Going to test compilers:  ibm/13.1.3
Testing compiler ibm/13.1.3
  Starting job ibm-13.1.3-OpenMP-release
  PASSED ibm-13.1.3-OpenMP-release
#######################################################
PASSED TESTS
#######################################################
ibm-13.1.3-OpenMP-release build_time=4028 run_time=134
```

bowman:
```
[ndellin@node05 TestAllSandia]$ ../../config/test_all_sandia intel/17.0.098 --build-list=OpenMP
Going to test compilers:  intel/17.0.098
Testing compiler intel/17.0.098
  Starting job intel-17.0.098-OpenMP-release
  PASSED intel-17.0.098-OpenMP-release
#######################################################
PASSED TESTS
#######################################################
intel-17.0.098-OpenMP-release build_time=1114 run_time=347
```

**Comment by ndellingwood** [comment]
Please look over the comments within the example I added in the tutorials, let me know if extra explanation etc. is needed.

**Pull request merged**
