### PR TITLE
Replace volatile_load by Kokkos::atomic_load for SYCL

### LINKED ISSUE #4567: UnorderedMap inserts duplicate keys on SYCL
UnorderedMap should insert each unique key only once. If a key is already in the map, ``insert(key).existing()`` should return true but that duplicate shouldn't actually go into the data structure. On SYCL though, a key can get inserted multiple times.

Reproducer:
```
#include "Kokkos_Core.hpp"
#include "Kokkos_UnorderedMap.hpp"

using ExecSpace = Kokkos::DefaultExecutionSpace;
using Device = Kokkos::Device<ExecSpace, typename ExecSpace::memory_space>;

int main()
{
  Kokkos::initialize();
  {
    std::cout << "Testing out UnorderedMap on " << ExecSpace::name() << '\n';
    int n = 10000;
    Kokkos::UnorderedMap<uint64_t, void, Device> myMap(n);
    int numToInsert = n * 0.75;
    //Insert each value in [0..numToInsert-1] 5 times
    int uniqueInserted;
    Kokkos::parallel_reduce(Kokkos::RangePolicy<ExecSpace>(0, numToInsert * 5), 
    KOKKOS_LAMBDA(int i, int& luniqueInserted)
    {   
      int valueToInsert = i % numToInsert;
      auto result = myMap.insert(valueToInsert);
      if(result.success() && !result.existing())
      {   
        luniqueInserted++;
      }   
      else if(result.failed())
      {   
        printf("Inserting failed!\n");
      }   
    }, uniqueInserted);
    std::cout << "Inserted " << uniqueInserted << " unique values successfully (should be " << numToInsert << ")\n";
  }
  Kokkos::finalize();
  return 0;
}
```
Here is the expected output (from Cuda as an example):
```
Testing out UnorderedMap on Cuda
Inserted 7500 unique values successfully (should be 7500)
```
but on SYCL:
```
Testing out UnorderedMap on SYCL
Inserted 7760 unique values successfully (should be 7500)
```
The exact number of values inserted varies from run to run, but it's always more than 7500. This is a minor blocker for Kokkos Kernels since we use UnorderedMap to do graph symmetrization for coloring and Gauss-Seidel. If needed we could work around it temporarily by using a simpler symmetrization scheme (like computing A + A^T and then merging duplicates).

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #4567. I'm not quite sure how `volatile_load` is supposed to work but replacing it with `Kokkos::atomic_load` seems sensible to me to avoid race conditions. The `bitset` test also failed for me on Intel hardware but this patch fixes that as well.

@brian-kelley Can you please check that this resolves #4567 for you?

### CODE REVIEW

**Comment by PhilMiller** [comment]
The `atomic_load` version should be preferable for every backend other than CUDA, since they all have compilers and hardware that together faithfully implement the C++11 memory model

**Comment by brian-kelley** [comment]
@masterleinad Yes, this fixes it. Thanks!

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Apparently, SYCL+CUDA still doesn't like this but it works on Intel GPUs with this patch...

**Comment by crtrott** [comment]
Volatile load here has nothing to do with race conditions, but only with not optimizing the load away. Using atomic_load will just make the code slower and thus likely avoid a race condition on some hardware which comes from somewhere else? Maybe we are missing a fence or so?

**Review by crtrott — CHANGES_REQUESTED** [review]
Don't think this is the root cause. Likely code is just getting slower with this, which avoids the actual race condition somewhere else on some hardware.

**Comment by masterleinad** [comment]
> Don't think this is the root cause. Likely code is just getting slower with this, which avoids the actual race condition somewhere else on some hardware.

The last commit should also work with SYCL+CUDA (I checked myself) which hints that the `memory_fence` might not quite work the same way with `SYCL`.

**Comment by masterleinad** [comment]
Retest this please.

**Review by crtrott — CHANGES_REQUESTED** [review]
did you try just calling some other explicit SYCL memory fence? Maybe there is something wrong with the implementation of Kokkos;:memory_fence with SYCL on?

**Review by crtrott — APPROVED** [review]

**Pull request merged**
