### PR TITLE
Implement option to disable deprecation warnings

### PR DESCRIPTION
**Pull request by masterleinad**
The new option currently just disables deprecation warnings for code marked with `KOKKOS_DEPRECATED`. At the moment, the default is `ON` changing the current behavior. For all CI, the option is `OFF`, though.
We might actually hide code depending on this option later.

### CODE REVIEW

**Comment by crtrott** [comment]
why rename it to _3? I mean we don't have a 2 and 1 and generally I think its ok to have an option which affects all "currently deprecated" stuff.

**Comment by masterleinad** [comment]
> why rename it to _3? I mean we don't have a 2 and 1 and generally I think its ok to have an option which affects all "currently deprecated" stuff.

That's the name we come up with in https://github.com/kokkos/internal-documents/blob/0fe07f0e040aaf845c889a5ada3a3a09e36e8e11/developer-notes/deprecation-policy.md. I thought we wanted something major release specific.

**Review by crtrott — CHANGES_REQUESTED** [review]
We need tests with deprecated code on for sure. In particular since that is what the default setting is. So only do one or two configs with it off, and most of it with it on.

**Comment by masterleinad** [comment]
> We need tests with deprecated code on for sure. In particular since that is what the default setting is. So only do one or two configs with it off, and most of it with it on.

Done. Now, only the MacOS builds, one `CUDA` build, and one `HIP` build will emit warnings for deprecated code.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
