### PR TITLE
Enable deprecated code and deprecated warnings in nightly CI

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Daniel's point is that we need coverage for both enabled and disabled.
How long do these builds take?

**Comment by masterleinad** [comment]
> Daniel's point is that we need coverage for both enabled and disabled.

It's more that we might break this build in the feature because we would be testing deprecated behavior (which is what we did in the past). A build that only build the library and errors out on deprecation warnings would be helpful either way.

**Review by masterleinad — APPROVED** [review]

**Comment by nmm0** [comment]
Maybe if a test fails because it's testing deprecated code we can guard the specific test with `KOKKOS_ENABLE_DEPRECATED_CODE_*` If we are testing with and without that flag enabled I don't think it would hurt our coverage

**Comment by masterleinad** [comment]
> Maybe if a test fails because it's testing deprecated code we can guard the specific test with `KOKKOS_ENABLE_DEPRECATED_CODE_*` If we are testing with and without that flag enabled I don't think it would hurt our coverage

That's what we are already doing.

**Comment by dalg24** [comment]
@Rombur 
The GCC build in the nightlies is failing with
```
[ 11%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Serial1.dir/serial/TestSerial_ArrayOps.cpp.o
[ 12%] Linking CXX executable Kokkos_CoreUnitTest_ToolIndependence
[ 12%] Built target Kokkos_CoreUnitTest_ToolIndependence
[ 12%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Default.dir/TestSharedHostPinnedSpace.cpp.o
[ 13%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreTestCompileOnly.dir/TestRangePolicyCTAD.cpp.o
[ 13%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_KokkosP.dir/tools/TestEventCorrectness.cpp.o
In file included from /var/jenkins/workspace/Kokkos_nightly/build/core/unit_test/serial/TestSerial_ArrayOps.cpp:2:
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp: In member function 'virtual void {anonymous}::serial_array_contiguous_capacity_Test::TestBody()':
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:117:65: error: 'Array' is deprecated [-Werror=deprecated-declarations]
  117 |       Kokkos::Array<int, KOKKOS_INVALID_INDEX, Kokkos::Array<>::contiguous>;
      |                                                                 ^~~~~~~~~~
In file included from /var/jenkins/workspace/Kokkos_nightly/core/src/KokkosExp_MDRangePolicy.hpp:29,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Tuners.hpp:28,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/impl/Kokkos_Tools_Generic.hpp:26,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Parallel.hpp:34,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_MemoryPool.hpp:26,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_TaskScheduler.hpp:34,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/Serial/Kokkos_Serial.hpp:37,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/decl/Kokkos_Declare_SERIAL.hpp:21,
                 from /var/jenkins/workspace/Kokkos_nightly/build/KokkosCore_Config_DeclareBackend.hpp:22,
                 from /var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Core.hpp:45,
                 from /var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:18:
/var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Array.hpp:211:26: note: declared here
  211 | struct KOKKOS_DEPRECATED Array<void, KOKKOS_INVALID_INDEX, void> {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp: In member function 'virtual void {anonymous}::serial_array_contiguous_element_access_Test::TestBody()':
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:136:65: error: 'Array' is deprecated [-Werror=deprecated-declarations]
  136 |       Kokkos::Array<int, KOKKOS_INVALID_INDEX, Kokkos::Array<>::contiguous>;
      |                                                                 ^~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Array.hpp:211:26: note: declared here
  211 | struct KOKKOS_DEPRECATED Array<void, KOKKOS_INVALID_INDEX, void> {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp: In member function 'virtual void {anonymous}::serial_array_contiguous_assignment_Test::TestBody()':
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:197:65: error: 'Array' is deprecated [-Werror=deprecated-declarations]
  197 |       Kokkos::Array<int, KOKKOS_INVALID_INDEX, Kokkos::Array<>::contiguous>;
      |                                                                 ^~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Array.hpp:211:26: note: declared here
  211 | struct KOKKOS_DEPRECATED Array<void, KOKKOS_INVALID_INDEX, void> {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp: In member function 'virtual void {anonymous}::serial_array_strided_capacity_Test::TestBody()':
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:255:71: error: 'Array' is deprecated [-Werror=deprecated-declarations]
  255 |   using A = Kokkos::Array<int, KOKKOS_INVALID_INDEX, Kokkos::Array<>::strided>;
      |                                                                       ^~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Array.hpp:211:26: note: declared here
  211 | struct KOKKOS_DEPRECATED Array<void, KOKKOS_INVALID_INDEX, void> {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp: In member function 'virtual void {anonymous}::serial_array_strided_element_access_Test::TestBody()':
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:273:71: error: 'Array' is deprecated [-Werror=deprecated-declarations]
  273 |   using A = Kokkos::Array<int, KOKKOS_INVALID_INDEX, Kokkos::Array<>::strided>;
      |                                                                       ^~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Array.hpp:211:26: note: declared here
  211 | struct KOKKOS_DEPRECATED Array<void, KOKKOS_INVALID_INDEX, void> {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp: In member function 'virtual void {anonymous}::serial_array_strided_assignment_Test::TestBody()':
/var/jenkins/workspace/Kokkos_nightly/core/unit_test/TestArrayOps.hpp:337:72: error: 'Array' is deprecated [-Werror=deprecated-declarations]
  337 |   using A  = Kokkos::Array<int, KOKKOS_INVALID_INDEX, Kokkos::Array<>::strided>;
      |                                                                        ^~~~~~~
/var/jenkins/workspace/Kokkos_nightly/core/src/Kokkos_Array.hpp:211:26: note: declared here
  211 | struct KOKKOS_DEPRECATED Array<void, KOKKOS_INVALID_INDEX, void> {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Pull request merged**
