### PR TITLE
Fix warnings. 

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
```
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? patch_teamvectorrange

Repository Status:  2f411bd228a2f84f1cb08b71a4d6ecc47a6c8b46 Fixing a number of unused parameter warnings


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=129 run_time=423
clang-6.0-Cuda_Pthread-release build_time=229 run_time=288
clang-6.0-OpenMP-release build_time=113 run_time=87
cuda-9.1-Cuda_OpenMP-release build_time=315 run_time=167
gcc-4.8.4-OpenMP-release build_time=106 run_time=102
gcc-4.8.4-Pthread-release build_time=97 run_time=314
gcc-5.3.0-Serial-release build_time=112 run_time=168
intel-16.0.1-OpenMP-release build_time=331 run_time=141
```

**Comment by ndellingwood** [comment]
Cross reference issues #1989 and #1984

**Comment by crtrott** [comment]
```
cat nohup.issue-1989-no-deprecated 
nohup: ignoring input
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git'
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? patch_teamvectorrange

Repository Status:  81802847ac885e8132c778ffb389acafb9954b5d Fix a deprecated code issue


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-OpenMP-release
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED intel-16.0.1-OpenMP-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  PASSED clang-6.0-Cuda_Pthread-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=131 run_time=272
clang-6.0-Cuda_Pthread-release build_time=248 run_time=189
clang-6.0-OpenMP-release build_time=129 run_time=77
cuda-9.1-Cuda_OpenMP-release build_time=289 run_time=163
gcc-4.8.4-OpenMP-release build_time=118 run_time=91
gcc-4.8.4-Pthread-release build_time=110 run_time=217
gcc-5.3.0-Serial-release build_time=112 run_time=139
intel-16.0.1-OpenMP-release build_time=355 run_time=141
```

**Comment by crtrott** [comment]
KokkosDev is still testing. I will merge when its done.

**Comment by crtrott** [comment]
On KokkosDev with a Kepler card the mdrange overlap test didn't succeed, since the number of work items was too large for a Kepler card (i.e. the kernels weren't able to overlap sufficiently). 

```
nohup: ignoring input
Running on machine: sems
Repository Status:  81802847ac885e8132c778ffb389acafb9954b5d Fix a deprecated code issue


Going to test compilers:  gcc/5.3.0 gcc/7.3.0 intel/17.0.1 clang/4.0.1 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/7.3.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-7.3.0-Serial-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler intel/17.0.1
  Starting job gcc-7.3.0-Serial-hwloc-release
  PASSED gcc-7.3.0-Serial-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED gcc-7.3.0-Serial-hwloc-release
Testing compiler clang/4.0.1
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  Starting job clang-4.0.1-Pthread_Serial-release
  PASSED intel-17.0.1-OpenMP-release
Testing compiler cuda/8.0.44
  Starting job clang-4.0.1-Pthread_Serial-hwloc-release
  PASSED clang-4.0.1-Pthread_Serial-hwloc-release
  PASSED clang-4.0.1-Pthread_Serial-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  FAILED cuda-8.0.44-Cuda_OpenMP-release
....
[  FAILED  ] default_exec.overlap_mdrange_policy (156 ms)
[ RUN      ] default_exec.overlap_team_policy
Time TeamPolicy: NonOverlap: 0.095478 Time Overlap: 0.047953
[       OK ] default_exec.overlap_team_policy (352 ms)
[----------] 37 tests from default_exec (21474 ms total)

[----------] Global test environment tear-down
[==========] 37 tests from 1 test case ran. (21474 ms total)
[  PASSED  ] 36 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] default_exec.overlap_mdrange_policy

 1 FAILED TEST
make[2]: *** [test-performance] Error 1
make[2]: Leaving directory `/home/crtrott/Kokkos/KokkosBuild/TestAll_2019-02-15_17.12.13/cuda/8.0.44/Cuda_OpenMP-release/core/perf_test'
make[1]: *** [test] Error 2
make[1]: Leaving directory `/home/crtrott/Kokkos/KokkosBuild/TestAll_2019-02-15_17.12.13/cuda/8.0.44/Cuda_OpenMP-release/core/perf_test'
make: *** [test] Error 2
#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-hwloc-release build_time=235 run_time=232
clang-4.0.1-Pthread_Serial-release build_time=258 run_time=527
gcc-5.3.0-OpenMP-hwloc-release build_time=258 run_time=175
gcc-5.3.0-OpenMP-release build_time=261 run_time=174
gcc-7.3.0-Serial-hwloc-release build_time=199 run_time=175
gcc-7.3.0-Serial-release build_time=199 run_time=173
intel-17.0.1-OpenMP-hwloc-release build_time=2665 run_time=1143
intel-17.0.1-OpenMP-release build_time=2706 run_time=1174
#######################################################
FAILED TESTS
#######################################################
cuda-8.0.44-Cuda_OpenMP-release (test failed)
```

Fixed that particular thing now: 
```
nohup: ignoring input
Running on machine: sems
Repository Status:  62baa43021a045ef496d05c8b68aa2cb30970709 CUDA: Adjust PerfTest for overlap so it passes on Kepler


Going to test compilers:  cuda/8.0.44
Testing compiler cuda/8.0.44
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
cuda-8.0.44-Cuda_OpenMP-release build_time=700 run_time=617
```

**Comment by crtrott** [comment]
```
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? patch_teamvectorrange

Repository Status:  62baa43021a045ef496d05c8b68aa2cb30970709 CUDA: Adjust PerfTest for overlap so it passes on Kepler


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=131 run_time=423
clang-6.0-Cuda_Pthread-release build_time=229 run_time=288
clang-6.0-OpenMP-release build_time=115 run_time=88
cuda-9.1-Cuda_OpenMP-release build_time=316 run_time=174
gcc-4.8.4-OpenMP-release build_time=102 run_time=102
gcc-4.8.4-Pthread-release build_time=97 run_time=312
gcc-5.3.0-Serial-release build_time=112 run_time=167
intel-16.0.1-OpenMP-release build_time=333 run_time=148
```

**Comment by ndellingwood** [comment]
@crtrott some change from either this PR or #1919 has broken debug builds in Jenkins for kokkos and kokkos-kernels, can you look into it? More details here:

https://github.com/kokkos/kokkos/issues/1984#issuecomment-464809594

**Pull request merged**
