### PR TITLE
Fix Compiler Warnings for Type Conversion in Atomic Decrement

### PR DESCRIPTION
**Pull request by nmhamster**
Suggestion from @dsunder to see if we can implement using Atomic subtractions and they do exist!

### CODE REVIEW

**Comment by nmhamster** [comment]
Turns out tests didn't compile because of license server. Argh. This has error, close and will reopen.

**Comment by crtrott** [comment]
Also atomic sub runs probably in the same problem right now.

**Comment by nmhamster** [comment]
@crtrott do you know that for sure?

**Comment by crtrott** [comment]
Oh I just checked, the sub op should actually be fine even for unsigned types.

**Pull request closed without merging**
