### PR TITLE
Testing updates

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Small changes to increase timeout time on tests (`KokkosContainers_UnitTest_OpenMP` times out more often than not in `cuda_92_xl_161_pascal` nightly builds) and updates deprecated command-line argument for device.

**Comment by ndellingwood** [comment]
retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by ndellingwood** [comment]
retest this please

**Comment by dalg24** [comment]
Retest this please

**Pull request merged**
