### PR TITLE
[4.2.01] Add missing gfx940

### PR DESCRIPTION
**Pull request by ndellingwood**
Merge pull request #6671 from rbberger/add_mi300_gfx940

Add missing gfx940

(cherry picked from commit 64a7774b675358b4bae3e60dad81d0aecaf53955)

### CODE REVIEW

**Comment by ndellingwood** [comment]
Adding @jjellio @ajpowelsnl

**Comment by ndellingwood** [comment]
This patch is needed by code teams using Trilinos for testing purposes

**Comment by ndellingwood** [comment]
CI failed the clang-format check on the CHANGELOG.md, but no changes were made.

```diff
+ ./scripts/docker/check_format_cpp.sh
diff --git a/CHANGELOG.md b/CHANGELOG.md
index c6115f4b3..c10534a49 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -43,7 +43,7 @@
 
 #### SYCL:
 - Enforce external `sycl::queues` to be in-order [\#6246](https://github.com/kokkos/kokkos/pull/6246)
-- Improve reduction performance: [\#6272](https://github.com/kokkos/kokkos/pull/6272) [\#6271](https://github.com/kokkos/kokkos/pull/6271) [\#6270](https://github.com/kokkos/kokkos/pull/6270) [\#6264](https://github.com/kokkos/kokkos/pull/6264) 
+- Improve reduction performance: [\#6272](https://github.com/kokkos/kokkos/pull/6272) [\#6271](https://github.com/kokkos/kokkos/pull/6271) [\#6270](https://github.com/kokkos/kokkos/pull/6270) [\#6264](https://github.com/kokkos/kokkos/pull/6264)
 - Allow using the SYCL execution space on AMD GPUs [\#6321](https://github.com/kokkos/kokkos/pull/6321)
 - Allow sorting via native oneDPL to support Views with stride=1 [\#6322](https://github.com/kokkos/kokkos/pull/6322)
 - Make in-order queues the default via macro [\#6189](https://github.com/kokkos/kokkos/pull/6189)
@@ -64,7 +64,7 @@
 - Add converting assignment to `DualView`:  [\#6474](https://github.com/kokkos/kokkos/pull/6474)
 
 
-### Build System Changes 
+### Build System Changes
 
 - Export `Kokkos_CXX_COMPILER_VERSION` [\#6282](https://github.com/kokkos/kokkos/pull/6282)
 - Disable default oneDPL support in Trilinos [\#6342](https://github.com/kokkos/kokkos/pull/6342)
```

I ran diff on copies of the CHANGELOG.md between the release-candidate-4.2.01 branch and this PR and no diffs occurred... can someone help?

**Comment by ndellingwood** [comment]
Trilinos patch up at https://github.com/trilinos/Trilinos/pull/12673

**Review by dalg24 — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
Trailing whitespace?

**Comment by ndellingwood** [comment]
> Trailing whitespace?

@dalg24 ah yep good call (quick check in vim). The whitespace was already present in the CHANGELOG on release-candidate-4.2.01 (not introduced in this PR), but was apparently fixed on the develop branch. I pushed the whitespace cleanup in [4d784fe](https://github.com/kokkos/kokkos/pull/6723/commits/4d784fe01e3b6e222fc69a4abb09fd64c000a431)

**Comment by ndellingwood** [comment]
Updated changelog PR #6656 to include this item

**Comment by ndellingwood** [comment]
The threads unit test failures are unrelated to changes in this PR, listing here for reference:
```
 The following tests FAILED:
	  1 - Kokkos_CoreUnitTest_Threads (Failed)
	 18 - Kokkos_CoreUnitTest_DeviceAndThreads (Failed)
	 40 - Kokkos_AlgorithmsUnitTest_StdSet_Team_H (Failed)
```

Also, the hpx failure should be unrelated
```
 /home/runner/work/kokkos/kokkos/hpx/libs/core/iterator_support/include/hpx/iterator_support/counting_iterator.hpp:58:53: error: no member named 'intmax_t' in namespace 'std'
                    (sizeof(Integer) >= sizeof(std::intmax_t)),
                                               ~~~~~^
...
```

**Comment by ndellingwood** [comment]
Rocm CI passing compilation but failing with system-related issues during ctest that should be unrelated to the PR, e.g.:
```
54:   what():  hipGetDeviceCount(&hipDevCount) error( hipErrorNoDevice): hipErrorNoDevice /var/jenkins/workspace/Kokkos_PR-6723/core/src/HIP/Kokkos_HIP_Instance.cpp:428
```

**Comment by dalg24** [comment]
The HPX failure is https://github.com/kokkos/kokkos/issues/6546 which was fixed in https://github.com/kokkos/kokkos/pull/6547
I would be fine just ignoring

**Comment by dalg24** [comment]
HIP CI build compiled.  Ignoring runtime failures that are denoting an issue with the machine (HIP runtime not detecting the GPUs)

**Pull request merged**
