### PR TITLE
fix typo in KOKKOS_SET_EXE_PROPERTY()

### LINKED ISSUE #2959: kokkos-3.1.00: KokkosCore_UnitTest_StackTraceTest test fails on openSUSE_Tumbleweed x86_64
```
[  819s]  6/33 Test  #6: KokkosCore_UnitTest_StackTraceTest ........***Failed  Error regular expression found in output. Regex=[FAILED]  0.01 sec
[  819s] Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
[  819s]   In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
[  819s]   For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
[  819s]   For unit testing set OMP_PROC_BIND=false
[  819s] [==========] Running 3 tests from 2 test cases.
[  819s] [----------] Global test environment set-up.
[  819s] [----------] 2 tests from defaultdevicetype_DeathTest
[  819s] [ RUN      ] defaultdevicetype_DeathTest.stacktrace_terminate
[  819s]
[  819s] [WARNING] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/tpls/gtest/gtest/gtest-all.cc:7321:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test cou
ldn't detect the number of threads.
[  819s] Top of f1
[  819s] Top of f0
[  819s] Top of f0
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/core/unit_test/TestStackTrace.hpp:160: Failure
[  819s] Death test: { test_stacktrace(true); }
[  819s]     Result: failed to die.
[  819s]  Error msg:
[  819s] [  DEATH   ]
[  819s] [  FAILED  ] defaultdevicetype_DeathTest.stacktrace_terminate (1 ms)
[  819s] [ RUN      ] defaultdevicetype_DeathTest.stacktrace_generic_term
[  819s]
[  819s] [WARNING] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/tpls/gtest/gtest/gtest-all.cc:7321:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
[  819s] Top of f1
[  819s] Top of f0
[  819s] Top of f0
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/core/unit_test/TestStackTrace.hpp:165: Failure
[  819s] Death test: { test_stacktrace(true, false); }
[  819s]     Result: failed to die.
[  819s]  Error msg:
[  819s] [  DEATH   ]
[  819s] [  FAILED  ] defaultdevicetype_DeathTest.stacktrace_generic_term (1 ms)
[  819s] [----------] 2 tests from defaultdevicetype_DeathTest (2 ms total)
[  819s]
[  819s] [----------] 1 test from defaultdevicetype
[  819s] [ RUN      ] defaultdevicetype.stacktrace_normal
[  819s] Top of f1
[  819s] Top of f0
[  819s] Top of f0
[  819s] test_f1: /home/abuild/rpmbuild/BUILDROOT/kokkos-3.1.00-6.1.x86_64//usr/lib64/libkokkoscore.so.3.1.0(_ZN6Kokkos4Impl15save_stacktraceEv+0x15) [0x7f6e7aa70355]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/KokkosCore_StackTraceTestExec(+0x409a) [0x55d20d90809a]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/KokkosCore_StackTraceTestExec(+0x43a8) [0x55d20d9083a8]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/libkokkos_gtest.so(+0x1b0e6) [0x7f6e7aae60e6]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/libkokkos_gtest.so(_ZN7testing4Test3RunEv+0xc5) [0x7f6e7ab010e5]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/libkokkos_gtest.so(_ZN7testing8TestInfo3RunEv+0x150) [0x7f6e7ab01260]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/libkokkos_gtest.so(_ZN7testing8TestCase3RunEv+0xb5) [0x7f6e7ab01345]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/libkokkos_gtest.so(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x43c) [0x7f6e7aaf558c]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/libkokkos_gtest.so(_ZN7testing8UnitTest3RunEv+0x68) [0x7f6e7aaf9a28]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/KokkosCore_StackTraceTestExec(+0x3e43) [0x55d20d907e43]
[  819s] /lib64/libc.so.6(__libc_start_main+0xeb) [0x7f6e7a6d1ceb]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/build/core/unit_test/KokkosCore_StackTraceTestExec(+0x3e8a) [0x55d20d907e8a][  819s]
[  819s] /home/abuild/rpmbuild/BUILD/kokkos-3.1.00/core/unit_test/TestStackTrace.hpp:76: Failure
[  819s] Value of: std::string::npos != foutput.find("stacktrace_test_f1")
[  819s]   Actual: false
[  819s] Expected: true
[  819s] [  FAILED  ] defaultdevicetype.stacktrace_normal (0 ms)
[  819s] [----------] 1 test from defaultdevicetype (0 ms total)
[  819s]
[  819s] [----------] Global test environment tear-down
[  819s] [==========] 3 tests from 2 test cases ran. (3 ms total)
[  819s] [  PASSED  ] 0 tests.
[  819s] [  FAILED  ] 3 tests, listed below:
[  819s] [  FAILED  ] defaultdevicetype_DeathTest.stacktrace_terminate
[  819s] [  FAILED  ] defaultdevicetype_DeathTest.stacktrace_generic_term
[  819s] [  FAILED  ] defaultdevicetype.stacktrace_normal
[  819s]
[  819s]  3 FAILED TESTS
[  819s]
```

Details here:
[x86_64.txt](https://github.com/kokkos/kokkos/files/4489553/x86_64.txt)

### PR DESCRIPTION
**Pull request by junghans**
Fix #2959

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Is this meant to target `master` or `develop`?

**Comment by junghans** [comment]
`master` as it would go into `3.1.01`.

**Comment by Rombur** [comment]
Retest this please

**Comment by masterleinad** [comment]
This now merged in `develop` (#2962).

**Comment by crtrott** [comment]
Hey I am closing this for now. We will do a 3.1.1 release I have this includes on my branch on my fork: 
https://github.com/crtrott/kokkos/tree/release-3.1.1

**Pull request closed without merging**
