### PR TITLE
Fix bounds errors with Kokkos::sort

### PR DESCRIPTION
**Pull request by kmorel**
We have noticed that `Kokkos::sort` sometimes fails in HIP. This
adds a test that demonstrates this bug. When I compile Kokkos
on the crusher platform at OLCF using the ROCm 5.1.0 module, this
test fails. This can be used to determine what is going wrong
with sort and provide a regression test for it.

Note that this PR does not _fix_ anything. Rather, this just
demonstrates the problem reported in #4978. I provide this to
the Kokkos developers so they have a simple way to replicate the
problem in #4978.

### CODE REVIEW

**Comment by dalg24** [comment]
OK to test

**Comment by dalg24** [comment]
I casted everything to `double` in the bin calculation in `BinOp1D`.  I changed the type of the data members to reduce the number of conversions.  I updated `BinOp3D` as well but didn't actually add a test for that guy.

**Review by kmorel — COMMENTED** [review]
I can verify that the changes fix the issue I was originally having when I submitted #4978.

That said, I noticed that some of the regression tests are failing in the PR checks.

**Comment by dalg24** [comment]
There is a `NaN` conversion to `int` in with `double`...

**Comment by dalg24** [comment]
Failure (issue with NVIDIA GPG repo key on the Clang+CUDA build) is unrelated.
https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/

This is ready.

**Review by nliber — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Review by crtrott — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Pull request merged**
