### PR TITLE
GHA: add intel oneapi builds

### PR DESCRIPTION
**Pull request by junghans**
Using https://github.com/kokkos/ci-containers/pull/6 and https://github.com/kokkos/ci-containers/pull/7

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
@junghans why draft?

**Comment by crtrott** [comment]
Retest this please.

**Comment by crtrott** [comment]
This broke horribly. The cmake config line?

**Comment by masterleinad** [comment]
What's the motivation for adding this if we are already testing with `SYCL`? Do we want to check host support? Then, we should at least turn on the SYCL (or the OpenMPTarget) backend.

**Comment by crtrott** [comment]
No, the motivation is to simply use the new Intel compiler for Host OpenMP or even Serial. ICPC is now legacy compiler. This is supposed to be the new Intel production compiler even just for pure CPU machines.

**Comment by masterleinad** [comment]
```
CMake Error: The source directory "/__w/kokkos/kokkos/builddir/-j2" does not exist.
```

**Comment by dalg24** [comment]
> Retest this please.

This only applies to Jenkins.

**Comment by junghans** [comment]
Maybe injecting `--verbose` breaks things....

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Comment by junghans** [comment]
I am bit unsure why `—verbose` breaks things, but ok. Verbose build would be nice to see if the right flags/compiler is used.

**Pull request merged**
