### PR TITLE
Bump Kokkos version on develop

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by crtrott** [comment]
lets do 3.7.99 for now

**Review by crtrott — CHANGES_REQUESTED** [review]
lets do 3.7.99

**Comment by masterleinad** [comment]
> lets do 3.7.99

Changed accordingly.

**Review by crtrott — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Not waiting for CI that seems stuck

**Pull request merged**
