### PR TITLE
Fix Zero Length Reduction failures in Kokkos nightlies for Pthreads

### PR DESCRIPTION
**Pull request by crtrott**
This PR is confirming that the issue with the zero length reducer in PThreads is reproduced if we actually use more than one thread for travis pthreads build... Will add fixes later to this PR and rename.

### CODE REVIEW

**Review by dalg24 — DISMISSED** [review]

**Comment by crtrott** [comment]
I actually expect this to fail btw ...

**Review by dalg24 — APPROVED** [review]
Essentially applying the changes from #3364 `OpenMP/Kokkos_OpenMP_Parallel.hpp `

**Comment by ndellingwood** [comment]
Cross-referencing #3433

**Comment by ndellingwood** [comment]
Cherry-pick to 3.2.1

**Pull request merged**
