### PR TITLE
Kokkos_HPX: update ParallelReduce routines for zero-length redux

### PR DESCRIPTION
**Pull request by ndellingwood**
Addresses failing defaultdevicetype.reduce_instantiation_b* tests

### CODE REVIEW

**Comment by ndellingwood** [comment]
Addresses failures mentioned in https://github.com/kokkos/kokkos/pull/3466#issuecomment-705268360
Basically pattern matches updates for zero-length arrays similar to #3452 and `OpenMP/Kokkos_OpenMP_Parallel.hpp` from #3364 

I confirm this allows failings tests to pass on apollo:

```
[ndellin@apollo unit_test]$ ./KokkosCore_UnitTest_Default --gtest_filter=defaultdevicetype.reduce_instantiation_b*
Note: Google Test filter = defaultdevicetype.reduce_instantiation_b*
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from defaultdevicetype
[ RUN      ] defaultdevicetype.reduce_instantiation_b1
[       OK ] defaultdevicetype.reduce_instantiation_b1 (305 ms)
[ RUN      ] defaultdevicetype.reduce_instantiation_b2
[       OK ] defaultdevicetype.reduce_instantiation_b2 (178 ms)
[ RUN      ] defaultdevicetype.reduce_instantiation_b3
[       OK ] defaultdevicetype.reduce_instantiation_b3 (52 ms)
[----------] 3 tests from defaultdevicetype (535 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (535 ms total)
[  PASSED  ] 3 tests
```

**Comment by ndellingwood** [comment]
[[skipci]]
[[skip-ci]]

**Comment by ndellingwood** [comment]
Just applied clang-format to the changed file

**Comment by ndellingwood** [comment]
Will need cherry-pick to 3.2.1

**Review by crtrott — APPROVED** [review]

**Pull request merged**
