### PR TITLE
Fix bash syntax error

### PR DESCRIPTION
**Pull request by sebrowne**
@etphipp

### CODE REVIEW

**Comment by etphipp** [comment]
Without this change, I get errors like this when building Kokkos on CEE machines that automatically set NVCC_WRAPPER_TMPDIR
```
    Run Build Command(s):/usr/bin/gmake cmTC_f86d4/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_f86d4.dir/build.make CMakeFiles/cmTC_f86d4.dir/build
    gmake[1]: Entering directory `/home/etphipp/project/Trilinos/build/sacado_cuda/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_f86d4.dir/testCXXCompiler.cxx.o
    /ascldap/users/etphipp/project/Trilinos/Trilinos/packages/kokkos/bin/nvcc_wrapper   -g -lineinfo -expt-extended-lambda -Xcudafe --diag_suppress=conversion_function_not_usable -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=code_is_unreachable -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored  -o CMakeFiles/cmTC_f86d4.dir/testCXXCompiler.cxx.o -c /ascldap/users/etphipp/project/Trilinos/build/sacado_cuda/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    nvcc fatal   : Could not open output file 'x/tmpxft_00012b96_0000000a'
    gmake[1]: *** [CMakeFiles/cmTC_f86d4.dir/testCXXCompiler.cxx.o] Error 1
    gmake[1]: Leaving directory `/home/etphipp/project/Trilinos/build/sacado_cuda/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_f86d4/fast] Error 2
```
The issue is temp_dir inside the nvcc_wrapper script is set to "x" in this case, instead of NVCC_WRAPPER_TMPDIR as it should be.

**Review by dalg24 — CHANGES_REQUESTED** [review]
PR must target `develop` branch.  Please update.

**Review by masterleinad — APPROVED** [review]
Yes, `temp_dir` is set to `x` if `NVCC_WRAPPER_TMPDIR` is specified and this pull request fixes that.

**Comment by sebrowne** [comment]
Forgive me for my ignorance but can I change this PR to target develop, or do I need to make a new one?  Can't believe I mistargeted it....

**Comment by sebrowne** [comment]
Closing in favor of #4524

**Comment by dalg24** [comment]
Update the PR the preferred option but that's ok

**Pull request closed without merging**
