### PR TITLE
Update clang-format CI build

### PR DESCRIPTION
**Pull request by dalg24**
The `nvidia/cuda:9.2-devel` image is wildly outdated and we don't actually use CUDA.  Clang+LLVM binaries are available for Ubuntu 14.04 and 16.04.  I picked the more recent one.  In my opinion we need to consider seriously bumping the clang-format version to something much more recent very soon.

As a drive-by-change, the clang-format CI build was already allowed to run on CPU-only nodes or on nodes that had NVIDIA GPUs (marked by labels "docker" and "nvidia-docker" respectively) and I enabled also running on nodes with AMD GPUs ("rocm-docker" label)

### CODE REVIEW

**Review by Rombur — DISMISSED** [review]

**Comment by dalg24** [comment]
> > Clang+LLVM binaries are available for Ubuntu 14.04 and 16.04.
> 
> You mean 16.04 and 18.04? You are using 18.04

Actually 14.04, 16.04, and 18.04 are available.  And I meant to use 18.04

**Comment by dalg24** [comment]
Retest this please

**Comment by masterleinad** [comment]
It currently fails with
```
/bin/sh: 1: gpg: not found
```

**Comment by dalg24** [comment]
> It currently fails with
> 
> ```
> /bin/sh: 1: gpg: not found
> ```

Yup I saw that.  Fixing now

**Review by cz4rs — APPROVED** [review]
Looks good to me, `Clang-Format` stage is passing and all other failures seem irrelevant.

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Pull request merged**
