### PR TITLE
Add implementations of missing HIPHostPinnedSpace methods for LAMMPS

### PR DESCRIPTION
**Pull request by arghdos**
Just the HIPHostPinnedSpace methods of https://github.com/kokkos/kokkos/pull/3102, as discussed this morning

### CODE REVIEW

**Comment by dalg24** [comment]
OK to test

**Comment by dalg24** [comment]
Retest this please

**Comment by arghdos** [comment]
The hanging is ... strange.  I can't reproduce locally:

```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_CXX_FLAGS=-Werror -Wno-unused-command-line-argument -Wno-braced-scalar-init -DKokkos_ENABLE_COMPILER_WARNINGS=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_HIP=ON ..
...
make -j
...
ctest --output-on-failure
...
 3/34 Test  #3: KokkosCore_UnitTest_HIP ................   Passed   49.03 sec
...
100% tests passed, 0 tests failed out of 34

Total Test time (real) = 136.47 sec
```

**Comment by masterleinad** [comment]
Retest this please.

**Pull request merged**
