### PR TITLE
Loosen restriction for using built-in sycl::group_broadcast

### PR DESCRIPTION
**Pull request by masterleinad**
After https://github.com/intel/llvm/pull/4910 has been merged, we can also use `sycl::group_broadcast` for `team_broadcast` for trivially-copyable types.
Fixes https://github.com/intel/llvm/issues/4717.

### CODE REVIEW

**Comment by masterleinad** [comment]
Based on top of #4739.

**Comment by dalg24** [comment]
Is this still on your radar?

**Comment by masterleinad** [comment]
> Is this still on your radar?

Rebased.

**Review by dalg24 — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
Not waiting for OpenMPTarget build.

**Pull request merged**
