### PR TITLE
Fix Volta failures other than tasking see Issue 1395

### PR DESCRIPTION
**Pull request by crtrott**
This fixes Volta builds without RDC enabled. Tasking is still broken.

### CODE REVIEW

**Comment by r-barnes** [comment]
It would probably be good to change the title of this PR or otherwise provide a description of what's been done.

**Comment by stanmoore1** [comment]
@crtrott Can you clarify, does this fix the LAMMPS issue described in #1395?

**Comment by crtrott** [comment]
Yes it does.

**Comment by stanmoore1** [comment]
@crtrott Great, thanks!

**Comment by stanmoore1** [comment]
@crtrott I confirm this fixes the LAMMPS issue mentioned in #1395, using a Titan V on X86 Rhel7 with CUDA 9.1

**Comment by crtrott** [comment]
Did a spot-check on kokkos-rdev. One test failed weirdly with a libkokkos not found error. But going into the directory and just hitting 'make build-test' fixed that. I also tested manually CUDA 7.5 which passed as well. 

```
[crtrott@kokkos-dev KokkosBuild]$ cat nohup.out 
nohup: ignoring input
Running on machine: sems
Repository Status:  043ae39a18356b269ea82c2a9662c6e920c4e74c Fix some CUDA warnings


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0

#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=279 run_time=652
clang-3.9.0-Pthread_Serial-release build_time=281 run_time=1668
cuda-8.0.44-Cuda_OpenMP-release build_time=969 run_time=613
gcc-5.3.0-OpenMP-hwloc-release build_time=408 run_time=764
gcc-6.1.0-Serial-hwloc-release build_time=184 run_time=1467
gcc-6.1.0-Serial-release build_time=304 run_time=1488
intel-17.0.1-OpenMP-hwloc-release build_time=680 run_time=995
intel-17.0.1-OpenMP-release build_time=700 run_time=793
#######################################################
FAILED TESTS
#######################################################
gcc-5.3.0-OpenMP-release (build failed)
```

**Pull request merged**
