### PR TITLE
Remove switch case with fallthrough

### PR DESCRIPTION
**Pull request by tvoskui**
@crtrott @masterleinad Starting fresh here - sorry for the churn, I didn't realize Kokkos had a devel branch workflow too.

### CODE REVIEW

**Comment by dalg24** [comment]
Please address https://github.com/kokkos/kokkos/pull/4845#issuecomment-1060900855

**Comment by tvoskui** [comment]
@dalg24 I do not know the answer to that

**Comment by dalg24** [comment]
If a project downstream properly treats Kokkos as a third-party library, then Kokkos headers should be treated as system headers which would suppress warnings (see compiler documentation).
In the case you are building Kokkos as part of your own project, you may not be able to do so.  We are only committed to build warning-free with the flags listed [here](https://github.com/kokkos/kokkos#build-system).   That said I don't have any particular objection to add implicit fallthrough warnings to the list, but we would have to actually test for it because otherwise you would have no guarantee we break it again tomorrow and also this is definitely not the only place in Kokkos that would raise such a warning.

**Comment by tvoskui** [comment]
It is built with Spack - beyond that I don't know the details. In any case, this PR just gets rid of the fall-through switch case entirely to get around that.

**Review by dalg24 — CHANGES_REQUESTED** [review]
@masterleinad your suggestion is less readable than the original version

**Comment by janciesko** [comment]
Linked PR: #4852

**Pull request closed without merging**
