### PR TITLE
GHA: test flang as FC

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
```
[ 66%] Building Fortran object CMakeFiles/example.dir/foo.f.o
/usr/bin/f18: could not find module file for __fortran_type_info
[100%] Linking CXX executable example
/usr/bin/ld: CMakeFiles/example.dir/foo.f.o: in function `print_fortran_':
f18-8854.f90:(.text+0x3f): undefined reference to `_gfortran_st_write'
/usr/bin/ld: f18-8854.f90:(.text+0x58): undefined reference to `_gfortran_transfer_character_write'
/usr/bin/ld: f18-8854.f90:(.text+0x67): undefined reference to `_gfortran_st_write_done'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/example.dir/build.make:122: example] Error 1
```
it seems the format module has not been ported to f18 yet.

**Comment by junghans** [comment]
Let's try again in 6 months.

**Comment by crtrott** [comment]
@junghans hey I am closing for now, but if you want to try this again and it works feel free to reopen.

**Comment by junghans** [comment]
@masterleinad @crtrott are you still using Fortran in the CI?

**Comment by junghans** [comment]
Ok I will rebase this PR on develop soon, so we get testing with `flang`.

**Pull request closed without merging**
