### PR TITLE
Update to HIP 3.7

### PR DESCRIPTION
**Pull request by masterleinad**
See https://github.com/ROCm-Developer-Tools/HIP/releases/tag/rocm-3.7.0 and https://hub.docker.com/r/rocm/dev-ubuntu-20.04/tags.

### CODE REVIEW

**Comment by arghdos** [comment]
If we're bumping the HIP version, we can get rid of the awful version check in the BlocksizeDeduction as well

**Comment by crtrott** [comment]
How critical is that for you guys. The admins finally got our machine to 3.5 and its working after weeks of back and forth. I would love to be able to do some stuff with HIP on our machine for a while before I have to ask them to upgrade again. If 3.7 did some critical bug fix whcih allows progress I am ok with this, but if it doesn't really fix any of our roadblocks I would love us to support 3.5 for a few more weeks.

**Comment by crtrott** [comment]
E.g. jump to 3.9 or whatever the release is that fixes the critical roadblock bug we got.

**Comment by Rombur** [comment]
There is a bug fix that is useful for block size deduction but unless @dalg24 plans to rewrite the block size deduction the same way he rewrote the block size deduction in CUDA, we can live with 3.5 a little bit longer.

**Comment by dalg24** [comment]
We decided we would extend support for 3.5

**Pull request closed without merging**
