### PR TITLE
Remove Makefiles for installing Kokkos via GNU Make

### PR DESCRIPTION
**Pull request by crtrott**
Addresses #2332

This actually still works with the generate_makefile.bash (which was moved for cleanup purposes):

```
Repository Status:  e7f0aae812663e069b4077df335c900c0386f235 Removing Makefiles which support installing Kokkos via GNU Make


sems-cmake/3.5.2(3):ERROR:150: Module 'sems-cmake/3.5.2' conflicts with the currently loaded module(s) 'sems-cmake/3.12.2'
sems-cmake/3.5.2(3):ERROR:102: Tcl command execution failed: conflict sems-cmake

Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1 hpx/1.2.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
Testing compiler hpx/1.2.1
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
  Starting job hpx-1.2.1-HPX-release
  PASSED hpx-1.2.1-HPX-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=151 run_time=530
clang-6.0-Cuda_Pthread-release build_time=262 run_time=388
clang-6.0-OpenMP-release build_time=130 run_time=118
cuda-9.1-Cuda_OpenMP-release build_time=363 run_time=206
gcc-4.8.4-OpenMP-release build_time=128 run_time=142
gcc-4.8.4-Pthread-release build_time=117 run_time=448
gcc-5.3.0-Serial-release build_time=136 run_time=185
hpx-1.2.1-HPX-release build_time=1156 run_time=416
intel-16.0.1-OpenMP-release build_time=447 run_time=381
```

### CODE REVIEW

**Comment by dalg24** [comment]
Another issue is `git ls-files | grep Makefile$` still reports
```
algorithms/unit_tests/Makefile
benchmarks/atomic/Makefile
benchmarks/bytes_and_flops/Makefile
benchmarks/gather/Makefile
benchmarks/gups/Makefile
benchmarks/policy_performance/Makefile
benchmarks/stream/Makefile
containers/performance_tests/Makefile
containers/unit_tests/Makefile
core/perf_test/Makefile
core/unit_test/Makefile
core/unit_test/standalone/Makefile
example/feint/Makefile
example/fenl/Makefile
example/fixture/Makefile
example/global_2_local_ids/Makefile
example/grow_array/Makefile
example/make_buildlink/Makefile
example/md_skeleton/Makefile
example/multi_fem/Makefile
example/query_device/Makefile
example/sort_array/Makefile
example/tutorial/01_hello_world/Makefile
example/tutorial/01_hello_world_lambda/Makefile
example/tutorial/02_simple_reduce/Makefile
example/tutorial/02_simple_reduce_lambda/Makefile
example/tutorial/03_simple_view/Makefile
example/tutorial/03_simple_view_lambda/Makefile
example/tutorial/04_simple_memoryspaces/Makefile
example/tutorial/05_simple_atomics/Makefile
example/tutorial/06_simple_mdrangepolicy/Makefile
example/tutorial/Advanced_Views/01_data_layouts/Makefile
example/tutorial/Advanced_Views/02_memory_traits/Makefile
example/tutorial/Advanced_Views/03_subviews/Makefile
example/tutorial/Advanced_Views/04_dualviews/Makefile
example/tutorial/Advanced_Views/05_NVIDIA_UVM/Makefile
example/tutorial/Advanced_Views/06_AtomicViews/Makefile
example/tutorial/Advanced_Views/07_Overlapping_DeepCopy/Makefile
example/tutorial/Advanced_Views/Makefile
example/tutorial/Algorithms/01_random_numbers/Makefile
example/tutorial/Algorithms/Makefile
example/tutorial/Hierarchical_Parallelism/01_thread_teams/Makefile
example/tutorial/Hierarchical_Parallelism/01_thread_teams_lambda/Makefile
example/tutorial/Hierarchical_Parallelism/02_nested_parallel_for/Makefile
example/tutorial/Hierarchical_Parallelism/03_vectorization/Makefile
example/tutorial/Hierarchical_Parallelism/04_team_scan/Makefile
example/tutorial/Hierarchical_Parallelism/Makefile
example/tutorial/Makefile
example/tutorial/launch_bounds/Makefile
example/virtual_functions/Makefile
```
so these changes do not fully address the potential misuse reported in #2298

**Comment by crtrott** [comment]
Those Makefiles are largely necessary. They are not part of installing Kokkos though. I fixed the failure which actually needed a small change. The purpose of having both in there right now is to keep testing passing. Should be removed later.

**Comment by dalg24** [comment]
> Those Makefiles are largely necessary.

Is appending `Makefile -> Makefile.deprecated` and then `make -f Makefile.deprecated` an option?

**Comment by crtrott** [comment]
I guess we can do that (though probably more with Makefile.internal since they are not deprecated). That said most of those directories do not have a CMakeList.txt yet anyway.

**Comment by crtrott** [comment]
Let rename the other Makefiles as part of the "Add CMakeList.txt to all examples" thing.

**Pull request merged**
