### PR TITLE
Split TestHalfOperators kernels to improve compilation time with SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
This improved the compilation time of the tests by 60 min (to around 20 min). The runtime of the kernel is negligible.

### CODE REVIEW

**Comment by crtrott** [comment]
So its not even splitting the test into multiple object files its just splitting the kernel 5 ways?

**Review by crtrott — APPROVED** [review]
Not sure I am loving the approach but I also don't immediately have a better idea for low overhead (in terms of lines of code) partitioning of the test.

**Comment by masterleinad** [comment]
> So its not even splitting the test into multiple object files its just splitting the kernel 5 ways?

Yes, since we can compile with `-fsycl-device-code-split=per_kernel` that does the trick.

**Comment by dalg24** [comment]
Looks like the build on the spack gltlab was significantly faster but I did not see improvement on the Jenkins build

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
