### PR TITLE
Issue 1976: fix pthreads dynamic schedule RangePolicy with non-zero begin

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
Spotcheck is running. Unittests were added first, and verified that they failed (i.e. a4510f9 has two failing tests with Pthreads).

**Comment by crtrott** [comment]
```
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? patch_teamvectorrange

Repository Status:  782deb31675231ef66052e912324ee64d63c4e09 Fix RangePolicy for Pthreads with Dynamic Schedule not starting at 0


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=172 run_time=442
clang-6.0-Cuda_Pthread-release build_time=302 run_time=318
clang-6.0-OpenMP-release build_time=147 run_time=84
cuda-9.1-Cuda_OpenMP-release build_time=341 run_time=171
gcc-4.8.4-OpenMP-release build_time=105 run_time=97
gcc-4.8.4-Pthread-release build_time=108 run_time=349
gcc-5.3.0-Serial-release build_time=113 run_time=164
intel-16.0.1-OpenMP-release build_time=377 run_time=167
```

**Comment by crtrott** [comment]
This fixes issue #1976

**Comment by ndellingwood** [comment]
@crtrott approved the PR, ready for merge.

**Pull request merged**
