### PR TITLE
Allow Kokkos to build on 32bit arches

### PR DESCRIPTION
**Pull request by nschloe**

### CODE REVIEW

**Comment by crtrott** [comment]
Hi

couple questions: a) did you test this on 64 bit with all backends (in particular also with Cuda?)
b) I don't quite get all the atomic changes: in particular the one where it seems a function calls itself again (i.e. the double overload). Can you explain what the purpose of that overload is?

**Comment by ginggs** [comment]
Hi!

The only testing I have done is verifying that Trilinos builds successfully and that deal.II builds and runs its build-time test suite successfully on top of that.

The first patch, "Only enable Kokkos assembly functions on amd64", gained us builds on arm64, mips64el and sparc64 on the [Debian buildds](https://buildd.debian.org/status/package.php?p=trilinos&suite=unstable) and on s390x on the [Ubuntu buildds](https://launchpad.net/ubuntu/+source/trilinos/12.6.4-1), where they also have libtbb for s390x.  I have received feedback from the deal.II maintainer that they have run a full test suite on amd64 with this patch included, but I do not know with which backends, or whether CUDA was tested.

The second patch gained us builds on armhf, i386 and x32 (a hybrid i386/amd64 architecture - a 32-bit userspace on top of a 64-bit kernel, for high performance).  However, the build still failed on architectures without __sync_val_compare_and_swap_8, e.g. powerpc and mips.  There was a [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63368) filed requesting an implementation, but has been closed WONTFIX.  That bug does mention a workaround which I would like to investigate.  Also, I do not believe the full deal.II test suite has been run on i386 yet.

Looking at that second patch again now, I'm not sure why `double atomic_compare_exchange` calls itself.  I may have inadvertently created infinite recursion there. :(

Regarding the differing sizes of ```unsigned long``` and ```unsigned long long``` on 32-bit architectures, a more portable solution may be to use ```int64_t``` and ```uint64_t```, which have fixed sizes, instead.

**Comment by mhoemmen** [comment]
> The only testing I have done is verifying that Trilinos builds successfully and that deal.II builds and runs its build-time test suite successfully on top of that.

Would you mind also running the Kokkos and perhaps also Tpetra tests?

**Comment by ginggs** [comment]
@nschloe is it possible to enable these tests during the build?

**Comment by mhoemmen** [comment]
> is it possible to enable these tests during the build?

Yes.  Set the CMake variable `Kokkos_ENABLE_TESTS:BOOL=ON` and run ctest.  If you feel like running other Trilinos packages' tests, that would be even better, but the minimum would be to run Kokkos' tests.  Thanks!

**Comment by nschloe** [comment]
Let's close this one and break it down into smaller pieces.

**Pull request closed without merging**
