### PR TITLE
Fix warnings with xl compiler

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
clang-format fix force pushed

**Review by masterleinad — COMMENTED** [review]
We have
```
IF((NOT (Kokkos_ENABLE_CUDA AND WIN32)) AND (NOT ("${KOKKOS_CXX_COMPILER_ID}" STREQUAL "Fujitsu")))
  TARGET_COMPILE_FEATURES(kokkos_gtest PUBLIC cxx_std_14)
ENDIF()

so we might need to be careful for the respective configurations when setting the compile feature for `kokkosprinter-tool`. Maybe, just put the same guard there?

**Comment by ndellingwood** [comment]
@masterleinad good catch, I force pushed the update with the added guards

**Comment by masterleinad** [comment]
Retest this please.

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Comment by masterleinad** [comment]
Retest this please.

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
we need this also cherry picked into the release branch

**Comment by masterleinad** [comment]
> we need this also cherry picked into the release branch

See #3931.

**Pull request merged**
