### PR TITLE
Incremental testing

### PR DESCRIPTION
**Pull request by rgayatri23**
Unit test for kokkos_malloc and kokkos_free in unit_test/incremental

### CODE REVIEW

**Comment by dalg24** [comment]
How does that PR relates to #2536 and #2537 ?

**Comment by crtrott** [comment]
Please Retest this

**Comment by dalg24** [comment]
Retest this please

**Comment by crtrott** [comment]
The parallel for test needs to copy the data back to the host first.

**Comment by rgayatri23** [comment]
Not needed to merge.

**Pull request closed without merging**
