### PR TITLE
Fix bugprone-undefined-memory-manipulation

### PR DESCRIPTION
**Pull request by masterleinad**
Related to #7575.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
Why did you elect to cast to `void*` which essentially inhibits diagnostic rather than write a suppression comment?
(Not necessarily asking for a change at this time)

**Comment by masterleinad** [comment]
> Why did you elect to cast to `void*` which essentially inhibits diagnostic rather than write a suppression comment?

I know that some compilers would warn depending on the respective kernel so I had thought about fixing it this way already. Ultimately, we really on `memcpy` being suitable in these cases anyway and any kind of warning is more annoying than helpful.

**Review by dalg24 — COMMENTED** [review]
So I expected that we need the changes to `Impl::TrivialWrapper` but I am curious if we actually got warnings for the other places or if you just grepped for it and applied everywhere without giving too much thought about it?

**Comment by masterleinad** [comment]
> I am curious if we actually got warnings for the other places or if you just grepped for it and applied everywhere without giving too much thought about it?

I first only did `TrivialWrapper` and got more complaints, see https://gitlab.spack.io/kokkos/kokkos/-/jobs/14130617, about reductions/scans but I didn't check if there were tests that warned for all of them.

**Review by dalg24 — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Review by JBludau — APPROVED** [review]
lgtm

**Comment by dalg24** [comment]
There is another warning raised in the Clang+CUDA build
```
/var/jenkins/workspace/Kokkos_PR-7590/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:592:5: error: undefined behavior, source object type 'const Kokkos::Impl::ParallelReduce<Kokkos::Impl::CombinedFunctorReducer<TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotl, P<unsigned long long>, 31>, Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE, Kokkos::RangePolicy<Kokkos::Cuda>, TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotl, P<unsigned long long>, 31>, int>::Reducer>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>' is not TriviallyCopyable [bugprone-undefined-memory-manipulation,-warnings-as-errors]
    memcpy(staging, &driver, sizeof(DriverType));
    ^
/var/jenkins/workspace/Kokkos_PR-7590/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:592:5: error: undefined behavior, source object type 'const Kokkos::Impl::ParallelReduce<Kokkos::Impl::CombinedFunctorReducer<TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotl, P<unsigned long>, 31>, Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE, Kokkos::RangePolicy<Kokkos::Cuda>, TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotl, P<unsigned long>, 31>, int>::Reducer>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>' is not TriviallyCopyable [bugprone-undefined-memory-manipulation,-warnings-as-errors]
/var/jenkins/workspace/Kokkos_PR-7590/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:592:5: error: undefined behavior, source object type 'const Kokkos::Impl::ParallelReduce<Kokkos::Impl::CombinedFunctorReducer<TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotr, P<unsigned long long>, 31>, Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE, Kokkos::RangePolicy<Kokkos::Cuda>, TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotr, P<unsigned long long>, 31>, int>::Reducer>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>' is not TriviallyCopyable [bugprone-undefined-memory-manipulation,-warnings-as-errors]
/var/jenkins/workspace/Kokkos_PR-7590/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp:592:5: error: undefined behavior, source object type 'const Kokkos::Impl::ParallelReduce<Kokkos::Impl::CombinedFunctorReducer<TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotr, P<unsigned long>, 31>, Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE, Kokkos::RangePolicy<Kokkos::Cuda>, TestBitRotateFunction<Kokkos::Cuda, BitRotateFunction_rotr, P<unsigned long>, 31>, int>::Reducer>, Kokkos::RangePolicy<Kokkos::Cuda>, Kokkos::Cuda>' is not TriviallyCopyable [bugprone-undefined-memory-manipulation,-warnings-as-errors]
2208 warnings generated when compiling for host.
Suppressed 2242 warnings (2203 in non-user code, 38 NOLINT, 1 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
4 warnings treated as errors
core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/build.make:260: recipe for target 'core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/cuda/TestCuda_BitManipulationBuiltins.cpp.o' failed
make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/cuda/TestCuda_BitManipulationBuiltins.cpp.o] Error 1
CMakeFiles/Makefile2:2045: recipe for target 'core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/all' failed
make[1]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Cuda1.dir/all] Error 2

**Comment by dalg24** [comment]
Ignoring HPX failure
```
/home/runner/work/kokkos/kokkos/kokkos/algorithms/unit_tests/TestRandom.hpp:287: Failure
Expected: (std::abs(variance_eps)) < (1.5 * tolerance), actual: 0.000776915 vs 0.000754056

**Pull request merged**
