### PR TITLE
Disable submitting test results to CDash

### PR DESCRIPTION
**Pull request by masterleinad**
`CDash` has been disabled for quite some already and AFAICT there is no plan to reenable it again. Hence, it appears reasonable to just disable the submit stage that currently fails for every CI run.

### CODE REVIEW

**Comment by dalg24** [comment]
Any good reason to use the CTest script in the first place?

**Comment by masterleinad** [comment]
> Any good reason to use the CTest script in the first place?

I decided to propose a minimal change that addresses the issue I am seeing right now. I don't see much wrong with using the `CTest` script and it is easier to re-enable it if we decide to submit to a CDash instance again.

That being said, I would also be fine with reverting https://github.com/kokkos/kokkos/pull/2844.

**Comment by dalg24** [comment]
>  I don't see much wrong with using the CTest script

1/ Delays printing of the log at each step.  2/ Increased complexity.


>  it is easier to re-enable it if we decide to submit to a CDash instance again.

Sure but we also saw there was little interest in it.

**Comment by dalg24** [comment]
>  I don't see much wrong with using the CTest script

1/ Delays printing of the log at each step.  2/ Increased complexity.


>  it is easier to re-enable it if we decide to submit to a CDash instance again.

Sure but we also saw there was little interest in it.

**Review by crtrott — APPROVED** [review]

**Comment by jrmadsen** [comment]
> `CDash` has been disabled for quite some already and AFAICT there is no plan to reenable it again. Hence, it appears reasonable to just disable the submit stage that currently fails for every CI run.

Yeah, the entire CDash database kept getting corrupted, forcing me to delete all the other projects and reinstall CDash from scratch (I had to do this 3 times over the course of about 2 weeks). I suspected it was because Kokkos was submitting so many results almost simultaneously. So I disabled the project in CDash and planned to give it a couple weeks... the database stopped getting corrupted so I never reenabled the project in CDash. I meant to say something about getting rid of it but it fell by the wayside with all the AMD stuff.

**Pull request merged**
