### PR TITLE
Fix #1208 by using __gnu_parallel::sort if available

### LINKED ISSUE #1208: Kokkos::sort defaults to std::sort on host
Thus, no OpenMP parallelism.  Options to fix:

  1. Use C++17 parallel algorithm extensions, if available
  2. Implement an OpenMP parallel sort, e.g., https://software.intel.com/en-us/articles/a-parallel-stable-sort-using-c11-for-tbb-cilk-plus-and-openmp
  3. ???

### PR DESCRIPTION
**Pull request by mhoemmen**
This is a redo of #1388.
Thanks to @ibaned and @crtrott for reviews and fixes!

I made all changes to Kokkos_Sort.hpp.  Here is what I did:

    1. Conditionally include header for `__gnu_parallel::sort`
    2. Add `try_gnu_sort`, analogous to `try_std_sort`.  It always returns
       false if the above header is not available.  Otherwise, it returns
       true if and only if OpenMP has been initialized, the View's rank is
       1, and the View's stride is 1.

### CODE REVIEW

**Comment by crtrott** [comment]
Mark, you don't need to open a new pull request. We just merge changes into the pull request that is fine. 

This is still not good to go since it will not compiler with NVCC.

**Comment by crtrott** [comment]
Running SpotCheck now on fixed build.

**Comment by crtrott** [comment]
Passed SpotCheck now:
```
Running on machine: apollo
Repository Status:  b1db1c6dad11c346edc9bc657d6916e87785eb35 Fix pull request for 1208 with NVCC


	ERROR loading module sems-tex/2015
	Module points to path  /projects/sems/install/rhel6-x86_64/sems/utility/tex/2015  which does not exist
	Please contact SEMS team
Going to test compilers:  gcc/4.8.4 gcc/5.1.0 intel/16.0.1 clang/3.9.0 clang/4.0.0 cuda/8.0.44
Testing compiler gcc/4.8.4
Testing compiler gcc/5.1.0
  Starting job gcc-4.8.4-OpenMP-release
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler intel/16.0.1
  Starting job gcc-5.1.0-Serial-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED gcc-5.1.0-Serial-release
Testing compiler clang/4.0.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-4.0.0-Cuda_Pthread-release
  PASSED intel-16.0.1-OpenMP-release
  PASSED clang-4.0.0-Cuda_Pthread-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=158 run_time=198
clang-4.0.0-Cuda_Pthread-release build_time=284 run_time=266
cuda-8.0.44-Cuda_OpenMP-release build_time=332 run_time=248
gcc-4.8.4-OpenMP-release build_time=146 run_time=113
gcc-4.8.4-Pthread-release build_time=127 run_time=208
gcc-5.1.0-Serial-release build_time=140 run_time=124
intel-16.0.1-OpenMP-release build_time=411 run_time=136
```

Need to wait for Travis Test.

**Comment by mhoemmen** [comment]
Thanks @crtrott ! :-D

I'm sitting (virtually) in a C++ subcommittee meeting now -- I'm hoping we can eventually let the standard implement sorting as well as other algorithms :-D .

**Comment by mhoemmen** [comment]
FYI @trilinos/tpetra we can pull this into Trilinos right away and start using it :-)

**Comment by ndellingwood** [comment]
@mhoemmen I ran into an error with this commit while trying to build Trilinos with the current Kokkos develop branch- I opened issue #1391 and a temporary workaround.

**Pull request merged**
