### PR TITLE
Include View label in bounds error on GPU

### PR DESCRIPTION
**Pull request by ibaned**
This implements request #870.

Passed the following `test_all_sandia` on `kokkos_dev`
```
cuda-7.0.28-Cuda_OpenMP-debug build_time=596 run_time=675
cuda-7.0.28-Cuda_Serial-debug build_time=435 run_time=797
cuda-8.0.44-Cuda_OpenMP-debug build_time=397 run_time=716
cuda-8.0.44-Cuda_Serial-debug build_time=322 run_time=731
```

### CODE REVIEW

**Comment by stanmoore1** [comment]
Sweet!

**Comment by ibaned** [comment]
One more comment from @dsunder : 
 - [ ] `implementation_get_private_label` can just be `label`, it doesn't grant people more access than before and everything is already in the `Impl` namespace

**Comment by ibaned** [comment]
With 7870e93, passed the following release `test_all_sandia` on `kokkos-dev`:
```
gcc-4.7.2-OpenMP_Serial-hwloc-release build_time=156 run_time=103
gcc-4.7.2-OpenMP_Serial-release build_time=157 run_time=104
```

**Comment by ibaned** [comment]
Also passed this debug:
```
cuda-7.0.28-Cuda_OpenMP-debug build_time=445 run_time=741
```
and I confirmed that
```cpp
#define KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK 1
```
was in `core/KokkosCore_config.h`

**Pull request merged**
