### PR TITLE
Fix Core header files installation

### LINKED ISSUE #4983: 3.6.00 installs the file include/CMakeLists.txt
Project's CMakeLists.txt should never be installed.

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4983
Do not install `core/src/CMakeLists.txt` nor `.cpp` files
```
diff -r install-devel install-thispr
Only in install-devel/include: CMakeLists.txt
Only in install-devel/include/Cuda: Kokkos_CudaSpace.cpp
Only in install-devel/include/Cuda: Kokkos_Cuda_Instance.cpp
Only in install-devel/include/Cuda: Kokkos_Cuda_Locks.cpp
Only in install-devel/include/Cuda: Kokkos_Cuda_Task.cpp
Only in install-devel/include/HIP: Kokkos_HIP_Instance.cpp
Only in install-devel/include/HIP: Kokkos_HIP_Locks.cpp
Only in install-devel/include/HIP: Kokkos_HIP_Space.cpp
Only in install-devel/include/HPX: Kokkos_HPX.cpp
Only in install-devel/include/HPX: Kokkos_HPX_Task.cpp
Only in install-devel/include/OpenMP: Kokkos_OpenMP_Exec.cpp
Only in install-devel/include/OpenMP: Kokkos_OpenMP_Task.cpp
Only in install-devel/include/OpenMPTarget: Kokkos_OpenMPTargetSpace.cpp
Only in install-devel/include/OpenMPTarget: Kokkos_OpenMPTarget_Exec.cpp
Only in install-devel/include/OpenMPTarget: Kokkos_OpenMPTarget_Instance.cpp
Only in install-devel/include/OpenMPTarget: Kokkos_OpenMPTarget_Task.cpp
Only in install-devel/include/SYCL: Kokkos_SYCL.cpp
Only in install-devel/include/SYCL: Kokkos_SYCL_Instance.cpp
Only in install-devel/include/SYCL: Kokkos_SYCL_Space.cpp
Only in install-devel/include/Threads: Kokkos_ThreadsExec.cpp
Only in install-devel/include/Threads: Kokkos_ThreadsExec_base.cpp
Only in install-devel/include/desul: .clang-format
Only in install-devel/include: dummy.cpp
Only in install-devel/include/impl: CMakeLists.txt
Only in install-devel/include/impl: Kokkos_CPUDiscovery.cpp
Only in install-devel/include/impl: Kokkos_Command_Line_Parsing.cpp
Only in install-devel/include/impl: Kokkos_Core.cpp
Only in install-devel/include/impl: Kokkos_Error.cpp
Only in install-devel/include/impl: Kokkos_ExecPolicy.cpp
Only in install-devel/include/impl: Kokkos_HBWSpace.cpp
Only in install-devel/include/impl: Kokkos_HostBarrier.cpp
Only in install-devel/include/impl: Kokkos_HostSpace.cpp
Only in install-devel/include/impl: Kokkos_HostSpace_deepcopy.cpp
Only in install-devel/include/impl: Kokkos_HostThreadTeam.cpp
Only in install-devel/include/impl: Kokkos_MemoryPool.cpp
Only in install-devel/include/impl: Kokkos_MemorySpace.cpp
Only in install-devel/include/impl: Kokkos_NumericTraits.cpp
Only in install-devel/include/impl: Kokkos_Profiling.cpp
Only in install-devel/include/impl: Kokkos_Serial.cpp
Only in install-devel/include/impl: Kokkos_Serial_Task.cpp
Only in install-devel/include/impl: Kokkos_SharedAlloc.cpp
Only in install-devel/include/impl: Kokkos_Spinwait.cpp
Only in install-devel/include/impl: Kokkos_Stacktrace.cpp
Only in install-devel/include/impl: Kokkos_hwloc.cpp
```

### CODE REVIEW

**Comment by dalg24** [comment]
Also a candidate for cherry-picking into 3.6 patch release

**Review by nmm0 — APPROVED** [review]
Looks good to me. At first I thought it would it would re-introduce #4713 but it doesn't on my machine despite the language in the cmake documentation:

```
The FILES_MATCHING option may be given before the first match option to disable installation of files (but not directories) not matched by any expression.
```

So I guess the CMake documentation is wrong or at least confusing?

**Comment by dalg24** [comment]
Same as you, I found the documentation confusing and just tried it out locally.  I can't remember why I had dopped it in the first place.

**Review by cz4rs — APPROVED** [review]
:+1:

**Pull request merged**
