### PR TITLE
Remove redundant RangePolicy constructor

### PR DESCRIPTION
**Pull request by masterleinad**
Following the discussion in https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1708708198675449, there are two possible constructors for
```
Kokkos::RangePolicy        policy(ExecutionSpace(), 0, N);
```
which only differ by a trailing variadic template argument, which is why some compilers have trouble with CTAD in this case. Since the variadic template argument can be empty, we don't actually need the constructor without the variadic template argument.

### CODE REVIEW

**Comment by masterleinad** [comment]
I rebased after #6803 was merged and added the respective test case.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
> Does that change anything about NVCC support?

No, it turns out that actually none of the test cases in that file work with `nvcc 11.0` (and `gcc 9.4.0`). I updated the test case to guard it completely in that case.

**Review by nliber — APPROVED** [review]
This is fine.

Do we want to go further (not necessarily in this P/R) and update the constructor we are forwarding to?  That constructor takes a parameter pack for `Args`, which is overkill, as the only thing you can pass to it is `ChunkSize`.  You can (IMO nonsensically) pass `ChunkSize` multiple times, so technically that would be a breaking change.

**Comment by masterleinad** [comment]
> Do we want to go further (not necessarily in this P/R) and update the constructor we are forwarding to? That constructor takes a parameter pack for `Args`, which is overkill, as the only thing you can pass to it is `ChunkSize`. You can (IMO nonsensically) pass `ChunkSize` multiple times, so technically that would be a breaking change.

@nliber Please take care of that in a follow-up pull request.

**Comment by dalg24** [comment]
Taking a leap of faith.  We are having issues with the CI but we want to make progress on this.

**Pull request merged**
