### PR TITLE
Initialize all data members in RangePolicy default constructor

### LINKED ISSUE #3497: threads.policy_converting_constructor_from_other_policy test hanging in nightly Pthreads builds with gcc
Following merge of PR #3491, nightly Pthreads builds with gcc started timing out in the `policy_converting_constructor_from_other_policy` unit test

Sample reproducer instructions (gcc/8.3.0):
```bash
module load sems-env sems-cmake/3.12.2 sems-gcc/8.3.0

# Via generate_makefile
$KOKKOS_PATH/generate_makefile.bash --with-devices=Pthread,Serial --arch=SNB,Volta70 --compiler=g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples

# Corresponding cmake line
cmake -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_CXX_FLAGS="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized" -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_PTHREAD=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ARCH_SNB=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH

cd core/unit_tests

./KokkosCore_UnitTest_Threads --gtest_filter=threads.policy_converting_constructor_from_other_policy
```

### PR DESCRIPTION
**Pull request by dalg24**
Another attempt to resolve #3497

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
lgtm

**Review by ndellingwood — COMMENTED** [review]
@dalg24 I just tested gcc/8.3 build with Pthreads, hang is still there in the offending test. Is this PR supposed to fully resolve #3497 or is it only an incremental step?

**Comment by dalg24** [comment]
> @dalg24 I just tested gcc/8.3 build with Pthreads, hang is still there in the offending test. Is this PR supposed to fully resolve #3497 or is it only an incremental step?

I was hoping it would.  I can't reproduce locally...

**Comment by dalg24** [comment]
Turns out #3497 was caused by UB in the `TeamPolicy<Threads, ...>` constructor.  I still think we should consider merging the changes I propose in this PR though.

**Review by masterleinad — APPROVED** [review]
Looks good to me. It's also in the spirit of https://github.com/kokkos/kokkos/pull/3494#pullrequestreview-510714753.

**Review by DavidPoliakoff — APPROVED** [review]

**Pull request merged**
