### PR TITLE
#4913: Make View self-assignment not produce double-free

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Comment by ldh4** [comment]
Seeing that `assign` function right above `operator=` has a similar functionality, would this change be needed there as well?

**Review by dalg24 — APPROVED** [review]

**Review by nmm0 — APPROVED** [review]
Looks good!

**Review by crtrott — CHANGES_REQUESTED** [review]
I think @ldh4 might be right. I.e. the assign function should check for something like this==&vt.m_track ?

**Comment by nliber** [comment]
@crtrott @ldh4 I don't think `assign` needs this, as it takes a `View`, not a `ViewTracker`, so self-assignment should not be possible as they are different types.

**Comment by crtrott** [comment]
@nliber but the tracker you are assigning to could be the tracker in the view or not?
```c++
v.m_track.assign(v);
```

**Comment by PhilMiller** [comment]
Perhaps the checks should be made at the layer further down, in `SharedAllocationTracker::assign_{direct,force_disable}`.

Also, there's a typo in the comments on line 63, `hinge`. I'll fix that.

**Comment by PhilMiller** [comment]
In `SharedAllocationTracker`, `operator=` and `assign_direct` are pretty straightforward to reason about, and should pretty clearly be guarded against self-assignment lest they decrement the `SharedAllocationRecord` to 0 and cause a deallocation.

I'm a bit more hesitant to touch `assign_force_disable` and `assign`, because they are potentially expected to also manipulate the flag state regardless of other circumstances. So maybe the right thing to do is to push this as a pre-condition on the callers, that they not be passed self references?

**Comment by PhilMiller** [comment]
Also, I think the actual condition for trackers to be equivalent is that they have the same results from `get_record()`?

**Comment by crtrott** [comment]
I doubt that the problem is if they have the same record, I think its really if the tracker is the same object, not whether they are sharing the same ref count.

**Comment by crtrott** [comment]
Closing this in favor of #5024. It neither let me push to the branch, nor issue a PR against the NexGenAnalytics fork ...

**Pull request closed without merging**
