### PR TITLE
Cleanup remove unused function `global_reduce`

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
`global_reduce` was introduced in 94a07ebbba6a0fde489b2a7b83027ed187e8b3d3 but was only implemented for `CUDA` and was later copied for `HIP` and a stub was created for `SYCL`. Furthermore, it is not tested and not used in `Trilinos`. Hence, I'm in favor of removing it.

**Comment by PhilMiller** [comment]
```
98% tests passed, 1 tests failed out of 46

Total Test time (real) = 2729.50 sec

The following tests FAILED:
	  7 - KokkosCore_UnitTest_CudaTimingBased (Failed)
Errors while running CTest
```

**Comment by PhilMiller** [comment]
Given that the only code changes are in comments and dead code, and the only failure was in a timing test that I would expect to be flaky, could this be merged please?

**Comment by masterleinad** [comment]
Retest this please.

**Review by dalg24 — APPROVED** [review]
Fine by me with the rational from https://github.com/kokkos/kokkos/pull/4189#pullrequestreview-716131907

**Comment by PhilMiller** [comment]
Second time around, all the tests passed. Could one of you please merge this?

**Pull request merged**
