### PR TITLE
Update internal desul file copies to 60c1115

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
OK so fixing an oversight in #6882 and bringing in the `AtomicRef` changes from #6872 (1st stage in stalled PR to introduce an atomic accessor)

Please update https://github.com/kokkos/kokkos/blob/3d27bf596c2ecf985f811d7e71b073c6ecc40d01/.github/workflows/continuous-integration-workflow.yml#L74-L75 too.  Looks good other than that.

**Comment by crtrott** [comment]
done

**Review by masterleinad — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]

**Comment by crtrott** [comment]
There is one unexpected timing  based failure for one of the CUDA builds with SharedSpace the rest looks ok. The way the timing based thing failed looks like a fluke.

**Comment by ndellingwood** [comment]
@crtrott should desul snapshot updates be added to the changelog?

**Comment by masterleinad** [comment]
> @crtrott should desul snapshot updates be added to the changelog?

I wouldn't add it.

**Pull request merged**
