### PR TITLE
Release candidate 3.6.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
The clang-tidy check failed with
```
Statistics zeroed
Scanning dependencies of target kokkosprinter-tool
[  0%] Building CXX object core/unit_test/CMakeFiles/kokkosprinter-tool.dir/tools/printing-tool.cpp.o
Error running 'clang-tidy': No such file or directory
gmake[2]: *** [core/unit_test/CMakeFiles/kokkosprinter-tool.dir/build.make:83: core/unit_test/CMakeFiles/kokkosprinter-tool.dir/tools/printing-tool.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2062: core/unit_test/CMakeFiles/kokkosprinter-tool.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target kokkoscore
[  0%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
[  0%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Command_Line_Parsing.cpp.o
Error running 'clang-tidy': No such file or directory
gmake[2]: *** [core/src/CMakeFiles/kokkoscore.dir/build.make:83: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
Error running 'clang-tidy': No such file or directory
gmake[2]: *** [core/src/CMakeFiles/kokkoscore.dir/build.make:96: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Command_Line_Parsing.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1811: core/src/CMakeFiles/kokkoscore.dir/all] Error 2
gmake: *** [Makefile:161: all] Error 2
Error: Process completed with exit code 2.
```

@dalg24 @masterleinad I had to resolve conflicts in .github/workflows/continuous-integration-workflow.yml after cherry-pick of #5109 and opted for the updates in that PR (as opposed to the existing state of this branch), was this a mistake on my part? I'm not familiar enough with the github workflows framework to discern between the two and opted for changes with the PR that fixed the issues with the Threads backend

**Comment by masterleinad** [comment]
Retest this please.

**Comment by ndellingwood** [comment]
Thanks @masterleinad !

**Comment by masterleinad** [comment]
Retest this please.

**Comment by ndellingwood** [comment]
@dalg24 @crtrott this should be ready for merge; I'll follow up by updating the snapshot to Trilinos

**Comment by fnrizzi** [comment]
why is there another one with same title #5051 ?

**Comment by masterleinad** [comment]
> why is there another one with same title #5051 ?

This targets the release-candidate-3.6.01 branch, #5051 targets master (from the release-candidate-3.6.01) branch. Thus, this is for finalizing the patch release, and the other one is supposed to only update `master`.

**Comment by fnrizzi** [comment]
> > why is there another one with same title #5051 ?
> 
> This targets the release-candidate-3.6.01 branch, #5051 targets master (from the release-candidate-3.6.01) branch. Thus, this is for finalizing the patch release, and the other one is supposed to only update `master` (as far as I understand).

thanks Daniel !

**Pull request merged**
