### PR TITLE
Move acquisition of memory scratch space to its own function

### PR DESCRIPTION
**Pull request by Rombur**
Fixes comment https://github.com/kokkos/kokkos/pull/5448#discussion_r969649443

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]
Thanks for the refactor.  (You need to fix the format.)
Did you consider whether some sort of scope guard that acquire scratch memory at construction and release it upon destruction would improve the code further?  (Not asking you to implement in this PR, just wondering if you explored that idea.)

**Review by masterleinad — CHANGES_REQUESTED** [review]
We use the same type of code in `SYCL` so change it uniformly.

**Comment by masterleinad** [comment]
Let me know if you prefer me to push the `SYCL` changes to this branch.

**Review by masterleinad — APPROVED** [review]
Looking somewhat deeper, we don't actually need the acquisition part in SYCL at the moment anyway.

**Pull request merged**
