### PR TITLE
Make sure messages in Kokkos::abort are newline terminated

### PR DESCRIPTION
**Pull request by masterleinad**
I noticed that some error messages are hard to read because the error message is not terminated by a newline.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
Why do you think the right thing is newline termination in all error message rather than doing it in the implementation of `Kokkos::abort`?

**Comment by masterleinad** [comment]
> Why do you think the right thing is newline termination in all error message rather than doing it in the implementation of `Kokkos::abort`?

The error message is passed as `const char*` making modifying it after the fact pretty difficult/tedious, especially on GPU backends where we can't use a temporary `std::string` or `std::stringstream`.

**Comment by dalg24** [comment]
> > Why do you think the right thing is newline termination in all error message rather than doing it in the implementation of `Kokkos::abort`?
> 
> The error message is passed as `const char*` making modifying it after the fact pretty difficult/tedious, especially on GPU backends where we can't use a temporary `std::string` or `std::stringstream`.

Fair point.  I would still lean towards string manipulation in `Kokkos::abort` rather than add the new lines at call site.  We can see what other think.

**Comment by masterleinad** [comment]
I still think this is the right solution.

**Pull request closed without merging**
