### PR TITLE
Support Reducer in ThreadVectorRange parallel_scan

### PR DESCRIPTION
**Pull request by Char-Aznable**
Partially address https://github.com/kokkos/kokkos/issues/3584

This doesn't include the HIP and/or task backend.

I have tested these using the following code:

```c++
#include <iostream>
#include <iomanip>
#include <utility>
#include <typeinfo>
#include <string>
#include <type_traits>
#include <Kokkos_Core.hpp>
#include <Kokkos_Random.hpp>
#include <Kokkos_DualView.hpp>

using ExecutionSpace = Kokkos::DefaultExecutionSpace;
using namespace std;

using TeamPolicy = Kokkos::TeamPolicy<ExecutionSpace>;
using Team = TeamPolicy::member_type;
static constexpr int n = 1e6;
static constexpr int nTeamThreadRange = 1e3;
static constexpr int nThreadVectorRange = 1e2;
static constexpr int nPerTeam = nTeamThreadRange * nThreadVectorRange;
static constexpr int nTeams = n / nPerTeam;

template < bool bInclusive, class Reducer, class ... Ts>
Kokkos::View<typename Reducer::value_type[n], Ts...>
getExpectedResults(const Reducer& reducer,
  const Kokkos::View<typename Reducer::value_type[n], Ts...>& inputs) {
  using value_type = typename Reducer::value_type;
  static_assert(Kokkos::View<value_type[n], Ts...>::is_hostspace,
    "Input view is not on the host space");
  value_type identity;
  reducer.init(identity);
  Kokkos::View<value_type[n], Ts...> expecteds("expecteds");
  for(int i = 0; i < expecteds.extent(0); ++i) {
    const int iVector = i % nThreadVectorRange;
    const value_type accum = iVector == 0 ? identity : expecteds(i-1);
    const value_type val  = bInclusive ? inputs(i) :
      (iVector == 0 ? identity : inputs(i-1));
    expecteds(i) = accum;
    reducer.join(expecteds(i), val);
  }
  return expecteds;
}

template < bool bInclusive, class Reducer>
void checkScan(const Kokkos::DualView<typename Reducer::value_type[n], ExecutionSpace>& inputs) {

  using value_type = typename Reducer::value_type;
  value_type tmp;
  Reducer reducer(tmp);

  Kokkos::DualView<typename Reducer::value_type[n], ExecutionSpace> outputs("outputs");

  //run ThreadVectorRange parallel_scan 
  TeamPolicy policy(nTeams, Kokkos::AUTO, Kokkos::AUTO);
  const std::string label = (bInclusive ? std::string("inclusive") : std::string("exclusive")) +
    std::string("Scan") + std::string(typeid(Reducer).name());
  Kokkos::parallel_for(label, policy, KOKKOS_LAMBDA (const Team& team) {
    const int iTeam = team.league_rank();
    const int iTeamOffset = iTeam * nPerTeam;
    Kokkos::parallel_for(Kokkos::TeamThreadRange(team, nTeamThreadRange),
      [&](const int i) {
      const int iThreadOffset = i * nThreadVectorRange;
      Kokkos::parallel_scan(Kokkos::ThreadVectorRange(team, nThreadVectorRange),
        [&](const int j, value_type& update, const bool bFinal) {
          const int iElement = j + iTeamOffset + iThreadOffset;
          const auto tmp = inputs.d_view(iElement);
          if(bInclusive) {
            reducer.join(update, tmp);
            if(bFinal) {
              outputs.d_view(iElement) = update;
            }
          } else {
            if(bFinal) {
              outputs.d_view(iElement) = update;
            }
            reducer.join(update, tmp);
          }
      }, reducer);
    });
  });
  Kokkos::fence();
  outputs.modify_device();
  outputs.sync_host();

  auto expected = getExpectedResults<bInclusive>(reducer, inputs.h_view);

  for(int i = 0; i < outputs.extent(0); ++i) {
    if(outputs.h_view(i) != expected(i)) {
      cerr << 
        setw(50) << 
        std::string("Wrong ") + label + std::string(" outputs at ") << 
        setw(10) <<
        i <<
        setw(20) << std::scientific << 
        outputs.h_view(i) <<
        setw(6) <<
        std::string(" != ") << 
        setw(20) << std::scientific << 
        expected(i) << "\n";
    }
    /* else { */
    /*   cout << */
    /*     setw(50) << */
    /*     std::string("Right ") + label + std::string(" outputs at ") << */ 
    /*     setw(10) << */
    /*     i << */ 
    /*     setw(20) << std::scientific << */ 
    /*     outputs.h_view(i) << "\n"; */
    /* } */
  }
}

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv); {
  using T = double;


  Kokkos::DualView<T[n], ExecutionSpace> inputs("inputs");
  Kokkos::Random_XorShift64_Pool<ExecutionSpace> rndPool(1931);
  Kokkos::fill_random(inputs.d_view, rndPool, T{1.0});

  Kokkos::fence();
  inputs.modify_device();
  inputs.sync_host();

  checkScan<false, Kokkos::Prod<T, ExecutionSpace>>(inputs);
  checkScan<true,  Kokkos::Prod<T, ExecutionSpace>>(inputs);

  checkScan<false, Kokkos::Max<T, ExecutionSpace>>(inputs);
  checkScan<true,  Kokkos::Max<T, ExecutionSpace>>(inputs);

  checkScan<false, Kokkos::Min<T, ExecutionSpace>>(inputs);
  checkScan<true,  Kokkos::Min<T, ExecutionSpace>>(inputs);

  } Kokkos::finalize();
}

```

### CODE REVIEW

**Comment by Char-Aznable** [comment]
@crtrott As we talked about this over Slack, is there any chance to get this in? I need to make a decision whether to keep my existing workflow for a lot of code as my branch is diverging from kokkos:develop. Thanks!

**Comment by masterleinad** [comment]
This looks mostly good to me if we combine the implementation with the preexisting ones and actually add the test to the test suite.

**Comment by Char-Aznable** [comment]
xref https://github.com/kokkos/kokkos/pull/3536, for which I could also put this into TeamThreadRange scan but probably in another PR.

I am not familiar with gtest as I used boost.unit_test exclusively so I don't know the best way to put the tests into Kokkos' test suite.

**Comment by masterleinad** [comment]
Superseded by #3861.

**Pull request closed without merging**
