### PR TITLE
#4058: Account for Apple's C library implementation having a less accurate erf(long double)

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
This resolved the failure for me, thanks!

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Fixes #4058

**Comment by dalg24** [comment]
I thought this was a Apple+GCC specific issue.  I develop often with AppleClang and this test has never been failing for me.

**Comment by PhilMiller** [comment]
Maybe libc++ vs libstdc++, though that would be weird since our reference tolerance values are from the folks who maintain the latter that seems to be failing

**Pull request merged**
