### PR TITLE
Drop legacy `Impl::memory_order*`

### PR DESCRIPTION
**Pull request by dalg24**
Related to step 3 in #5789

These are in `Impl::` and I double checked they are not used in Trilinos.

### CODE REVIEW

**Comment by dalg24** [comment]
Retest this please

**Review by ldh4 — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Ignoring the `hipErrorOutOfMemory` failures

**Pull request merged**
