### PR TITLE
Fix compiling with PGI as host compiler

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://github.com/kokkos/kokkos/issues/3125#issuecomment-658290471.
We just try the standard flags for `NVIDIA` instead of asking `CMake` for the version flags for PGI. It might be a good idea to do that always for `NVIDIA` but I didn't want to change too much.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
On second thought, it seems better if we just always use standard flags when using `nvcc` but I am happy to drop the last commit until after the release.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Of course, the last pull request has the problem that we don't set the standard as property anymore. That might cause some problems with flags set downstream.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by jjwilke** [comment]
I'm feeling like this is the wrong way to fix it. We might be better fixing nvcc_wrapper to handle the correct flags.  We went through a bunch of trouble to set C++ standard flags through the compiler features. I don't really want to regress to setting them explicitly as compiler flags.

**Comment by dalg24** [comment]
Superseded by #3254

**Pull request closed without merging**
