### PR TITLE
Ask git for the base directory when fixing formatting

### LINKED ISSUE #3365: Make apply-clang-format not format my entire kokkos-root/.. directory accidently.
the apply-clang-format script unconditionally cds one level up and then runs. If I do source scripts/apply-clang-format in the root dir it will clang-format my entire parent directory! This happened now twice to me since I am in the habid of sourcing scripts instead of just running them. I want this fixed ...

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #3365.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
What will this do if I'm in a git directory above Kokkos?

**Comment by masterleinad** [comment]
That will likely be problematic. If `sourcing` is a valid use case we lose all context information anyway, though. I don't know if we can do any better than the previous solution or this one then.
We could of course error out if we can't find the script at `scripts/apply-clang-format`.

**Comment by DavidPoliakoff** [comment]
```
 We could of course error out if we can't find the script at scripts/apply-clang-format.
```

That's a great idea

**Comment by DavidPoliakoff** [comment]
Actually, an analogous answer would be to check whether the absolute path of the script is equal to the current working directory (or something like that). Basically "if you source this, error out." Bonus points for checking the username and sending a rude message if it's @crtrott ;)

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
