### PR TITLE
Merge pull request #4841 from e10harvey/add_threads_tpl_option

### PR DESCRIPTION
**Pull request by ndellingwood**
cmake: Replace Enable_PTHREAD with ENABLE_THREADS
(cherry picked from commit 947a4967ab3d3ff7de65865b23990b4036983506)

### CODE REVIEW

**Comment by ndellingwood** [comment]
Cross-reference #4841

**Comment by ndellingwood** [comment]
@dalg24 @crtrott this is ready for merge

**Comment by crtrott** [comment]
@ndellingwood @e10harvey this needs to be updated or?

**Comment by ndellingwood** [comment]
@crtrott I think this should be ready for merge, Evan updated the PR

**Comment by ndellingwood** [comment]
@dalg24 this is ready for merge I believe

**Comment by ndellingwood** [comment]
@dalg24 @crtrott this is ready for merge, needed so that the release-candidate-3.6.0 branch compiles when the threads backend is enabled

**Pull request merged**
