### PR TITLE
Implement `Kokkos::Experimental::{min,max,minmax}(std::initializer_list)`

### PR DESCRIPTION
**Pull request by dalg24**
Rational: reviewed some code downstream that was doing things like `min(a, min(b, c)`

Make sure you see the drib-by fixing of a defect in `operator==` for `Kokkos::pair<T1, T2>` that was missing the `constexpr` specifier.
About the overloads I am adding, I just followed closely the design of `std::{min,max,minmax}` (see https://eel.is/c++draft/alg.min.max)

### CODE REVIEW

**Review by PhilMiller — APPROVED** [review]

**Comment by fnrizzi** [comment]
@dalg24 one thing to make sure: `minmax` in the std is supposed to do this: "If several elements are equivalent to the smallest element, the iterator to the first such element is returned. If several elements are equivalent to the largest element, the iterator to the last such element is returned."
I saw that in your minmax tests you don't check for this but only that the values found are the smallest and max, so I would suggest adding a test to verify this. do you agree?

**Review by fnrizzi — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Comment by dalg24** [comment]
> @dalg24 one thing: `minmax` in the std is supposed to do this: " If several elements are equivalent to the smallest, the leftmost such element is returned. If several elements are equivalent to the largest, the rightmost such element is returned."
> I saw that in your minmax tests you don't check for this but only that the values found are the smallest and max.
> I think this is fine because minmax returns the values not iterators.

I overlooked it.  I think actually this means that my `max` and my `minmax` do not follow the standard specs.

**Review by fnrizzi — CHANGES_REQUESTED** [review]
as discussed, i think we need to verify/fix behavior

**Comment by masterleinad** [comment]
Surprisingly, a (different) OpenMPTarget test is failing:
```
[ RUN      ] openmptarget.unique_token_global
4: /var/jenkins/workspace/Kokkos/core/unit_test/TestUniqueToken.hpp:151: Failure
4: Expected equality of these values:
4:   sum
4:     Which is: 9999990
4:   int64_t(N) * R
4:     Which is: 10000000
4: [  FAILED  ] openmptarget.unique_token_global (261 ms)
```

**Comment by dalg24** [comment]
For reference it looks like implementations of the standard library compute the same thing as I did https://godbolt.org/z/qP5Tv3jds

**Comment by fnrizzi** [comment]
@dalg24 
There is a difference in how `max` behaves when it is by itself vs when it is part of `minmax`.

- `std::min(std::initializer_list)`: 
  - If several values are equivalent to the smallest, returns the **leftmost one**

- `std::max(std::initializer_list)`: 
  - If several values are equivalent to the greatest, returns the **LEFTMOST one**

- `std::minmax(std::initializer_list)`: 
  - If several elements are equivalent to the SMALLEST, the **leftmost** is returned. 
  - If several elements are equivalent to the LARGEST, the **rightmost** such element is returned.

See this: https://godbolt.org/z/9EohjbsGT

**Review by fnrizzi — APPROVED** [review]
thanks for getting it through :)

**Pull request merged**
