### PR TITLE
[HIP] Fixup do not use C++11 workaround

### PR DESCRIPTION
**Pull request by dalg24**
Related to #2679

### CODE REVIEW

**Comment by dmcdougall** [comment]
Is that the only place it occurs?  I got multiple compiler errors of the same flavour (but they _could_ have all been coming from this header file...)

**Comment by dalg24** [comment]
> Is that the only place it occurs? I got multiple compiler errors of the same flavour (but they _could_ have all been coming from this header file...)

I am building as we write so not 100% sure.  I haven't caught other occurrences when I grepped for it in `core/src/HIP/`

**Comment by dmcdougall** [comment]
Cool.  Thanks!

**Comment by dalg24** [comment]
@dmcdougall Well it's linking now, so we will know in a while ;)
I am heading home, I think that was it.

**Comment by dmcdougall** [comment]
Thank you for fixing that.

**Pull request merged**
