### PR TITLE
Split Kokkos_SYCL_Parallel*

### PR DESCRIPTION
**Pull request by masterleinad**
Splitting implementations into headers for every policy/parallel_* combination makes it clearer where to find what.

### CODE REVIEW

**Comment by dalg24** [comment]
How does that PR plays with other open PRs such as #6272, #6271, or #6270?
Which ones need to be reviewed/merged first.

**Comment by masterleinad** [comment]
> How does that PR plays with other open PRs such as #6272, #6271, or #6270? Which ones need to be reviewed/merged first.

This one will probably conflict with all of them. My preference would be to get #6264, #6270, #6271, and #6272 merged before this one.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by Rombur** [comment]
Retest this please

**Comment by masterleinad** [comment]
Only `CUDA-11.7-NVHPC` is failing.

**Review by Rombur — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
