### PR TITLE
Fix failing unit test.  Address issue #858

### PR DESCRIPTION
**Pull request by dsunder**

### CODE REVIEW

**Comment by ibaned** [comment]
@dsunder are you sure you want me as the reviewer and not @crtrott ?

**Comment by dsunder** [comment]
Hey Dan, I'm making a quick fix and then I'll reopen.  I put you as a reviewer since Christian is out and it is a straightforward fix.  I'm removing the setenv("OMP_PROC_BIND", false, 0) calls from the code -- that I put in on this branch -- and putting that logic in the appropriate makefiles.

**Comment by ibaned** [comment]
Okay, got it.

**Comment by ibaned** [comment]
@dsunder will we have to do something about `OMP_PROC_BIND` in the TriBITS unit test calls as well?

**Comment by dsunder** [comment]
test_all_sandia on kokkos-dev now builds and test cleanly with these changes.

**Comment by dsunder** [comment]
@ibaned We should modify the Tribits to set OMP_PROC_BIND=false for unit testing.  I did a little searching, and environment variables for testing should be in 'ctest' scripts and not in the CMakeLists.txt.  I know how to do that with raw cmake, but I'm not sure how it works with Tribits.

**Pull request merged**
