### PR TITLE
rename testing scripts

### PR DESCRIPTION
**Pull request by ndellingwood**
Remove cm_* from cmake based scripts
Prepend gnu_ to deprecated makefile-based scripts

### CODE REVIEW

**Comment by ndellingwood** [comment]
Failed with gcc/4.8.4 issue

```
Failed in branch GCC-4.8.4
unexpected EOF
```

Retest this please

**Comment by ndellingwood** [comment]
Jenkins-CI failed again with gcc/4.8.4 issue

```
Failed in branch GCC-4.8.4
unexpected EOF
```

**Comment by dalg24** [comment]
Retest this please

**Comment by ndellingwood** [comment]
@dalg24 @crtrott ready for merge

**Pull request merged**
