### PR TITLE
Replace KOKKOS_DEBUG with KOKKOS_ENABLE_DEBUG

### PR DESCRIPTION
**Pull request by masterleinad**
AFAICT `KOKKOS_DEBUG` is never defined (via `CMake`) and should be replaced by `KOKKOS_ENABLE_DEBUG` which is what this pull request does.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
Fine by me

**Comment by dalg24** [comment]
This is triggering unused parameter warnings on two builds.

**Review by crtrott — APPROVED** [review]

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
It turns out that I need this for #3451. Any chance to merge even though `KokkosCore_UnitTest_OpenMP` is timing out on `GCC-5.3.0`?

**Comment by scottbiersdorff** [comment]
@rgayatri23 

> This is triggering unused parameter warnings on two builds.

Also a compilation error with the nvc++ compiler:

Building CXX object core/src/CMakeFiles/kokkoscore.dir/OpenMPTarget/Kokkos_OpenMPTargetSpace.cpp.o
"/tmp/qa/kokkos_dev_openmptarget_0/kokkos/core/src/OpenMPTarget/Kokkos_OpenMPTargetSpace.cpp", line 228: error: identifier "space" is undefined
    (void)space;
          ^

**Pull request merged**
