### PR TITLE
Fixup NVIDIA GPU arch macro with autodetection

### LINKED ISSUE #3472: KokkosCore_config.h differs if NVIDIA GPU Arch is implicitly determined vs explicitly provided as CMake option
Configuring Kokkos with an explicit GPU arch code results in two macro definitions in `KokkosCore_config.h`, one for the specified arch (e.g. `KOKKOS_ARCH_KEPLER35`) and a more general arch (e.g. `KOKKOS_ARCH_KEPLER`).
When configuring Kokkos without the GPU arch code and letting it be automagically determined, only the more specific arch macro is defined (i.e. `KOKKOS_ARCH_KEPLER35`). It would be nice for this to be consistent, I ran into this with a false-failure in a Trilinos test that relies on the generic arch macros in a case where I did not provide a specific GPU option to cmake at configuration.

**Reproducer example** (on kokkos-dev system with Kepler35 GPU):

Explicitly provided arch configuration
```bash
cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
```

KokkosCore_config.h snip
```c++
#define KOKKOS_ARCH_KEPLER
/* #undef KOKKOS_ARCH_KEPLER30 */
/* #undef KOKKOS_ARCH_KEPLER32 */
#define KOKKOS_ARCH_KEPLER35
/* #undef KOKKOS_ARCH_KEPLER37 */
```

-----

Implicitly determined arch configuration
```bash
cmake -DCMAKE_CXX_COMPILER=$KOKKOS_PATH/bin/nvcc_wrapper -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE $KOKKOS_PATH
```

KokkosCore_config.h snip
```c++
/* #undef KOKKOS_ARCH_KEPLER */
/* #undef KOKKOS_ARCH_KEPLER30 */
/* #undef KOKKOS_ARCH_KEPLER32 */
#define KOKKOS_ARCH_KEPLER35
/* #undef KOKKOS_ARCH_KEPLER37 */
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #3472 

I moved the block after the architecture auto-detection.

### CODE REVIEW

**Comment by dalg24** [comment]
We should consider this for the 3.2 release update

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Review by ndellingwood — APPROVED** [review]
LGTM, confirmed the KokkosCore_config.h file is not consistent in Trilinos with/without specifying the Kokkos ARCH at configure time.

**Comment by ndellingwood** [comment]
`KokkosCore_UnitTest_OpenMP` timed out in CI, unrelated to PR changes
retest this please

**Comment by dalg24** [comment]
Retest this please

**Pull request merged**
