### PR TITLE
Enable KOKKOS_DEBUG_* options for build type Debug

### PR DESCRIPTION
**Pull request by masterleinad**
As noticed in https://github.com/kokkos/kokkos/pull/2262/files#r319693810, `KOKKOS_ENABLE_DEBUG` and `KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK` are not set for `CMAKE_BUILD_TYPE=Debug` while `--debug` enables these preprocessor variables. This seems inconsistent and this pull request changes the default value for these `CMake` options and `KOKKOS_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK` accordingly.

Also, `-lineinfo` was not set properly in `Debug` mode.

### CODE REVIEW

**Comment by crtrott** [comment]
I am not sure that bounds check should be on by default based on the cmake build type. The performance characteristics and also the error behavior changes quite a lot if you do that. Essentially every kernel code generation is dramatically different, so you run in some sense a completely different set of instructions if you do this.

**Comment by crtrott** [comment]
We will discuss this tomorrow at the meeting.

**Comment by masterleinad** [comment]
By default the build type is empty, so these defaults are only set if you explicitly request `Debug` mode.

**Comment by dalg24** [comment]
> We will discuss this tomorrow at the meeting.

Decision:  `CMAKE_BUILD_TYPE` set to `Debug` implies `Kokkos_ENABLE_DEBUG` and `Kokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK` are both `ON`.  `Kokkos_ENABLE_ DEBUG_BOUNDS_CHECK` needs to be set explicitly.

**Comment by masterleinad** [comment]
Yes, I changed that accordingly.

**Pull request merged**
