### PR TITLE
explicitly enable KOKKOS_ENABLE_ASM for archs, not disable

### PR DESCRIPTION
**Pull request by nschloe**
Split off from PR #410. This change enables `KOKKOS_ENABLE_ASM` for amd64 and `x86_64` rather then disabling it "everywhere" else.

Fixes some build errors on Debian.

Thanks to Graham Inggs for the patch.

### CODE REVIEW

**Comment by crtrott** [comment]
Hi, can you issue the pull requests against develop?

**Comment by nschloe** [comment]
@crtrott Changed that.

**Comment by crtrott** [comment]
@nmhamster do you have any objections to this change?

**Comment by nmhamster** [comment]
@crtrott @nschloe looks good to me.

**Pull request merged**
