### PR TITLE
Fix version macros

### PR DESCRIPTION
**Pull request by masterleinad**
As noticed by @lucbv, `cmakedefine` variables are undefined if the `CMake` variable is 0.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]
How didn't we notice before...

**Comment by masterleinad** [comment]
> @masterleinad may I add a unit test and push directly to your branch?

Sure, go ahead!

**Review by lucbv — APPROVED** [review]
Thanks for the update, the unit-test is also a good enhancement : )

**Review by nmm0 — APPROVED** [review]
Looks good to me, we should never have used cmakedefine for this

**Comment by nmm0** [comment]
4.0.0 release branch PR https://github.com/kokkos/kokkos/pull/5872

**Comment by dalg24** [comment]
> Looks good to me, we should never have used cmakedefine for this

You can blame me for that.  Thanks Luc and Daniel for fixing.

**Comment by dalg24** [comment]
For reference this is a fixup for #5424

**Pull request merged**
