### PR TITLE
Fix CUDA 8 build again with activemask

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
I reran just the CUDA checks:

Cuda 9.1 using nvcc:
```
[==========] 142 tests from 3 test cases ran. (351750 ms total)
[  PASSED  ] 142 tests.
```

Clang 6.0 with Cuda 9.0:
```
[==========] 141 tests from 3 test cases ran. (258453 ms total)
[  PASSED  ] 141 tests.
```

**Comment by crtrott** [comment]
And also passed on White with Cuda 8:

```
[==========] 141 tests from 3 test cases ran. (127134 ms total)
[  PASSED  ] 141 tests.
```

**Comment by crtrott** [comment]
Ok if someone approves this we can just merge. The travis checks will not touch the changed files.

**Comment by ndellingwood** [comment]
@crtrott approved, ready for merge

**Comment by vqd8a** [comment]
On white:
```Testing compiler cuda/8.0.44
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  FAILED cuda-8.0.44-Cuda_OpenMP-release

[----------] Global test environment tear-down
[==========] 142 tests from 3 test cases ran. (122036 ms total)
[  PASSED  ] 141 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] cuda.reducers_int
```
If merged, I will fix the correctness comparison by another PR.

**Pull request merged**
