### PR TITLE
Disable OpenMPTarget unit tests that cause ICEs with icpx

### PR DESCRIPTION
**Pull request by masterleinad**
Trying to compile those unit tests with `icpx` for `OpenMPTarget` (and Intel GPUs) causes internal compiler errors.

### CODE REVIEW

**Comment by JBludau** [comment]
Could you comment more details of which version of icpx/GPU combinations this is an issue for? This way we would have it documented here

**Review by crtrott — APPROVED** [review]

**Comment by masterleinad** [comment]
> Could you comment more details of which version of icpx/GPU combinations this is an issue for? This way we would have it documented here

I don't think that I can add anything meaningful. As usual, the compiler version is some compiler drop that doesn't mean anything outside the testbeds.

**Comment by JBludau** [comment]
can you at least mark the disabled tests with a hint to the problem in the `FIXME` comment? Otherwise we probably will forget what the reason was for disabling it

**Review by fnrizzi — APPROVED** [review]

**Comment by masterleinad** [comment]
> can you at least mark the disabled tests with a hint to the problem in the `FIXME` comment? Otherwise we probably will forget what the reason was for disabling it

Here you go.

**Review by JBludau — APPROVED** [review]
looks good

**Comment by masterleinad** [comment]
Retest this please.

**Comment by crtrott** [comment]
Retest this please.

**Pull request merged**
