### PR TITLE
Allow ETI again

### PR DESCRIPTION
**Pull request by masterleinad**
Reverts https://github.com/kokkos/kokkos/pull/2475 mostly. That pull request was meant to remove something unused but it turns out that the code base still allows using explicit template instantiation. It is just not exposed via `CMake` anymore.
The alternative to this pull request is to remove all the files related to ETI, of course. It seems that no one was complaining about this configuration option missing in the last releases.

### CODE REVIEW

**Comment by crtrott** [comment]
I was actually thinking yesterday of putting the PR together to do this. This ETI stuff was a largely failed experiment. It turns out in real applications it takes the compiler as much or more time to navigate the tree of partial specializations to find the right one, as it takes to compile the simple deep copy kernels.

**Comment by masterleinad** [comment]
So your preference is to remove it altogether?

**Comment by crtrott** [comment]
yes

**Comment by masterleinad** [comment]
Even better, we don't have to worry about making that work for the new backends! Pull request incoming.

**Comment by masterleinad** [comment]
Closed in favor of #3157.

**Pull request closed without merging**
