### PR TITLE
Allowing calls with truly no __launch_bounds__

### PR DESCRIPTION
**Pull request by LeviBarnes**
Previous change hurt performance in some cases. This change specifies no launch bounds unless the user provides them.

### CODE REVIEW

**Comment by stanmoore1** [comment]
I cherry-picked 4a95dd0 and confirmed this commit does fix my performance regression issue #1139.

**Comment by ibaned** [comment]
This should fix #1139 when merged

**Comment by hcedwar** [comment]
Hold off on the merge.  I am reviewing.

**Comment by hcedwar** [comment]
replacing with PR #1147

**Comment by crtrott** [comment]
Done via #1147

**Pull request closed without merging**
