### PR TITLE
WIP for OffsetView

### PR DESCRIPTION
**Pull request by swbova**
This supports #567 .

A few notes:

- I do not like the name OffsetView.  I think it generates confusion with the ViewOffset<> class, as well  as the offsets abstraction for mapping multi-d indices into the flat storage.  Perhaps ShiftedView is an alternative?  Moreover, it isn't a View per se, it is a completely different class template.
- I put in code to support 'index semantics'  where min_index(d) <= i <= max_index(d) (inclusive of max)
- also support iterator semantics where  begin(d) <= i < end(d) (exclusive of end)
- Haven't tested RangePolicy for negative begins and interoperability thereof with eg parallel_for()
- Haven't tried to build on the gpu yet.
- Still need to start subviews and deep copy.

I am not sure about providing assignment operators for interoperability.  ie OffsetView = View and View = OffsetView.   I guess because it has a side effect of conversion, which seems inappropriate for the '=' operator.  Currently you can create a View from an OffsetView by calling OffsetView::view(), and you can create an OffsetView from a View by calling a constructor that takes a View and a Kokkos::Array of minimum indices.  

I don't have a unit test, but there is some [code attached](https://github.com/kokkos/kokkos/files/2006815/offsetview.txt)
that I have been using to drive development.  This will give some idea of the intended usage.

### CODE REVIEW

**Comment by swbova** [comment]
Hey, this request already has added value.  Just noticed that I accidentally deleted a LOT of deprecated code from View...oops.  Hafta put that back...

**Comment by tcfisher** [comment]
Here are my opinions:
1. ShiftedView, OffsetView, or GenericBoundsView are all fine to me.
2. Assignment of an OffsetView to a View I think is pretty important. If my viewtype is templated and can be either a View or and OffsetView, I don't want to have to create a traits to get the view. It should just work. I'm surprised OffsetView isn't a View. I'm sure there was a reason but that's the behavior I would want. I think the assignment going the other way is nice as well.

**Comment by ibaned** [comment]
Spot check spits out shadow warnings, these need to get fixed before merging:
```
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:889:52: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
          OffsetView( const View<RT, RP...> & view) :
                                                    ^
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In constructor ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const index_list_type&)’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:905:53: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
                ,const index_list_type & minIndices) :
                                                     ^
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In constructor ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&)’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:927:45: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
                ,const begins_type & begins) :
                                             ^
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:927:45: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int***; RP = {Kokkos::Threads}; DataType = int***; Properties = {Kokkos::Threads}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 3ul>]’:
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:186:89:   required from ‘void Test::test_offsetview_construction(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:418:58:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
          OffsetView( const View<RT, RP...> & view
          ^
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const index_list_type&) [with RT = int**; RP = {Kokkos::Threads}; DataType = int**; Properties = {Kokkos::Threads}; Kokkos::Experimental::index_list_type = std::initializer_list<long int>]’:
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:217:55:   required from ‘void Test::test_offsetview_construction(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:418:58:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:904:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
          OffsetView( const View<RT, RP...> & view
          ^
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&) [with RT = int**; RP = {Kokkos::Threads}; DataType = int**; Properties = {Kokkos::Threads}]’:
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:223:37:   required from ‘void Test::test_offsetview_construction(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:418:58:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:889:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
          OffsetView( const View<RT, RP...> & view) :
          ^
ar cr libkokkos.a Kokkos_Core.o Kokkos_CPUDiscovery.o Kokkos_Error.o Kokkos_ExecPolicy.o Kokkos_HostBarrier.o Kokkos_HostSpace.o Kokkos_HostThreadTeam.o Kokkos_hwloc.o Kokkos_MemoryPool.o Kokkos_Profiling_Interface.o Kokkos_SharedAlloc.o Kokkos_Spinwait.o Kokkos_UnorderedMap_impl.o Kokkos_ThreadsExec_base.o Kokkos_ThreadsExec.o
ranlib libkokkos.a
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int; RP = {Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; DataType = int; Properties = {Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 0ul, void>]’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1210:94:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T>::type>::type Kokkos::Experimental::Impl::subview_offset(const Kokkos::Experimental::OffsetView<D, P ...>&, T) [with D = int*; P = {Kokkos::Threads}; T = int; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T>::type>::type = Kokkos::Experimental::OffsetView<int, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1522:72:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type Kokkos::Experimental::subview(const Kokkos::Experimental::OffsetView<D, P ...>&, Args ...) [with D = int*; P = {Kokkos::Threads}; Args = {int}; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type = Kokkos::Experimental::OffsetView<int, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:265:76:   required from ‘void Test::test_offsetview_subview(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:421:53:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
          OffsetView( const View<RT, RP...> & view
          ^
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int*; RP = {Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; DataType = int*; Properties = {Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 1ul, void>]’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1244:99:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1>::type>::type Kokkos::Experimental::Impl::subview_offset(const Kokkos::Experimental::OffsetView<D, P ...>&, T0, T1) [with D = int**; P = {Kokkos::Threads}; T0 = Kokkos::Impl::ALL_t; T1 = int; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1>::type>::type = Kokkos::Experimental::OffsetView<int*, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1522:72:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type Kokkos::Experimental::subview(const Kokkos::Experimental::OffsetView<D, P ...>&, Args ...) [with D = int**; P = {Kokkos::Threads}; Args = {Kokkos::Impl::ALL_t, int}; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type = Kokkos::Experimental::OffsetView<int*, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:273:89:   required from ‘void Test::test_offsetview_subview(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:421:53:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int*; RP = {Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; DataType = int*; Properties = {Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 1ul, void>]’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1244:99:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1>::type>::type Kokkos::Experimental::Impl::subview_offset(const Kokkos::Experimental::OffsetView<D, P ...>&, T0, T1) [with D = int**; P = {Kokkos::Threads}; T0 = int; T1 = Kokkos::Impl::ALL_t; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1>::type>::type = Kokkos::Experimental::OffsetView<int*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1522:72:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type Kokkos::Experimental::subview(const Kokkos::Experimental::OffsetView<D, P ...>&, Args ...) [with D = int**; P = {Kokkos::Threads}; Args = {int, Kokkos::Impl::ALL_t}; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type = Kokkos::Experimental::OffsetView<int*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:278:89:   required from ‘void Test::test_offsetview_subview(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:421:53:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int**; RP = {Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; DataType = int**; Properties = {Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 2ul, void>]’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1282:103:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1, T2>::type>::type Kokkos::Experimental::Impl::subview_offset(const Kokkos::Experimental::OffsetView<D, P ...>&, T0, T1, T2) [with D = int***; P = {Kokkos::Threads}; T0 = Kokkos::Impl::ALL_t; T1 = Kokkos::Impl::ALL_t; T2 = int; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1, T2>::type>::type = Kokkos::Experimental::OffsetView<int**, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1522:72:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type Kokkos::Experimental::subview(const Kokkos::Experimental::OffsetView<D, P ...>&, Args ...) [with D = int***; P = {Kokkos::Threads}; Args = {Kokkos::Impl::ALL_t, Kokkos::Impl::ALL_t, int}; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type = Kokkos::Experimental::OffsetView<int**, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:290:102:   required from ‘void Test::test_offsetview_subview(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:421:53:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int**; RP = {Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; DataType = int**; Properties = {Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 2ul, void>]’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1282:103:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1, T2>::type>::type Kokkos::Experimental::Impl::subview_offset(const Kokkos::Experimental::OffsetView<D, P ...>&, T0, T1, T2) [with D = int***; P = {Kokkos::Threads}; T0 = Kokkos::Impl::ALL_t; T1 = int; T2 = Kokkos::Impl::ALL_t; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1, T2>::type>::type = Kokkos::Experimental::OffsetView<int**, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1522:72:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type Kokkos::Experimental::subview(const Kokkos::Experimental::OffsetView<D, P ...>&, Args ...) [with D = int***; P = {Kokkos::Threads}; Args = {Kokkos::Impl::ALL_t, int, Kokkos::Impl::ALL_t}; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type = Kokkos::Experimental::OffsetView<int**, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:294:102:   required from ‘void Test::test_offsetview_subview(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:421:53:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp: In instantiation of ‘Kokkos::Experimental::OffsetView<DataType, Properties>::OffsetView(const Kokkos::View<RT, RP ...>&, const begins_type&) [with RT = int***; RP = {Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; DataType = int***; Properties = {Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u>}; Kokkos::Experimental::OffsetView<DataType, Properties>::begins_type = Kokkos::Array<long int, 3ul>]’:
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1320:107:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1, T2, T3>::type>::type Kokkos::Experimental::Impl::subview_offset(const Kokkos::Experimental::OffsetView<D, P ...>&, T0, T1, T2, T3) [with D = int****; P = {Kokkos::Threads}; T0 = Kokkos::Impl::ALL_t; T1 = Kokkos::Impl::ALL_t; T2 = Kokkos::Impl::ALL_t; T3 = int; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, T0, T1, T2, T3>::type>::type = Kokkos::Experimental::OffsetView<int***, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:1522:72:   required from ‘typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type Kokkos::Experimental::subview(const Kokkos::Experimental::OffsetView<D, P ...>&, Args ...) [with D = int****; P = {Kokkos::Threads}; Args = {Kokkos::Impl::ALL_t, Kokkos::Impl::ALL_t, Kokkos::Impl::ALL_t, int}; typename Kokkos::Experimental::Impl::GetOffsetViewTypeFromViewType<typename Kokkos::Impl::ViewMapping<void, Kokkos::ViewTraits<DataType, Properties ...>, Args ...>::type>::type = Kokkos::Experimental::OffsetView<int***, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:360:118:   required from ‘void Test::test_offsetview_subview(unsigned int) [with Scalar = int; Device = Kokkos::Threads]’
/home/daibane/src/kokkos/containers/unit_tests/TestOffsetView.hpp:421:53:   required from here
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘begins’ shadows a member of 'this' [-Werror=shadow]
/home/daibane/src/kokkos/containers/src/Kokkos_OffsetView.hpp:926:10: error: declaration of ‘view’ shadows a member of 'this' [-Werror=shadow]
```

**Comment by swbova** [comment]
thanks!
>

**Comment by swbova** [comment]
passed two spot checks on kokkos-dev:

test_all_sandia --spot-check  --with-cuda-options=enable_lambda cuda/8.0.44
 and 
test_all_sandia --spot-check

#######################################################
PASSED TESTS
#######################################################
cuda-8.0.44-Cuda_OpenMP-release build_time=547 run_time=620
cuda-8.0.44-Cuda_Pthread-release build_time=540 run_time=710
cuda-8.0.44-Cuda_Serial-release build_time=536 run_time=683

#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=206 run_time=263
clang-3.9.0-Pthread_Serial-release build_time=209 run_time=417
cuda-8.0.44-Cuda_OpenMP-release build_time=593 run_time=499
gcc-5.3.0-OpenMP-hwloc-release build_time=185 run_time=130
gcc-5.3.0-OpenMP-release build_time=184 run_time=127
gcc-6.1.0-Serial-hwloc-release build_time=149 run_time=174
gcc-6.1.0-Serial-release build_time=146 run_time=172
intel-17.0.1-OpenMP-hwloc-release build_time=490 run_time=190
intel-17.0.1-OpenMP-release build_time=495 run_time=205

**Pull request merged**
