### PR TITLE
Add TSX-RTM Transaction Regions to HostSpace for Fast Lock Acquire/Release

### PR DESCRIPTION
**Pull request by nmhamster**
1. Add's TSX-RTM Transaction Regions (`XBEGIN` and `XEND`) to `HostSpace` for faster lock acquire and release.
2. Add support for `KOKKOS_ENABLE_TM` to build system if BDW and SKX system architecture is selected.
3. Add `-mrtm` calls when GCC is used to enable TSX-RTM code generation on `SKL`

### CODE REVIEW

**Comment by nmhamster** [comment]
Will re-issue, we need to add RTM support into Broadwell architecture selection as well.

**Comment by crtrott** [comment]
Ok, but we'll probably take until after we got our current issues fixed before accepting it in.

**Comment by nmhamster** [comment]
@crtrott sure. This is no rush for the changes but don't want them to get out of sync if we keep modifying `Makefile.kokkos`.

**Comment by mhoemmen** [comment]
Any plans on exposing a software transactional memory interface, or will this stay an implementation detail for now?

**Comment by nmhamster** [comment]
@mhoemmen - not sure how to do this efficiently on GPU, so probably will be implementation assistance for now. I would like to see this for assembly.

**Comment by mhoemmen** [comment]
@nmhamster Thanks for the quick reply!  I'm mainly just curious.  I don't have any use cases for hardware-assisted transactional memory.

**Comment by crtrott** [comment]
I have been thinking about this. I believe it is possible to emulate one, but it would stink terribly for high conflict rates.

**Comment by mhoemmen** [comment]
The issue with hardware-assisted atomics is that the whole transaction has to fit in a tiny cache, else it fails.  Thus, there's not much room between use cases covered by 128-bit atomic CAS, and use cases that will never fit in cache.

**Comment by nmhamster** [comment]
@crtrott - any chance we can get this PR moved along?

**Comment by nmhamster** [comment]
@crtrott any update on when this is going to make it in?

**Comment by crtrott** [comment]
As soon as we got a promotion through (probably next week).

**Comment by crtrott** [comment]
I am merging manually to fix the merge conflicts.

**Pull request merged**
