### PR TITLE
Fix HIPCC CMake interaction

### PR DESCRIPTION
**Pull request by crtrott**
Fix for #2791 alternative to #2789

### CODE REVIEW

**Comment by crtrott** [comment]
```
cmake -DKokkos_ENABLE_HIP=ON -DKokkos_ARCH_MI60=ON -DCMAKE_CXX_COMPILER=hipcc -DKokkos_ENABLE_TESTS=ON -DCMAKE_CXX_FLAGS=--gcc-toolchain=/home/projects/x86-64/gcc/9.2.0  -DCMAKE_CXX_EXTENSIONS=OFF ~/Kokkos/kokkos
```
This works on my head node.

**Comment by Rombur** [comment]
This doesn't work for me:
```
cd /home/users/bt2/kokkos/build/core/unit_test && /opt/rocm/bin/hipcc  -DGTEST_HAS_PTHREAD=0 -I/home/users/bt2/kokkos/tpls/gtest -I/home/users/bt2/kokkos/build/core/unit_test -I/home/users/bt2/kokkos/core/unit_test  -fno-gpu-rdc -g   -o CMakeFiles/kokkos_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o -c /home/users/coe0132/kokkos/tpls/gtest/gtest/gtest-all.cc
clang-10: error: ROCm agent detector could not identify any valid targets; please specify the target explicitly by passing a valid value to -amdgpu-target
clang-10: warning: -amdgpu-target argument 'gfx000' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]
```

**Comment by crtrott** [comment]
What is your configure line?

**Comment by crtrott** [comment]
What is your configure line?

**Comment by crtrott** [comment]
The issue is the "-fno-gpu-rdc" being used for gtest-all.cc but it doesn't get all Kokkos flags ...

**Comment by Rombur** [comment]
This works for now.

**Comment by alephpiece** [comment]
I was wondering could I just add a link-time option for cross compilation? It may be something like

`target_link_libraries(test PRIVATE --amdgpu-target=gfx906)`

`clang-10` complains that the argument `--amdgpu-target=` is dropped whenever I take this argument as a compile-time option. But it actually is a link-time option. See https://github.com/RadeonOpenCompute/hcc/issues/363

**Pull request merged**
