### PR TITLE
TestVector: Fix dangling-else warning as error

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Fix for error triggered by `-Werror=dangling-else` in nightly gcc builds:

Error message:
```
/home/jenkins/slave/workspace/Kokkos_develop_kokkosdev2_gcc830_openmp_serial_cpp14/kokkos/containers/unit_tests/TestVector.hpp:66:8: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
```

Sample reproducer for kokkos-dev-2:
```bash
  # Reproducer instructions:
  #   Load modules:
        module load sems-env sems-cmake/3.12.2 sems-gcc/8.3.0

        $KOKKOS_PATH/generate_makefile.bash --with-devices=OpenMP --arch=SNB,Volta70 --compiler=/projects/sems/install/rhel7-x86_64/sems/compiler/gcc/8.3.0/base/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="14" --ldflags=""  --kokkos-path=$KOKKOS_PATH --with-options=disable_deprecated_code --with-cuda-options= --no-examples 
```

**Comment by ndellingwood** [comment]
Cross-reference #3123

**Comment by ndellingwood** [comment]
May I add `-Wall` to the GCC/4.8.4 PR test?

**Comment by dalg24** [comment]
I am confused which one of these 
```
-Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized
```
enable `-Wdangling-else`.  I could not figure it out when looking at the [doc](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)

**Comment by ndellingwood** [comment]
-Wall triggers -Wparentheses which triggered dangling-else in this particular case
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

**Comment by dalg24** [comment]
> May I add `-Wall` to the GCC/4.8.4 PR test?

You are always welcome to suggest such changes.  But it should already be set via
https://github.com/kokkos/kokkos/blob/d3d7375337a85ad505814d3702d859c17f7780c2/.jenkins#L238

**Comment by ndellingwood** [comment]
@dalg24 I just peaked at `kokkos/cmake/kokkos_arch.cmake` to confirm and see that `-Wall` should be set for GNU or DEFAULT. I'll monitor the other gcc builds, maybe this only shows up in compiler versions newer than gcc/4.8.4...

**Comment by dalg24** [comment]
The doc for 4.8.4 is [here](https://gcc.gnu.org/onlinedocs/gcc-4.8.4/gcc/Warning-Options.html)

**Comment by dalg24** [comment]
It looks like it was added in the GCC 7 release series

**Comment by ndellingwood** [comment]
@dalg24 Thanks for the older gcc/4.8.4 link, confirmed that gcc/4.8.4 builds without issue without this change (as expected from your comment).

**Comment by dalg24** [comment]
Proposed resolution:  we merge your fix as is and we make sure we enable [readability-braces-around-statements](https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html) when we set up ClangTidy.

@calewis and I are working on this.

**Pull request merged**
