### PR TITLE
Fix compiler warnings with newest SYCL compiler

### PR DESCRIPTION
**Pull request by masterleinad**
The newest compiler drop introduces some more deprecation warnings.

### CODE REVIEW

**Comment by masterleinad** [comment]
Relies on https://github.com/intel/llvm/commit/e99f298e20511ae3f592f1a4d3a491507a91b01c.

**Comment by masterleinad** [comment]
It might make sense to wait for https://github.com/intel/llvm/issues/5215 with this so that `generic_space` can also be used for `SYCL+Cuda`.

**Comment by masterleinad** [comment]
> Do we check/document the version of the compiler? Otherwise looks good

The reported compiler version is still the same so we can't really update it but there should be a new release before our next release and I will update (again) as soon as that happened.

**Comment by trws** [comment]
Has that happened yet @masterleinad? I'm 100% good with this change, but it would be nice to report a compiler version when it works.

**Comment by masterleinad** [comment]
> Has that happened yet @masterleinad? I'm 100% good with this change, but it would be nice to report a compiler version when it works.

@trws https://github.com/intel/llvm/pull/5148 was merged on 12/23/2021 but it's not in the oneAPI 2022.1 release. All nightly releases from this year should support it (including compilers used in the testbeds).

**Comment by dalg24** [comment]
Please cleanup the history

**Comment by masterleinad** [comment]
> Please cleanup the history

Done.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by dalg24** [comment]
```
47: [ RUN      ] default_exec.overlap_mdrange_policy
47: Time MDRangePolicy: NonOverlap: 0.016478 Time Overlap: 0.008292
47: /var/jenkins/workspace/Kokkos/core/perf_test/PerfTest_ExecSpacePartitioning.cpp:476: Failure
47: Expected: (time_overlapped_reduce) < (1.5 * time_no_overlapped_reduce), actual: 0.0180087 vs 0.0132896
47: [  FAILED  ] default_exec.overlap_mdrange_policy (117 ms)

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
