### PR TITLE
Remove atomic_compare_exchange_strong in this file as it overloa…

### PR DESCRIPTION
**Pull request by jrobcary**
…d conflicts with definition in non-Windows file.

### CODE REVIEW

**Comment by jrobcary** [comment]
Now removed.

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
OK to test

**Comment by crtrott** [comment]
What kind of configuration gave the conflict? Asking since we do have Windows tests in our CI which did pass all along.

**Comment by jrobcary** [comment]
Here is my configuration script:

https://github.com/kokkos/kokkos-kernels/files/6448641/grating.txcorp.com-trilinos-ser-config.sh.txt

**Comment by crtrott** [comment]
Oh I see its probably a difference between clang-cl and cl

**Comment by jrobcary** [comment]
The return types are different for the two methods.  Maybe the Windows
on is not up to date?

**Review by Rombur — APPROVED** [review]

**Comment by jrobcary** [comment]
Thanks for approving this.  How do these changes get migrated to the trilinos repo?

**Comment by masterleinad** [comment]
> Thanks for approving this. How do these changes get migrated to the trilinos repo?

We could discuss including it in the next patch release.

**Comment by jrobcary** [comment]
Thanks.  I am trying to understand the process and time scales.
So once in kokkos/master, is it

Kokkos makes a patch release.  (Approx how often?)
Trilinos pick up patch release.

Or do trilinos periodically pull kokkos/master into its repo?

Thx.

**Comment by masterleinad** [comment]
We try to keep `Kokkos` in sync with `Trilinos` as much as we can. This means patches go to kokkos/develop first, are possibly cherry-picked into kokkos/release-candidate* for a (point) release, releases are merged into kokkos/master and snapshotted into `Trilinos`. Releases happen every couple of months as you can see in https://github.com/kokkos/kokkos/releases.

**Pull request merged**
