### PR TITLE
Master release 4.4.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos snapshot PR: https://github.com/trilinos/Trilinos/pull/13334
Do not merge until confirmation that PR has passed testing and is approved

**Comment by ndellingwood** [comment]
* CUDA-12.2-NVHPC-AS-HOST-COMPILER job failed with:
```
[ 26%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Default.dir/default/TestDefaultDeviceTypeViewAPI.cpp.o
/var/jenkins/workspace/Kokkos_PR-7202/bin/nvcc_wrapper: line 659: 12352 Segmentation fault      (core dumped) TMPDIR=${temp_dir} $nvcc_command
make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Default.dir/build.make:328: core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Default.dir/default/TestDefaultDeviceTypeViewAPI.cpp.o] Error 139
make[2]: *** Waiting for unfinished jobs....
```

* SYCL-OneAPI job aborted

* CUDA-11.0.3-Clang-Tidy job failed all unit tests with multiple instances of
```
60:   what():  cudaGetDeviceCount(&count) error( cudaErrorNoDevice): no CUDA-capable device is detected /var/jenkins/workspace/Kokkos_PR-7202/core/src/impl/Kokkos_Core.cpp:134
```

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by ndellingwood** [comment]
Trilinos PR passed https://github.com/trilinos/Trilinos/pull/13334 , this is should be ready for final review

**Review by dalg24 — APPROVED** [review]

**Review by aprokop — APPROVED** [review]

**Comment by dalg24** [comment]
Ignoring NVHPC's segfault and GPU not being detectcect in Clang+CUDA build

**Pull request merged**
