### PR TITLE
Kokkos_Serial: Workaround intel ICE issue with Trilinos

### PR DESCRIPTION
**Pull request by ndellingwood**
Workaround intel/17,18,19 internal compiler error in Trilinos by making m_space_instance a SerialInternal* pointer type

### CODE REVIEW

**Comment by dalg24** [comment]
ClangFormat test failed
```diff
diff --git a/core/src/impl/Kokkos_Serial.cpp b/core/src/impl/Kokkos_Serial.cpp
index 98dd62311..9be629943 100644
--- a/core/src/impl/Kokkos_Serial.cpp
+++ b/core/src/impl/Kokkos_Serial.cpp
@@ -170,10 +170,12 @@ void SerialInternal::resize_thread_team_data(size_t pool_reduce_bytes,
 
 Serial::Serial()
 #if defined(KOKKOS_COMPILER_INTEL)
-    : m_space_instance(&Impl::SerialInternal::singleton()) {}
+    : m_space_instance(&Impl::SerialInternal::singleton()) {
+}
 #else
     : m_space_instance(&Impl::SerialInternal::singleton(),
-                       [](Impl::SerialInternal*) {}) {}
+                       [](Impl::SerialInternal*) {}) {
+}
 #endif
 
 bool Serial::impl_is_initialized() {
```

**Comment by ndellingwood** [comment]
The OpenMPTarget build failed in the `Random_XorShift1024_0` test which fails on occasional, I'm guessing that should be unrelated to the changes in this PR.
`[  FAILED  ] openmptarget.Random_XorShift1024_0 (280 ms)`

**Comment by ndellingwood** [comment]
Update: Testing serial build of Trilinos with these changes allowed a complete build and introduced no new test failures compared to Trilinos' develop branch.

**Comment by ndellingwood** [comment]
Once merged to develop I'll cherry-pick over to release-candidate-3.5.0

**Pull request merged**
