### PR TITLE
Drop protected destructors in derived classes

### PR DESCRIPTION
**Pull request by dalg24**
Tentative fix for #2772

### CODE REVIEW

**Comment by dalg24** [comment]
Did that fix the issue with the Intel compiler?

**Comment by masterleinad** [comment]
This does not compile since they are still defined.

**Comment by dalg24** [comment]
> This does not compile since they are still defined.

Yeah I just saw that :D

**Comment by masterleinad** [comment]
I would just declare the derived destructors `noexcept`.

**Comment by dalg24** [comment]
> I would just declare the derived destructors `noexcept`.

Yes that is issue.  I just don't get why they are protected though.

**Comment by dalg24** [comment]
It looks like it is a Intel 16 error only https://godbolt.org/z/Vb4QeU

**Comment by dhollman** [comment]
All destructors are `noexcept` unless you specifically say `noexcept(false)`.  Not enough of the readers of Kokkos code know that, though, so it's probably a good idea to put it there explicitly. Alternatively, there's no real reason to declare the destructor if it's going to be defaulted. It'll just work.

**Pull request closed without merging**
