### PR TITLE
fix spelling error

### PR DESCRIPTION
**Pull request by nschloe**

### CODE REVIEW

**Comment by mhoemmen** [comment]
Hi Nico!  Alas, Kokkos works like Trilinos, where one must base pull requests against the develop branch.

**Comment by nschloe** [comment]
@mhoemmen Changed.

**Comment by ibaned** [comment]
Hi @nschloe , although it is good common Git workflow to start your topic branch from `master`, it just happens that in the Kokkos project this causes trouble for you because we haven't merged `master` back into `develop` in a while. I've gone ahead and cherry-picked your commit into a new pull request, #1222 . If thats okay with you, lets continue there and close this one.

**Comment by nschloe** [comment]
Sure, thank you!

**Pull request closed without merging**
