### PR TITLE
Kokkos : added experimental team barrier

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
- it passes Kokkos unit tests.
 - the team barrier is more effective on Xeon Phi.
 - for sandybridge, it behaves similar to Kokkos hierarchical team barrier.
 - modification is wrapped by #ifdef KOKKOS_HOST_TEAM_BARRIER_EXPERIMENTAL #endif
 - remove #define KOKKOS_HOST_TEAM_BARRIER_EXPERIMENTAL on Kokkos_Macro.hpp
   to recover the previous version.

### CODE REVIEW

**Comment by crtrott** [comment]
Can I assume that this pull request i mute?

**Comment by hcedwar** [comment]
mute, a.k.a. disregard

**Comment by kyungjoo-kim** [comment]
Oh.... I just put the safe guard team threads and put a performance test on my branch and was about to update this pull request. Anyway. I found another bug in TaskPolicy while testing the core barrier. I am not sure if this is related to the previous bug (testing task only interface does not produce the segmentation fault error. With team interface and tasks are spawned without dependence, it trigger segmentation error. GDB tells me that set_team_shared is where it happens, which is also called from TaskPolicyQueue::driver. I cannot decipher the logic behind of team tasking and shared memory and we can talk after Carter come back.

**Comment by hcedwar** [comment]
you can always open a new pull request - the old one was really stale...

From: kyungjoo-kim +ADw-notifications+AEA-github.com+ADw-mailto:notifications+AEA-github.com+AD4APg-
Reply-To: kokkos/kokkos +ADw-reply++00740e6deba5bd47e8337466503159e5020d23e800e39cab92cf0000000112ef151192a169ce05c758AQA-reply.github.com+ADw-mailto:reply++00740e6deba5bd47e8337466503159e5020d23e800e39cab92cf0000000112ef151192a169ce05c758AQA-reply.github.com+AD4APg-
Date: Wednesday, March 2, 2016 at 1:54 PM
To: kokkos/kokkos +ADw-kokkos+AEA-noreply.github.com+ADw-mailto:kokkos+AEA-noreply.github.com+AD4APg-
Cc: Harold Edwards +ADw-hcedwar+AEA-sandia.gov+ADw-mailto:hcedwar+AEA-sandia.gov+AD4APg-
Subject: +AFs-EXTERNAL+AF0- Re: +AFs-kokkos+AF0- Kokkos : added experimental team barrier (+ACM-58)


Oh.... I just put the safe guard team threads and put a performance test on my branch and was about to update this pull request. Anyway. I found another bug in TaskPolicy while testing the core barrier. I am not sure if this is related to the previous bug (testing task only interface does not produce the segmentation fault error. With team interface and tasks are spawned without dependence, it trigger segmentation error. GDB tells me that set+AF8-team+AF8-shared is where it happens, which is also called from TaskPolicyQueue::driver. I cannot decipher the logic behind of team tasking and shared memory and we can talk after Carter come back.

+IBQ-

**Pull request closed without merging**
