### PR TITLE
Add macro indicating lambda works in all spaces

### PR DESCRIPTION
**Pull request by ibaned**
[#1019]

### CODE REVIEW

**Comment by hcedwar** [comment]
At first glance the proposed new `KOKKOS_ENABLE_LAMBDA_ALL_SPACES` is redundant with
the existing `KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA` 
Typically the `KOKKOS_ENABLE_...` is used for options set at configuration.
Is the requirement for a macro set by Kokkos that indicates dispatch lambdas are unconditionally available in the current configuration?

**Comment by mhoemmen** [comment]
@hcedwar Kokkos' CMake option for enabling lambdas doesn't appear to work.  Kokkos_Macros.hpp just enables lambdas dependent on the CUDA version; it ignores the CMake option.

**Comment by hcedwar** [comment]
The `KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA` is implemented as an output, not an input as the name hints.  Is this already the needed macro?

**Comment by ibaned** [comment]
Force pushed the new solution, `KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA` takes on this new meaning. Added a compile time check. Running spot checks now.

**Comment by ibaned** [comment]
Passed spot checks
```
cuda-7.5.18-Cuda_Serial-release build_time=377 run_time=561
cuda-8.0.44-Cuda_Serial-release build_time=349 run_time=547
```

**Pull request merged**
