### PR TITLE
Address issue #1385 not using __constant__ for lock arrays on CUDA

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
Clang CUDA tests:
```
nohup: ignoring input
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git'
Running on machine: apollo
Repository Status:  7cbb858cb1a6fe5d7dceccd32ab801cdb694dd93 Address issue #1385 not using __constant__ for lock arrays on CUDA


	ERROR loading module sems-tex/2015
	Module points to path  /projects/sems/install/rhel6-x86_64/sems/utility/tex/2015  which does not exist
	Please contact SEMS team
Going to test compilers:  clang/4.0.0
Testing compiler clang/4.0.0
  Starting job clang-4.0.0-Cuda_Serial-release
  Starting job clang-4.0.0-Cuda_Pthread-release
  PASSED clang-4.0.0-Cuda_Serial-release
  PASSED clang-4.0.0-Cuda_Pthread-release
#######################################################
PASSED TESTS
#######################################################
clang-4.0.0-Cuda_Pthread-release build_time=333 run_time=411
clang-4.0.0-Cuda_Serial-release build_time=321 run_time=412
```

**Comment by crtrott** [comment]
Some NVCC based tests:
```
nohup: ignoring input
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git'
Running on machine: apollo
Repository Status:  7cbb858cb1a6fe5d7dceccd32ab801cdb694dd93 Address issue #1385 not using __constant__ for lock arrays on CUDA


	ERROR loading module sems-tex/2015
	Module points to path  /projects/sems/install/rhel6-x86_64/sems/utility/tex/2015  which does not exist
	Please contact SEMS team
Going to test compilers:  cuda/8.0.44 cuda/7.0.28 cuda/7.5.18
Testing compiler cuda/8.0.44
  Starting job cuda-8.0.44-Cuda_Serial-release
  PASSED cuda-8.0.44-Cuda_Serial-release
Testing compiler cuda/7.0.28
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
  Starting job cuda-7.0.28-Cuda_OpenMP-release
  PASSED cuda-7.0.28-Cuda_OpenMP-release
  Starting job cuda-7.0.28-Cuda_Pthread-release
  PASSED cuda-7.0.28-Cuda_Pthread-release
```

**Comment by crtrott** [comment]
Note: this will copy stuff up to the device for each kernel in each translation unit once, not once per teanslation unit. But repeated calls to the same kernel in the same translation unit will not issue copies again.

**Comment by ibaned** [comment]
> Note: this will copy stuff up to the device for each kernel in each translation unit once, not once per translation unit.

@crtrott I'm a bit worried about lifetimes here, the details are tricky. [This page](https://stackoverflow.com/questions/185624/static-variables-in-an-inlined-function) mentions that:
```
A static local variable in an extern inline function always refers to the same object.

7.1.2/4 - C++98/C++14 (n3797)
```

So basically this means that `lock_array_copied` is actually a true global variable if this macro (`KOKKOS_ENSURE_CUDA_LOCK_ARRAYS_ON_DEVICE `) gets put in an `extern inline` function (note that just `inline` is the same as `extern inline`, only `static inline` is different). And I think the `CudaParallelLaunch` constructor is an `extern inline` function. However, because `CudaParallelLaunch` is templated on the "driver type" (which includes functor/lambda, work tag, etc.) then there is a different instantiation of it for every kernel, so I guess they are separated by kernel (but not by translation unit!). There may be trouble if by some bad compilation setup the exact same kernel (same `DriverType`) gets instantiated in two translation units.

Is it worth it just for peace of mine to line up the lifetimes exactly by making `lock_array_copied` a `static` global variable instead of a function-local one? Then it will be per translation unit (always) and if `__device__` is the same they will line up safely.

Then again, I think your current implementation has the benefit that if a translation unit doesn't launch any `Kokkos::Cuda` kernels, then it doesn't get the global variable in it. Maybe thats enough benefit to just say to users "be careful to instantiate your kernel only once".

Actually, this may not be feasible. There is code like the `ViewFill` and other stuff in `Crs` that is all in headers, and if two users fill a `Kokkos::View<double*>` then they both instantiate the kernel. Maybe we should go with the safer option.

Sorry for the stream of consciousness.

**Comment by crtrott** [comment]
SpotCheck:
```
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? benchmarks/atomic/KokkosCore_config.h
?? benchmarks/atomic/KokkosCore_config.tmp
?? benchmarks/atomic/Kokkos_CPUDiscovery.o
?? benchmarks/atomic/Kokkos_Core.o
?? benchmarks/atomic/Kokkos_CudaSpace.o
?? benchmarks/atomic/Kokkos_Cuda_Impl.o
?? benchmarks/atomic/Kokkos_Cuda_Locks.o
?? benchmarks/atomic/Kokkos_Cuda_Task.o
?? benchmarks/atomic/Kokkos_Error.o
?? benchmarks/atomic/Kokkos_ExecPolicy.o
?? benchmarks/atomic/Kokkos_HostBarrier.o
?? benchmarks/atomic/Kokkos_HostSpace.o
?? benchmarks/atomic/Kokkos_HostThreadTeam.o
?? benchmarks/atomic/Kokkos_MemoryPool.o
?? benchmarks/atomic/Kokkos_Profiling_Interface.o
?? benchmarks/atomic/Kokkos_Serial.o
?? benchmarks/atomic/Kokkos_Serial_Task.o
?? benchmarks/atomic/Kokkos_SharedAlloc.o
?? benchmarks/atomic/Kokkos_Spinwait.o
?? benchmarks/atomic/Kokkos_UnorderedMap_impl.o
?? benchmarks/atomic/Kokkos_hwloc.o
?? benchmarks/atomic/libkokkos.a
?? benchmarks/atomic/main.o
?? benchmarks/atomic/test.cuda

Repository Status:  83b8110a753550f5879167dad3f3c53a32fbe41f Make locak_array_copied a true static file scope variable


	ERROR loading module sems-tex/2015
	Module points to path  /projects/sems/install/rhel6-x86_64/sems/utility/tex/2015  which does not exist
	Please contact SEMS team
Going to test compilers:  gcc/4.8.4 gcc/5.1.0 intel/16.0.1 clang/3.9.0 clang/4.0.0 cuda/8.0.44
Testing compiler gcc/4.8.4
Testing compiler gcc/5.1.0
  Starting job gcc-4.8.4-Pthread-release
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler intel/16.0.1
  Starting job gcc-5.1.0-Serial-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED gcc-5.1.0-Serial-release
Testing compiler clang/4.0.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-4.0.0-Cuda_Pthread-release
  PASSED intel-16.0.1-OpenMP-release
  PASSED clang-4.0.0-Cuda_Pthread-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=158 run_time=197
clang-4.0.0-Cuda_Pthread-release build_time=286 run_time=263
cuda-8.0.44-Cuda_OpenMP-release build_time=329 run_time=255
gcc-4.8.4-OpenMP-release build_time=144 run_time=114
gcc-4.8.4-Pthread-release build_time=127 run_time=211
gcc-5.1.0-Serial-release build_time=140 run_time=116
intel-16.0.1-OpenMP-release build_time=412 run_time=136
```

**Comment by ibaned** [comment]
Here are some performance numbers for an application running in a mode where all the kernels are small (the mesh is tiny). This uses a recent copy of Kokkos develop, and the second dataset just reverts the merge commit from this pull request. I run the test 4 times to get better statistics.
```
Kokkos bf7831f10957104828f6104c976abc2ce79924cd

1/1 Test #4: cube .............................   Passed    4.63 sec
1/1 Test #4: cube .............................   Passed    5.01 sec
1/1 Test #4: cube .............................   Passed    4.64 sec
1/1 Test #4: cube .............................   Passed    4.65 sec

Kokkos: no lock arrays fix

1/1 Test #4: cube .............................   Passed    6.37 sec
1/1 Test #4: cube .............................   Passed    5.40 sec
1/1 Test #4: cube .............................   Passed    5.41 sec
1/1 Test #4: cube .............................   Passed    5.46 sec
```

**Pull request merged**
