### PR TITLE
Fix duplicated linker flags

### LINKED ISSUE #2305: Duplicated compile flags in tests
Trying to compile with `Kokkos` configured via
"-DKokkos_OPTIONS=COMPILER_WARNINGS,CUDA_LAMBDA,CUDA_RELOCATABLE_DEVICE_CODE,CUDA_UVM" using `nvcc_wrapper` gives
```
cd /scratch/my_docker/kokkos/build/core/unit_test && /opt/cmake/bin/cmake -E cmake_link_script CMakeFiles/KokkosCore_UnitTest_DefaultInit_14.dir/link.txt --verbose=1
/scratch/my_docker/kokkos/bin/nvcc_wrapper    --relocatable-device-code=true CMakeFiles/KokkosCore_UnitTest_DefaultInit_14.dir/UnitTestMain.cpp.o CMakeFiles/KokkosCore_UnitTest_DefaultInit_14.dir/default/TestDefaultDeviceTypeInit_14.cpp.o  -o KokkosCore_UnitTest_DefaultInit_14 libkokkos_gtest.a ../../libkokkos.a libkokkos_gtest.a --relocatable-device-code=true /usr/lib/x86_64-linux-gnu/libdl.so
nvcc fatal   : redefinition of argument 'relocatable-device-code'
```
In fact, all compile flags are duplicated. The same compile line after enabling warnings looks like
```
cd /scratch/my_docker/kokkos/build/core/unit_test && /opt/cmake/bin/cmake -E cmake_link_script CMakeFiles/KokkosCore_UnitTest_DefaultInit_14.dir/link.txt --verbose=1
/scratch/my_docker/kokkos/bin/nvcc_wrapper    -Wall -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized --relocatable-device-code=true CMakeFiles/KokkosCore_UnitTest_DefaultInit_14.dir/UnitTestMain.cpp.o CMakeFiles/KokkosCore_UnitTest_DefaultInit_14.dir/default/TestDefaultDeviceTypeInit_14.cpp.o  -o KokkosCore_UnitTest_DefaultInit_14 libkokkos_gtest.a ../../libkokkos.a libkokkos_gtest.a -Wall -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized --relocatable-device-code=true /usr/lib/x86_64-linux-gnu/libdl.so
nvcc fatal   : redefinition of argument 'relocatable-device-code'
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2305 for me.

### CODE REVIEW

**Comment by dalg24** [comment]
> Fixes #2305 for me.

#2305 description is outdated.  `Kokkos_OPTIONS` has been deprecated.  Please update.

Does https://github.com/kokkos/kokkos/pull/2383/commits/09a521377b40f74c25bd423c304c217f7247d185 show the duplicated flags?  If not, how would one reproduce the issue.

**Comment by masterleinad** [comment]
After deprecating `KOKKOS_OPTIONS`, I see the failing build with
```
cmake -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_TESTS=ON  ..
```
and `CMake version` 3.13.4. I don't see the duplicated flags in https://github.com/kokkos/kokkos/commit/09a521377b40f74c25bd423c304c217f7247d185.

**Comment by dalg24** [comment]
How does this PR interact with #2384 ?

**Comment by masterleinad** [comment]
#2384 doesn't fix the problem but deleting the same lines still lets me compile and run the tests successfully.

**Comment by jjwilke** [comment]
I missed a 3.13 check. If you look kokkos_tribits.cmake line 342 - 3.13 finally introduces the command `target_link_options`. So kokkos is adding link options in `INTERFACE_LINK_OPTIONS`.  The test library is adding the same flags, but only doing it the only way of adding them to `INTERFACE_LINK_LIBRARIES`. Separate variables must not get deduplicated - hence the doubling of the flags.  I think we just need to replicate the logic around if 3.13.

**Comment by masterleinad** [comment]
>  I think we just need to replicate the logic around if 3.13.

I can confirm that that works as well. Is there any reason trying adding these flags at all if they are already set correctly transitively? In particular, I observe the exact compile commands replicating the logic and just deleting it, both with `CMake 3.13.4` and with `CMake 3.10.2`.

**Comment by jjwilke** [comment]
Yeah, test libraries probably don't need to be built with all the Kokkos bells and whistles. Probably it's good enough to just set the C++ standard feature and leave it be.

**Comment by masterleinad** [comment]
> I would say keep the deletion but then make sure `target_compile_features` are set based on `KOKKOS_CXX_STANDARD`.

I don't see any difference adding that, but it should also not harm.

**Comment by masterleinad** [comment]
@jeffmiles63 Can you please test if this is sufficient for #2362? If not, please tell me how to reproduce the errors you see.

**Comment by masterleinad** [comment]
Let's go with #2384 then. That fixes the issue for me as well.

**Pull request closed without merging**
