### PR TITLE
Use SYCLSharedUSMSpace in TestDualView

### PR DESCRIPTION
**Pull request by masterleinad**
Similar to what #5112 does.

### CODE REVIEW

**Comment by dalg24** [comment]
Will conflict with #5112

**Comment by masterleinad** [comment]
> Will conflict with https://github.com/kokkos/kokkos/pull/5112

Just like half of my other pull requests, I guess. :slightly_smiling_face:

**Review by dalg24 — APPROVED** [review]
I suppose this can go first since I just requested changes on the other PR.
Sorry Jakob

**Review by JBludau — APPROVED** [review]
glad you saw this, I wanted to message you but forgot

**Pull request merged**
