### PR TITLE
Makefile.kokkos: update KOKKOS_INTERNAL_CXX**_FLAG

### PR DESCRIPTION
**Pull request by ndellingwood**
Part of issue #1914, this allows the XL compiler to properly set
flags for c++14, c++17, etc.

### CODE REVIEW

**Comment by ndellingwood** [comment]
Fix issue with setting the cxxstandard through generate_makefile with the xlC compiler, reported by @nmhamster in #1914.

**Comment by ndellingwood** [comment]
@crtrott can you take at the change? I tested by generating makefiles on white with xl and gcc with/without the cxxstandard option, and comfirmed the build line in each case had the proper flag for -std=c++**.

**Comment by crtrott** [comment]
Check whether those are actually known flags.

**Comment by ndellingwood** [comment]
@crtrott 

c++17: `/opt/ibm/xlC/16.1.0/bin/.orig/xlC: error: 1501-210 command option std contains an incorrect subargument`

c++1y: works fine

c++1z: `/opt/ibm/xlC/16.1.0/bin/.orig/xlC: error: 1501-210 command option std contains an incorrect subargument`

c++2a: `/opt/ibm/xlC/16.1.0/bin/.orig/xlC: error: 1501-210 command option std contains an incorrect subargument`

Updated the commit with changes; rebased to cleanup the commit history which required a force-push.

**Comment by ndellingwood** [comment]
@crtrott I fixed the comments for the variables not recognized by xl, this should be ready to merge now.

**Pull request merged**
