### PR TITLE
CTAD (deduction guides) for reducers

### PR DESCRIPTION
**Pull request by nliber**
Refactoring #5319 into smaller P/Rs

### CODE REVIEW

**Comment by dalg24** [comment]
All the builds with GPU backend that actually ran the test you added are failing (CUDA build that passes is using generated GNU makefiles and does not have the `reduce_ctads` unit test)
```
4: [ RUN      ] cuda.reducer_ctads
4: Kokkos::Impl::ViewOffset assignment of LayoutLeft from LayoutStride  requires stride == 1
4: Backtrace:
4:                         [0xebcef0]
4:                         [0xeb0e08]
4:                         [0xeb0e88]
4:                         [0x420e46]
4:                         [0xd9c843]
4:                         [0xd9be1c]
4:                         [0xd9bca6]
4:                         [0xe85684]
4:                         [0xe5d8e8]
4:                         [0xe5ec80]
4:                         [0xe5f54b]
4:                         [0xe6f37e]
4:                         [0xe86254]
4:                         [0xe6ed9c]
4:                         [0x41c2f0]
4: __libc_start_main [0x7faf59dc4bf7]
4:                         [0x41c1fa]
 4/45 Test  #4: KokkosCore_UnitTest_Cuda1 ....................Child aborted***Exception:  41.79 sec
```

**Review by crtrott — CHANGES_REQUESTED** [review]
Should this just be a compile only test with static asserts?

**Comment by nliber** [comment]
Tests are now compile-time.

**Review by tcclevenger — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Fine with me. You could probably reduce the size of the tests using some macros since it's fairly repetitive.

**Review by PhilMiller — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Pull request merged**
