### PR TITLE
[3.7.01] Add support for detecting MPI local rank with MPICH

### PR DESCRIPTION
**Pull request by dalg24**
Cherry-pick #5525 into RC 3.7.01

### CODE REVIEW

**Comment by dalg24** [comment]
Will ignore OpenACC failure

**Review by masterleinad — APPROVED** [review]

**Review by JBludau — APPROVED** [review]
same as for the develop

**Comment by dalg24** [comment]
Ignoring OpenACC build failure

**Comment by stanmoore1** [comment]
We also have these in LAMMPS: `PMI_LOCAL_RANK` for ALCF Polaris, `MPT_LRANK` for HPE MPI

**Comment by dalg24** [comment]
> We also have these in LAMMPS: `PMI_LOCAL_RANK` for ALCF Polaris, `MPT_LRANK` for HPE MPI

I can't find any mention of `MPT_LRANK`.  Do you know where it is documented?

**Comment by stanmoore1** [comment]
Not sure, it was given to us by someone who had a cluster running SGI MPT.

**Pull request merged**
