### PR TITLE
nvcc_wrapper: Will interoperate better with SEMS compiler modules

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jgfouca** [comment]
@crtrott , this might be worth a quick look. The idea is to use an environment variable set by the SEMS compiler modules to pick the default compiler inside nvcc_wrapper.

**Comment by nmhamster** [comment]
Jim, you might be able to probe the GPU type from nvidia-smi?

**Comment by crtrott** [comment]
I am not sure I 100% agree with this change. In the end nvcc_wrapper is meant for more than Sandia machines and in particular more than SEMS supported machines. Maybe it would be better the other way around that the SEMS modules set the Kokkos environment variable. 

Regarding probing the GPU, we could do that potentially but there are issues with multi GPU systems as well as clusters, where you can't probe the GPU on the nodes you are building at (e.g. on shannon and titan).

**Comment by nmhamster** [comment]
Does this have to be a "SEMS" prefixed variable, couldn't we have a KOKKOS_DEFAULT_COMPILER in the environment and have the SEMS modules export that too?

**Comment by crtrott** [comment]
Thats what we have already: NVCC_WRAPPER_DEFAULT_COMPILER.

**Comment by jgfouca** [comment]
So far, the SEMS team has resisted me putting Kokkos specific stuff directly into SEMS stuff (e.g. defining KOKKOS environment variables in SEMS modules).

I just did a force push to add support back for NVCC_WRAPPER_DEFAULT_COMPILER as a fallback option if SEMS_COMPILER is not defined. I did not intend to take that out, sorry.

This should not impact people outside sandia... SEMS_COMPILER won't be defined and you'll get the original behavior.

**Comment by jgfouca** [comment]
As far as the GPU probing, it does not have to be full-proof, it just has to provide a reasonable default in most cases to save the user some typing in the common cases.

**Comment by crtrott** [comment]
Yeah but regarding the GPUs at the moment the reasonable default is CC3.5 which is true for effectively everyone at the moment except for laptops.

**Comment by jgfouca** [comment]
Fair enough, I'll remove my comment. What do you think about my previous comment?

**Comment by jgfouca** [comment]
Closing, not going to merge.

**Pull request closed without merging**
