### PR TITLE
Add support for SpacemiT K60 (RISC-V)

### PR DESCRIPTION
**Pull request by diehlpk**
Recently, the first RISC_V CPU (SpacemiT K60) which supports vectorization was released. I am attempting to compile Kokkos with scalar types for now and this allows to compile Kokkos on the boards. 

A second pull request with support for SVE vectorization will follow.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
I know virtually nothing about RISC-V architectures but it seems like you conflated a product name with the architecture.
Should it be called "64GCVB" instead?

**Comment by lucbv** [comment]
@dalg24 do we have a clear idea of how we name these though? Some of the ARM ones are just `ARMVX_PRODUCT` others are `ARMVX`? On the other hand most `x86_64` architectures are just named after the vendor product line name?

**Comment by dalg24** [comment]
> @dalg24 do we have a clear idea of how we name these though? Some of the ARM ones are just `ARMVX_PRODUCT` others are `ARMVX`? On the other hand most `x86_64` architectures are just named after the vendor product line name?

I don't.  Suggestion on how to improve the status quo are welcome.

**Comment by diehlpk** [comment]
> I know virtually nothing about RISC-V architectures but it seems like you conflated a product name with the architecture. Should it be called "64GCVB" instead?

As far as I understand the full name of the CPU is `SpacemiT K1 Otca-core X60(RV64GCVB),RVA22,RVV1.0`.

So I am happy to use `RV64GCVB` instead.

**Comment by diehlpk** [comment]
@dalg24 I updated the name.

**Comment by diehlpk** [comment]
> > @dalg24 do we have a clear idea of how we name these though? Some of the ARM ones are just `ARMVX_PRODUCT` others are `ARMVX`? On the other hand most `x86_64` architectures are just named after the vendor product line name?
> 
> I don't. Suggestion on how to improve the status quo are welcome.

For the first RISC-V support, we use `RISCV_CPUNAME` and I liked that approach.

**Comment by lucbv** [comment]
My worry is that we might have more than one `RISCV_CPUNAME` that ends up with the same compiler flags which is a bit unfortunate. I like RVA22V it states the profile and the optional V extension that is supported, RVA22V is also a superset of RV64GCBV so technically more precise than the later...

**Comment by diehlpk** [comment]
Screenshot 2024-08-07 at 2 22 40 PM

It seems that vectorization works and we see improvements. Scaling does not work so well but it is a single-board computer anyways.

**Comment by diehlpk** [comment]
> My worry is that we might have more than one `RISCV_CPUNAME` that ends up with the same compiler flags which is a bit unfortunate. I like RVA22V it states the profile and the optional V extension that is supported, RVA22V is also a superset of RV64GCBV so technically more precise than the later...

Ok, I can use  RVA22V and will do soon a new commit.

**Comment by diehlpk** [comment]
@lucbv I changed the name. Could you please have a look again?

**Review by lucbv — APPROVED** [review]

**Comment by lucbv** [comment]
@diehlpk that's okay with me, thanks for taking the time to look at this and discuss it!

**Comment by diehlpk** [comment]
@dalg24 could you please have a look? I would like to get it merge to setup some weekly tests.

**Comment by dalg24** [comment]
Retest this please (worried about the format)

**Review by crtrott — APPROVED** [review]
I agree with the name, the reasoning seems as good as any.

**Comment by ndellingwood** [comment]
Looks like this needs a 4.5 changelog entry

**Pull request merged**
