### PR TITLE
Clean up KOKKOS_LIB_INCLUDE_DIRECTORIES, append include directories to associated targets in Trilinos builds

### PR DESCRIPTION
**Pull request by ndellingwood**
Motivated by issue https://github.com/trilinos/Trilinos/issues/12984 , thanks to @maartenarnst for triage within the Trilinos issue

Remove `KOKKOS_HAS_TRILINOS` branch from the `KOKKOS_LIB_INCLUDE_DIRECTORIES` function, as it is no longer needed since TriBITS/Trilinos has switched to using targets

### CODE REVIEW

**Comment by ndellingwood** [comment]
This change got me past the build errors in Trilinos of the form:
```
17:35:55 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPC_Serial/Trilinos/kokkos/core/src/View/MDSpan/Kokkos_MDSpan_Header.hpp(47): catastrophic error: cannot open source file "/home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPC_Serial/Trilinos/kokkos/core/src/View/MDSpan/Kokkos_MDSpan_Header.hpp"
17:35:55   #include <mdspan/mdspan.hpp>
```

It is hacky, I'm all ears for suggestions for a more preferred way to handle this

**Comment by masterleinad** [comment]
```diff
diff --git a/cmake/kokkos_tribits.cmake b/cmake/kokkos_tribits.cmake
index 3ebf775fa..cfc7db252 100644
--- a/cmake/kokkos_tribits.cmake
+++ b/cmake/kokkos_tribits.cmake
@@ -490,15 +490,11 @@ ENDFUNCTION()
 
 
 FUNCTION(KOKKOS_LIB_INCLUDE_DIRECTORIES TARGET)
-  IF(KOKKOS_HAS_TRILINOS)
-    #ignore the target, tribits doesn't do anything directly with targets
-    TRIBITS_INCLUDE_DIRECTORIES(${ARGN})
-  ELSE() #append to a list for later
-    KOKKOS_LIB_TYPE(${TARGET} INCTYPE)
-    FOREACH(DIR ${ARGN})
-      TARGET_INCLUDE_DIRECTORIES(${TARGET} ${INCTYPE} $<BUILD_INTERFACE:${DIR}>)
-    ENDFOREACH()
-  ENDIF()
+  #append to a list for later
+  KOKKOS_LIB_TYPE(${TARGET} INCTYPE)
+  FOREACH(DIR ${ARGN})
+    TARGET_INCLUDE_DIRECTORIES(${TARGET} ${INCTYPE} $<BUILD_INTERFACE:${DIR}>)
+  ENDFOREACH()
 ENDFUNCTION()
 
 FUNCTION(KOKKOS_LIB_COMPILE_OPTIONS TARGET)
```
should also fix it (and goes toward cleaning up special casing for `Trilinos`/`TrBbITS`).

**Comment by masterleinad** [comment]
> @masterleinad that change should be generally safe? I wasn't bold enough to try that before putting in this PR, but that is definitely preferred

Yes, `Trilinos` should have switched to using targets and your pull request is essentially doing the same anyway.

**Comment by ndellingwood** [comment]
@masterleinad I tested a build of Tpetra and test against the install after ripping out the Trilnos-branch of the `KOKKOS_LIB_INCLUDE_DIRECTORIES` and all looks well, I'll update the PR

The documentation https://tribits.org/doc/TribitsUsersGuide.html#tribits-include-directories had me nervous about install testing ramifications with removing the branch, but maybe the use of the `BUILD_INTERFACE` generator expression removes the potential issue (maybe I misunderstand the usage and tribits interactions)? In any case, install testing ran fine and will be nice to clean up `KOKKOS_LIB_INCLUDE_DIRECTORIES`

**Comment by ndellingwood** [comment]
I updated the title and description to better reflect changes following @masterleinad 's suggestion

**Review by nmm0 — APPROVED** [review]
Looks good, thanks for fixing this!

**Review by masterleinad — APPROVED** [review]

**Comment by ndellingwood** [comment]
HIP CI jobs failed with `what():  Desul::Error: init_lock_arrays_hip: post malloc error(hipErrorOutOfMemory): hipErrorOutOfMemory` runtime failures, unrelated to changes in this PR

@crtrott @dalg24 PR should be ready for merge when you get the chance

**Comment by ndellingwood** [comment]
@dalg24 @crtrott any requests on changes? Otherwise, this should be ready for merge

**Pull request merged**
