### PR TITLE
Fix bogus warnings with deprecated `MasterLock`

### PR DESCRIPTION
**Pull request by dalg24**
Fix warnings reported here https://github.com/kokkos/kokkos/issues/4828#issuecomment-1098578333

@ndellingwood would you try cherry-picking this into RC 3.6

cc @rppawlo

### CODE REVIEW

**Comment by ndellingwood** [comment]
> @ndellingwood would you try cherry-picking this into RC 3.6

@dalg24 will do, thanks!

**Review by ndellingwood — APPROVED** [review]

**Comment by rppawlo** [comment]
Thanks @dalg24 !

**Review by Rombur — APPROVED** [review]

**Comment by ndellingwood** [comment]
Cherry-picked to release-candidate-3.6.0 PR #4967

**Comment by masterleinad** [comment]
Already part of Kokkos 3.6.0.

**Pull request merged**
