### PR TITLE
More math functions

### LINKED ISSUE #4765: Consider implementing nextafterf and friends math functions
This function (and maybe some [others](https://en.cppreference.com/w/cpp/numeric/math/nextafter)) could useful in certain situations. For example, when rounding up a double to a nearest float, e.g.
```c++
#include <cmath>
float round_up(double x) {
  float f = x;
  if (double(f) < x)
    x = std::nextafterf(x, FLT_MAX);
}
```
A particular use case in mind is being conservative when constructing a reduced precision bounding volume around a set of data so that it is guaranteed that all the values are within that bounding volume (i.e., no false negatives).

This function in the C++ standard since C++11, but I'm not sure how portable it is.

I've seen some implementations doing it by multiplying by `1 + 2^(-23)` for positive values to round up, and `1 - 2^(-23)` to round down for floats. Others seem to do bit manipulation on integers.

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4765 
Partially resolving #4767 

Adding `round`, ~~`rint`,~~ `logb`, `nextafter`, `copysign`,  and `signbit`
~~Adding `round`, `lround`\*, `llround`\*\*, `rint`, `lrint`\*, `llrint`\*\*, `logb`, `nextafter`, `copysign`,  and `signbit`~~
Naming functions that are missing in comments
~~** are missing with the SYCL backend~~

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
Looks OK to me. I checked that the respective `SYCL` functions are indeed not implemented.
We should add unit tests, though.

**Comment by dalg24** [comment]
Withdrawing the functions that are prefix with `l` and `ll` and that are not provided by SYCL.  I overlooked that their return type was `long` and `long long` respectively.  Will push tests shortly.

**Comment by dalg24** [comment]
`signbit` is not tested (not trying to sweep it under the carpet but would rather withdraw than right all the boilerplate code needed)

**Comment by dalg24** [comment]
On 2nd thought withdrawing `rint` for now since CUDA does not honor the dynamically-set rounding mode.  We can revisit later.

**Comment by dalg24** [comment]
Retest this please

**Review by Rombur — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Looks OK to me,

**Comment by dalg24** [comment]
Failure is clearly unrelated (clang crashing when compiling `TestOpenMPTarget_Complex.cpp`)

**Pull request merged**
