### PR TITLE
Replace TeamThreadRange by TeamVectorRange in local_deep_copy

### PR DESCRIPTION
**Pull request by janciesko**
Replaces TeamThreadRange by TeamVectorRange in local_deep_copy. This potentially improves concurrency. 
Implements issue: #4054

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
This looks reasonable. Have you tried to measure performance improvements?

**Comment by janciesko** [comment]
Good point, let me see if this scales with vec size > 1 now.

**Comment by janciesko** [comment]
```
#include <Kokkos_Core.hpp>
using view_t = Kokkos::View<double*>;
using teampolicy_t = Kokkos::TeamPolicy<>;

int main(int argc, char *argv[]) {
    Kokkos::ScopeGuard kokkos(argc, argv);
    int N = argc > 1 ? atoi(argv[1]) : 100000000;
    int tsize = argc > 2 ? atoi(argv[2]) : 1;
    int vecsize = argc > 3 ? atoi(argv[3]) : 1; 
    {
        view_t view = view_t("View", N);        
        teampolicy_t team_policy = teampolicy_t(1,tsize,vecsize);
        Kokkos::Timer timer;
        Kokkos::parallel_for(team_policy,
          KOKKOS_LAMBDA (const teampolicy_t::member_type & team)
          {
                Kokkos::Experimental::local_deep_copy(team, view, 1.234);   
          });

        Kokkos::fence();
        double t = timer.seconds();
        printf("%f\n", t);
    }
}
```
is giving:
Figure_2
Figure_1

**Comment by janciesko** [comment]
Retest this please

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
(resolved conflicts introduced by merge of #4520)

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Comment by janciesko** [comment]
Retest this please

**Review by rgayatri23 — APPROVED** [review]

**Comment by janciesko** [comment]
Retest this please

**Pull request merged**
