### PR TITLE
Warn if a command line argument prefixed by `--kokkos*` is not recognized

### PR DESCRIPTION
**Pull request by dalg24**
Do not silently ignore a `--kokkos*` argument because it is likely a typo.

Drive-by changes:
* Fix typo in error message and replace mentions to deprecated command line arguments
* Refactor to avoid code duplication when processing args

### CODE REVIEW

**Review by cz4rs — COMMENTED** [review]
Looks good. Can you add a unit test for `parse_command_line_arguments` so we have the desired behavior documented?

**Comment by dalg24** [comment]
One thing to consider is that other project in the Kokkos ecosystem might want to define their own command line argument and this change would force them to parse their own command line argument before Kokkos gets initialized.
@lucbv @nmm0 @janciesko

**Comment by dalg24** [comment]
From a Slack discussion with @nmm0: we could exclude `--kokkos-ext*`

**Review by cz4rs — APPROVED** [review]
Looks good to me.
Some additional tests are in the "nice to have" category and shouldn't block getting this merged.

**Comment by dalg24** [comment]
We decided we would not warn at this time.  Will open a new PR with
```diff
diff --git a/core/src/impl/Kokkos_Core.cpp b/core/src/impl/Kokkos_Core.cpp
index 7bc007ed9..dc689581c 100644
--- a/core/src/impl/Kokkos_Core.cpp
+++ b/core/src/impl/Kokkos_Core.cpp
@@ -735,9 +735,6 @@ void parse_command_line_arguments(int& narg, char* arg[],
       if (check_arg(arg[iarg], "--kokkos-help")) {
         remove_flag = true;
       }
-    } else if (strncmp("--kokkos", arg[iarg], 8) == 0) {
-      std::cerr << "Warning: command line argument '" << arg[iarg]
-                << "' was not recognized and will be ignored" << std::endl;
     }

     if (remove_flag) {
```

**Pull request closed without merging**
