### PR TITLE
Improved handling of exit code from ctest in CI

### PR DESCRIPTION
**Pull request by jrmadsen**
@dalg24 @masterleinad

### CODE REVIEW

**Comment by dalg24** [comment]
Please add a dummy commit that breaks code to verify that CDash does not show that tests are passing.
We can drop it before we merge

**Comment by jrmadsen** [comment]
> Please add a dummy commit that breaks code to verify that CDash does not show that tests are passing.
We can drop it before we merge

Verified that adding `#include <break_ctest_for_all_compilers.hpp>` to Kokkos_Core.hpp caused everything to fail

**Review by dalg24 — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Comment by dalg24** [comment]
Merging despite the SYCL failure.  @nliber @masterleinad please look into these

**Pull request merged**
