### PR TITLE
Update compilers tested nightly on kokkos-dev:

### PR DESCRIPTION
**Pull request by jgfouca**
Remove gcc 4.8.4, add gcc/6.1.0, remove clang/3.5.2 and 3.6.1, add clang/3.7.1 and 3.8.1 and 3.9.0, remove cuda 7.0.28, add cuda 8.0.44

### CODE REVIEW

**Comment by jgfouca** [comment]
@crtrott let me know if you like these updates.

**Comment by jgfouca** [comment]
Going to merge since I removed 3.5.2 from SEMS NFS TPLs.

**Comment by crtrott** [comment]
This was not right. We still need Cuda 7, GCC 4.8.4 and at least clang 3.6 (which was only released last year).

**Comment by mhoemmen** [comment]
Don't we need GCC 4.7.2 still?

**Comment by crtrott** [comment]
That was not dropped.

**Pull request merged**
