### PR TITLE
Fix GCC 4.x issue

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
Fixes issue #2460

**Comment by dhollman** [comment]
Probably should leave a comment that this works around a GCC 4.x bug

**Comment by crtrott** [comment]
How was this not caught earlier:
```
/var/jenkins/workspace/Kokkos/core/src/impl/Kokkos_Error.hpp:122:3: error: use of the 'nodiscard' attribute is a C++17 extension [-Werror,-Wc++17-extensions]

  KOKKOS_ATTRIBUTE_NODISCARD

  ^
```

**Comment by crtrott** [comment]
This even fails with clang only. (Clang 3.9 in this case).
```
/projects/sems/install/rhel6-x86_64/sems/compiler/clang/3.9.0/base/bin/clang++ -I./ -I/home/crtrott/Kokkos/kokkos/core/src -I/home/crtrott/Kokkos/kokkos/containers/src -I/home/crtrott/Kokkos/kokkos/algorithms/src -I/home/crtrott/Kokkos/kokkos/core/src/eti --std=c++11 -mavx --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base -I./ -I/home/crtrott/Kokkos/kokkos/core/src -I/home/crtrott/Kokkos/kokkos/containers/src -I/home/crtrott/Kokkos/kokkos/algorithms/src -I/home/crtrott/Kokkos/kokkos/core/src/eti -I/home/crtrott/Kokkos/kokkos/tpls/gtest -I/home/crtrott/Kokkos/kokkos/core/unit_test -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized   -c /home/crtrott/Kokkos/kokkos/core/unit_test/threads/TestThreads_AtomicOperations_complexfloat.cpp
In file included from /home/crtrott/Kokkos/kokkos/core/unit_test/threads/TestThreads_Init.cpp:46:
In file included from /home/crtrott/Kokkos/kokkos/core/unit_test/TestInit.hpp:49:
In file included from /home/crtrott/Kokkos/kokkos/core/src/Kokkos_Core.hpp:53:
In file included from /home/crtrott/Kokkos/kokkos/core/src/Kokkos_Serial.hpp:55:
In file included from /home/crtrott/Kokkos/kokkos/core/src/Kokkos_Parallel.hpp:52:
In file included from /home/crtrott/Kokkos/kokkos/core/src/Kokkos_View.hpp:53:
In file included from /home/crtrott/Kokkos/kokkos/core/src/Kokkos_HostSpace.hpp:57:
/home/crtrott/Kokkos/kokkos/core/src/impl/Kokkos_Error.hpp:122:3: error: use of the 'nodiscard' attribute is a C++1z extension [-Werror,-Wc++1z-extensions]
  KOKKOS_ATTRIBUTE_NODISCARD
  ^
/home/crtrott/Kokkos/kokkos/core/src/Kokkos_Macros.hpp:614:38: note: expanded from macro 'KOKKOS_ATTRIBUTE_NODISCARD'
#define KOKKOS_ATTRIBUTE_NODISCARD [[nodiscard]]
```

**Comment by dhollman** [comment]
How is that getting defined as anything other than empty? We can pull out the `nodiscard` stuff if it will help. Basically, I think the compiler is reporting that it supports `nodiscard` (even though it's not part of the standard you asked for)

**Comment by crtrott** [comment]
OK "#if defined(__has_cpp_attribute)" is not good enough a test. This needs to have an explicit compiler dependend list for which compilers this works and doesn't.

**Comment by crtrott** [comment]
Yeah my guess is the compiler misreports. Actually maybe the problem is that the __has_cpp_attribute comes from the header files (i.e. GCC) but then the compiler (clang or nvcc) has to do something with nodiscard and fails ...

**Comment by dhollman** [comment]
No, `__has_cpp_attribute` always comes from the compiler directly.

We probably should just use `#if defined(KOKKOS_ENABLE_CXX17) || defined(KOKKOS_ENABLE_CXX20)`

**Comment by dhollman** [comment]
By the way, in a separate issue, `KOKKOS_ENABLE_CXX17` should mean that `KOKKOS_ENABLE_CXX14` and `KOKKOS_ENABLE_CXX11` are also enabled...

**Comment by crtrott** [comment]
I gotta leave the office, can you change the discard thing to simply enable if KOKKOS_ENABLE_CXX17 || 20?

**Comment by masterleinad** [comment]
I guess checking that the value returned from `__has_cpp_attribute(nodiscard)` is at least 201603 would also have worked. At least, https://godbolt.org/z/xclIrY shows that the feature macro is defined as zero up to `clang 5.0`.

**Comment by masterleinad** [comment]
It would be good to decide what to do here soonish so that all the other pull requests compile again (after rebasing).

**Pull request merged**
