### PR TITLE
nvcc wrapper: remove troubling flag to fix 6628

### PR DESCRIPTION
**Pull request by fnrizzi**
fixes https://github.com/kokkos/kokkos/issues/6628 , but still investigating why

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]

**Comment by fnrizzi** [comment]
> I's like to understand better what the problem here is.

i agree, i was looking into it

**Comment by ndellingwood** [comment]
For reference, the nvcc_wrapper impacted Cuda+OpenMP nightly builds for multiple combos of cuda + gcc that were tested (cuda/11.0,1,2,4,7 and cuda/12.0 + gcc/8.3,5 and gcc/9.2)

**Comment by masterleinad** [comment]
Ultimately, `CMake`s `find_package` doesn't seem to handle to handle `-v` well when used for `nvcc` (instead of the host compiler). The behavior for `--verbose` is the same but requesting verbose `Makefiles` adds `-v` to the compiler flags and not `--verbose`. It would remove `--verbose` as well, though, to be consistent if we decide to remove `-v` from the flags `nvcc` handles.

**Comment by ndellingwood** [comment]
@masterleinad interesting, so the issue is cmake-nvcc interaction? I suppose this did not occur for example in the CUDA-12.2-NVHPC CI build (which tests with OpenMP and CUDA) since nvc++ was the compiler rather than nvcc?

**Comment by masterleinad** [comment]
> I suppose this did not occur for example in the CUDA-12.2-NVHPC CI build (which tests with OpenMP and CUDA) since nvc++ was the compiler rather than nvcc?

Possibly, I think `-DCMAKE_VERBOSE_MAKEFILE=ON` triggered the issue with `nvcc` at least.

**Comment by ndellingwood** [comment]
@masterleinad are you okay to move forward with this PR for avoiding the issue?

**Comment by masterleinad** [comment]
> @masterleinad are you okay to move forward with this PR for avoiding the issue?

As I said before, I would prefer to remove `--verbose` for consistency (even if it's not triggered right now).

**Comment by fnrizzi** [comment]
@masterleinad done

**Review by masterleinad — APPROVED** [review]

**Review by cz4rs — APPROVED** [review]

**Comment by dalg24** [comment]
> > @masterleinad are you okay to move forward with this PR for avoiding the issue?
> 
> As I said before, I would prefer to remove `--verbose` for consistency (even if it's not triggered right now).

Why is it ok to remove?  That flag was supported before #6615

**Comment by masterleinad** [comment]
> Why is it ok to remove? That flag was supported before #6615

My only concern is that we would run into the same problems if `CMake` decides to use `--verbose` instead of `-v`. Note that these flags would still not be ignored but just passed to the host compiler instead.

**Review by crtrott — CHANGES_REQUESTED** [review]
I am against removing --verbose

**Review by crtrott — APPROVED** [review]

**Pull request merged**
