### PR TITLE
Disable gcc-5.3.0 in CI temporarily

### PR DESCRIPTION
**Pull request by masterleinad**
All pull requests are currently failing because of problems in `gcc-5.3.0`. This pull request disables that CI check until we have a proper fix.

### CODE REVIEW

**Comment by Rombur** [comment]
I am working on creating a new image today.

**Comment by masterleinad** [comment]
Superseded by #4576.

**Comment by nmm0** [comment]
#4576 is ICE'ing right now, should we merge this temporarily, disabling gcc 5, until the ICE is worked out?

**Review by nmm0 — APPROVED** [review]
Looks good to me but we should wait for at least another team member in agreement before merging.

**Review by Rombur — APPROVED** [review]

**Pull request merged**
