### PR TITLE
Make Kokkos::initialize(/* no args */) honor environment variables 

### LINKED ISSUE #2719: Kokkos environment variables are not respected when using Kokkos::initialize() with no arguments
The check for environment variables occurs in lines https://github.com/kokkos/kokkos/blob/7df3e14cedd8d59eed1b790eeaed81c97d4446ff/core/src/impl/Kokkos_Core.cpp#L674-L826 of the `void initialize(int& narg, char* arg[])` routine. 

Variables are then set and passed to `Impl::initialize_internal(arguments)`.

However, if `Kokkos::initialize()` is called without any arguments, this results in the call https://github.com/kokkos/kokkos/blob/7df3e14cedd8d59eed1b790eeaed81c97d4446ff/core/src/Kokkos_Core.hpp#L126 which calls to `Impl::initialize_internal(arguments)` https://github.com/kokkos/kokkos/blob/7df3e14cedd8d59eed1b790eeaed81c97d4446ff/core/src/impl/Kokkos_Core.cpp#L839-L841 without any checking of arguments or environment variables, resulting in use of environment variables not being respected.

### PR DESCRIPTION
**Pull request by dalg24**
Fix #2719

### CODE REVIEW

**Comment by dalg24** [comment]
> Looks reasonable to me. Did you test locally that everything works as expected?


You know I did not.  See 5d258dc I had not even tried to compile ;)

**Comment by dalg24** [comment]
Retest this please

**Comment by masterleinad** [comment]
> You know I did not. See [5d258dc](https://github.com/kokkos/kokkos/commit/5d258dced65b24bb8ac1d99e0415b7bd6b4cab08) I had not even tried to compile ;)

Actually not. That commit was building when I commented so I assumed you might have figured it out and checked it.
We should really just make sure the environmental variables are respected as expected before merging.

Retest this please.

**Comment by dalg24** [comment]
Retest this please

**Comment by masterleinad** [comment]
I did some testing locally and eveything worked fine.

**Comment by dalg24** [comment]
Retest this please

**Pull request merged**
