### PR TITLE
Add missing C++11 flags to algorithms gtest library

### LINKED ISSUE #2744: Older clang and gcc nightly failures on kokkos-dev
Since renaming of testing scripts to use the cmake build system, older clang and gcc nightly builds are failing with error messages like:

```
cd /home/ndellin/kokkos/testing/ClangTestAll/TestAll_2020-02-10_12.41.16/clang/4.0.1/Serial-release/core/src && /projects/sems/install/rhel6-x86_64/sems/compiler/clang/4.0.1/base/bin/clang++   -I/home/ndellin/kokkos/testing/ClangTestAll/TestAll_2020-02-10_12.41.16/clang/4.0.1/Serial-release/core/src -I/home/ndellin/kokkos/core/src -I/home/ndellin/kokkos/testing/ClangTestAll/TestAll_2020-02-10_12.41.16/clang/4.0.1/Serial-release  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/kokkoscore.dir/impl/Kokkos_Stacktrace.cpp.o -c /home/ndellin/kokkos/core/src/impl/Kokkos_Stacktrace.cpp
/home/ndellin/kokkos/tpls/gtest/gtest/gtest-all.cc:1424:20: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
  typedef unsigned long long BiggestConvertible;  // NOLINT
                   ^  
```

For the above clang case, this is the cmake line called by `test_all_sandia`:
```
cmake -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel6-x86_64/sems/compiler/clang/4.0.1/base/bin/clang++ -DCMAKE_CXX_FLAGS=-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  --gcc-toolchain=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX= -DKokkos_ENABLE_SERIAL=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=RELEASE /home/ndellin/kokkos
```

These modules are loaded:
```
Loading module sems-env
Loading module sems-cmake/3.12.2
Loading module kokkos-env
Loading module kokkos-hwloc/1.10.1/base
Loading module sems-clang/4.0.1
```

Here is the `test_all_sandia` command for this case:

`<PATHTOKOKKOS/scripts/testing_scripts/test_all_sandia clang/4.0.1 --build-list="Serial,Pthreads_Serial"`

Affecting clang/3.7.1, clang/3.8.1, clang/4.0.1, gcc/4.8.4, gcc/4.9.3, gcc/5.3.0

@jeffmiles63 any guess as to the cause?

### PR DESCRIPTION
**Pull request by jjwilke**
Fixes #2744.

### CODE REVIEW

**Comment by jjwilke** [comment]
Confirmed. I don't actually think we need the algorithms gtest either. I couldn't possibly tell you why I did that over a year ago.

**Comment by jeffmiles63** [comment]
the PR branch fails too

**Comment by jjwilke** [comment]
Can you post the error and output from `make VERBOSE=1`?

**Comment by jeffmiles63** [comment]
```
[ 99%] Building CXX object algorithms/unit_tests/CMakeFiles/kokkosalgorithms_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o
cd /ascldap/users/jsmiles/Development/test-cmake-clang/kokkos/build/algorithms/unit_tests && /projects/sems/install/rhel7-x86_64/sems/compiler/clang/3.8.1/base/bin/clang++  -DGTEST_HAS_PTHREAD=0 -I/ascldap/users/jsmiles/Development/test-cmake-clang/kokkos/build/algorithms/unit_tests -I/ascldap/users/jsmiles/Development/kokkos-develop/kokkos/algorithms/unit_tests -I/ascldap/users/jsmiles/Development/kokkos-develop/kokkos/algorithms/unit_tests/../src -I/ascldap/users/jsmiles/Development/kokkos-develop/kokkos/tpls/gtest  -O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -O3 -DNDEBUG   -o CMakeFiles/kokkosalgorithms_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o -c /ascldap/users/jsmiles/Development/kokkos-develop/kokkos/tpls/gtest/gtest/gtest-all.cc
/ascldap/users/jsmiles/Development/kokkos-develop/kokkos/tpls/gtest/gtest/gtest-all.cc:1424:20: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
  typedef unsigned long long BiggestConvertible;  // NOLINT
                   ^
1 error generated.
make[2]: *** [algorithms/unit_tests/CMakeFiles/kokkosalgorithms_gtest.dir/__/__/tpls/gtest/gtest/gtest-all.cc.o] Error 1
make[2]: Leaving directory `/home/jsmiles/Development/test-cmake-clang/kokkos/build'
make[1]: *** [algorithms/unit_tests/CMakeFiles/kokkosalgorithms_gtest.dir/all] Error 2
make[1]: Leaving directory `/home/jsmiles/Development/test-cmake-clang/kokkos/build'
make: *** [all] Error 2
```

**Comment by jjwilke** [comment]
Are you on the right branch? Otherwise you would be getting the same for `kokkos_gtest`

**Comment by jeffmiles63** [comment]
# On branch fix-algo-gtest-flags
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	./
nothing added to commit but untracked files present (use "git add" to track)

**Comment by jjwilke** [comment]
I am not reproducing the error. It doesn't make any sense to me that you would be getting a failure on `kokkosalgorithms_gtest` and not `kokkos_gtest`.

**Comment by jeffmiles63** [comment]
weird:  I tried this again this morning with the PR version and it worked fine...not sure what changed?

**Pull request merged**
