### PR TITLE
Kokkos: Remove listing of undefined TPL deps (trilinos/Trilinos#11152)

### PR DESCRIPTION
**Pull request by bartlettroscoe**
Matches changes in Trilinos PR https://github.com/trilinos/Trilinos/pull/11154 which fixes trilinos/Trilinos#11152.

### CODE REVIEW

**Comment by PhilMiller** [comment]
Ok to test

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
Failure (no space left on device) is clearly unrelated

**Comment by bartlettroscoe** [comment]
> Is it undefined because there is no `cmake/tpls/FindTPLHPX.cmake` file?

Yes

**Review by dalg24 — APPROVED** [review]

**Comment by ndellingwood** [comment]
Will need cherry-pick to release-candidate-3.7.01 to avoid clobber of matching changes with trilinos/Trilinos#11154 during 3.7.01 release

**Pull request merged**
