### PR TITLE
Cleanup OpenMPTaget ParallelReduce

### LINKED ISSUE #5987: OpenMPTarget backend build broken on AMD GPUs
#5954 broke OpenMPTarget on AMD GPUs.  The code below needs to be updated.
https://github.com/kokkos/kokkos/blob/9480cb5f8ce56f545f6b693993dad31056d00a4f/core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp#L145-L152

OPENMPTARGET-ROCM CI build was disabled in #5063.  #5436 is attempting to re-enable.  One of the testing system is down and we are hurting for AMD GPUs in the CI at the moment so I am not suggesting to proceed right now but we need to make sure we don't forget about this.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #5987 and is part of #5982.

### CODE REVIEW

**Review by Rombur — APPROVED** [review]

**Review by cz4rs — APPROVED** [review]
Looks good to me.

**Review by rgayatri23 — APPROVED** [review]
LGTM

**Comment by dalg24** [comment]
Please cherry-pick against 4.0.01 patch release and add to the changelog

**Comment by masterleinad** [comment]
> Please cherry-pick against 4.0.01 patch release and add to the changelog under "bug fixes"

https://github.com/kokkos/kokkos/pull/5954 was not part of the 4.0.00 release so I don't think there is any bug to fix.

**Comment by dalg24** [comment]
Oh right.  My bad.  We still need to look into #5988

**Pull request merged**
