### PR TITLE
Add special GCC check for C++17

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Comment by masterleinad** [comment]
I guess you only wanted to push 54923d6dc4e78c97b685c832d50ce2b79f7c39c7 here?

**Comment by jjwilke** [comment]
> I guess you only wanted to push [54923d6](https://github.com/kokkos/kokkos/commit/54923d6dc4e78c97b685c832d50ce2b79f7c39c7) here?

This will go in after PR #2334.

**Comment by jjwilke** [comment]
Is there an easy way to re-trigger the tests? AFAICT the Jenkins job did not actually fail. This was just Jenkins temporarily freaking out.

**Comment by dalg24** [comment]
> Is there an easy way to re-trigger the tests? AFAICT the Jenkins job did not actually fail. This was just Jenkins temporarily freaking out.

Jenkins report code format violated in `cmake/compile_tests/clang_omp.cpp`.  Fix it or do
```diff
diff --git a/.clang-format-ignore b/.clang-format-ignore
index b163a2bf..7a40bc7b 100644
--- a/.clang-format-ignore
+++ b/.clang-format-ignore
@@ -1,2 +1,3 @@
 core/unit_test/config/results/*
 tpls/gtest/gtest/*
+cmake/*
```

**Pull request merged**
