### PR TITLE
Add configuration to target CUDA compute capability 8.6

### PR DESCRIPTION
**Pull request by keichi**
This PR adds a flag to compile Kokkos with CUDA compute capability 8.6 (changes are based on #3122). I need this because I'm working with Ampere-based RTX cards.

### CODE REVIEW

**Review by masterleinad — DISMISSED** [review]
Looks good to me.

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
OK to test

**Comment by keichi** [comment]
I ran the unit tests on RTX3090 and the following tests in `KokkosCore_UnitTest_Cuda2` failed.

https://github.com/kokkos/kokkos/blob/78538c8574777342f64c7da657f419778eaa2a10/core/unit_test/TestTeamTeamSize.hpp#L163-L167

https://github.com/kokkos/kokkos/blob/78538c8574777342f64c7da657f419778eaa2a10/core/unit_test/TestTeamTeamSize.hpp#L178-L182

After some debugging I figured out `cuda_get_max_block_size()` was returning zero. I think the reason is that `properties.MaxThreadsPerBlock` is 1536 on CC 8.6 while it's 2048 on other devices (I've tested on P100 and V100). I modified `cuda_deduce_block_size()` to account for that but I'm unsure if the fix is correct. Please review.

**Review by crtrott — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]
LGTM

**Pull request merged**
