### PR TITLE
Remove uvm allocation limit

### LINKED ISSUE #2641: Is CudaUVMSpace limit on number of allocations still valid?
Issue #300 mentions a limit of 65536 simultaneous UVM allocations, and I just hit this in a test problem. Is that limit still true with recent Cuda versions, I can't find a mention of it in the Cuda documentation but I may not be looking in the right place.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #2641.

### CODE REVIEW

**Comment by masterleinad** [comment]
Just being conservative since there is a public static member function `Kokkos::CudaUVMSpace::number_of_allocations()`.

**Comment by dalg24** [comment]
> Just being conservative since there is a public static member function `Kokkos::CudaUVMSpace::number_of_allocations()`.

Do we track the number allocation anywhere else?

**Comment by masterleinad** [comment]
> Do we track the number allocation anywhere else?

`QThreads_TaskQueue` and `Kokkos_TaskQueue` have
```
int m_count_alloc;     // Current number of allocations
```
but these are the only occurrences of something the like. So the answer is "no".

**Comment by dalg24** [comment]
Should we consider deprecating that `Kokkos::CudaUVMSpace::number_of_allocations()` function then?  Any opinion?

**Comment by DavidPoliakoff** [comment]
@dalg24 either deprecate it or implement it for others. I'm in favor of deprecating

**Comment by dalg24** [comment]
@crtrott what do you think?

**Pull request merged**
