### PR TITLE
Fix parsing bug for number of devices command line argument

### PR DESCRIPTION
**Pull request by dalg24**
Introduced in #3718
Reported by @stanmoore1

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks good. Thanks!

**Review by DavidPoliakoff — APPROVED** [review]
++:beer:-we-owe-stan

**Comment by dalg24** [comment]
Retest this please (does not seem to have triggered a build on Jenkins)

**Comment by masterleinad** [comment]
Looks like it passed CI.

**Review by nliber — APPROVED** [review]

**Pull request merged**
