### PR TITLE
Change allocation header to 256B alignment

### PR DESCRIPTION
**Pull request by arghdos**
Change-Id: Ia76fe488d7f491f0df884fe57b49bb70954a2ecf

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Failure (Clang crashing in OpenMPTarget when compiling `TestSerial_Complex.cpp`) is unrelated

**Review by crtrott — CHANGES_REQUESTED** [review]
I am not sure I want to do this unconditionally. I think we should restrict to HIP or even to HIP with 90A arch.

**Comment by rgayatri23** [comment]
Retest this please.

**Comment by arghdos** [comment]
Rebased onto https://github.com/kokkos/kokkos/pull/4782 to make it conditional on VEGA.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
