### PR TITLE
Allow NVHPC as device compiler only with Kokkos_ENABLE_IMPL_NVHPC_AS_DEVICE_COMPILER=ON

### PR DESCRIPTION
**Pull request by masterleinad**
This pull request introduces an option to allow `nvc++` as `Cuda` device compiler (with the default being "OFF").
This partially reverts https://github.com/kokkos/kokkos/pull/5020 that allowed using `nvc++` as `Cuda` device compiler.

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
I think this is good enough for now.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
`HIP-ROCm-5.6-C++20` is timing out. all other `jenkins` CI builds, particularly the `NVHPC` builds, pass.

**Review by lucbv — APPROVED** [review]
That looks fine but we should try to keep these IMPL options limited as there is now way to prevent users from accessing them...

**Comment by crtrott** [comment]
This is a stopgap until we get more clarity on the direction of the nvc++.

**Pull request merged**
