### PR TITLE
Replace typedefs in core/unit_test

### PR DESCRIPTION
**Pull request by masterleinad**
Part of #3213. Excluding `core/unit_test/incremental`

### CODE REVIEW

**Comment by rgayatri23** [comment]
Is there a reason why incremental test are not included in this replacement?

**Comment by masterleinad** [comment]
> Is there a reason why incremental test are not included in this replacement?

I tried to split the changes a little bit. The incremental tests are covered in https://github.com/kokkos/kokkos/pull/3227.

**Comment by rgayatri23** [comment]
Ah ok, everything else looks good to me.

**Review by calewis — APPROVED** [review]
Obviously it's not practical to review every line in a reasonable amount of time.  This is where we get to find out if our tests are robust enough :), I did look at about a hundred lines and didn't see anything wrong. LGTM.

**Review by rgayatri23 — APPROVED** [review]

**Pull request merged**
