### PR TITLE
CMakeLists.txt: Fix for Trilinos_CXX_COMPILER_FLAGS

### PR DESCRIPTION
**Pull request by ndellingwood**
Applies changes of #3987 only when sycl is backend, otherwise `Trilinos_CXX_COMPILER_FLAGS` flags may have extra quotes causing compile problems

### CODE REVIEW

**Comment by masterleinad** [comment]
What kind of problems are you seeing? I had hoped that we ruled out any issues before merging the pull request introducing the extra quotes.

**Comment by ndellingwood** [comment]
@masterleinad Without the in this, after install of Trilinos (confirmed with an OpenMP build) some flags in the `Trilinos_CXX_COMPILER_FLAGS` variable of <trilinos-install>/lib/cmake/Trilinos/TrilinosConfig.cmake have extra quotes:

`SET(Trilinos_CXX_COMPILER_FLAGS "-g "-fopenmp"  -O3 -DNDEBUG")` (extra quotes around -fopenmp)

This caused issues when configuring an app that links with a Trilinos install and pulls in the cxx flags via the `Trilinos_CXX_COMPILER_FLAGS` variable.

When I helped test the earlier PR I had built and installed Trilinos but did not test the install with an external app and did not catch this at that point.

**Review by masterleinad — APPROVED** [review]
Hmmm... I'm fine with the change but it would be good to verify that this won't be a problem for building the app with `SYCL` support, too.

**Comment by ndellingwood** [comment]
@masterleinad I don't have access to a platform with sycl to test on, there is a small demo app in Trilinos that relies on Tpetra that may be a good candidate tot test (possibly with the PR tracking ongoing Trilinos/Tpetra support for Sycl). I'll message you on slack to discuss more details

**Comment by ndellingwood** [comment]
@masterleinad this issue may be specific to OpenMP with the fopenmp flag, I checked nightly Cuda builds of Trilinos with Kokkos develop and configuring+building against the Trilinos install did not fail in those cases

**Comment by crtrott** [comment]
@masterleinad do we still want this?

**Comment by masterleinad** [comment]
If we get the TriBITS changes in https://github.com/trilinos/Trilinos/pull/9189 merged, we don't need this.

**Review by crtrott — CHANGES_REQUESTED** [review]
Putting this on hold to see what Trilinos does.

**Comment by crtrott** [comment]
I will close this since its not a proper fix and we want to solve this differently.

**Pull request closed without merging**
