### PR TITLE
Add support for Cavium ThunderX2 Processor

### PR DESCRIPTION
**Pull request by nmhamster**
Add support for Cavium ThunderX2 Processor

### CODE REVIEW

**Comment by nmhamster** [comment]
@crtrott - any chance we can squeeze this into the promotion?

**Comment by ndellingwood** [comment]
@nmhamster @crtrott I need to rerun integration tests after another wave of changes, so if it needs to go through a round of nightlies I think we have time to make it into the promotion.

**Comment by crtrott** [comment]
I merged it into develop.

**Comment by nmhamster** [comment]
@crtrott - thank you!

**Pull request merged**
