### PR TITLE
Replace wrapping_fetch_inc/dec with fetch_inc/dec_mod

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Review by dalg24 — CHANGES_REQUESTED** [review]
Fix the format and make sure it does not introduce more conflicts with Desul

**Review by dalg24 — COMMENTED** [review]
Looks good except `TestAtomicOperations.hpp` which is out of sync with Desul

**Comment by crtrott** [comment]
Retest this please.

**Comment by crtrott** [comment]
Note even if we want to keep TestAtomicOperations in sync with desul (which I don't necessarily think we need to) the ground-truth would be Kokkos not desul. This is a Kokkos unittest we might have copied over to desul to have a starting point, but it was never my intention to keep these synced up.

**Review by dalg24 — APPROVED** [review]
I am ok with resolving unit test sync later

**Review by Rombur — APPROVED** [review]

**Pull request merged**
