### PR TITLE
Enable examples for SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
The return type for `extent` is `size_t`.
Again, I would prefer using #3615 instead of commenting all the `printf`s.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — CHANGES_REQUESTED** [review]
I am not happy with the changes to explicit size_t. Folks should not use size_t for loop counters since its often bad for performance. Rather cast the return of extent. These examples generally should reflect best practices.

**Comment by masterleinad** [comment]
> I am not happy with the changes to explicit size_t. Folks should not use size_t for loop counters since its often bad for performance. Rather cast the return of extent. These examples generally should reflect best practices.

Doesn't it make more sense then to let `extent` return `ViewType::size_type`?

**Comment by dalg24** [comment]
I had the same initial reaction than you but then I look at `View::extent` implementation and changed my mind
https://github.com/kokkos/kokkos/blob/78538c8574777342f64c7da657f419778eaa2a10/core/src/Kokkos_View.hpp#L655-L660

**Comment by masterleinad** [comment]
I guess this is a bigger discussion that we might not need to have here. For now, I just cast the upper bounds instead.

**Comment by masterleinad** [comment]
Ready from my side. Needs more reviews.

**Review by Rombur — APPROVED** [review]
Looks good.

> Again, I would prefer using #3615 instead of commenting all the printfs.

I disagree here. I don't think we want users to use that macro.

**Comment by masterleinad** [comment]
> I disagree here. I don't think we want users to use that macro.

Yes, that's true.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
