### PR TITLE
Master release 4.3.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos snapshot PR: https://github.com/trilinos/Trilinos/pull/12879
Do not merge until confirmation that PR has passed testing and is approved

**Review by masterleinad — APPROVED** [review]
Comparing with `develop`, this looks good to me. `develop` is only missing the changelog update.

**Comment by ndellingwood** [comment]
> `develop` is only missing the changelog update

@masterleinad yes, thanks for the reminder. now that the release seems in its final state I'll put up a PR to develop with the changelog update

**Comment by ndellingwood** [comment]
changelog update PR to develop is up: https://github.com/kokkos/kokkos/pull/6919

**Comment by ndellingwood** [comment]
Trilinos snapshot PR https://github.com/trilinos/Trilinos/pull/12879 passed CI

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
