### PR TITLE
Fixup CUDA arch auto detection in Trilinos

### PR DESCRIPTION
**Pull request by dalg24**
Tentative fix for https://github.com/kokkos/kokkos/issues/5320#issuecomment-1209623403

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
Need to cherry-pick into RC 3.7

**Comment by masterleinad** [comment]
Does this actually fix something?

**Comment by dalg24** [comment]
> Does this actually fix something?

Should fix the error reported in the description https://github.com/kokkos/kokkos/issues/5320#issuecomment-1209623403

**Review by Rombur — APPROVED** [review]

**Comment by masterleinad** [comment]
> Should fix the error reported in the description [#5320 (comment)](https://github.com/kokkos/kokkos/issues/5320#issuecomment-1209623403)

I didn't need this trying to enable CUDA in Trilinos.

**Pull request merged**
