### PR TITLE
Release 4.1.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by masterleinad** [comment]
Why is the source not the `release-candidate-4.1.00` branch?

**Comment by ndellingwood** [comment]
@masterleinad I merged release-candidate-4.1.00 to my local master then submitted as the PR, to avoid an extra duplicate round of testing (PR of merge of master to release-candidate-4.1.00 followed by PR of release-candidate-4.1.00 back to master)

Here is the diff between this PR and release-candidate-4.1.00, which has diffs between CHANGELOG.md and master_history.txt (which is not updated to develop)
[pr-to-rc-diff.txt](https://github.com/kokkos/kokkos/files/11808559/pr-to-rc-diff.txt)

**Comment by ndellingwood** [comment]
@masterleinad commit [ea7b124](https://github.com/kokkos/kokkos/pull/6231/commits/ea7b12448420671e53d890e3279268efa27a3421) has fixup for the changelog to address some strange merge mess (duplicates of 4.1.00 and 4.0.01 after/before 3.7.02)

**Review by masterleinad — APPROVED** [review]
Fine with me after making sure that this matches `release-candidate-4.1.00` closely.

**Comment by masterleinad** [comment]
Are we waiting for #6241?

**Pull request merged**
