### PR TITLE
Fix incorrect macro definitions when compiling with Intel compiler on…

### PR DESCRIPTION
**Pull request by cjj19970505**
… Windows.

Define KOKKOS_RESTRICT as __restrict on Windows.
Disable KOKKOS_IMPL_ENABLE_STACKTRACE.
Define KOKKOS_THREAD_LOCAL as __declspec(thread).
Use __declspec for attribute.

Fixed: #4080

### CODE REVIEW

**Comment by dalg24** [comment]
OK to test

**Comment by cjj19970505** [comment]
Any idea why CI failed ?  It seems not related to my changes.

**Comment by masterleinad** [comment]
> Any idea why CI failed ? It seems not related to my changes.

You were targeting the wrong branch which is not compatible with our current CI. I changed the target branch of this pull request to `develop`. Can you please rebase?

**Comment by masterleinad** [comment]
There are a lot of unrelated commits now. All your actual changes should be contained in [`166a291` (#4085)](https://github.com/kokkos/kokkos/pull/4085/commits/166a29156755c911a4367bba331bf570a57ad2a5). Can you please drop the other commits?

**Comment by crtrott** [comment]
Note this is an artifact from us never merging master back into develop...., his commit was developed on top of master, then merged develop into master, and now requests to merge back into develop. I still think its a mistake that we handle that that way, but I was overruled ;-)

**Comment by masterleinad** [comment]
Let us know if you need help with picking the one relevant commit. If you prefer, we can do that for you.

**Comment by cjj19970505** [comment]
Crtrott is right. I made some mistakes here. I think I should make my changes on develop brach and create another PR. I am closing this and create a new one.

**Comment by crtrott** [comment]
I am issuing it now

**Comment by crtrott** [comment]
#4087 just cherry picked your commit

**Pull request closed without merging**
