### PR TITLE
Deprecate ViewAllocateWithoutInitializing

### PR DESCRIPTION
**Pull request by masterleinad**
Follow-up to #3264. It turns out that there was
```
#cmakedefine KOKKOS_ENABLE_DEPRECATION_WARNINGS
```
missing. Additionally, this pull request introduces `KOKKOS_DEPRECATED_WITH_COMMENT`.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Comment by crtrott** [comment]
Meeting decision: this approach is ok, i.e. turn deprecation warnings off when deprecated code is enabled in a build.

**Review by DavidPoliakoff — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
I think this change (actually deprecating `ViewAllocateWithoutInitializing`) was not a good idea because it has virtually no cost on our side (it is just an alias) and it will affect a lot of user code and mostly look like a nuisance

**Comment by crtrott** [comment]
It is actually very low cost to maintain this since we figured out how to make this just an alias:
Should we revert this:

SF F N A SA
1 5 6 1 0

Weak consensus: we revert this. Remove the comment that we intent to deprecate it.

**Pull request merged**
