### PR TITLE
Improve subgroup usage in SYCL TeamPolicy

### PR DESCRIPTION
**Pull request by masterleinad**
This pull request should supersede #4123 when ready.

### CODE REVIEW

**Comment by masterleinad** [comment]
Hmm.. I can't reproduce the test failure on `V100`. Let's see if rebuilding helps, otherwise let's do this after updating the SYCL CI

Retest this please.

**Comment by masterleinad** [comment]
Blocked by #4244.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Only `gcc-5.3.0` is failing and that is clearly unrelated.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Review by nliber — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Pull request merged**
