### PR TITLE
Create HIP API function wrappers in HIPInternal

### PR DESCRIPTION
**Pull request by tcclevenger**
Version of https://github.com/kokkos/kokkos/pull/6299 for HIP. Addresses https://github.com/kokkos/kokkos/issues/6324. Needed for multiple GPU support.

### CODE REVIEW

**Review by masterleinad — CHANGES_REQUESTED** [review]
I would rather have the changes to CUDA functions in a separate pull request.

**Comment by tcclevenger** [comment]
@masterleinad I'll create a Cuda reorg PR once we are happy with this one. Now this PR only edits in the `HIP/` dir.

**Comment by ajpowelsnl** [comment]
@masterleinad , @Rombur - what is the status of this PR?

**Comment by tcclevenger** [comment]
This needs a lot of updates based on how the impl in Cuda went. I may look in to reworking this PR next on my list.

**Comment by masterleinad** [comment]
It probably makes sense to tackle this together with multi-GPU support.

**Pull request closed without merging**
