### PR TITLE
Fixup for seeding random engines (issue with DeviceType template arg)

### LINKED ISSUE #2693: device_type for Kokkos_Random ?
I have the following error message when I use Kokkos::Device into the random function. If I use an execution space, it is fine. However, the source code template argument name is DeviceType.
 
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/kokkos/algorithms/src/Kokkos_Random.hpp(707):                                                                    
error: class "Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>" has no member "max_hardware_threads"                                  
          detected during instantiation of "Kokkos::Random_XorShift64_Pool<DeviceType>::Random_XorShift64_Pool(uint64_t) [with DeviceType=DeviceType]"  
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #2693

### CODE REVIEW

**Comment by dalg24** [comment]
I guess I should show the good example and test.
To the reviewer: I only changed some occurrences and kept instantiation with execution space on purpose.  I am not sure how long it takes to run these unit tests.  If that's very fast we could consider instantiating all combinations.

**Comment by masterleinad** [comment]
Let us know when this is ready for review.

**Comment by masterleinad** [comment]
https://github.com/kokkos/kokkos/blob/586d07ba08e2bb9aae6fe644cf7ac16853dd32bd/algorithms/src/Kokkos_Random.hpp#L942-L946 and https://github.com/kokkos/kokkos/blob/586d07ba08e2bb9aae6fe644cf7ac16853dd32bd/algorithms/src/Kokkos_Random.hpp#L1000-L1004 that likely need the same fix.

**Comment by dalg24** [comment]
Thanks I fixed and amended the changes.

**Pull request merged**
