### PR TITLE
Fixup signature of `hip_parallel_launch_global_memory`

### PR DESCRIPTION
**Pull request by dalg24**
Fixup for #5448 

Need to investigate why this was not caught by the unit tests

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Comment by Rombur** [comment]
I don't think that's the correct solution. We do the same thing in CUDA. For a LocalLaunch we pass the driver by value and for a GlobalLaunch we pass a pointer

**Comment by Rombur** [comment]
I know where the bug is from. I'll create a PR later

**Review by crtrott — CHANGES_REQUESTED** [review]
Sorry I was stupid when I approved this is wrong.

**Comment by dalg24** [comment]
Closing in favor of upcoming fix from Bruno

**Pull request closed without merging**
