### PR TITLE
Add cuda ada hopper arch to version 3.7 maintenance branch

### PR DESCRIPTION
**Pull request by akohlmey**
These are the changes make to the Kokkos library copy bundled with LAMMPS to support compiling/running with the CUDA Ada (sm_89)  and Hopper (sm_90) architectures.

### CODE REVIEW

**Review by dalg24 — CHANGES_REQUESTED** [review]
You must target the develop branch.  Once merged we would then consider whether to cherry-pick or not.

**Comment by dalg24** [comment]
(You should be able to edit and change the destination branch without closing)

**Comment by akohlmey** [comment]
> (You should be able to edit and change the destination branch without closing)

I have to branch off of develop instead of the 3.7 maintenance and that doesn't need the Hopper related bits.

**Comment by dalg24** [comment]
You could have push forced once you did that.  Anyway no big deal.

**Pull request closed without merging**
