### PR TITLE
cmake: Do not add C++ standard flags explicitly when inside Trilinos

### PR DESCRIPTION
**Pull request by bradking**
TriBITS and Trilinos are switching to CMake's standard settings to enable C++11 support.  We no longer need to add any such flags ourselves.

### CODE REVIEW

**Comment by bradking** [comment]
See trilinos/Trilinos#6814 for the Trilinos updates using this change to kokkos.

**Comment by bradking** [comment]
This is WIP pending testing in trilinos/Trilinos#6814.

**Comment by dalg24** [comment]
OK to test

**Comment by ndellingwood** [comment]
is resolution of #2731 required before this can be tested within Trilinos?

**Comment by crtrott** [comment]
This should not go into master. If you are hot fixing Trilinos's version of Kokkos that is Trilinos's thing, and then we need to mirror the change in develop. But this shouldn't go directly into master.

**Comment by bradking** [comment]
I've rebased on `develop` and re-targeted the PR.

**Comment by crtrott** [comment]
Is the testing done for this in Trilinos @bradking

**Comment by bradking** [comment]
@bartlettroscoe have you been able to test this change in Trilinos?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe have you been able to test this change in Trilinos?

@bradking, not yet.  I have several things I need to do before can get to testing this.  I will need to test on a few platforms and test against SPARC and EMPIRE so it will be quite a bit of work.  I also need to test with a couple versions of CMake just to be sure (including cmake 3.16 with EMPIRE).

**Comment by bradking** [comment]
I'll close this PR temporarily and re-open once the Trilinos side has been tested.

**Comment by bartlettroscoe** [comment]
FYI: I am about the set up to merge the Trilinos PR:

* https://github.com/trilinos/Trilinos/pull/6814

that has these changes to Kokkos which you can see in:

* https://github.com/trilinos/Trilinos/pull/6814/files?diff=unified&w=1#diff-35cc56277bb8a696a39ba07e7b2de40f
* https://github.com/trilinos/Trilinos/pull/6814/files?diff=unified&w=1#diff-3d8f177f60a673e9ee053791f5f90b14

Hope this is okay.

**Comment by bartlettroscoe** [comment]
@bradking, can you please reopen this GitHub issue?  I can't do it.

**Comment by bradking** [comment]
@dalg24 thanks for re-opening.

I just pushed an update to rebase the change on the current `develop` branch.

**Pull request merged**
