### PR TITLE
Quiet warnings about multiple optimization flags when they're repetitions of the same argument

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Comment by dalg24** [comment]
Why should we treat duplicated optimization flags differently when they are duplicated?

**Comment by PhilMiller** [comment]
Substantively, in the case where it's the same flag repeated (e.g. `-O3 -O3 -O3`), it's inconsequential that the duplicates are being stripped. The warning only indicates a problem to be fixed, where the user may not get what they were expecting, or has a broken/inconsistent configuration, if they ever differ.

Practically, EMPIRE's build system and its use of Trilinos ends up with exactly this sort of duplication on **every single** one of several thousand object files. It's pure noise in the output of every CUDA build. If there were some corner of the code (say a random TPL) in which the warning actually indicated a real problem, we wouldn't know, because we're not going to look past all the cases where it's not telling us anything interesting.

**Comment by PhilMiller** [comment]
I'll admit that there's probably something subtly wrong in EMPIRE's build system leading to this (I know of many other things that are not so subtly wrong), but the effort to investigate and resolve it would be much lower priority than a few dozen other things that need work. If we still got this warning on a smaller subset of files after quieting down the noise, we'd have a much clearer reason to pursue the breakage.

**Comment by dalg24** [comment]
> Substantively, in the case where it's the same flag repeated (e.g. -O3 -O3 -O3), it's inconsequential that the duplicates are being stripped. The warning only indicates a problem to be fixed, where the user may not get what they were expecting, or has a broken/inconsistent configuration, if they ever differ.

I disagree.  I don't think that -O1 -O2 -O3 is any worse but this is my personal opinion and we can wait to see how others feel about this.

Would you consider an alternate solution that let you suppress that warning altogether?

**Comment by PhilMiller** [comment]
I'd definitely consider an alternate solution that suppressed the warning in the exact duplication case.

**Comment by fnrizzi** [comment]
Personally, I think in this case, duplicate flags is a problem caused by the application, so it should be up to app to fix it and provide the *right* flags, so I would vote for not stripping all duplicates but just giving a warning. And leaving it up to the app to disable that warning. Or better spend time fixing it :)

**Comment by fnrizzi** [comment]
Arguing against myself, I would also say the it would not be such a burden for us to support stripping duplicates. So even that solution would not be too bad IMMO.

**Review by crtrott — APPROVED** [review]
Behaves similar to NVCC 11 which warns for different flags but not the same. 
NVCC 9/10 error out with multiple optimization flags.

**Pull request merged**
