### PR TITLE
Add resize and realloc functions to Kokkos_ScatterView

### PR DESCRIPTION
**Pull request by stanmoore1**
@ibaned can we add `resize` and `realloc` functions to `ScatterView` like in this PR? These are useful for persistent memory.

### CODE REVIEW

**Comment by ibaned** [comment]
These look wrong... shouldn't they handle the hidden dimension equal to number of threads?

**Comment by stanmoore1** [comment]
Ah yes, good point.

**Comment by stanmoore1** [comment]
@ibaned does this look right now?

**Comment by ibaned** [comment]
Yea, they look reasonable. I think to present a common interface, there should be a free function `realloc(reduction_view, n0, ...)`, but that can be easily added.

**Comment by stanmoore1** [comment]
@ibaned `ScatterView` doesn't work for `LayoutLeft` due to https://github.com/kokkos/kokkos/issues/1263. I get a segfault without 7ff64d2.

**Comment by ibaned** [comment]
@stanmoore1 I think I merged this and resolved the conflicts just before you did. I'm going to just close this, but I'm pretty sure all the changes made it in.

**Pull request closed without merging**
