### PR TITLE
Enable some more SYCL tests

### PR DESCRIPTION
**Pull request by masterleinad**
Based on #3741.

### CODE REVIEW

**Review by dalg24 — CHANGES_REQUESTED** [review]
OK with the DynamicView changes

Why is Reductions_DeviceView not in the list(REMOVE_ITEM SYCL_SOURCES1B ...)?
The unit test seems pointless with the `#ifdef`s. What am I missing?

**Comment by masterleinad** [comment]
> Why is Reductions_DeviceView not in the list(REMOVE_ITEM SYCL_SOURCES1B ...)?

There was already `reduce_device_view_range_policy` that was working.

> The unit test seems pointless with the #ifdefs. What am I missing?

On second thought, I agree that it makes more sense to disable it. I still improved the FIXME description and let the functor compile so we can check that at least compiling it works fine.

**Review by dalg24 — APPROVED** [review]
Squash the two commits before we merge

**Comment by masterleinad** [comment]
> Squash the two commits before we merge

Here you go.

**Pull request merged**
