### PR TITLE
Address slowdown in Kokkos_ReductionView

### PR DESCRIPTION
**Pull request by stanmoore1**
@ibaned the slowdown is coming from the `if (dest.data() == internal_view.data())` branching, though I'm not sure why. The compiler seems to like this better. Could modify LayoutLeft as well, I didn't yet.

### CODE REVIEW

**Comment by ibaned** [comment]
This looks quite strange... can you quantify how much slowdown and with which backend?

**Comment by stanmoore1** [comment]
OpenMP backend, KNL hardware, 64 MPI x 4 OpenMP threads, Intel 17.0.4 compiler

| Code version  | Reduction Kernel Time | Total Run Time |
| ------------- | ------------- | ------------- |
| issue-825, 6abd375 | 1.39285  | 4.04607 | 
| PR #1241 | 1.20641  | 3.86367 | 
| hand-coded reduction  | 1.23723  | 3.92866 |

**Comment by stanmoore1** [comment]
These numbers are very reproducible if I run multiple times too.

**Comment by stanmoore1** [comment]
I'm not going to pretend I understand why this PR is faster, and I'm not claiming it is faster on every compiler/hardware, but I do care about KNL a lot.

**Comment by ibaned** [comment]
Fair enough, I think what matters is the numbers for the record.
I'll grab this and go from there.

**Pull request merged**
