### PR TITLE
Fix CMake->GMake->CMake TPL handling

### PR DESCRIPTION
**Pull request by ibaned**
Still a bit of a work in progress, needs testing. should address the remainder of #1365 though.

### CODE REVIEW

**Comment by ibaned** [comment]
Standalone (pure CMake) build with HWLOC enabled works for me, as does an in-TriBITS build with CUDA enabled.

**Comment by ibaned** [comment]
@etphipp this pull request should fully fix the HWLOC issue. Could you give it a try and let me know if it does?

**Comment by ibaned** [comment]
Passes spot check:
```
Running on machine: sems
Repository Status:  275ead352993a56427d7ed63870fa746ddad4b4d Remove debug messages from CMake


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-5.3.0-OpenMP-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED intel-17.0.1-OpenMP-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=187 run_time=89
clang-3.9.0-Pthread_Serial-release build_time=200 run_time=218
cuda-8.0.44-Cuda_OpenMP-release build_time=499 run_time=539
gcc-5.3.0-OpenMP-hwloc-release build_time=259 run_time=111
gcc-5.3.0-OpenMP-release build_time=256 run_time=107
gcc-6.1.0-Serial-hwloc-release build_time=199 run_time=149
gcc-6.1.0-Serial-release build_time=203 run_time=124
intel-17.0.1-OpenMP-hwloc-release build_time=563 run_time=162
intel-17.0.1-OpenMP-release build_time=565 run_time=170
```
This is ready to go in as far as I can tell

**Comment by etphipp** [comment]
I can confirm it does now work if you enable HWLOC, but unfortunately it generates CMake errors if you don't have any TPLs enabled:
```
CMake Error at kokkos/CMakeLists.txt:47 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at kokkos/CMakeLists.txt:48 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at kokkos/CMakeLists.txt:50 (list):
  list sub-command REMOVE_ITEM requires list to be present.


CMake Error at kokkos/CMakeLists.txt:51 (list):
  list sub-command REMOVE_ITEM requires list to be present.
```
I think the issue is variables such as KOKKOS_GMAKE_TPL_INCLUDE_DIRS are empty if there are no TPLs enabled, and you probably need to check for this case before doing the string replacements.

**Comment by ibaned** [comment]
@etphipp good catch! guess theres another pull request coming up...

**Comment by etphipp** [comment]
That PR appears to fix it, however there is still the issue with recompiles without rerunning cmake from scratch:
```
etphipp@elbert opt_gcc_49_cuda_nouvm_inline $ make -j32 -k
CMake Error at kokkos/cmake/kokkos_settings.cmake:21 (message):
  KOKKOS_ARCH=SNB,Kepler35 should only contain semicolons (;), not commas
  (,).
Call Stack (most recent call first):
  kokkos/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by ibaned** [comment]
@etphipp that comma/semicolon issue should have been fixed by #1361 , and I can't replicate it with current Kokkos develop. Can you send more detailed instructions for replicating it?

**Comment by etphipp** [comment]
I have a library called Genten that builds with the Kokkos CMake system.  When I build for Cuda, I have this:
```
 -D KOKKOS_ARCH="SNB;Kepler35" \
```
When I run cmake from scratch, everything works fine.  But if I touch a CMakeLists.txt file and then just run "make", I get the above error.

I've never exactly understood how cmake runs differently in these two cases, but it appears to me KOKKOS_ARCH has already been transformed by replacing ';' with ',', resulting in the error.

**Comment by etphipp** [comment]
Oh, wait, it does appear to be working now.  I'm not sure what happened.  Must not have been at HEAD when I thought I was.  Sorry for the trouble!

**Comment by ibaned** [comment]
@etphipp no problem, glad we got all your issues resolved. Feel free to open new issues if you find something else.

**Pull request merged**
