### PR TITLE
Export CMake config when Kokkos is installed from a generated makefile

### PR DESCRIPTION
**Pull request by dalg24**
Partially addressing #1966 

This will export a proper CMake target when Kokkos is installed using a regular makefile produced by `generate_makefile.bash`

Here is how one could compile the `bytes_and_flops` benchmark using CMake:
```CMake
find_package(kokkos REQUIRED)
kokkos_check_required(DEVICES OpenMP Cuda ARCH Power9 Volta70)
add_executable(bytes_and_flops ${KOKKOS_PATH}/benchmarks/bytes_and_flops/main.cpp)
target_link_libraries(bytes_and_flops Kokkos::kokkos)
target_include_directories(bytes_and_flops ${KOKKOS_PATH}/benchmarks/bytes_and_flops)
```
The `kokkos_check_required` function let the user ensure that the Kokkos install that is found has the proper devices enabled and/or that the target architectures are appropriate.  Say the user forgot to enable Cuda when they built Kokkos, instead of an error at build time, an error would be emitted at configuration time:
```Bash
-- Found KOKKOS: <snip>/include
-- Could NOT find KOKKOS_DEVICES (missing: Cuda)
-- Could NOT find KOKKOS_ARCH (missing: Volta70)
CMake Error at <snip>/lib/cmake/kokkos/kokkos-config.cmake:90 (message):
  Kokkos does NOT provide all backends and/or architectures requested
Call Stack (most recent call first):
  CMakeLists.txt:4 (kokkos_check_requested)


-- Configuring incomplete, errors occurred!
```

Bikeshedding: we are free to rename the package name `kokkos`, the target `Kokkos::kokkos`, or the function `kokkos_check_required ` to whatever you think would be more appropriate.

### CODE REVIEW

**Comment by ndellingwood** [comment]
I ran a CMake configuration test with Trilinos (including the changes from PR #2073), it completed without configuration errors.

**Comment by dhollman** [comment]
Pinging @jjwilke

**Comment by jjwilke** [comment]
Sorry, I missed this. Everything looks correct and functionally equivalent to the standalone CMake. I guess my question would be why are using the Makefile install if we are using CMake downstream. Why not just install Kokkos with CMake to start?

**Comment by jjwilke** [comment]
The concern here would be having a KokkosConfig.cmake and a kokkos-config.cmake generated differently with potentially diverging functionality. Maybe no harm done. Maybe this frustrates people.

**Comment by jjwilke** [comment]
The more I think about this, there more I think this is moving the wrong direction.

Raw makefile installation should be a rare use case for mini-apps - and generally labeled "deprecated". There are going to be a lot of CMake packaging changes - particularly as Tribits evolves with CMake3 support.  If you want a CMake package, you should install with CMake.

**Comment by junghans** [comment]
> Raw makefile installation should be a rare use case for mini-apps - and generally labeled "deprecated". 

Please go ahead and do that, so that we can tell our users to not use the makefile installation anymore.

**Pull request closed without merging**
