### PR TITLE
Cherry-pick #2580 and #2662 into release-candidate-3.0

### PR DESCRIPTION
**Pull request by masterleinad**
~~In combination with #2656,~~ this pull request synchronizes `nvcc_wrapper` between `develop` and `release-candidate-3.0`

### CODE REVIEW

**Comment by dalg24** [comment]
```diff
--- nvcc_wrapper_develop
+++ nvcc_wrapper_rc
@@ -194,12 +194,12 @@
   -rdc=*|-maxrregcount*|--maxrregcount*)
     cuda_args="$cuda_args $1"
     ;;
-  #Handle unsupported standard flags
-  --std=c++1y|-std=c++1y|--std=c++1z|-std=c++1z|--std=gnu++1y|-std=gnu++1y|--std=gnu++1z|-std=gnu++1z|--std=c++2a|-std=c++2a|--std=c++17|-std=c++17)
+  #Handle c++11
+  --std=c++1y|-std=c++1y|--std=c++1z|-std=c++1z|--std=gnu++1y|-std=gnu++1y|--std=gnu++1z|-std=gnu++1z)
     fallback_std_flag="-std=c++14"
     # this is hopefully just occurring in a downstream project during CMake feature tests
-    # we really have no choice here but to accept the flag and change  to an accepted C++ standard
-    echo "nvcc_wrapper does not accept standard flags $1 since partial standard flags and standards after C++14 are not supported. nvcc_wrapper will use $fallback_std_flag instead. It is undefined behavior to use this flag. This should only be occurring during CMake configuration."
+    # we really have no choice here but to accept the flag and "promote" to the corresponding C++ standard
+    echo "nvcc_wrapper does not accept intermediate standard flag $1, but it will use $fallback_std_flag instead. It is undefined behavior to use this flag. This should only be occurring during CMake configuration."
     if [ -n "$std_flag" ]; then
        warn_std_flag
        shared_args=${shared_args/ $std_flag/}
@@ -217,7 +217,7 @@
     std_flag=$corrected_std_flag
     shared_args="$shared_args $std_flag"
   ;;
-  --std=c++11|-std=c++11|--std=c++14|-std=c++14)
+  --std=c++11|-std=c++11|--std=c++14|-std=c++14|--std=c++17|-std=c++17)
     if [ -n "$std_flag" ]; then
        warn_std_flag
        shared_args=${shared_args/ $std_flag/}
```

**Comment by masterleinad** [comment]
That is what #2656 is supposed to do.

**Comment by dalg24** [comment]
Did you mean to exclude #2643?

**Comment by dalg24** [comment]
Retest this please

**Comment by masterleinad** [comment]
It might be less confusing just also cherry-picking #2643 here. Supersedes #2656 now.

**Comment by jjwilke** [comment]
Yeah, maybe easier to just have a single "make 3.0 match develop" PR here and close #2656

**Pull request merged**
