### PR TITLE
Cleanup constant memory threshold in Cuda backend

### PR DESCRIPTION
**Pull request by Rombur**
Outdated comment that looked like a copy/paste accident

### CODE REVIEW

**Comment by masterleinad** [comment]
https://github.com/kokkos/kokkos/commit/9ef2e89e39c68458ecd86cb94f8a360fc89f3c70 changed this fro `0x000000` to `0x000200`.

**Comment by crtrott** [comment]
Yeah there might have been a reason for that. When I did the work item property stuff I reran tons of benchmarks to figure out what a good value for that threshold is...

**Comment by dhollman** [comment]
It looks to me like maybe @crtrott updated this when the launch bounds customization was added (allowing for a more reasonable default since the launch bounds customization is now available) but forgot to change the comment next to it to reflect the change.

**Comment by jeffmiles63** [comment]
Here are the Benchmark results from kokkos-dev-2

## Rombur:memory_threshold
BytesAndFlops: 4.4810150 5.5449950
miniMD: 7.2684900 4.2878150 12.2164000 2
MiniFE: 2.2643400 2.2264050 2
Total Result:  5.46992

## Kokkos Master
BytesAndFlops: 4.4812250 5.5222350
miniMD: 7.2755850 4.3260600 12.2103000 2
MiniFE: 2.2815950 2.3449200 2
Total Result:  5.4917

looks like a slight decrease - %0.4

**Comment by crtrott** [comment]
lets just fix the comment, based on so many customers having latency issues in particular with small linear algebra kernels.

**Pull request merged**
