### PR TITLE
Use 2 ULP in mathematical functions test

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes the failing ICC CI.

### CODE REVIEW

**Review by DavidPoliakoff — APPROVED** [review]
Looks good to me, if it passes CI

**Comment by crtrott** [comment]
I actually want a 2 at each of the definition sites. The comparison should use the ulp * epsilon and not add anything.

**Review by crtrott — CHANGES_REQUESTED** [review]
See my above comment.

**Review by DavidPoliakoff — APPROVED** [review]
Sure, this works too

**Review by crtrott — APPROVED** [review]
Thanks!

**Comment by masterleinad** [comment]
The ICC CI passed.

**Pull request merged**
