### PR TITLE
[4.0.0] Work around Intel Classic ICE in Sacado during release testing

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
I guess we should do the same for `develop`.

**Comment by ndellingwood** [comment]
@crtrott  Several failures, the CI Jenkins fail in `KokkosCore_UnitTest_CudaTimingBased` is typically spurious, the others may be legitimate

The HPX test fails with a segfault in `workgraph_fib`
```
[ RUN      ] hpx.workgraph_fib
{what}: Segmentation fault
```

icpx OpenMP test fails with a segfault in the `default_exec.overlap_range_policy` subtest of `KokkosCore_PerfTestExec` (the test apparently just hangs)

Testing an intel/19.0.5 OpenMP build of Sacado compiled successfully with no occurrence of ICE

**Comment by PhilMiller** [comment]
The HPX failure is likely related to https://github.com/kokkos/kokkos/issues/5748 - it's clearly not using the OpenMP code, so it can't be affected by this.

**Comment by crtrott** [comment]
Closing this in favor of potentially using inline limiting compiler flags.

**Pull request closed without merging**
