### PR TITLE
DynRankView: Update memory_traits to non-deprecated versions

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Specialization of `operator[](...)` for Sacado and Stokhos with deprecated code disabled was triggered during Trilinos testing for 2.9 promotion.

**Comment by ibaned** [comment]
started spot check on `kokkos-dev`

**Comment by ibaned** [comment]
Passed most tests, only failed to to hangup signal, don't think its a Kokkos issue:
```
#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-release build_time=225 run_time=535
cuda-8.0.44-Cuda_OpenMP-release build_time=608 run_time=665
gcc-5.3.0-OpenMP-hwloc-release build_time=197 run_time=132
gcc-5.3.0-OpenMP-release build_time=214 run_time=153
gcc-7.3.0-Serial-hwloc-release build_time=164 run_time=257
gcc-7.3.0-Serial-release build_time=167 run_time=301
intel-17.0.1-OpenMP-hwloc-release build_time=470 run_time=202
intel-17.0.1-OpenMP-release build_time=534 run_time=209
```

**Comment by ndellingwood** [comment]
Thanks @ibaned !

**Pull request merged**
