### PR TITLE
Remove XL compiler support

### PR DESCRIPTION
**Pull request by masterleinad**
Based on top of #5323. I didn't touch the test scripts for Sandia machines.

### CODE REVIEW

**Review by cz4rs — APPROVED** [review]
Looks good to me.

**Review by fnrizzi — APPROVED** [review]

**Review by dalg24 — COMMENTED** [review]
Please open an issue to add a configure option to enable;le configuring with a compiler that is not supported

**Comment by dalg24** [comment]
Will merge after you update the none -> not and open an issue

**Comment by masterleinad** [comment]
> Will merge after you update the none -> not and open an issue

See https://github.com/kokkos/kokkos/issues/5413.

**Pull request merged**
