### PR TITLE
Add missing fence() calls in resize(View) that effectively do deep_copy(resized, orig)

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Comment by dalg24** [comment]
Retest this please.

Please provide a description and make sure you explain why these fences are missing.

**Comment by crtrott** [comment]
The rational is that a resize effectively does a deep_copy. I.e. conceptually it does:
```c++
view_t new_view(old_view.label(), new_length);
deep_copy(subview(new_view,old_length), old_view);
```

Now the way resize is implemented it calls to an implementation mechanism of deep_copy which does not fence on its own, that means the copy will not be done by the time the call returns. The argument is that that is inconsistent with other memory oriented operations like deep_copy. 

That said I now thought we should discuss this. Zero initialization is asynchronous for example, maybe resize is more like that?

**Comment by msimberg** [comment]
If you're looking for more motivation for this, I've been working on updating the HPX backend and saw some failing tests with the asynchronous option enabled. One of the failures was this: https://github.com/kokkos/kokkos/blob/e4831441fb213bd29485327b02cf1b54149a58a7/core/unit_test/TestViewMapping_a.hpp#L934-L941. Either resize needs to fence or the test needs to fence after the resize if

**Comment by masterleinad** [comment]
I get
```
$ git grep -n "Impl::ViewRemap"
containers/src/Kokkos_DynamicView.hpp:600:    Kokkos::Impl::ViewRemap<dst_type, src_type>(dst, src);
containers/src/Kokkos_DynamicView.hpp:625:    Kokkos::Impl::ViewRemap<dst_type, src_type>(dst, src);
core/src/Kokkos_CopyViews.hpp:2985:  Kokkos::Impl::ViewRemap<view_type, view_type>(v_resized, v);
core/src/Kokkos_CopyViews.hpp:3083:  Kokkos::Impl::ViewRemap<view_type, view_type>(v_resized, v);
core/src/Kokkos_CopyViews.hpp:3100:  Kokkos::Impl::ViewRemap<view_type, view_type>(v_resized, v);
```
so we should at least treat the instances in `Kokkos_DynamicView.hpp` similarly.

> That said I now thought we should discuss this. Zero initialization is asynchronous for example, maybe resize is more like that?

IMHO, we should consider adding overloads that take an execution space and make that asynchronous while the current version is synchronous.
Also, AFAICT, zero initialization still fences the execution space it's executed one, see https://github.com/kokkos/kokkos/blob/347cb126a397e8194ca78dc01be0e7fc911c8d52/core/src/impl/Kokkos_ViewMapping.hpp#L2925-L2949.

**Review by dalg24 — CHANGES_REQUESTED** [review]
See #3966 
You need to add a label to these fences

**Comment by DavidPoliakoff** [comment]
(just a string on the fence calls, something to identify what this fence is for tools)

**Comment by crtrott** [comment]
Oh it does fence, yeah then we should fence for sure and add an overload which takes the exec space instnace.

**Comment by PhilMiller** [comment]
Can the overloads for execution space instance come later?

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Review by DavidPoliakoff — APPROVED** [review]
I'm just reviewing the fence profiling stuff, but that part looks good to me

**Pull request merged**
