### PR TITLE
Rework Clang-Tidy configuration and setup for hunting down bugprone-* warnings

### PR DESCRIPTION
**Pull request by dalg24**
* Updated the Clang-Tidy configuration to increase readability
* "Inverted" the logic for bugprone checks
  *  enable them all and (temporarily) disable the ones that currently report issues

The intent is to be able to incrementally resolve the issues being reported (not as part of this PR) and minimize conflicts in the configuration file.
I am specifically targeting bugprone-* checks, I still don't want us to pursue all sorts of random checks that can be found (see #3199)

PS: Talk to me before you try fixing any of these in follow up work to avoid duplicating efforts.

### CODE REVIEW

**Review by Rombur — APPROVED** [review]

**Comment by masterleinad** [comment]
I need something like
```diff
diff --git a/.clang-tidy b/.clang-tidy
index 0e11f994e..4991d1181 100644
--- a/.clang-tidy
+++ b/.clang-tidy
@@ -1,7 +1,9 @@
-Checks: '-*,
+Checks: >
+  -*,
   bugprone-*,
   -bugprone-assignment-in-if-condition,
   -bugprone-branch-clone,
+  -bugprone-crtp-constructor-accessibility,
   -bugprone-easily-swappable-parameters,
   -bugprone-empty-catch,
   -bugprone-exception-escape,
@@ -9,17 +11,18 @@ Checks: '-*,
   -bugprone-integer-division,
   -bugprone-macro-parentheses,
   -bugprone-misplaced-widening-cast,
-  -bugprone-multi-level-implicit-pointer-conversion
+  -bugprone-multi-level-implicit-pointer-conversion,
   -bugprone-narrowing-conversions,
   -bugprone-non-zero-enum-to-bool-conversion,
   -bugprone-reserved-identifier,
+  -bugprone-return-const-ref-from-parameter,
   -bugprone-signed-char-misuse,
   -bugprone-sizeof-expression,
   -bugprone-suspicious-include,
   -bugprone-suspicious-memory-comparison,
   -bugprone-suspicious-string-compare,
   -bugprone-switch-missing-default-case,
-  -bugprone-unchecked-optional-access
+  -bugprone-unchecked-optional-access,
   -bugprone-unhandled-self-assignment,
   -bugprone-unused-raii,
   -bugprone-use-after-move,
@@ -28,6 +31,6 @@ Checks: '-*,
   modernize-use-nullptr,
   modernize-use-using,
   kokkos-*,
-'
+
 FormatStyle: file
 HeaderFilterRegex: '(algorithms|benchmarks|containers|core|example|simd).*\.hpp'
```
for my `clang-tidy` to run clean.

**Comment by dalg24** [comment]
The INTEL-DATA-CENTER-MAX-1100 build does not seem to pickup the suppressions, but interestingly it also reported `bugprone-crtp-constructor-accessibility` so I am going to add it to the list.
@masterleinad any idea what is going on with it?

**Comment by dalg24** [comment]
Thanks!

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
This one is so bizarre (in the HPX build)
```
/home/runner/work/kokkos/kokkos/kokkos/core/unit_test/UnitTest_ScopeGuard.cpp:148:16: error: suspicious exception object created but not thrown; did you mean 'throw is_copy_assignable'? [bugprone-throw-keyword-missing,-warnings-as-errors]
static_assert(!std::is_copy_assignable<Kokkos::ScopeGuard>());
               ^
/home/runner/work/kokkos/kokkos/kokkos/core/unit_test/UnitTest_ScopeGuard.cpp:149:16: error: suspicious exception object created but not thrown; did you mean 'throw is_copy_constructible'? [bugprone-throw-keyword-missing,-warnings-as-errors]
static_assert(!std::is_copy_constructible<Kokkos::ScopeGuard>());
               ^
/home/runner/work/kokkos/kokkos/kokkos/core/unit_test/UnitTest_ScopeGuard.cpp:152:16: error: suspicious exception object created but not thrown; did you mean 'throw is_move_assignable'? [bugprone-throw-keyword-missing,-warnings-as-errors]
static_assert(!std::is_move_assignable<Kokkos::ScopeGuard>());
               ^
/home/runner/work/kokkos/kokkos/kokkos/core/unit_test/UnitTest_ScopeGuard.cpp:153:16: error: suspicious exception object created but not thrown; did you mean 'throw is_move_constructible'? [bugprone-throw-keyword-missing,-warnings-as-errors]
static_assert(!std::is_move_constructible<Kokkos::ScopeGuard>());
               ^
3367 warnings generated.

**Comment by tpadioleau** [comment]
@dalg24 could be better with `static_assert(!std::is_copy_assignable_v<Kokkos::ScopeGuard>);` ?

**Comment by masterleinad** [comment]
> @dalg24 could be better with `static_assert(!std::is_copy_assignable_v<Kokkos::ScopeGuard>);` ?

You could try it out in a separate pull request. 🙂

**Comment by tpadioleau** [comment]
> You could try it out in a separate pull request. 🙂

sure

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
