### PR TITLE
Standalone compilation with tests

### PR DESCRIPTION
**Pull request by nschloe**
_Note: Don't merge yet._

This is a first shot at getting standalone compilation of Kokkos to work. I had to disable some failing tests (mostly due to `Kokkos::complex` not being found) and tinker a bit with Tribits, but all in all the changes are fairly minimal. Kokkos compiles fine and all test are passing:
```
Test project /home/nschloe/software/kokkos/build
      Start  1: KokkosContainers_UnitTest
 1/20 Test  #1: KokkosContainers_UnitTest ............   Passed  152.25 sec
      Start  2: KokkosAlgorithms_UnitTest
 2/20 Test  #2: KokkosAlgorithms_UnitTest ............   Passed   52.79 sec
      Start  3: KokkosCore_UnitTest_Serial
 3/20 Test  #3: KokkosCore_UnitTest_Serial ...........   Passed   62.09 sec
      Start  4: KokkosCore_UnitTest_DefaultInit_1
 4/20 Test  #4: KokkosCore_UnitTest_DefaultInit_1 ....   Passed    0.04 sec
      Start  5: KokkosCore_UnitTest_DefaultInit_2
 5/20 Test  #5: KokkosCore_UnitTest_DefaultInit_2 ....   Passed    0.04 sec
      Start  6: KokkosCore_UnitTest_DefaultInit_3
 6/20 Test  #6: KokkosCore_UnitTest_DefaultInit_3 ....   Passed    0.04 sec
      Start  7: KokkosCore_UnitTest_DefaultInit_4
 7/20 Test  #7: KokkosCore_UnitTest_DefaultInit_4 ....   Passed    0.03 sec
      Start  8: KokkosCore_UnitTest_DefaultInit_5
 8/20 Test  #8: KokkosCore_UnitTest_DefaultInit_5 ....   Passed    0.04 sec
      Start  9: KokkosCore_UnitTest_DefaultInit_6
 9/20 Test  #9: KokkosCore_UnitTest_DefaultInit_6 ....   Passed    0.04 sec
      Start 10: KokkosCore_UnitTest_DefaultInit_7
10/20 Test #10: KokkosCore_UnitTest_DefaultInit_7 ....   Passed    0.04 sec
      Start 11: KokkosCore_UnitTest_DefaultInit_8
11/20 Test #11: KokkosCore_UnitTest_DefaultInit_8 ....   Passed    0.04 sec
      Start 12: KokkosCore_UnitTest_DefaultInit_9
12/20 Test #12: KokkosCore_UnitTest_DefaultInit_9 ....   Passed    0.04 sec
      Start 13: KokkosCore_UnitTest_DefaultInit_10
13/20 Test #13: KokkosCore_UnitTest_DefaultInit_10 ...   Passed    0.04 sec
      Start 14: KokkosCore_UnitTest_DefaultInit_11
14/20 Test #14: KokkosCore_UnitTest_DefaultInit_11 ...   Passed    0.04 sec
      Start 15: KokkosCore_UnitTest_DefaultInit_12
15/20 Test #15: KokkosCore_UnitTest_DefaultInit_12 ...   Passed    0.04 sec
      Start 16: KokkosCore_UnitTest_DefaultInit_13
16/20 Test #16: KokkosCore_UnitTest_DefaultInit_13 ...   Passed    0.04 sec
      Start 17: KokkosCore_UnitTest_DefaultInit_14
17/20 Test #17: KokkosCore_UnitTest_DefaultInit_14 ...   Passed    0.03 sec
      Start 18: KokkosCore_UnitTest_DefaultInit_15
18/20 Test #18: KokkosCore_UnitTest_DefaultInit_15 ...   Passed    0.05 sec
      Start 19: KokkosCore_UnitTest_DefaultInit_16
19/20 Test #19: KokkosCore_UnitTest_DefaultInit_16 ...   Passed    0.04 sec
      Start 20: KokkosCore_UnitTest_HWLOC
20/20 Test #20: KokkosCore_UnitTest_HWLOC ............   Passed    0.03 sec

100% tests passed, 0 tests failed out of 20
```

### CODE REVIEW

**Comment by mhoemmen** [comment]
Hi @nschloe !  Does "standalone compilation" mean "using CMake"?  More importantly, could you make this a PR against the develop branch, once it's ready to merge?  Thanks :-)

**Comment by nschloe** [comment]
> Does "standalone compilation" mean "using CMake"?

Exactly.

> More importantly, could you make this a PR against the develop branch, once it's ready to merge?

I will. (Btw [one can set a default branch in GitHub](https://help.github.com/articles/setting-the-default-branch/), PRs are by default created against it.)

**Comment by mhoemmen** [comment]
Thanks @nschloe !  I'm not sure if the Kokkos leads want develop to be the default branch, that is, the branch that users would clone and see by default.  I think they would prefer that users get the master branch by default.  Is there a way to separate the branch that users would clone by default, from the branch that users would do PRs against by default?

**Comment by nschloe** [comment]
Cloning and working on one branch, but PRing into another with potentially big differences between them? That's probably not something that GitHub wants to encourage for the average developer, so I'd say it's not possible.

**Comment by crtrott** [comment]
Basically we want people to clone the stable master branch, but pull requests should be issued against the develop branch.

**Comment by crtrott** [comment]
Ok i looked at the changes. What is the matter with the commented out tests? Also why does that one test require the test for Lambda dispatch. It doesn't for the GNU Make build. Any idea? If not I am going off and check it myself. Looks like the actual changes to enable tests should be the one in the main CMakeList.txt and the tribits.cmake is that right?

**Comment by crtrott** [comment]
Any comment on my previous question? Otherwise I go ahead and see that I get the cmake things fixed this week.

**Comment by crtrott** [comment]
Ok I think I got this sorted out. I cherry picked a couple commits and did some extra work. Let me know if you see any issues.

**Comment by nschloe** [comment]
@crtrott Thanks! I just successfully compiled Kokkos with CMake.

**Pull request closed without merging**
