### PR TITLE
Add OpenMP check for clang

### PR DESCRIPTION
**Pull request by jjwilke**
Address #2250

@jjwilke please do not put the issue number in PR's subject, include it in the description instead.

### CODE REVIEW

**Comment by crtrott** [comment]
CMake doesn't figure this out? Or is it because we do not do CMake_ENABLE_OpenMP?

**Comment by jjwilke** [comment]
> CMake doesn't figure this out? Or is it because we do not do CMake_ENABLE_OpenMP?

Correct. We don't trigger CMake openmp checks (I don't think CMake has a  cmdline flag for forcing the test?) We can use `FindOpenMP` from CMake, if you trust it. That's definitely easier than what we have now where we have our own check and pick our own flags based on the compiler.  

Would you prefer to let CMake pick the flags?

**Comment by crtrott** [comment]
I guess not until someone shows me this works correctly if we compile with OpenMPTarget on ...

**Comment by crtrott** [comment]
Force pushed clang-format fixup

**Comment by jjwilke** [comment]
Yeah, I had been trying (originally) to make the CMake as much a perfect clone of `Makefile.kokkos` as possible.

I think using `find_package(OpenMP)` is a better long-term strategy. Any changes would be "non-API breaking" and are easy enough to do later.

**Comment by dalg24** [comment]
> `CMake_ENABLE_OpenMP`

I hope that you are kidding

**Comment by dalg24** [comment]
> We can use FindOpenMP from CMake, if you trust it.

Any reason we should not?

**Comment by crtrott** [comment]
I believe this is obsolete. After merging develop into this branch where are no differences to develop. Seems to be have merged as part of #2337

**Pull request closed without merging**
