### PR TITLE
Add restrict to DriverTypes to help compiler prove member variable re…

### PR DESCRIPTION
**Pull request by arghdos**
…ads do not alias w/ global writes

Change-Id: Ib46e666966e5d5b6d6de8b19992275847b8ac86f

### CODE REVIEW

**Review by dalg24 — CHANGES_REQUESTED** [review]
You missed
https://github.com/kokkos/kokkos/blob/5b318e322397d2b308698ad740a8c2d4fe4e59ba/core/src/HIP/Kokkos_HIP_KernelLaunch.hpp#L116-L120

**Comment by arghdos** [comment]
updated.

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Comment by Rombur** [comment]
@arghdos How sure are we that adding `__restrict__` is always correct? This PR breaks the CI on MI60 and it *might* be the cause of random fails on MI100

**Comment by arghdos** [comment]
@Rombur -- which tests are failing?  We're already marking the `DriverType` as `const` (i.e., can't be written to), so I am trying to understand what it could actually alias with.  All I can come up with off the top of my head is the extremely pathological:

```
__device__ int* some_global;

class Functor foo {
   int* some_ref;
   View v;  
   __host__ __device__
   foo () {
       some_ref = some_global;
   }
   operator()(i) {
      some_global[i] = i;
      V(i) = some_ref[i];
   }
};
```

**Comment by Rombur** [comment]
The failing test is `hip.view_api_b` : https://github.com/kokkos/kokkos/blob/master/core/unit_test/TestViewAPI.hpp#L951-L971

**Comment by stanmoore1** [comment]
I know this caused a test to fail but it gives over 3 TFLOPS improvement on AMD (!), can we revisit?

v3.6.00
```
./bytes_and_flops.exe 2 100000 1024 1 1 8 64 256 6000
NKRUFTS: 100000 1024 1 8 64 256 6000 Time: 0.006993s Bandwidth: 327.307344GiB/s GFlop/s: 15199.935020
```
cherry-pick 801be4b43cf4988fc3dda40b43f5189e68f1bfd8 in v3.6.00
```
~/kokkos/benchmarks/bytes_and_flops> ./bytes_and_flops.exe 2 100000 1024 1 1 8 64 256 6000
NKRUFTS: 100000 1024 1 8 64 256 6000 Time: 0.005773s Bandwidth: 396.473060GiB/s GFlop/s: 18411.944816
```

**Comment by arghdos** [comment]
It's only my perpetually growing to-do list :P.  

 The 4.5 compiler issue is... unfortunate, but more problematic I think the solution I had here _probably_ isn't _legal_ for the general case, see, e.g.: https://github.com/kokkos/kokkos/pull/4755#issuecomment-1034942276.

**Comment by arghdos** [comment]
I suspect the _true_ solution is to figure out what in the heck our compiler thinks is aliasing w/ the member variables in the Teams struct and mark _just those_ as `restrict`'d

**Pull request merged**
