### PR TITLE
DESUL: Use builtin atomics  in the HIP backend

### PR DESCRIPTION
**Pull request by Rombur**
This PR uses builtin atomics in atomic_fetch for the HIP backend. The code  was extracted from  #6031.

### CODE REVIEW

**Comment by crtrott** [comment]
Lets wait till its merged in Desul.

**Review by dalg24 — APPROVED** [review]
Please confirm that this is in sync with what was actually merged into Desul

**Comment by Rombur** [comment]
> Please confirm that this is in sync with what was actually merged into Desul

Yes, it is the same code

**Review by masterleinad — APPROVED** [review]

**Comment by ndellingwood** [comment]
Does this merit a changelog entry for 4.4 #6914 ?

**Comment by masterleinad** [comment]
> Does this merit a changelog entry for 4.4 #6914 ?

done

**Pull request merged**
