### PR TITLE
LayoutTiled: Initial implementation

### PR DESCRIPTION
**Pull request by ndellingwood**
Added LayoutTiled to Kokkos_Layouts;
ViewOffset for LayoutTiled with
operator(), ViewMapping overloads and
tile_subview functions for ranks 2-8.

Initial unit testing on host for ranks 2 and 3.

1. Add unit tests for remaining ranks
2. Add missing ExecSpace testing
3. Consider specializations of LayoutTiled to support default iterate
patterns - update ViewOffset, etc
4. Move Iterate enum type to common location
6. Decide what to name the ViewLayoutTiled file, or where contents go

 Changes to be committed:
	modified:   core/src/Kokkos_Layout.hpp
	new file:   core/src/impl/Kokkos_ViewLayoutTiled.hpp
	new file:   core/unit_test/TestViewLayoutTiled.hpp
	modified:   core/unit_test/serial/TestSerial_Other.cpp

### CODE REVIEW

**Comment by ndellingwood** [comment]
This is work with @swbova, pinging him on this new collaboration PR/branch :)

**Comment by swbova** [comment]
thanks for the shoutout :-)
I've fetched, built and run the unit test

**Comment by ndellingwood** [comment]
Changes to Kokkos_CopyViews were needed to enable deep_copy to work with LayoutTiled, first attempt of those changes pushed to my fork (not this PR) until we decide if that is the way to make deep_copy work.

**Comment by ibaned** [comment]
@ndellingwood and @crtrott need to coordinate on the final touches to this feature.

**Comment by swbova** [comment]
Here is a stencil-based gradient test code:

``` c++
#include <Kokkos_Core.hpp>
#include <iostream>
#include <impl/Kokkos_ViewLayoutTiled.hpp>
#include <Kokkos_Timer.hpp>

template <class ViewType>
struct ErrorNorm {
   
   ErrorNorm() = delete;
   
   const double hx;
   const double hy;
   const double hz;
   
   ViewType numericalGrad;
   ViewType analyticGrad;
   
   ErrorNorm(ViewType numerical, ViewType analytic, 
         const double dx, const double dy, const double dz ) :
            hx(dx), hy(dy), hz(dz),
            numericalGrad(numerical), analyticGrad(analytic){
   }
   
   void operator() (int i, int j, int k, double & sumMe) const {
      sumMe += (numericalGrad(k,j,i) - analyticGrad(k,j,i))*(numericalGrad(k,j,i) - analyticGrad(k,j,i))*hx*hy*hz;
   }
};

template <class ViewType>
struct InitializeCoords {
   
   InitializeCoords() = delete;
   
   const double hx;
   const double hy;
   const double hz;
   
   ViewType coords;
   
   InitializeCoords(ViewType coords_,
         const double dx, const double dy, const double dz ) :
            hx(dx), hy(dy), hz(dz),
            coords(coords_){
      std::cout << "InitializeCoords" <<  std::endl;
   }
   
   void operator() (int i, int j, int k) const {
     //      std::cout << i << " " << j << " " << k << std::endl;
      coords(k, j, i, 0) = i * hx;  
      coords(k, j, i, 1) = j * hy;  
      coords(k, j, i, 2) = k * hz;  
   }
};

template <typename FType, typename CoordsType, typename DType>
struct InitializeFields {
   
   InitializeFields() = delete;
   
   const double L;
   const double amplitude = 1;
   
   FType fields;
   CoordsType coords;
   DType dfdx;
   
   InitializeFields(CoordsType coords_, FType fields_, DType dfdx_, 
         const double L_) :
            L(L_), fields(fields_), coords(coords_), dfdx(dfdx_){
   }
   
   void operator() (int i, int j, int k) const {
      const double x = coords(k,j,i,0);
      const double xi = x/L;
      fields(k,j,i,0) = amplitude*xi*xi;
      fields(k,j,i,1) = amplitude*xi*xi;
      dfdx(k,j,i) = 2*amplitude*x/(L*L);
      
      //      std::cout << i << " " << j << " " << k << std::endl;
}
};
template <typename FType, typename DType>
struct InteriorGradient {
   
   InteriorGradient() = delete;
   
   const double invhx;
   const int fieldIndex;
   
   FType fields;
   DType dfdx;
   
   InteriorGradient(FType fields_, DType dfdx_, 
         const double hx_, const int fieldIndex_) :
            invhx(0.5/hx_), fieldIndex(fieldIndex_), fields(fields_), dfdx(dfdx_){
   }
   
   void operator() (int i, int j, int k) const {
      dfdx(k,j,i) = (fields(k,j,i+1, fieldIndex) - fields(k,j,i-1, fieldIndex) )*invhx; 
   }
};
template <typename FType, typename DType>
struct LeftGradient {
   
   LeftGradient() = delete;
   
   const double invhx;
   const int fieldIndex;
   
   FType fields;
   DType dfdx;
   
   LeftGradient(FType fields_, DType dfdx_, 
         const double hx_, const int fieldIndex_) :
            invhx(1./hx_), fieldIndex(fieldIndex_), fields(fields_), dfdx(dfdx_){
   }
   
   void operator() (int i, int j, int k) const {
      dfdx(k,j,i) = (fields(k,j,i+1, fieldIndex) - fields(k,j,i, fieldIndex) )*invhx; 
   }
};
template <typename FType, typename DType>
struct RightGradient {
   
   RightGradient() = delete;
   
   const double invhx;
   const int fieldIndex;
   
   FType fields;
   DType dfdx;
   
   RightGradient(FType fields_, DType dfdx_, 
         const double hx_, const int fieldIndex_) :
            invhx(1./hx_), fieldIndex(fieldIndex_), fields(fields_), dfdx(dfdx_){
   }
   
   void operator() (int i, int j, int k) const {
      dfdx(k,j,i) = (fields(k,j,i, fieldIndex) - fields(k,j,i-1, fieldIndex) )*invhx; 
   }
};

int main (int narg, char* arg[]){

  
   if(narg < 2) {
      std::cout << "Usage: gradient nx ny nz \n    where nx = number of cells in x dimension." << std::endl;   
      std::cout << "                                     ny = number of cells in y dimension." << std::endl;   
      std::cout << "                                     nz = number of cells in z dimension." << std::endl;   
      return 1;
   }

   std::cout << "initializing kokkos....." << std::endl;

   Kokkos::initialize (narg, arg);

   std::cout << "......done." << std::endl;

   const double L = 10;

   const int Nx = std::stoi(arg[1]);
   const int Ny = std::stoi(arg[2]);
   const int Nz = std::stoi(arg[3]);
   const double hx = L/Nx;
   const double hy = L/Ny;
   const double hz = L/Nz;

   std::cout << "Nx = " << Nx << std::endl;
   std::cout << "Ny = " << Ny << std::endl;
   std::cout << "Nz = " << Nz << std::endl;
   std::cout << "L = " << L << std::endl;
   std::cout << "hx = " << hx << std::endl;
   std::cout << "hy = " << hy << std::endl;
   std::cout << "hz = " << hz << std::endl;

   Kokkos::Timer timer;
   double errorRight = 0;
   double errorTiled = 0;
   {  // standard default layout

      using View3DType = Kokkos::View<double***, Kokkos::LayoutRight>;
      using View4DType = Kokkos::View<double****, Kokkos::LayoutRight>;
      using CoordsType = Kokkos::View<double****, Kokkos::LayoutRight> ;
      
      CoordsType coords("coords", Nz,Ny,Nx,3);
      
      View4DType fields("fields", Nz,Ny,Nx,2);
      
      View3DType dfdx("analyticGrad", Nz,Ny,Nx);
      View3DType df0dx("grad0", Nz,Ny,Nx);
      View3DType df1dx("grad1", Nz,Ny,Nx);

      Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDRP({0,0,0}, {Nx,Ny,Nz});
      
      Kokkos::parallel_for("initialize coords", threeDRP, 
            InitializeCoords<CoordsType>(coords, hx, hy, hz) );


      Kokkos::parallel_for("initialize fields", threeDRP, 
            InitializeFields<View4DType, CoordsType, View3DType>(coords, fields, dfdx, L)
      );
      
      Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDInteriorXRP({1,  0,0},
                                                                {Nx-1,Ny,Nz});
      //  std::cout << "at interior " << std::endl;
      const int fieldIndex = 0;
      Kokkos::parallel_for("computeGradXInterior", threeDInteriorXRP, 
            InteriorGradient<View4DType, View3DType>(fields, df0dx, hx, fieldIndex)
      );

      Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDLeftXBCRP({0,0,0},
                                                              {1,Ny,Nz});

      Kokkos::parallel_for("computeGradLeftXBC", threeDLeftXBCRP, 
            LeftGradient<View4DType, View3DType>(fields, df0dx, hx, fieldIndex)
      );


      Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDRightXBCRP({Nx-1,0,0},
            {Nx,Ny,Nz});
      Kokkos::parallel_for("computeGradXRightBC", threeDRightXBCRP, 
            RightGradient<View4DType, View3DType>(fields, df0dx, hx, fieldIndex)

      );

      Kokkos::parallel_reduce("computeError", threeDRP, 
            ErrorNorm<View3DType>( df0dx, dfdx, hx, hy, hz), errorRight);

      errorRight = sqrt(errorRight);
      std::cout << "standard layout gradient error = " << errorRight << "\n";
   }

   const double timeRight = timer.seconds();
   std::cout << "timeRight = " << timeRight << " seconds." << std::endl;   
   {  // Tiled layout

      std::cout << "tiled layouts" << "\n";

      timer.reset();
      
       static constexpr int Tx_size = 4;
       static constexpr int Ty_size = 4;
       static constexpr int Tz_size = 4;

       const int NT0 = int( std::ceil( double(Nx) / Tx_size ) );
       const int NT1 = int( std::ceil( double(Ny)/ Ty_size ) );
       const int NT2 = int( std::ceil( double(Nz)/ Tz_size ) );

       std::cout << "Tx_size = " << Tx_size << "\n";
       std::cout << "Ty_size = " << Ty_size << "\n";
       std::cout << "Tz_size = " << Tz_size <<  "\n";

       std::cout << "NT0 = " << NT0 << "\n";
       std::cout << "NT1 = " << NT1 << "\n";
       std::cout << "NT2 = " << NT2 << "\n";

       typedef Kokkos::LayoutTiled<Kokkos::Pattern::Iterate::Right, Kokkos::Pattern::Iterate::Right, Tz_size, Ty_size, Tx_size, 2>   LayoutRR_4D;
       typedef Kokkos::LayoutTiled<Kokkos::Pattern::Iterate::Right, Kokkos::Pattern::Iterate::Right, Tz_size, Ty_size, Tx_size>   LayoutRR_3D;

       // the following only issues a warning if the tile size is not a power of 2.
       typedef Kokkos::LayoutTiled<Kokkos::Pattern::Iterate::Right, Kokkos::Pattern::Iterate::Right, Tz_size, Ty_size, Tx_size, 4>   LayoutRR_Coords;


       if(Nx < Tx_size) {
          Kokkos::abort("mesh x dimension is smaller than tile size");
       } else if(Ny < Ty_size) {
          Kokkos::abort("mesh y dimension is smaller than tile size");
       } else if(Nz < Tz_size) {
          Kokkos::abort("mesh z dimension is smaller than tile size");
       }

       using View3DType = Kokkos::View<double***, LayoutRR_3D>;
       using View4DType = Kokkos::View<double****, LayoutRR_4D>;
       using CoordsType = Kokkos::View<double****, LayoutRR_Coords>;
       
       View4DType fields("fields", Nz,Ny,Nx,2);
       CoordsType coords("coords", Nz,Ny,Nx,3);

       View3DType dfdx("analyticGrad", Nz,Ny,Nx);
       View3DType df0dx("grad0", Nz,Ny,Nx);
       View3DType df1dx("grad1", Nz,Ny,Nx);

       //global indexed loop
       Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDRP({0,0,0}, {Nx, Ny, Nz}, {Tx_size, Ty_size, Tz_size});
       Kokkos::parallel_for("initialize coords", threeDRP, 
             InitializeCoords<CoordsType>(coords, hx, hy, hz) 
       );
       std::cout << "after intialize coords" << "\n";

       //tiled indexed loop
#if 0
       Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDRPTiled({0,0,0}, {NT0, NT1, NT2});
       
       Kokkos::parallel_for("initialize fields", threeDRPTiled, KOKKOS_LAMBDA(int ti, int tj, int tk) {
          
          auto fieldsTileSubview = Kokkos::tile_subview( fields, tk, tj, ti, 0 );
          auto dfdxTileSubview = Kokkos::tile_subview( dfdx, tk, tj, ti);
          auto coordsTileSubview = Kokkos::tile_subview( coords, tk, tj, ti, 0 );
//          std::cout << "( " << ti << ", " << tj << ", " << tk << ") " << std::endl;
          for ( int k = 0; k < Tz_size; ++k ) {
             for ( int j = 0; j < Ty_size; ++j ) {
                for ( int i = 0; i < Tx_size; ++i ) {
                   const double x = coords(k,j,i,0);
                   const double xi = x/L;
                   fieldsTileSubview(k,j,i,0) = amplitude*xi*xi;
                   fieldsTileSubview(k,j,i,1) = amplitude*xi*xi;
                   dfdxTileSubview(k,j,i) = 2*amplitude*x/(L*L);
                }
             }
          }
       }
       );
#else
       
       Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDRPTiled({0,0,0}, {Nx, Ny, Nz},
             {Tx_size, Ty_size, Tz_size});

       Kokkos::parallel_for("initialize fields", threeDRPTiled, 
             InitializeFields<View4DType, CoordsType, View3DType>(coords, fields, dfdx, L)
       );
#endif
       std::cout << "after intialize fields" << "\n";

       //compute gradients
       Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDInteriorXRP({1,0,0}, {Nx-1, Ny, Nz},
                                                                          {Tx_size, Ty_size, Tz_size});
       const int fieldIndex = 0;
       Kokkos::parallel_for("computeGradXInterior", threeDInteriorXRP, 
             InteriorGradient<View4DType, View3DType>(fields, df0dx, hx, fieldIndex)
       );

       std::cout << "after compute gradX interor" << "\n";
       Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDLeftXBCRP( {0,0,0}, {1, Ny, Nz}, 
             {Tx_size, Ty_size, Tz_size});

       Kokkos::parallel_for("computeGradLeftXBC", threeDLeftXBCRP, 
             LeftGradient<View4DType, View3DType>(fields, df0dx, hx, fieldIndex)
       );

       Kokkos::MDRangePolicy <Kokkos::Rank<3>> threeDRightXBCRP({Nx - 1,0,0}, {Nx, Ny,Nz}, 
             {Tx_size, Ty_size, Tz_size});
       
       Kokkos::parallel_for("computeGradXRightBC", threeDRightXBCRP,
             RightGradient<View4DType, View3DType>(fields, df0dx, hx, fieldIndex)
       );

       //compare
       Kokkos::parallel_reduce("computeError", threeDRP,   
             ErrorNorm<View3DType>( df0dx, dfdx, hx, hy, hz), errorTiled);

       errorTiled = sqrt(errorTiled);
       std::cout << "tiled layout gradient error = " << errorTiled << "\n";
   }
   const double timeTiled = timer.seconds();

   
   std::cout << "timeTiled = " << timeTiled << " seconds." << std::endl;
   std::cout << "tiled is " << (errorTiled - errorRight)/errorRight*100  <<" % different " << "\n";
   std::cout << "tiled is " << (timeRight - timeTiled)/timeRight*100 << " % faster." << "\n";
   Kokkos::finalize();
   return 0;
}
```

**Comment by swbova** [comment]
Compiled on host with serial backend and clang compiler -O3, ran some cases, got the following preliminary data, with  N=Nx=Ny=Nz

N  | % faster
---|-----
10  | -13.3
50 |   14
100 |  17
200 | 30
400 | 46

thse times are approximate, as I ran the cases a few times and eyeball averaged them.  as the problem size gets larger, variability decreases.  the time for N=10 is less than a millisecond.

**Comment by ndellingwood** [comment]
Updated the PR. Added more unit testings, guarded tests that use lambdas as needed when testing with Cuda, cleaned up some comments, guarded all LayoutTiled related code so that it is only compiled and tested when deprecated code is disabled. 
Merged (no-ff) with the current develop branch and resolved merge conflicts.

**Comment by ajpowelsnl** [comment]
@ibaned , @dalg24 -- is this (2018) PR still active?  If not, may we close?  If so, please summarize remaining steps, and definition of done.

**Comment by masterleinad** [comment]
This was merged at Oct 5, 2018.

**Pull request merged**
