### PR TITLE
MDRangePolicy: Fix tile dims when range span is 0

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Waiting on Cuda to finish but those builds unaffected by PR

```
[ndellin@kokkos-dev TestAllSandia]$ ../../config/test_all_sandia --spot-check
Running on machine: sems
Repository Status:  7e706e2e762a0f3e4313b658fadc8d67aadc9564 MDRangePolicy: Fix tile dims when range span is 0


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED gcc-6.1.0-Serial-hwloc-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
```

**Comment by ibaned** [comment]
@ndellingwood is this needed in the current promotion?

**Comment by ibaned** [comment]
nevermind I see from the promotion discussion that it is.

**Comment by ndellingwood** [comment]
This PR fixes case with division by 0 in the `MDRangePolicy`. This issue broke `Kokkos::resize` when applied to a default constructed View whose extents were all 0.

**Comment by ndellingwood** [comment]
@hcedwar @ibaned could either of you merge this PR?

**Comment by ibaned** [comment]
@ndellingwood I still haven't gotten permission

**Comment by ibaned** [comment]
CC'ing @crtrott

**Pull request merged**
