### PR TITLE
Added "TRIBITS Pthread" to PTHREAD CMake configuration in Kokkos.

### PR DESCRIPTION
**Pull request by kuberry**
Registers "Pthread" as a Tribits option that could be enabled (in Trilinos).

### CODE REVIEW

**Comment by kuberry** [comment]
Addresses issue #3555

**Review by jjwilke — APPROVED** [review]
According to discussion here https://github.com/kokkos/kokkos/issues/3555
this was tested with trilinos and solves the issue.

**Comment by ndellingwood** [comment]
Job has been hanging in CI for a couple days, trying a retest

**Comment by ndellingwood** [comment]
retest this please

**Comment by ndellingwood** [comment]
@dalg24 @masterleinad this PR has been hanging in Jenkins for a couple days, is there a way to check status or restart?

**Comment by dalg24** [comment]
OK to test

**Comment by ndellingwood** [comment]
@dalg24 I tested this PR in Trilinos (only Kokkos enabled, a gcc/7.2.0 build with Pthreads) and confirm successful configure/compilation/passing tests

Trilinos SHA: trilinos/Trilinos@c23783ec3ea1bc04a26c15bb2c61431d37807fde


<details>
<summary>Ctest summary snip</summary>
Test project /ascldap/users/ndellin/Trilinos/Build/ATDM-kd2-override-pthread
      Start  1: KokkosCore_UnitTest_Serial1_MPI_1
 1/35 Test  #1: KokkosCore_UnitTest_Serial1_MPI_1 ..................   Passed  154.55 sec
      Start  2: KokkosCore_UnitTest_Serial2_MPI_1
 2/35 Test  #2: KokkosCore_UnitTest_Serial2_MPI_1 ..................   Passed   48.74 sec
      Start  3: KokkosCore_UnitTest_SerialGraph_MPI_1
 3/35 Test  #3: KokkosCore_UnitTest_SerialGraph_MPI_1 ..............   Passed    0.08 sec
      Start  4: KokkosCore_UnitTest_Threads_MPI_1
 4/35 Test  #4: KokkosCore_UnitTest_Threads_MPI_1 ..................   Passed  197.81 sec
      Start  5: KokkosCore_UnitTest_Default_MPI_1
 5/35 Test  #5: KokkosCore_UnitTest_Default_MPI_1 ..................   Passed    0.48 sec
      Start  6: KokkosCore_UnitTest_PushFinalizeHook_MPI_1
 6/35 Test  #6: KokkosCore_UnitTest_PushFinalizeHook_MPI_1 .........   Passed    0.08 sec
      Start  7: KokkosCore_UnitTest_Develop_MPI_1
 7/35 Test  #7: KokkosCore_UnitTest_Develop_MPI_1 ..................   Passed    0.07 sec
      Start  8: KokkosCore_UnitTest_PushFinalizeHook_terminate
 8/35 Test  #8: KokkosCore_UnitTest_PushFinalizeHook_terminate .....   Passed    2.13 sec
      Start  9: KokkosCore_ProfilingTestLibraryLoad_MPI_1
 9/35 Test  #9: KokkosCore_ProfilingTestLibraryLoad_MPI_1 ..........   Passed    0.08 sec
      Start 10: KokkosCore_UnitTest_DefaultInit_1_MPI_1
10/35 Test #10: KokkosCore_UnitTest_DefaultInit_1_MPI_1 ............   Passed    0.07 sec
      Start 11: KokkosCore_UnitTest_DefaultInit_2_MPI_1
11/35 Test #11: KokkosCore_UnitTest_DefaultInit_2_MPI_1 ............   Passed    0.07 sec
      Start 12: KokkosCore_UnitTest_DefaultInit_3_MPI_1
12/35 Test #12: KokkosCore_UnitTest_DefaultInit_3_MPI_1 ............   Passed    0.08 sec
      Start 13: KokkosCore_UnitTest_DefaultInit_4_MPI_1
13/35 Test #13: KokkosCore_UnitTest_DefaultInit_4_MPI_1 ............   Passed    0.07 sec
      Start 14: KokkosCore_UnitTest_DefaultInit_5_MPI_1
14/35 Test #14: KokkosCore_UnitTest_DefaultInit_5_MPI_1 ............   Passed    0.07 sec
      Start 15: KokkosCore_UnitTest_DefaultInit_6_MPI_1
15/35 Test #15: KokkosCore_UnitTest_DefaultInit_6_MPI_1 ............   Passed    0.07 sec
      Start 16: KokkosCore_UnitTest_DefaultInit_7_MPI_1
16/35 Test #16: KokkosCore_UnitTest_DefaultInit_7_MPI_1 ............   Passed    0.08 sec
      Start 17: KokkosCore_UnitTest_DefaultInit_8_MPI_1
17/35 Test #17: KokkosCore_UnitTest_DefaultInit_8_MPI_1 ............   Passed    0.07 sec
      Start 18: KokkosCore_UnitTest_DefaultInit_9_MPI_1
18/35 Test #18: KokkosCore_UnitTest_DefaultInit_9_MPI_1 ............   Passed    0.07 sec
      Start 19: KokkosCore_UnitTest_DefaultInit_10_MPI_1
19/35 Test #19: KokkosCore_UnitTest_DefaultInit_10_MPI_1 ...........   Passed    0.07 sec
      Start 20: KokkosCore_UnitTest_DefaultInit_11_MPI_1
20/35 Test #20: KokkosCore_UnitTest_DefaultInit_11_MPI_1 ...........   Passed    0.07 sec
      Start 21: KokkosCore_UnitTest_DefaultInit_12_MPI_1
21/35 Test #21: KokkosCore_UnitTest_DefaultInit_12_MPI_1 ...........   Passed    0.08 sec
      Start 22: KokkosCore_UnitTest_DefaultInit_13_MPI_1
22/35 Test #22: KokkosCore_UnitTest_DefaultInit_13_MPI_1 ...........   Passed    0.08 sec
      Start 23: KokkosCore_UnitTest_DefaultInit_14_MPI_1
23/35 Test #23: KokkosCore_UnitTest_DefaultInit_14_MPI_1 ...........   Passed    0.08 sec
      Start 24: KokkosCore_UnitTest_DefaultInit_15_MPI_1
24/35 Test #24: KokkosCore_UnitTest_DefaultInit_15_MPI_1 ...........   Passed    0.07 sec
      Start 25: KokkosCore_UnitTest_DefaultInit_16_MPI_1
25/35 Test #25: KokkosCore_UnitTest_DefaultInit_16_MPI_1 ...........   Passed    0.08 sec
      Start 26: KokkosCore_UnitTest_HostBarrier_MPI_1
26/35 Test #26: KokkosCore_UnitTest_HostBarrier_MPI_1 ..............   Passed    0.07 sec
      Start 27: KokkosCore_IncrementalTest_PTHREAD_MPI_1
27/35 Test #27: KokkosCore_IncrementalTest_PTHREAD_MPI_1 ...........   Passed    0.08 sec
      Start 28: KokkosCore_IncrementalTest_SERIAL_MPI_1
28/35 Test #28: KokkosCore_IncrementalTest_SERIAL_MPI_1 ............   Passed    2.94 sec
      Start 29: KokkosCore_UnitTest_CTestDevice_MPI_1
29/35 Test #29: KokkosCore_UnitTest_CTestDevice_MPI_1 ..............   Passed    0.08 sec
      Start 30: KokkosCore_UnitTest_CMakePassCmdLineArgs_0_MPI_1
30/35 Test #30: KokkosCore_UnitTest_CMakePassCmdLineArgs_0_MPI_1 ...   Passed    0.08 sec
      Start 31: KokkosCore_UnitTest_CMakePassCmdLineArgs_1_MPI_1
31/35 Test #31: KokkosCore_UnitTest_CMakePassCmdLineArgs_1_MPI_1 ...   Passed    0.07 sec
      Start 32: KokkosContainers_UnitTest_Threads_MPI_1
32/35 Test #32: KokkosContainers_UnitTest_Threads_MPI_1 ............   Passed   96.88 sec
      Start 33: KokkosContainers_UnitTest_Serial_MPI_1
33/35 Test #33: KokkosContainers_UnitTest_Serial_MPI_1 .............   Passed   90.22 sec
      Start 34: KokkosContainers_PerformanceTest_Threads_MPI_1
34/35 Test #34: KokkosContainers_PerformanceTest_Threads_MPI_1 .....   Passed  247.01 sec
      Start 35: KokkosAlgorithms_UnitTest_MPI_1
35/35 Test #35: KokkosAlgorithms_UnitTest_MPI_1 ....................   Passed   66.47 sec

100% tests passed, 0 tests failed out of 35

Subproject Time Summary:
Kokkos    = 909.11 sec*proc (35 tests)

Total Test time (real) = 909.15 sec
</details>

**Pull request merged**
