### PR TITLE
Fix flags passed to ARM compiler and NVHPC when `Kokkos_ARCH_NATIVE=ON`

### LINKED ISSUE #5808: ARCH=NATIVE not supported with ARM Compiler suite & NVHPC on ARM Systems
Hello, 

I am trying Kokkos on an ARM platform using the ARM compiler for Linux (https://developer.arm.com/downloads/-/arm-compiler-for-linux). Also I am using the NATIVE backend. Using this combination, I get the following error during the build:
```
error: the clang compiler does not support '-march=native'
```

Indeed march/mtune/mcpu flags handling is different among arch/compilers (see this article for instance https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu)

On ARM we expect the flag to be `-mcpu=native` instead of having `-mtune=native -march=native`. I encountered similar issue when using the NVidia suite (nvhpc 22.9) on ARM platform (`nvc++-Error-Unknown switch: -mtune=native`).

I did not find any reference on ARCH=NATIVE on ARM platforms in the Kokkos documentation, and also tried few keywords in the tracker without any luck. Is there any workaround ?

Below is a sample script to reproduce the issue (just have to adapt compiler env setup).

PS: I would like the atos.net domain to be authorized on the slack or get an invitation 😇

Best.

## compilers (with versions)
arm-compiler-for-linux_22.1_RHEL-8_aarch64

## Kokkos release or commit used (i.e., the sha1 number)
3.7.1 targz from github releases

## platform and backend

Using Kokkos_ARCH=NATIVE on ARM systems:
* Ampere Altra Q8030 (Neoverse N1)
* Fujitsu FX700 (A64FX)

## cmake configure command
```
(cd build && cmake \
        -DKokkos_ARCH_NATIVE=ON \
        -G "Unix Makefiles" \
        ../kokkos-3.7.01)
```

## output from cmake command
```
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is Clang 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /software/arm/armclang-22.1/arm-linux-compiler-22.1_Generic-AArch64_RHEL-8_aarch64-linux/bin/armclang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- The project name is: Kokkos
-- SERIAL backend is being turned on to ensure there is at least one Host space. To change this, you must enable another host execution space and configure with -DKokkos_ENABLE_SERIAL=OFF or change CMakeCache.txt
-- Using -std=gnu++14 for C++14 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: NoTypeDefined
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  NATIVE
-- Found TPLLIBDL: /usr/include  
-- Using internal desul_atomics copy
-- Kokkos Devices: SERIAL, Kokkos Backends: SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /home_nfs/bmorvana/test/kokkos_bug_001/build
```

## code needed to reproduce the bug
Kokkos source

## command line needed to reproduce the bug
cmake above + make

## please also attach the `KokkosCore_config.h` header file (generated during the build);
irrelevant (kokkos build failed)

## Reproducer:
```bash
#!/bin/bash -eu

## Fetch & Extract
[ ! -f kokkos-3.7.1.tar.gz ] && wget https://github.com/kokkos/kokkos/archive/refs/tags/3.7.01.tar.gz -O kokkos-3.7.1.tar.gz
[ ! -d kokkos-3.7.01 ] && tar xf kokkos-3.7.1.tar.gz

## Setup Compiler Env
## adapt to your system
module use /software/arm/armclang-22.1/modulefiles
module load acfl/22.1
export CXX=armclang++

## Configure
rm -rf build prefix
mkdir -p build prefix
(cd build && cmake \
        -DKokkos_ARCH_NATIVE=ON \
        -G "Unix Makefiles" \
        ../kokkos-3.7.01) |& tee 01_cmake.log

## Build - observe failure
(cd build && make VERBOSE=1)
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #5808 

Haven't actually tested.
Also not sure yet what flags we should be using with the NVHPC compiler.

cc @antoine-morvan does that do what you want?

### CODE REVIEW

**Comment by antoine-morvan** [comment]
Works fine with NVHPC. Just suggesting the use of tp=host instead of tp=native (as native is an alias for host).


Does not work for ARMClang. CMake is identifying the compiler as clang:
```
-- Setting default Kokkos CXX standard to 17
-- The CXX compiler identification is Clang 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /software/arm/armclang-22.1/arm-linux-compiler-22.1_Generic-AArch64_RHEL-8_aarch64-linux/bin/armclang++ - skipped
```

Thus the following will not be taken 
```
    ARMClang -mcpu=native
```

A fix could be to use -mcpu=native when the compiler is clang AND platform is ARM.

**Comment by dalg24** [comment]
What version of CMake were you using?

**Comment by antoine-morvan** [comment]
In the test above I was using CMake 3.20.2. Just tried with 3.25.1 and observed similar behavior.

**Review by crtrott — APPROVED** [review]

**Review by rgayatri23 — APPROVED** [review]

**Comment by masterleinad** [comment]
According to https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu#_ftn1 and https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html (which is cited by the former one),
> When GNU or LLVM compilers use the same flags on x86, the -mcpu flag is just a deprecated synonym for -mtune. 

Thus, it appears to me that we should use `-march=native -mtune=native` for x86 and `-mcpu=native` for `Arm`. Can you please elaborate why you are choosing `-mcpu=native` instead (also for standard x86)?

**Comment by dalg24** [comment]
> According to https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu#_ftn1 and https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html (which is cited by the former one),
> 
> > When GNU or LLVM compilers use the same flags on x86, the -mcpu flag is just a deprecated synonym for -mtune.
> 
> Thus, it appears to me that we should use `-march=native -mtune=native` for x86 and `-mcpu=native` for `Arm`. Can you please elaborate why you are choosing `-mcpu=native` instead (also for standard x86)?

#5808 reports that ARMClang compiler is being identified by CMake as plain vanilla Clang.
What alternative do you suggest?  Just before setting the compiler specific arch flag, if the compiler is clang `${cxx} --version` and regex match to determine if it is ARMClang?

For the record, ARMClang prints
```
Arm C/C++/Fortran Compiler version 21.1 (build number 1069) (based on LLVM 12.0.1)

**Comment by masterleinad** [comment]
godbolt is telling me for clang++
```
clang-15: warning: argument unused during compilation: '-mcpu=native' [-Wunused-command-line-argument]
```
and we also see that in the CI. I think we should parse `${cxx} --version` to overwrite the `CMake`'s compiler identification with `ARMClang` and set `-mcpu=native` only for that.

**Comment by antoine-morvan** [comment]
I don't know how godbolt handles its LLVM toolchains, but the ones I use have support for "-mpcu=native":

Spack LLVM@15.0.7
```
✓ aarch64    [o118] bmorvana@o118 ~ $ uname -a
Linux o118 4.18.0-240.el8.aarch64 #1 SMP Wed Sep 23 05:09:38 EDT 2020 aarch64 aarch64 aarch64 GNU/Linux
✓ aarch64    [o118] bmorvana@o118 ~ $ clang++ --version
clang version 14.0.6
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home_nfs/bmorvana/git/spack/opt/spack/linux-rhel8-neoverse_n1/gcc-8.5.0/llvm-14.0.6-6fl2325pwkrzvlyx3gldtqtxubu4u6jq/bin
✓ aarch64    [o118] bmorvana@o118 ~ $ echo "" | clang++ -c -o a.o -xc - -mcpu=native -Wall -Werror -Wextra
✓ aarch64    [o118] bmorvana@o118 ~ $ file a.o
a.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), not stripped
✓ aarch64    [o118] bmorvana@o118 ~ $
```
Spack LLVM@14.0.7
```
✓ aarch64    [o118] bmorvana@o118 ~ $ clang++ --version
clang version 15.0.7
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home_nfs/bmorvana/git/spack/opt/spack/linux-rhel8-neoverse_n1/gcc-8.5.0/llvm-15.0.7-ifeepbtbpk6tdyx4nxr7q5zdvi3eebdu/bin
✓ aarch64    [o118] bmorvana@o118 ~ $ echo "" | clang++ -c -g -o a.o -xc - -mcpu=native -Wall -Werror -Wextra
✓ aarch64    [o118] bmorvana@o118 ~ $ file a.o
a.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), not stripped
✓ aarch64    [o118] bmorvana@o118 ~ $
```

RedHat LLVM @14.0.6:
```
$ clang++ --version
clang version 14.0.6 (Red Hat 14.0.6-1.module+el8.7.0+15816+ec020e8f)
Target: aarch64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
✓ aarch64    [o118] bmorvana@o118 ~ $ echo "" | clang++ -c -g -o a.o -xc - -mcpu=native -Wall -Werror -Wextra
✓ aarch64    [o118] bmorvana@o118 ~ $ file a.o
a.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), not stripped
✓ aarch64    [o118] bmorvana@o118 ~ $
```

I also mention in the initial issue that LLVM versions prior to 15 do not support `-march=native` on ARM:
```
$ clang++ --version
clang version 14.0.6 (Red Hat 14.0.6-1.module+el8.7.0+15816+ec020e8f)
Target: aarch64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
 $ echo "" | clang++ -c -g -o a.o -xc - -march=native -Wall -Werror -Wextra
clang-14: error: the clang compiler does not support '-march=native'
```

Additionally, `-mcpu=native` is the ARM recommandation for GNU & LLVM compilers when compiling for ARM, not only its own, as recalled in the link in the initial issue: https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu . This is to temper when considering all the existing compilers ofc (like nvidia or fujitsu)

Finally, this is a general recommandation for all non x86 targets to use `-mcpu=native` : https://maskray.me/blog/2022-08-28-march-mcpu-mtune

**Comment by crtrott** [comment]
Also -mcpu is deprecated in GCC ... https://godbolt.org/z/Gf6WTvrxe

**Comment by crtrott** [comment]
And again the problem is that if I knew I am not on x86 why use native ... All in all I think we need to figure out how to identify clang-arm ...

**Comment by masterleinad** [comment]
@antoine-morvan Would try again with my branch? I tested it now by setting a dummy version string.

**Comment by antoine-morvan** [comment]
> Also -mcpu is deprecated in GCC ... https://godbolt.org/z/Gf6WTvrxe

Yes, on x86. Not on ARM (and most likely not on other architectures).

> And again the problem is that if I knew I am not on x86 why use native ...

Because it is the recommended way.

> All in all I think we need to figure out how to identify clang-arm ...

No, this issue is not specific to armclang. As stated above, vanilla LLVM prior to 15 on ARM fails with `-march=native`. And even with LLVM 15+, `-mcpu=native` is still the recommended way on ARM.

You should see it the other way arround: x86 is an exception where you use march/mtune, and all the other use mcpu.

And again godbolt toolchains do not behave similarly to production toolchains, please don't base your build system on this.

**Comment by antoine-morvan** [comment]
> @antoine-morvan Would you try again with my branch? I tested it now by setting a dummy version string.

still some issues:

```
CMake Error at cmake/kokkos_compiler_id.cmake:223 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  cmake/kokkos_tribits.cmake:215 (INCLUDE)
  CMakeLists.txt:213 (KOKKOS_SETUP_BUILD_ENVIRONMENT)


CMake Error at cmake/kokkos_compiler_id.cmake:224 (STRING):
  STRING sub-command FIND requires 3 or 4 parameters.
Call Stack (most recent call first):
  cmake/kokkos_tribits.cmake:215 (INCLUDE)
  CMakeLists.txt:213 (KOKKOS_SETUP_BUILD_ENVIRONMENT)

```

**Comment by masterleinad** [comment]
I opened https://github.com/kokkos/kokkos/pull/5831 to try setting the flag according to the target architecture.

**Comment by dalg24** [comment]
Superseded by #5831 and #5840

**Pull request closed without merging**
