### PR TITLE
Add View::stride(N) and use it in ScatterView

### PR DESCRIPTION
**Pull request by ibaned**
[#1214]

### CODE REVIEW

**Comment by crtrott** [comment]
Could you add a unit test. Seems like we don't have one to test the view stride interface at all ...

**Comment by ibaned** [comment]
```
Running on machine: sems
Repository Status:  9c7e4668bac97c3330a0a7e111395aafd5eb14b4 Add unit test for View::stride() methods


Going to test compilers:  gcc/4.8.4
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP_Serial-release
  Starting job gcc-4.8.4-OpenMP_Serial-hwloc-release
  PASSED gcc-4.8.4-OpenMP_Serial-hwloc-release
  PASSED gcc-4.8.4-OpenMP_Serial-release
#######################################################
PASSED TESTS
#######################################################
gcc-4.8.4-OpenMP_Serial-hwloc-release build_time=216 run_time=159
gcc-4.8.4-OpenMP_Serial-release build_time=218 run_time=159
```

**Comment by ibaned** [comment]
This seems to be segfaulting on Clang, probably don't merge

**Comment by ibaned** [comment]
Okay, segfaulting was caused by very strange behavior of `ViewMapping::Stride(Integral*)`. Removed that behavior and spot check passed:
```
Running on machine: sems
Repository Status:  84dd1e4c20095eaef72cf93f17a82a7108230540 Change ViewMapping::stride to not include span


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-release
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED intel-17.0.1-OpenMP-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=187 run_time=86
clang-3.9.0-Pthread_Serial-release build_time=197 run_time=213
cuda-8.0.44-Cuda_OpenMP-release build_time=476 run_time=575
gcc-5.3.0-OpenMP-hwloc-release build_time=251 run_time=144
gcc-5.3.0-OpenMP-release build_time=250 run_time=147
gcc-6.1.0-Serial-hwloc-release build_time=197 run_time=138
gcc-6.1.0-Serial-release build_time=196 run_time=166
intel-17.0.1-OpenMP-hwloc-release build_time=542 run_time=169
intel-17.0.1-OpenMP-release build_time=543 run_time=187
```

**Pull request merged**
