### PR TITLE
Device type for scatter view

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by crtrott** [comment]
Addresses issue #2826

**Comment by crtrott** [comment]
This is weird I actually did run and test this with CUDA and its still passing for me??

**Comment by ibaned** [comment]
No idea... one interesting thing is it was CUDA with DEBUG on

**Comment by crtrott** [comment]
I can't reproduce this using the same cmake command ...

**Comment by crtrott** [comment]
Retest this please

**Comment by stanmoore1** [comment]
I confirm this fixes #2826.

**Comment by masterleinad** [comment]
Retest this please.

**Pull request merged**
