### PR TITLE
Par deep copy simple

### PR DESCRIPTION
**Pull request by crtrott**
Alternative pull request to #1992 implementing deep copy via parallel_for. Performance data given in #1992.

### CODE REVIEW

**Comment by jjellio** [comment]
Copied and pasted your impl into my deep_copy impl

```
On a HSW desktop processor,
OMP_NUM_THREADS=7 OMP_PLACES=cores OMP_PROC_BIND=spread \
numactl -C 0-6 -m0 ./prog<name>.exe
```

|serial|me|trott|
| ------------- |:-------------:| -----:|
|Raw: 7.765531 GB/s|Raw: 29.880058 GB/s|Raw: 16.859784 GB/s|
|Rank1: 13.818712 GB/s|Rank1: 30.536385 GB/s|Rank1: 30.030004 GB/s|
|Rank2: 13.818344 GB/s|Rank2: 30.314402 GB/s|Rank2: 30.279677 GB/s|
|Rank3: 13.814651 GB/s|Rank3: 30.418345 GB/s|Rank3: 30.123991 GB/s|
|Raw: 7.763938 GB/s|Raw: 30.115790 GB/s|Raw: 16.449381 GB/s|
|Rank1: 13.809586 GB/s|Rank1: 30.453474 GB/s|Rank1: 29.949020 GB/s|
|Rank2: 13.822707 GB/s|Rank2: 30.381002 GB/s|Rank2: 30.136652 GB/s|
|Rank3: 13.817094 GB/s|Rank3: 30.501395 GB/s|Rank3: 30.165583 GB/s|
|Raw: 7.989883 GB/s|Raw: 30.012041 GB/s|Raw: 16.479550 GB/s|
|Rank1: 13.819685 GB/s|Rank1: 30.486119 GB/s|Rank1: 29.989804 GB/s|
|Rank2: 2.851219 GB/s|Rank2: 17.275346 GB/s|Rank2: 2.349073 GB/s|
|Rank3: 1.762009 GB/s|Rank3: 10.287346 GB/s|Rank3: 1.046823 GB/s|
|Raw: 7.771126 GB/s|Raw: 29.977445 GB/s|Raw: 17.291761 GB/s|
|Rank1: 13.815124 GB/s|Rank1: 30.370175 GB/s|Rank1: 30.047559 GB/s|
|Rank2: 2.851054 GB/s|Rank2: 17.112296 GB/s|Rank2: 2.360907 GB/s|
|Rank3: 3.331902 GB/s|Rank3: 10.641823 GB/s|Rank3: 1.066812 GB/s|
|Raw: 7.765293 GB/s|Raw: 30.525187 GB/s|Raw: 16.536300 GB/s|
|Rank4: 13.831618 GB/s|Rank4: 30.366700 GB/s|Rank4: 30.095904 GB/s|
|Rank5: 13.832466 GB/s|Rank5: 30.532714 GB/s|Rank5: 30.130301 GB/s|
|Raw: 7.768155 GB/s|Raw: 30.168962 GB/s|Raw: 17.363738 GB/s|
|Rank4: 13.813352 GB/s|Rank4: 30.461322 GB/s|Rank4: 30.253287 GB/s|
|Rank5: 13.808267 GB/s|Rank5: 30.616734 GB/s|Rank5: 30.078450 GB/s|
|Raw: 7.759612 GB/s|Raw: 29.841537 GB/s|Raw: 16.414850 GB/s|
|Rank4: 1.860402 GB/s|Rank4: 10.587571 GB/s|Rank4: 1.009037 GB/s|
|Rank5: 1.867037 GB/s|Rank5: 10.649579 GB/s|Rank5: 0.926837 GB/s|
|Raw: 7.769762 GB/s|Raw: 29.903787 GB/s|Raw: 17.239355 GB/s|
|Rank4: 1.862021 GB/s|Rank4: 10.597397 GB/s|Rank4: 0.963900 GB/s|
|Rank5: 1.866715 GB/s|Rank5: 10.610520 GB/s|Rank5: 0.907640 GB/s|
|Raw: 7.766320 GB/s|Raw: 30.039873 GB/s|Raw: 16.814163 GB/s|
|Rank6: 13.818914 GB/s|Rank6: 30.500596 GB/s|Rank6: 30.003138 GB/s|
|Raw: 7.770009 GB/s|Raw: 30.258532 GB/s|Raw: 16.618564 GB/s|
|Rank6: 13.810578 GB/s|Rank6: 30.464068 GB/s|Rank6: 30.003805 GB/s|
|Raw: 7.768738 GB/s|Raw: 30.294368 GB/s|Raw: 17.457840 GB/s|
|Rank6: 1.877345 GB/s|Rank6: 10.654180 GB/s|Rank6: 0.862504 GB/s|
|Raw: 7.769996 GB/s|Raw: 30.002194 GB/s|Raw: 16.389585 GB/s|
|Rank6: 1.877886 GB/s|Rank6: 10.661961 GB/s|Rank6: 0.849876 GB/s|
|Raw: 7.766777 GB/s|Raw: 30.206422 GB/s|Raw: 16.420899 GB/s|
|Rank7: 13.803484 GB/s|Rank7: 30.479535 GB/s|Rank7: 30.207962 GB/s|
|Raw: 7.765261 GB/s|Raw: 30.185094 GB/s|Raw: 16.468513 GB/s|
|Rank7: 13.816615 GB/s|Rank7: 30.369420 GB/s|Rank7: 30.215506 GB/s|
|Raw: 7.769292 GB/s|Raw: 29.732757 GB/s|Raw: 16.523155 GB/s|
|Rank7: 1.595060 GB/s|Rank7: 9.060515 GB/s|Rank7: 0.913207 GB/s|
|Raw: 7.769505 GB/s|Raw: 30.055192 GB/s|Raw: 16.466453 GB/s|
|Rank7: 1.694799 GB/s|Rank7: 9.577468 GB/s|Rank7: 0.927278 GB/s|
|Raw: 7.764475 GB/s|Raw: 29.781603 GB/s|Raw: 16.493215 GB/s|
|Rank8: 13.810531 GB/s|Rank8: 30.483620 GB/s|Rank8: 30.131758 GB/s|
|Raw: 7.768709 GB/s|Raw: 29.830822 GB/s|Raw: 16.457190 GB/s|
|Rank8: 13.819237 GB/s|Rank8: 30.502811 GB/s|Rank8: 30.243081 GB/s|
|Raw: 7.769229 GB/s|Raw: 29.695090 GB/s|Raw: 16.911768 GB/s|
|Rank8: 1.618543 GB/s|Rank8: 9.166357 GB/s|Rank8: 0.876526 GB/s|
|Raw: 7.765075 GB/s|Raw: 30.296305 GB/s|Raw: 16.468337 GB/s|
|Rank8: 1.598135 GB/s|Rank8: 8.936853 GB/s|Rank8: 0.853912 GB/s|
|Raw: 3.162787 GB/s|Raw: 19.755277 GB/s|Raw: 7.358420 GB/s|
|Rank1: 3.001376 GB/s|Rank1: 15.495771 GB/s|Rank1: 8.616770 GB/s|
|Rank2: 2.994093 GB/s|Rank2: 15.839907 GB/s|Rank2: 8.638451 GB/s|
|Rank3: 2.995149 GB/s|Rank3: 15.602295 GB/s|Rank3: 8.646884 GB/s|
|Rank4: 2.995180 GB/s|Rank4: 15.622365 GB/s|Rank4: 8.661895 GB/s|
|Rank5: 2.995514 GB/s|Rank5: 14.744024 GB/s|Rank5: 8.665584 GB/s|
|Rank6: 2.995419 GB/s|Rank6: 15.836115 GB/s|Rank6: 8.624434 GB/s|
|Rank7: 2.994787 GB/s|Rank7: 16.245389 GB/s|Rank7: 8.618481 GB/s|
|Rank8: 2.995015 GB/s|Rank8: 15.279147 GB/s|Rank8: 8.634954 GB/s|
|Raw: 3.157467 GB/s|Raw: 19.814772 GB/s|Raw: 7.353194 GB/s|
|Rank1: 3.027282 GB/s|Rank1: 16.048139 GB/s|Rank1: 8.646430 GB/s|
|Rank2: 2.995777 GB/s|Rank2: 15.196669 GB/s|Rank2: 8.655499 GB/s|
|Rank3: 2.995236 GB/s|Rank3: 16.261115 GB/s|Rank3: 8.661502 GB/s|
|Rank4: 2.995176 GB/s|Rank4: 15.698133 GB/s|Rank4: 8.657261 GB/s|
|Rank5: 2.995542 GB/s|Rank5: 15.097728 GB/s|Rank5: 8.654683 GB/s|
|Rank6: 2.995208 GB/s|Rank6: 15.509452 GB/s|Rank6: 8.650910 GB/s|
|Rank7: 2.995670 GB/s|Rank7: 16.088156 GB/s|Rank7: 8.660206 GB/s|
|Rank8: 2.994835 GB/s|Rank8: 15.522702 GB/s|Rank8: 8.651947 GB/s|
|Raw: 6.187617 GB/s|Raw: 21.595865 GB/s|Raw: 10.071074 GB/s|
|Rank1: 6.188899 GB/s|Rank1: 21.715519 GB/s|Rank1: 8.959299 GB/s|
|Rank2: 6.190318 GB/s|Rank2: 21.560128 GB/s|Rank2: 8.944734 GB/s|
|Rank3: 6.187450 GB/s|Rank3: 21.632484 GB/s|Rank3: 8.952709 GB/s|
|Raw: 6.189885 GB/s|Raw: 21.482427 GB/s|Raw: 10.088066 GB/s|
|Rank1: 6.186270 GB/s|Rank1: 21.355554 GB/s|Rank1: 8.943159 GB/s|
|Rank2: 6.187787 GB/s|Rank2: 21.495067 GB/s|Rank2: 8.909941 GB/s|
|Rank3: 6.185784 GB/s|Rank3: 21.728129 GB/s|Rank3: 8.949142 GB/s|
|Raw: 6.186165 GB/s|Raw: 21.490989 GB/s|Raw: 10.170486 GB/s|
|Rank4: 6.188181 GB/s|Rank4: 21.778533 GB/s|Rank4: 8.953608 GB/s|
|Rank5: 6.189326 GB/s|Rank5: 21.495511 GB/s|Rank5: 8.928333 GB/s|
|Raw: 6.191137 GB/s|Raw: 21.219077 GB/s|Raw: 10.175912 GB/s|
|Rank4: 6.191123 GB/s|Rank4: 21.540506 GB/s|Rank4: 8.913292 GB/s|
|Rank5: 6.190319 GB/s|Rank5: 21.523991 GB/s|Rank5: 8.947345 GB/s|
|Raw: 6.192046 GB/s|Raw: 21.229309 GB/s|Raw: 10.073278 GB/s|
|Rank6: 6.189779 GB/s|Rank6: 21.590200 GB/s|Rank6: 8.939268 GB/s|
|Raw: 6.189967 GB/s|Raw: 21.928221 GB/s|Raw: 9.998736 GB/s|
|Rank6: 6.190280 GB/s|Rank6: 21.210966 GB/s|Rank6: 8.926407 GB/s|
|Raw: 6.192977 GB/s|Raw: 21.779989 GB/s|Raw: 10.080514 GB/s|
|Rank7: 6.190250 GB/s|Rank7: 21.557172 GB/s|Rank7: 8.944669 GB/s|
|Raw: 6.186871 GB/s|Raw: 21.428734 GB/s|Raw: 10.089268 GB/s|
|Rank7: 6.188393 GB/s|Rank7: 21.433375 GB/s|Rank7: 8.938434 GB/s|
|Raw: 6.190943 GB/s|Raw: 21.337198 GB/s|Raw: 10.053319 GB/s|
|Rank8: 6.189673 GB/s|Rank8: 21.513042 GB/s|Rank8: 8.937250 GB/s|
|Raw: 6.189103 GB/s|Raw: 21.819778 GB/s|Raw: 10.133411 GB/s|
|Rank8: 6.190932 GB/s|Rank8: 21.653144 GB/s|Rank8: 8.934699 GB/s|
|Raw: 4.732106 GB/s|Raw: 27.686437 GB/s|Raw: 12.332754 GB/s|
|Rank1: 3.169914 GB/s|Rank1: 14.237625 GB/s|Rank1: 7.553146 GB/s|
|Rank2: 3.232744 GB/s|Rank2: 14.281956 GB/s|Rank2: 3.873743 GB/s|
|Rank3: 3.194843 GB/s|Rank3: 13.966642 GB/s|Rank3: 2.437975 GB/s|
|Raw: 4.732103 GB/s|Raw: 27.605764 GB/s|Raw: 13.530861 GB/s|
|Rank1: 3.185470 GB/s|Rank1: 14.392537 GB/s|Rank1: 7.404294 GB/s|
|Rank2: 3.221564 GB/s|Rank2: 14.385094 GB/s|Rank2: 3.858031 GB/s|
|Rank3: 3.160663 GB/s|Rank3: 14.807795 GB/s|Rank3: 2.404039 GB/s|
|Raw: 4.734235 GB/s|Raw: 26.671639 GB/s|Raw: 13.194183 GB/s|
|Rank4: 3.125235 GB/s|Rank4: 13.894962 GB/s|Rank4: 1.974704 GB/s|
|Rank5: 3.134635 GB/s|Rank5: 13.713599 GB/s|Rank5: 1.799379 GB/s|
|Raw: 4.732837 GB/s|Raw: 27.599056 GB/s|Raw: 13.156109 GB/s|
|Rank4: 3.176979 GB/s|Rank4: 14.141484 GB/s|Rank4: 1.985362 GB/s|
|Rank5: 3.088865 GB/s|Rank5: 13.819601 GB/s|Rank5: 1.800277 GB/s|
|Raw: 4.734547 GB/s|Raw: 27.310472 GB/s|Raw: 13.888000 GB/s|
|Rank6: 2.997200 GB/s|Rank6: 13.688184 GB/s|Rank6: 1.491376 GB/s|
|Raw: 4.802436 GB/s|Raw: 27.604818 GB/s|Raw: 13.233753 GB/s|
|Rank6: 3.026157 GB/s|Rank6: 14.127509 GB/s|Rank6: 1.489988 GB/s|
|Raw: 4.734048 GB/s|Raw: 27.477133 GB/s|Raw: 13.243631 GB/s|
|Rank7: 2.732864 GB/s|Rank7: 13.280283 GB/s|Rank7: 1.805026 GB/s|
|Raw: 4.731271 GB/s|Raw: 27.397336 GB/s|Raw: 13.224010 GB/s|
|Rank7: 1.994917 GB/s|Rank7: 10.546600 GB/s|Rank7: 1.295671 GB/s|
|Raw: 4.732817 GB/s|Raw: 27.679412 GB/s|Raw: 13.245563 GB/s|
|Rank8: 2.052171 GB/s|Rank8: 10.630165 GB/s|Rank8: 1.246787 GB/s|
|Raw: 4.732032 GB/s|Raw: 27.088323 GB/s|Raw: 13.200865 GB/s|
|Rank8: 2.225433 GB/s|Rank8: 11.557378 GB/s|Rank8: 1.246817 GB/s|

**Comment by crtrott** [comment]
See #1992 @jjellio data was probably off.

**Comment by jjellio** [comment]
Data here deleted, correct table is in 1992. I still see my impl winning at large sizes, and for small sizes the tuning between threaded vs not is the hard part.

My Tuning parameter was determined from Tpetra SpMV copyAndPermute calls.... I dont see how to choose a good one.  10-20KB is probably good. KNL is a nightmare. My Impl was a few factors better than serial on KNL. Data is on gitlab-ex

**Comment by jjellio** [comment]
I would really really prefer, if it was possible to use:
```
omp_target_memcpy()
```

We can push on vendors to make it not suck.

**Comment by crtrott** [comment]
Follow up should implement performance test posted in comments of #1992, but before merging this we should also check other sizes of scalar types. (i.e. deep_copy of int and complex<double>) I am not so worried about types which are not aligned to 4 bytes that just doesn't make much sense. That said, a deep_copy test of char with a non-4 byte length should be added. If the int test is slower than the double test, we should also just make it do a double loop, and then copy the last bytes extra.

**Comment by crtrott** [comment]
Running spot-check now. This is a proper fix including dealing with weird alignments etc. Performance is as stated in other pull request, but I gonna post some here again in a bit.

**Comment by crtrott** [comment]
Failed on CUDA only because of LAMBDA requirement in test :
```
Repository Status:  a1f41fb81cabb602aa4a3eba756440c0b266433e Committing missing test files


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  FAILED cuda-9.1-Cuda_OpenMP-release
...
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=131 run_time=425
clang-6.0-Cuda_Pthread-release build_time=226 run_time=290
clang-6.0-OpenMP-release build_time=115 run_time=87
gcc-4.8.4-OpenMP-release build_time=106 run_time=100
gcc-4.8.4-Pthread-release build_time=98 run_time=313
gcc-5.3.0-Serial-release build_time=113 run_time=169
intel-16.0.1-OpenMP-release build_time=333 run_time=145
#######################################################
FAILED TESTS
#######################################################
cuda-9.1-Cuda_OpenMP-release (build failed)
```

Pushing fix for CUDA now.

**Comment by crtrott** [comment]
Performance Comparing develop with this branch: 
- SKX: 20 cores single socket (kokkos-dev-2 gcc)
  - OMP_NUM_THREADS=20 OMP_PLACES=cores OMP_PROC_BIND=close
- ARM: 32 cores single socket (Mayer head node, ARM/19) 
  - OMP_NUM_THREADS=32 OMP_PLACES=cores OMP_PROC_BIND=close
- KNL: 16 cores (voltrino, intel 18)
  - OMP_NUM_THREADS=16 OMP_PLACES=cores OMP_PROC_BIND=close

N | R | SKX dev | SKX new | KNL dev | KNL new | ARM dev | ARM new
-- | -- | -- | -- | -- | -- | -- | --
16 | 6250000 | 25.926426 | 25.253 | 1.528901 | 1.352947 | 12.08018 | 10.831
32 | 3125000 | 35.556717 | 31.08876 | 3.045936 | 2.659929 | 16.82753 | 15.81419
64 | 1562500 | 56.531181 | 54.3911 | 5.863814 | 5.462643 | 20.71904 | 19.82258
128 | 781250 | 73.170239 | 72.00388 | 10.69854 | 9.775768 | 24.06035 | 23.81894
256 | 390625 | 84.766527 | 83.97565 | 19.23019 | 16.8282 | 27.87461 | 27.44335
512 | 195312 | 84.653798 | 82.49335 | 31.98911 | 28.01224 | 27.9936 | 29.16749
1024 | 97656 | 88.486784 | 86.55619 | 47.2689 | 41.25552 | 29.78997 | 29.64954
2048 | 48828 | 74.534728 | 71.60765 | 50.90886 | 40.58667 | 29.57595 | 29.02028
4096 | 24414 | 61.504905 | 60.43566 | 26.18853 | 24.81282 | 19.41748 | 19.43894
8192 | 12207 | 62.311522 | 61.64208 | 26.62828 | 25.70841 | 19.49054 | 19.5709
16384 | 6103 | 60.951907 | 52.22458 | 27.11016 | 43.77224 | 19.17202 | 10.46503
32768 | 3051 | 61.033601 | 102.204 | 26.68492 | 78.15142 | 17.09831 | 20.71288
65536 | 1525 | 27.365384 | 163.5542 | 12.31443 | 108.1718 | 17.12007 | 39.85122
131072 | 762 | 17.391316 | 286.8012 | 14.80497 | 153.8465 | 17.12407 | 73.94229
262144 | 381 | 15.48375 | 467.3387 | 16.345 | 186.1539 | 17.13215 | 129.2348
524288 | 190 | 14.324618 | 717.6106 | 16.47818 | 132.6588 | 17.13484 | 204.0066
1048576 | 95 | 14.383194 | 857.5629 | 16.35548 | 133.3081 | 17.13379 | 183.195
2097152 | 47 | 14.175949 | 235.0075 | 16.7028 | 139.8658 | 13.30359 | 205.22
4194304 | 23 | 13.501271 | 101.1375 | 16.59701 | 140.2042 | 10.44905 | 93.7079
8388608 | 11 | 12.078879 | 73.2933 | 16.46197 | 144.2827 | 10.38282 | 92.06852
16777216 | 5 | 10.998024 | 64.87061 | 16.39578 | 146.8658 | 10.33296 | 93.77025
33554432 | 2 | 10.58879 | 62.62998 | 16.43884 | 149.2976 | 10.11361 | 97.73799
67108864 | 1 | 10.412933 | 61.41154 | 16.43609 | 149.3317 | 10.2278 | 98.72023

Average Speedup
 - SKX 9.7 (15.3 for over 16k length) 
 - KNL 4.9 (7.5 for over 16k length)
 - ARM 4.8 (7.2 for over 16k length)

**Comment by jjellio** [comment]
I would check if you are currently in parallel, and if so choose the single threaded case. (Dan suggested that, and I tend to agree), people probably have this inside a parallel region somewhere, sure you can let it break (it is their fault), but maybe a better way to handle it.

**Comment by crtrott** [comment]
The Cuda retest passed (see the last commit which only changed a cuda subdirectory test file). This is ready to go in. 

@jjellio Regarding testing for parallel scope: this code will actually either just work (because it calls memcpy) - or fail with a message that you are calling it inside of a parallel scope, due to the fact that Kokkos::parallel_for will check. So I don't think we need to hold this up. This (the check execution) wasn't happening for the native OpenMP code but I believe it would have just worked as well with the usual nesting rules of OpenMP.

**Comment by crtrott** [comment]
Ok good to go.

**Comment by jhux2** [comment]
@jjellio @crtrott Thanks for all your hard work!

@crtrott When is the next Kokkos snapshot into Trilinos scheduled?

**Pull request merged**
