### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Please hold PR until successful pass and merge of https://github.com/trilinos/Trilinos/pull/11600

**Comment by ndellingwood** [comment]
retest this please

**Comment by ndellingwood** [comment]
HIP-ROCm-5.2 build error:
```
    Building CXX object CMakeFiles/cmTC_322d5.dir/thread_safety_attributes.cpp.o

    /opt/rocm/bin/hipcc    -Werror -Wno-unused-command-line-argument -DNDEBUG -Wall -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized  -std=c++11  -Wall  -Wextra  -Wshadow  -Wfloat-equal  -Wsuggest-override  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing  -Wthread-safety    -o CMakeFiles/cmTC_322d5.dir/thread_safety_attributes.cpp.o -c /var/jenkins/workspace/Kokkos/build/_deps/googlebenchmark-src/cmake/thread_safety_attributes.cpp

    In file included from /var/jenkins/workspace/Kokkos/build/_deps/googlebenchmark-src/cmake/thread_safety_attributes.cpp:2:

    In file included from /var/jenkins/workspace/Kokkos/build/_deps/googlebenchmark-src/cmake/../src/mutex.h:7:

    /var/jenkins/workspace/Kokkos/build/_deps/googlebenchmark-src/cmake/../src/check.h:8:10: fatal error: 'benchmark/export.h' file not found

    #include "benchmark/export.h"

             ^~~~~~~~~~~~~~~~~~~~

    1 error generated when compiling for gfx908.

```

@masterleinad @dalg24 any suggestion on the underlying cause of this error? Is this a CI quirk or something more substantial?

**Comment by dalg24** [comment]
This is not the cause for failure.   The actual issue is a runtime error (hipErrorOutOfMemory) and it is unrelated to this PR.

**Review by dalg24 — APPROVED** [review]

**Comment by ndellingwood** [comment]
https://github.com/trilinos/Trilinos/pull/11600 merged

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Pull request merged**
