### PR TITLE
Fix SIMD for GCC less than 8

### PR DESCRIPTION
**Pull request by ibaned**
GCC 7.2.0 and older don't provide the special
case _mm512_cmplt_pd_mask and friends, but all
the way down to GCC 5.5.0 do support the
three-argument _mm512_cmp_pd_mask intrinsic.
Instead of cluttering with #ifdef __GNUC__ < 8
everywhere, just use the three-argument instrinsic
always.
The Intel documentation suggests performance will
not suffer...

### CODE REVIEW

**Comment by ibaned** [comment]
Fixes #5313

**Review by PhilMiller — CHANGES_REQUESTED** [review]
https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#expand=727,1063,4909,1062,1062,1063&text=_mm512_mask_cmp_pd_mask&ig_expand=840
The documentation seems to show constants offering any of these comparisons. Could we just use them, rather than making obscure inversions?

**Comment by ibaned** [comment]
> https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#expand=727,1063,4909,1062,1062,1063&text=_mm512_mask_cmp_pd_mask&ig_expand=840 The documentation seems to show constants offering any of these comparisons. Could we just use them, rather than making obscure inversions?

Does 566848f41bb4360e4041b37fe5037252d38ae011 address this?

**Review by PhilMiller — APPROVED** [review]

**Comment by dalg24** [comment]
I would have expected we'd target the 3.7 release candidate branch and potentially do nothing in `develop` until we agree on the minimum GCC version we support going forward

**Comment by ibaned** [comment]
Pointed to 3.7 release candidate instead, please let me know if there is anything more I can do. To @dalg24 's point, the minimum GCC version that I know this works for is GCC 5.5.0. Of course I would love minimum GCC 8.1.0  :)

**Pull request merged**
