### PR TITLE
Fix ViewCtorProp specialization for SequentialHostInit

### PR DESCRIPTION
**Pull request by masterleinad**
Extracted from https://github.com/kokkos/kokkos/pull/7480/files#r1821082227. Basically, the specialization is missing to define a `sequential_host_init` alias. Let's see if we can just remove the specialization and if not we'll add the missing alias.

### CODE REVIEW

**Comment by dalg24** [comment]
What happened with the 1st commit that removes the specialization?
It looks like the MSVC build was interrupted, I cannot see an error.  I didn't see an error with NVCC either.

Also I can see that the alias is missing but I would like to know whether you just realized it was not there of if you actually got an error?  It would be good to add coverage for whatever that is fixing.

**Comment by masterleinad** [comment]
> It looks like the MSVC build was interrupted, I cannot see an error. I didn't see an error with NVCC either.

The log for the first commit (https://github.com/kokkos/kokkos/actions/runs/12303060987/job/34339315620?pr=7605) has
```
D:/a/kokkos/kokkos/core/src\View/Kokkos_ViewCtor.hpp(214): error C3520: 'P': parameter pack must be expanded in this context [D:\a\kokkos\kokkos\build\algorithms\unit_tests\Kokkos_AlgorithmsUnitTest_StdAlgoCompileOnly.vcxproj]
  D:/a/kokkos/kokkos/core/src\View/Kokkos_ViewCtor.hpp(214): note: the template instantiation context (the oldest one first) is
  C:\Users\runneradmin\AppData\Local\Temp\tmpxft_00000274_00000000-7_TestStdAlgorithmsCompileOnly.cudafe1.stub.c(9): note: see reference to class template instantiation 'Kokkos::Impl::FunctorAnalysis<Kokkos::Impl::FunctorPatternInterface::REDUCE,Kokkos::RangePolicy<Kokkos::Cuda>,Kokkos::FirstLoc<__int64,Kokkos::HostSpace>,Kokkos::FirstLocScalar<__int64>>' being compiled
  D:/a/kokkos/kokkos/core/src\impl/Kokkos_FunctorAnalysis.hpp(120): note: see reference to class template instantiation 'Kokkos::FirstLoc<__int64,Kokkos::HostSpace>' being compiled
  D:/a/kokkos/kokkos/core/src\Kokkos_Parallel_Reduce.hpp(1121): note: see reference to class template instantiation 'Kokkos::View<Kokkos::FirstLocScalar<__int64>,Space>' being compiled
          with
          [
              Space=Kokkos::HostSpace
          ]
  D:/a/kokkos/kokkos/core/src\View/Kokkos_ViewLegacy.hpp(1208): note: while compiling class template member function 'Kokkos::View<Kokkos::FirstLocScalar<__int64>,Space>::View(Kokkos::FirstLocScalar<__int64> *,const size_t,const size_t,const size_t,const size_t,const size_t,const size_t,const size_t,const size_t)'
          with
          [
              Space=Kokkos::HostSpace
          ]
  D:/a/kokkos/kokkos/core/src\Kokkos_Parallel_Reduce.hpp(1126): note: see the first reference to 'Kokkos::View<Kokkos::FirstLocScalar<__int64>,Space>::View' in 'Kokkos::FirstLoc<__int64,Kokkos::HostSpace>::FirstLoc'
          with
          [
              Space=Kokkos::HostSpace
[...]
```
I pushed the other fix after finding errors when monitoring that log.



> Also I can see that the alias is missing but I would like to know whether you just realized it was not there of if you actually got an error? It would be good to add coverage for whatever that is fixing.

It gets triggered in #7480. That's why I referred to that pull request.

**Comment by dalg24** [comment]
> It gets triggered in #7480. That's why I referred to that pull request.

Did you figure out what unmanaged view construction syntax yields the error?
Because we'd certainly want to add coverage in this PR

**Comment by masterleinad** [comment]
> Did you figure out what unmanaged view construction syntax yields the error?

With the changes to https://github.com/kokkos/kokkos/pull/7480/files#diff-ce6fbf19bf16c4ab89d35b2340a49768b223db1a800575b8313f27a801ab080d every constructing of an unmanaged View would detect the missing alias.

I added a test but I don't think there is a way to trigger the issue only using public interfaces right now.

**Comment by masterleinad** [comment]
In `jenkins` only the CUDA-12.2-NVHPC-AS-HOST-COMPILER is failing ICEing the compiler which looks unrelated.

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Pull request merged**
