### PR TITLE
Issue 1069

### PR DESCRIPTION
**Pull request by chipfreitag**
Implement algorithm unit/tests for ROCm .  Also resolve issue 1070.

### CODE REVIEW

**Comment by ibaned** [comment]
for book-keeping, actually linking to issues (need to use pound sign `#` and put in description, not title.
#1069, #1070

**Comment by chipfreitag** [comment]
Just added containers/unit_tests to the issue branch.    There are also test escapes for various tests that fail to build for rocm.  These could be ignored during merge.

**Comment by ibaned** [comment]
@crtrott merged the issue branch before you added those things. You'll need to create a new pull request.

**Comment by crtrott** [comment]
If you want to keep a pull request open and just openend it so other people can already start reviewing, just put a comment into the discussion that it is not ready to be merged.

**Pull request merged**
