### PR TITLE
Set CUDA stream in kernel launches

### PR DESCRIPTION
**Pull request by msimberg**
This PR

* adds an execution space instance to `MDRangePolicy`, and constructor overloads to pass an instance
* adds an execution space instance to the CUDA `TeamInternalPolicy`
* gets the stream from the execution space instance and passes it to the CUDA kernel launches

This would still need a follow-up to actually set the number of instances/streams to something bigger than 1 (the default, can't be changed by user). Maybe a command line option or environment variable? I've currently just changed the default number of streams to test locally.

A couple of tests fail for me, but they do so also on develop so I'm assuming they're unrelated to these changes. The failure is this (and it's always these two tests):

```
[ RUN      ] cuda.view_layoutstride_right_to_layoutleft_assignment                                                                                                                                                                                                               
view_layoutstride_right_to_layoutleft_assignment: srand(1540574933)                                                                                                                                                                                                              
/apps/daint/UES/simbergm/src/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:539: Failure                                                                                                                                                                               
Death test: {dst=src;}                                                                                                                                                                                                                                                           
    Result: died but not with expected error.                                                                                                                                                                                                                                    
  Expected: View assignment must have compatible layouts                                                                                                                                                                                                                         
Actual msg:                                                                                                                                                                                                                                                                      
[  DEATH   ] terminate called after throwing an instance of 'std::runtime_error'                                                                                                                                                                                                 
[  DEATH   ]   what():  cudaDeviceSynchronize() error( cudaErrorDevicesUnavailable): all CUDA-capable devices are busy or unavailable /apps/daint/UES/simbergm/src/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119                                                                 
[  DEATH   ] Traceback functionality not available                                                                                                                                                                                                                               
[  DEATH   ]                                                                                                                                                                                                                                                                     
[  DEATH   ]                                                                                                                                                                                                                                                                     
[  FAILED  ] cuda.view_layoutstride_right_to_layoutleft_assignment (19 ms)                                                                                                                                                                                                       
[ RUN      ] cuda.view_layoutstride_left_to_layoutright_assignment                                                                                                                                                                                                               
view_layoutstride_left_to_layoutright_assignment: srand(1540574933)
/apps/daint/UES/simbergm/src/kokkos/core/unit_test/TestViewLayoutStrideAssignment.hpp:662: Failure
Death test: {dst=src;}
    Result: died but not with expected error.
  Expected: View assignment must have compatible layouts
Actual msg:
[  DEATH   ] terminate called after throwing an instance of 'std::runtime_error'
[  DEATH   ]   what():  cudaDeviceSynchronize() error( cudaErrorDevicesUnavailable): all CUDA-capable devices are busy or unavailable /apps/daint/UES/simbergm/src/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
[  DEATH   ] Traceback functionality not available
[  DEATH   ]
[  DEATH   ]
[  FAILED  ] cuda.view_layoutstride_left_to_layoutright_assignment (19 ms)
```

Let me know if you think this might be a real problem, in which case I'll open an issue.

### CODE REVIEW

**Comment by crtrott** [comment]
There are a number of issues to be resolved with this we will start prioritizing this after the next promotion.

**Comment by msimberg** [comment]
Sure. Feel free to ignore this PR as well and do it in a better way. This will be very useful for launching CUDA work from within HPX.

**Comment by crtrott** [comment]
I have a new pull request (#1919) which does this correctly. But I need to merge your changes to TeamPolicy and MDRangePolicy in.

**Comment by msimberg** [comment]
@crtrott sounds good. Would you like me to remove the CUDA stream related changes from this PR in that case?

**Comment by crtrott** [comment]
I am doing it. I will merge in the one commit which modifies MDRangePolicy, and then manually add back in the TeamPolicyInternal space.

**Comment by crtrott** [comment]
Closing this at it is subsumed in #1932

**Pull request closed without merging**
