### PR TITLE
Fix Kokkos README's FENL link

### PR DESCRIPTION
**Pull request by mhoemmen**
FENL example lives in TrilinosCouplings now.

### CODE REVIEW

**Review by masterleinad — DISMISSED** [review]
You have to target `develop`.

**Comment by masterleinad** [comment]
The alternative would be to just delete these lines, of course, since we don't have any control over the future (location) of this example anyway.

**Comment by cedricchevalier19** [comment]
I think FENL example should also be listed in https://github.com/kokkos/kokkos-miniapps if this repo is still active.

**Review by dalg24 — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
The format check passed.  Ignoring everything else

**Pull request merged**
