### PR TITLE
Add modernize-use-using clang-tidy check

### PR DESCRIPTION
**Pull request by masterleinad**
This also fixes the places the current CI running the check is complaining about.

### CODE REVIEW

**Review by DavidPoliakoff — APPROVED** [review]
Looks good

**Comment by masterleinad** [comment]
Just to be clear: There still are places where we are using `typedef`.

**Comment by dalg24** [comment]
> Just to be clear: There still are places where we are using `typedef`.

Please elaborate.

**Comment by masterleinad** [comment]
> Please elaborate.

I only fixed the places `Clang` complained about for a configuration with `Kokkos_ENABLE_OPENMP` and `Kokkos_ENABLE_CUDA`. I am expecting that enabling other backends (like `Threads`, `OpenMPTarget`, `HPX`, maybe even `HIP`) `clang-tidy` would find (and fix) more places.
Still, even for the enabled backends, there are a number of places the check doesn't catch (maybe because these code paths are not covered by unit tests), like in `core/src/Cuda/Kokkos_Cuda_Parallel.hpp`.

**Pull request merged**
