### PR TITLE
Rc 3.6.0 changelog

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
@dalg24 @crtrott @masterleinad are more changes coming for this PR before it can be merged?

**Comment by dalg24** [comment]
Yes

**Review by dalg24 — DISMISSED** [review]
Blocking since we haven't gone over the full change log yet

**Comment by dalg24** [comment]
This is ready for review

**Review by crtrott — APPROVED** [review]

**Comment by masterleinad** [comment]
Looks like https://github.com/kokkos/kokkos/pull/4323 is missing?
Also, `Update HPX backend` #4241 and https://github.com/kokkos/kokkos/pull/4599 improving `NVHPC` support.

**Review by e10harvey — APPROVED** [review]
Thank you, @ndellingwood .

**Review by masterleinad — APPROVED** [review]

**Comment by ndellingwood** [comment]
@crtrott @dalg24 ready for merge I think? I don't have permissions to do so

**Pull request merged**
