### PR TITLE
Fix Reducers with Tagged Operators

### PR DESCRIPTION
**Pull request by crtrott**
This should fix both #1250 and #1251

### CODE REVIEW

**Comment by crtrott** [comment]
I am running some testing still but wanted travis to get started.

**Comment by crtrott** [comment]
Spotcheck on apollo past:
```
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=113 run_time=137
clang-4.0.0-Cuda_Pthread-release build_time=206 run_time=285
cuda-8.0.44-Cuda_OpenMP-release build_time=236 run_time=283
gcc-4.7.2-OpenMP-release build_time=101 run_time=74
gcc-4.7.2-Pthread-release build_time=97 run_time=74
gcc-5.1.0-Serial-release build_time=91 run_time=66
intel-16.0.1-OpenMP-release build_time=288 run_time=118

```

**Comment by crtrott** [comment]
Basically what needed to happen is that if a Reducer instead of an actual functor is given to our adapters which ferret out whether a join, init and final exist, we need to ignore the Tag since the reducers don't take the tag argument. Hence we need to pass a void on.

**Comment by ibaned** [comment]
Ah, nevermind, #1250 and #1251 illustrate how there could be tags and reducers at the same time. This all makes sense now.

**Comment by crtrott** [comment]
Yeah the main purpose is actually with multiple tagged operators in a class, and then combining this with min and max reductions etc.

**Pull request merged**
