### PR TITLE
More CUDA Volta issues

### PR DESCRIPTION
**Pull request by crtrott**
Issue #1942 and others

Only CUDA stuff was changed hence I only spot checked CUDA, but did that more thoroughly. 

```
[crtrott@apollo KokkosBuild]$ cat nohup.issue-1942-b 
nohup: ignoring input
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git'
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? patch_teamvectorrange

Repository Status:  b43d8a5e44d73c55a62cfa3ad5dc0747f1089db4 Make CUDA scratch resize not realloc but delete and allocate


Going to test compilers:  cuda/10.0 cuda/9.1 clang/6.0 clang/7.0
Testing compiler cuda/10.0
  Starting job cuda-10.0-Cuda_Serial-release
  PASSED cuda-10.0-Cuda_Serial-release
Testing compiler cuda/9.1
  Starting job cuda-10.0-Cuda_OpenMP-release
  PASSED cuda-10.0-Cuda_OpenMP-release
  Starting job cuda-9.1-Cuda_Serial-release
  PASSED cuda-9.1-Cuda_Serial-release
Testing compiler clang/6.0
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
  Starting job clang-6.0-Cuda_Serial-release
  PASSED clang-6.0-Cuda_Serial-release
Testing compiler clang/7.0
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
  Starting job clang-7.0-Cuda_Serial-release
  PASSED clang-7.0-Cuda_Serial-release
  Starting job clang-7.0-Cuda_Pthread-release
  PASSED clang-7.0-Cuda_Pthread-release
#######################################################
PASSED TESTS
#######################################################
clang-6.0-Cuda_Pthread-release build_time=222 run_time=283
clang-6.0-Cuda_Serial-release build_time=219 run_time=252
clang-7.0-Cuda_Pthread-release build_time=245 run_time=285
clang-7.0-Cuda_Serial-release build_time=239 run_time=253
cuda-10.0-Cuda_OpenMP-release build_time=369 run_time=162
cuda-10.0-Cuda_Serial-release build_time=360 run_time=153
cuda-9.1-Cuda_OpenMP-release build_time=366 run_time=163
cuda-9.1-Cuda_Serial-release build_time=354 run_time=151
```

### CODE REVIEW

**Comment by stanmoore1** [comment]
I'm getting a compile error in the automated ExaMiniMD regression tests than use the latest `develop` branch of Kokkos:

```
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp(839)>: error: identifier "m" is undefined
          detected during:
            instantiation of "__nv_bool Kokkos::Impl::cuda_single_inter_block_reduce_scan2<DoScan,FunctorType,ArgTag>(const FunctorType &, Kokkos::Cuda::size_type, Kokkos::Cuda::size_type, Kokkos::Cuda::size_type *, Kokkos::Cuda::size_type *, Kokkos::Cuda::size_type *) [with DoScan=true, FunctorType=NeighborCSR<t_neigh_mem_space>, ArgTag=NeighborCSR<t_neigh_mem_space>::TagCreateOffsets]"
(987): here
            instantiation of "__nv_bool Kokkos::Impl::cuda_single_inter_block_reduce_scan<DoScan,FunctorType,ArgTag>(const FunctorType &, Kokkos::Cuda::size_type, Kokkos::Cuda::size_type, Kokkos::Cuda::size_type *, Kokkos::Cuda::size_type *, Kokkos::Cuda::size_type *) [with DoScan=true, FunctorType=NeighborCSR<t_neigh_mem_space>, ArgTag=NeighborCSR<t_neigh_mem_space>::TagCreateOffsets]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(2024)>: here
            instantiation of "void Kokkos::Impl::ParallelScan<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::initial() const [with FunctorType=NeighborCSR<t_neigh_mem_space>, Traits=<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(2100)>: here
            instantiation of "void Kokkos::Impl::ParallelScan<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::operator()() const [with FunctorType=NeighborCSR<t_neigh_mem_space>, Traits=<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp(180)>: here
            instantiation of "void Kokkos::Impl::cuda_parallel_launch_local_memory(DriverType) [with DriverType=Kokkos::Impl::ParallelScan<NeighborCSR<t_neigh_mem_space>, Kokkos::RangePolicy<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>, Kokkos::DefaultExecutionSpace>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp(398)>: here
            instantiation of "Kokkos::Impl::CudaParallelLaunch<DriverType, Kokkos::LaunchBounds<0U, 0U>, false>::CudaParallelLaunch(const DriverType &, const dim3 &, const dim3 &, int, cudaStream_t) [with DriverType=Kokkos::Impl::ParallelScan<NeighborCSR<t_neigh_mem_space>, Kokkos::RangePolicy<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>, Kokkos::DefaultExecutionSpace>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(2151)>: here
            instantiation of "void Kokkos::Impl::ParallelScan<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::execute() [with FunctorType=NeighborCSR<t_neigh_mem_space>, Traits=<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Kokkos_Parallel.hpp(435)>: here
            instantiation of "void Kokkos::parallel_scan(const ExecutionPolicy &, const FunctorType &, const std::string &, Kokkos::Impl::enable_if<Kokkos::is_execution_policy<ExecutionPolicy>::value, void>::type *) [with ExecutionPolicy=Kokkos::RangePolicy<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>, FunctorType=NeighborCSR<t_neigh_mem_space>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/kokkos/core/src/Kokkos_Parallel.hpp(490)>: here
            instantiation of "void Kokkos::parallel_scan(const std::string &, const ExecutionPolicy &, const FunctorType &) [with ExecutionPolicy=Kokkos::RangePolicy<NeighborCSR<t_neigh_mem_space>::TagCreateOffsets, Kokkos::IndexType<int>>, FunctorType=NeighborCSR<t_neigh_mem_space>]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/src//../src/neighbor_types/neighbor_csr.h(409)>: here
            instantiation of "void NeighborCSR<MemorySpace>::create_neigh_list(System *, Binning *, __nv_bool, __nv_bool) [with MemorySpace=t_neigh_mem_space]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/src//../src/neighbor_types/neighbor_csr.h(170)>: here
            instantiation of "NeighborCSR<MemorySpace>::NeighborCSR() [with MemorySpace=t_neigh_mem_space]"
<https://jenkins-srn.sandia.gov:8443/job/ExaMiniMD_CUDA_Winstone/ws/src//../src/neighbor_types/neighbor_csr.h(48)>: here
```

**Comment by stanmoore1** [comment]
Also getting compile errors like:

```
kokkos/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp(836): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
```

**Comment by stanmoore1** [comment]
ExaMiniMD regression tests use:

```
module load sems-gcc/4.8.4
module load kokkos-cuda/8.0.44
module load sems-openmpi/1.8.7
module load kokkos-openmpi/1.8.7/cuda
```

**Comment by crtrott** [comment]
It did pass with CUDA 10 -G flag. 

```
nohup: ignoring input
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git'
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? patch_teamvectorrange

Repository Status:  b43d8a5e44d73c55a62cfa3ad5dc0747f1089db4 Make CUDA scratch resize not realloc but delete and allocate


Going to test compilers:  cuda/10.0
Testing compiler cuda/10.0
  Starting job cuda-10.0-Cuda_Serial-release
  PASSED cuda-10.0-Cuda_Serial-release
  Starting job cuda-10.0-Cuda_OpenMP-release
  PASSED cuda-10.0-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
cuda-10.0-Cuda_OpenMP-release build_time=502 run_time=352
cuda-10.0-Cuda_Serial-release build_time=497 run_time=352
```

**Comment by stanmoore1** [comment]
>It did pass with CUDA 10 -G flag.

Great!!

**Comment by stanmoore1** [comment]
@crtrott this also breaks the standard LAMMPS `SNAP` examples. They fail with:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalInstruction): an illegal instruction was encountered /ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
```

**Comment by stanmoore1** [comment]
@crtrott Here is a backtrace from LAMMPS SNAP using `cuda-memcheck` with `-G`:

```
========= Illegal Instruction
=========     at 0x000000f0 in __cuda_sm70_shflsync_down_p
=========     by thread (0,30,0) in block (23,0,0)
=========     Device Frame:/home/projects/ppc64le-pwr9-nvidia/cuda/9.2.88/include/sm_30_intrinsics.hpp:208:_INTERNAL_51_tmpxft_0001ca76_00000000_6_pair_snap_kokkos_cpp1_ii_0ebca60e::__shfl_down_sync(unsigned int, int, unsigned int, int) (_INTERNAL_51_tmpxft_0001ca76_00000000_6_pair_snap_kokkos_cpp1_ii_0ebca60e::__shfl_down_sync(unsigned int, int, unsigned int, int) : 0x260)
=========     Device Frame:/home/projects/ppc64le-pwr9-nvidia/cuda/9.2.88/include/sm_30_intrinsics.hpp:376:_INTERNAL_51_tmpxft_0001ca76_00000000_6_pair_snap_kokkos_cpp1_ii_0ebca60e::__shfl_down_sync(unsigned int, __int64, unsigned int, int) (_INTERNAL_51_tmpxft_0001ca76_00000000_6_pair_snap_kokkos_cpp1_ii_0ebca60e::__shfl_down_sync(unsigned int, __int64, unsigned int, int) : 0x2c0)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp:128:void Kokkos::Impl::cuda_shfl_down<double>(double&, Kokkos::Impl::cuda_shfl_down<double> const &, int, std::enable_if<__operator_==__(unsigned long=8, __sizeof__()), int>::type, unsigned int) (void Kokkos::Impl::cuda_shfl_down<double>(double&, Kokkos::Impl::cuda_shfl_down<double> const &, int, std::enable_if<__operator_==__(unsigned long=8, __sizeof__()), int>::type, unsigned int) : 0x350)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Team.hpp:297:_ZN6Kokkos4Impl14CudaTeamMember13vector_reduceINS_3SumIdNS_9HostSpaceEEEEENSt9enable_ifIXsr6Kokkos10is_reducerIT_EE5valueEvE4typeERKS7_ (_ZN6Kokkos4Impl14CudaTeamMember13vector_reduceINS_3SumIdNS_9HostSpaceEEEEENSt9enable_ifIXsr6Kokkos10is_reducerIT_EE5valueEvE4typeERKS7_ : 0x7a0)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Team.hpp:820:_ZN6Kokkos15parallel_reduceIiZZN9LAMMPS_NS9SNAKokkosINS_4CudaEE10compute_biERKNS_4Impl14CudaTeamMemberEENKUlRKiE_clESA_EUliRdE0_dEENSt9enable_ifIXntsr6Kokkos10is_reducerIT1_EE5valueEvE4typeERKNS5_33ThreadVectorRangeBoundariesStructIT_S6_EERKT0_RSF_ (_ZN6Kokkos15parallel_reduceIiZZN9LAMMPS_NS9SNAKokkosINS_4CudaEE10compute_biERKNS_4Impl14CudaTeamMemberEENKUlRKiE_clESA_EUliRdE0_dEENSt9enable_ifIXntsr6Kokkos10is_reducerIT1_EE5valueEvE4typeERKNS5_33ThreadVectorRangeBoundariesStructIT_S6_EERKT0_RSF_ : 0x800)
=========     Device Frame:/home/stamoor/lammps_master/src/Obj_kokkos_cuda_mpi_db/../sna_kokkos_impl.h:363:_ZZN9LAMMPS_NS9SNAKokkosIN6Kokkos4CudaEE10compute_biERKNS1_4Impl14CudaTeamMemberEENKUlRKiE_clES9_ (_ZZN9LAMMPS_NS9SNAKokkosIN6Kokkos4CudaEE10compute_biERKNS1_4Impl14CudaTeamMemberEENKUlRKiE_clES9_ : 0x3550)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Team.hpp:644:_ZN6Kokkos12parallel_forIiZN9LAMMPS_NS9SNAKokkosINS_4CudaEE10compute_biERKNS_4Impl14CudaTeamMemberEEUlRKiE_EEvRKNS5_31TeamThreadRangeBoundariesStructIT_S6_EERKT0_ (_ZN6Kokkos12parallel_forIiZN9LAMMPS_NS9SNAKokkosINS_4CudaEE10compute_biERKNS_4Impl14CudaTeamMemberEEUlRKiE_EEvRKNS5_31TeamThreadRangeBoundariesStructIT_S6_EERKT0_ : 0x5b0)
=========     Device Frame:/home/stamoor/lammps_master/src/Obj_kokkos_cuda_mpi_db/../sna_kokkos_impl.h:330:LAMMPS_NS::SNAKokkos<Kokkos::Cuda(Kokkos::Impl::CudaTeamMember const &)>::compute_bi (LAMMPS_NS::SNAKokkos<Kokkos::Cuda(Kokkos::Impl::CudaTeamMember const &)>::compute_bi : 0x6b0)
=========     Device Frame:/home/stamoor/lammps_master/src/Obj_kokkos_cuda_mpi_db/../pair_snap_kokkos_impl.h:563:_ZNK9LAMMPS_NS14PairSNAPKokkosIN6Kokkos4CudaEEclILi2ELi1EEEvNS_11TagPairSNAPIXT_EXT0_EEERKNS1_10TeamPolicyIJS2_S6_EE11member_typeER10s_EV_FLOAT (_ZNK9LAMMPS_NS14PairSNAPKokkosIN6Kokkos4CudaEEclILi2ELi1EEEvNS_11TagPairSNAPIXT_EXT0_EEERKNS1_10TeamPolicyIJS2_S6_EE11member_typeER10s_EV_FLOAT : 0x5f20)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp:1289:_ZNK6Kokkos4Impl14ParallelReduceIN9LAMMPS_NS14PairSNAPKokkosINS_4CudaEEENS_10TeamPolicyIJS4_NS2_11TagPairSNAPILi2ELi1EEEEEENS_11InvalidTypeES4_E9exec_teamIS8_EENSt9enable_ifIXntsr3std7is_sameIT_vEE5valueEvE4typeERKNS0_14CudaTeamMemberER10s_EV_FLOAT (_ZNK6Kokkos4Impl14ParallelReduceIN9LAMMPS_NS14PairSNAPKokkosINS_4CudaEEENS_10TeamPolicyIJS4_NS2_11TagPairSNAPILi2ELi1EEEEEENS_11InvalidTypeES4_E9exec_teamIS8_EENSt9enable_ifIXntsr3std7is_sameIT_vEE5valueEvE4typeERKNS0_14CudaTeamMemberER10s_EV_FLOAT : 0x460)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp:1377:_ZNK6Kokkos4Impl14ParallelReduceIN9LAMMPS_NS14PairSNAPKokkosINS_4CudaEEENS_10TeamPolicyIJS4_NS2_11TagPairSNAPILi2ELi1EEEEEENS_11InvalidTypeES4_E3runERKdRKi (_ZNK6Kokkos4Impl14ParallelReduceIN9LAMMPS_NS14PairSNAPKokkosINS_4CudaEEENS_10TeamPolicyIJS4_NS2_11TagPairSNAPILi2ELi1EEEEEENS_11InvalidTypeES4_E3runERKdRKi : 0x1390)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp:1317:_ZNK6Kokkos4Impl14ParallelReduceIN9LAMMPS_NS14PairSNAPKokkosINS_4CudaEEENS_10TeamPolicyIJS4_NS2_11TagPairSNAPILi2ELi1EEEEEENS_11InvalidTypeES4_EclEv (_ZNK6Kokkos4Impl14ParallelReduceIN9LAMMPS_NS14PairSNAPKokkosINS_4CudaEEENS_10TeamPolicyIJS4_NS2_11TagPairSNAPILi2ELi1EEEEEENS_11InvalidTypeES4_EclEv : 0x1f90)
=========     Device Frame:/ascldap/users/stamoor/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp:163:void Kokkos::Impl::cuda_parallel_launch_constant_memory<Kokkos::Impl::ParallelReduce<LAMMPS_NS::PairSNAPKokkos<Kokkos::Cuda>, Kokkos::TeamPolicy<>, Kokkos::InvalidType, Kokkos::Cuda>>(void) (void Kokkos::Impl::cuda_parallel_launch_constant_memory<Kokkos::Impl::ParallelReduce<LAMMPS_NS::PairSNAPKokkos<Kokkos::Cuda>, Kokkos::TeamPolicy<>, Kokkos::InvalidType, Kokkos::Cuda>>(void) : 0x3c0)
```

**Comment by crtrott** [comment]
Can you try the LAMMPS SNAP thing with CUDA 10? The -G didn't work for me either with CUDA but for reasons clearly not related to what we were doing.

**Comment by stanmoore1** [comment]
The CUDA 8 compile issue is fixed, and the standard LAMMPS SNAP examples run.

**Pull request merged**
