### PR TITLE
Fixes to enable target library, issue #1354

### PR DESCRIPTION
**Pull request by hcedwar**
For issue #1354 
Testing in progress

### CODE REVIEW

**Comment by ibaned** [comment]
@hcedwar I see comments related to Volta. Does this improve the task dag situation on Volta?

I can start a spot check if you'd like.

**Comment by hcedwar** [comment]
Spot check is running on Kokkos-dev

Sent from my iPad

On Feb 7, 2018, at 10:15 AM, Dan Ibanez <notifications@github.com<mailto:notifications@github.com>> wrote:


@hcedwar<https://github.com/hcedwar> I see comments related to Volta. Does this improve the task dag situation on Volta?

I can start a spot check if you'd like.

**Comment by hcedwar** [comment]
nohup: ignoring input
Running on machine: sems

Repository Status:  96069a1cd982239118d08ecb4ffa1984774b8a30 Fixes to enable target library, issue #1354


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-5.3.0-OpenMP-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED intel-17.0.1-OpenMP-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=184 run_time=88
clang-3.9.0-Pthread_Serial-release build_time=201 run_time=224
cuda-8.0.44-Cuda_OpenMP-release build_time=492 run_time=573
gcc-5.3.0-OpenMP-hwloc-release build_time=260 run_time=112
gcc-5.3.0-OpenMP-release build_time=258 run_time=111
gcc-6.1.0-Serial-hwloc-release build_time=213 run_time=137
gcc-6.1.0-Serial-release build_time=202 run_time=136
intel-17.0.1-OpenMP-hwloc-release build_time=581 run_time=163
intel-17.0.1-OpenMP-release build_time=575 run_time=167

**Comment by hcedwar** [comment]
The task dag thread teams are currently assumed to be warp synchronous.  This assumption no longer holds on Volta so the task dag will need #if Volta code sections, as soon as we can build & test on a Volta system.

**Pull request merged**
