### PR TITLE
More travis improvements

### LINKED ISSUE #2395: Update Travis CI testing
- inject -O3 -Werror again?
  - Yes.
- build with the legacy build system? (one build maybe)
  - One build would be good: note use the generate_makefile_bash inside the scripts testing directory
- enable OPENMP for Device Parallel?
  - Yeah for a couple builds
- test more or less compilers?
  - I think this is fine for now
- run travis only for the develop and master branch? (Will only work for branches with the new ci file)
  - were you running it for anything else?
- test different CMake build types?
  - probably should have one OpenMP debug build
- turn one build in a canary build? (as a sniff test before the other builds)
  - yeah that sounds like a good idea: like some GCC / OpenMP / Release build

Do you want to first merge this and then do all the other things?

_Originally posted by @crtrott in https://github.com/kokkos/kokkos/pull/2392#issuecomment-536030644_

### PR DESCRIPTION
**Pull request by junghans**
Left over from https://github.com/kokkos/kokkos/pull/2392#issuecomment-536030644

Fix #2395

### CODE REVIEW

**Comment by junghans** [comment]
@dalg24 btw, can you enable the "auto cancelation" feature in travis? (see https://blog.travis-ci.com/2017-09-21-default-auto-cancellation).

**Comment by junghans** [comment]
Now Travis actually found a real issue:
```
../../libkokkos.a(Kokkos_ThreadsExec_base.cpp.o): In function `Kokkos::Impl::ThreadsExec::spawn()':
Kokkos_ThreadsExec_base.cpp:../../libkokkos.a((Kokkos_ThreadsExec_base.cpp.o.text+0x159)): In function `Kokkos::Impl::ThreadsExec::spawn()':
Kokkos_ThreadsExec_base.cpp:(.text+0x159): undefined reference to `pthread_create'
: undefined reference collect2: error: ld returned 1 exit status
to `pthread_create'
collect2: error: ld returned 1 exit status
core/unit_test/CMakeFiles/KokkosCore_UnitTest_DefaultInit_4.dir/build.make:101: recipe for target 'core/unit_test/KokkosCore_UnitTest_DefaultInit_4' failed
make[2]: *** [core/unit_test/KokkosCore_UnitTest_DefaultInit_4] Error 1
```

**Comment by masterleinad** [comment]
> Now Travis actually found a real issue:
[...]

That should be addressed by #2394. So testing more configurations has already proven useful. :slightly_smiling_face:

**Comment by junghans** [comment]
The `UnitTest_OpenMP` times out after 20min on the non-release-non-debug build not 100% sure why. Debug and Release builds are fine.

**Comment by crtrott** [comment]
Does travis set OpenMP affinities? If you don't set them this might explain problems with time outs.

**Comment by junghans** [comment]
> Does travis set OpenMP affinities? If you don't set them this might explain problems with time outs.

There is:
```
  - export OMP_NUM_THREADS=2
  - export OMP_PLACES=threads
  - export OMP_PROC_BIND=spread
```
set.

**Comment by junghans** [comment]
Plus I worked around the time-out issue by adding `-O2` to CXXFLAGS.

**Comment by junghans** [comment]
@dalg24 @crtrott, except for adding the legacy build this PR will fix #2395. You might want to down select some builds down the road (or now). We will need to reenable the pthread builds once #2405 got merged.

**Comment by junghans** [comment]
It will comment on future PRs, but for this PR it is here: https://codecov.io/gh/kokkos/kokkos/pull/2402/tree

**Pull request merged**
