### PR TITLE
Remove CudaFunctorAdapter

### PR DESCRIPTION
**Pull request by masterleinad**
I came across `CudaFunctorAdapter` multiple times and looking at the reduction interface some more today, I don't think we need it anymore. Originally, we suspected that it could be removed already for `CUDA 8` but that turned out to be wrong.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Review by dalg24 — APPROVED** [review]
Thanks for cleaning that up

**Comment by crtrott** [comment]
Did we test this with CUDA 9 and lambdas enabled?

**Comment by masterleinad** [comment]
> Did we test this with CUDA 9 and lambdas enabled?

Yes, we have https://github.com/kokkos/kokkos/blob/5e8eb22dc81dee995dec8dbe5fd395baf5a8b6ee/.jenkins#L275-L303 in the CI.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
