### PR TITLE
unit_test/CMakeLists.txt: update tools regex when lambda disabled

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
This PR addresses failures in some nightly tests like
https://jenkins-son.sandia.gov/job/Kokkos_apollo/1230/consoleFull

**Comment by ndellingwood** [comment]
Previous PR #3047 addressed some compilation issues with Cuda builds when lambdas were disabled, this PR updates the regex expression used to determine passing tests when lambdas are disabled.

**Comment by ndellingwood** [comment]
For reference, without this type of change testing without lambdas enabled results in messages like:

```bash
05:55:19 11/38 Test #11: KokkosCore_ProfilingTestLibraryLoad ......***Failed  Required regular expression not found.Regex=[kokkosp_init_library::kokkosp_allocate_data:[HC][ou][sd][ta][a-zA-Z]*:source:0x[0-9a-f]*:40::kokkosp_begin_parallel_for:Kokkos::View::initialization:0:0::kokkosp_end_parallel_for:0::kokkosp_allocate_data:[HC][ou][sd][ta][a-zA-Z]*:destination:0x[0-9a-f]*:40::kokkosp_begin_parallel_for:Kokkos::View::initialization:0:0::kokkosp_end_parallel_for:0::kokkosp_begin_deep_copy:[HC][ou][sd][ta][a-zA-Z]*:destination:0x[0-9a-f]*:[HC][ou][sd][ta][a-zA-Z]*:source:0x[0-9a-f]*:40::kokkosp_end_deep_copy::kokkosp_begin_parallel_for:parallel_for:[0-9]*:0::kokkosp_end_parallel_for:0::kokkosp_begin_parallel_reduce:parallel_reduce:0:1::kokkosp_end_parallel_reduce:1::kokkosp_begin_parallel_scan:parallel_scan:[0-9]*:2::kokkosp_end_parallel_scan:2::kokkosp_push_profile_region:push_region::kokkosp_pop_profile_region::kokkosp_create_profile_section:created_section:3::kokkosp_start_profile_section:3::kokkosp_stop_profile_section:3::kokkosp_destroy_profile_section:3::kokkosp_profile_event:profiling_event::kokkosp_deallocate_data:[HC][ou][sd][ta][a-zA-Z]*:destination:0x[0-9a-f]*:40::kokkosp_deallocate_data:[HC][ou][sd][ta][a-zA-Z]*:source:0x[0-9a-f]*:40::kokkosp_finalize_library::
```

Reproducer instructions (kokkos-dev-2):
```bash
module load sems-env sems-cmake/3.12.2 kokkos-env sems-cuda/9.2 sems-gcc/5.3.0

export KOKKOS_PATH=$HOME/kokkos

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=SNB,Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="11" --ldflags="" --with-cuda --kokkos-path=$KOKKOS_PATH --no-examples
```

**Comment by masterleinad** [comment]
Hmm... This slowly becomes really cumbersome. What about just avoiding `KOKKOS_LAMBDA` in the test case to avoid the necessity to restrict it at all instead?

**Comment by DavidPoliakoff** [comment]
Or disabling the test at a CMake level if we don't support lambdas...

Actually, if we enable Serial in our CUDA builds, just using regular captures ([=]) and specifying that it's a Serial RangePolicy should work.

**Comment by ndellingwood** [comment]
@DavidPoliakoff @masterleinad I can replace the lambda with functors, unless the intent of the test is to hit the lambda code paths. I'll close this, thanks for quick feedback.

**Pull request closed without merging**
