### PR TITLE
Couple more icpc -Werror fixes

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
These showed up in nightly intel/2021.3 icpc testing; did not occur with intel/19.0.5 nor intel/2023.2.0 using icpc

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
> These showed up in nightly intel/2021.3 icpc testing; did not occur with intel/19.0.5 nor intel/2023.2.0 using icpc

I'm glad when we can stop supporting Intel classic compilers.

**Review by ldh4 — APPROVED** [review]

**Review by aprokop — APPROVED** [review]

**Comment by ndellingwood** [comment]
* Cuda CI jobs are failing but unrelated to changes in the PR: `what():  cudaGetDeviceCount(&count) error( cudaErrorNoDevice): no CUDA-capable device is detected`
* Sycl CI jobs failed but unrelated to changes in this PR, some sort of connectivity issues  `HTTP request sent, awaiting response...  No data received. Giving up.`
* OpenACC CI fail also due to connectivity issues `ERROR: Error cloning remote repo 'origin'`

The changes in this PR would not impact those jobs in any case, @dalg24 @crtrott is it okay to merge this?

**Review by dalg24 — APPROVED** [review]
Make sure to say in your description that this is a fixup for #7095

**Comment by ndellingwood** [comment]
@dalg24 thanks, I updated the description to ping that PR and why these changes didn't show up when I issued #7095

**Pull request merged**
