### PR TITLE
[skip ci] add option to disable desul

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Will use this option to disable desul atomics for testing primarily with kokkos-kernels nightlies until the full shift to use of desul atomics is complete

**Review by masterleinad — APPROVED** [review]
Looks reasonable to me.

**Comment by crtrott** [comment]
wait is KokkosKernels using our generate_makefile.bash?

**Review by e10harvey — APPROVED** [review]

**Comment by ndellingwood** [comment]
@crtrott most kokkos-kernels testing is calling Kokkos' cmake directly, but I think there is some usage of the generate_makefile on machines that require building on the head node before launching ctest on the compute node (I'll double check). In that case, I can replace the generate_makefile calls with direct cmake usage

**Comment by crtrott** [comment]
@ndellingwood checkout #4140 that should fix the underlying issue hopefully. Can you test that?

**Comment by crtrott** [comment]
not sure I want this for now.

**Pull request closed without merging**
