### PR TITLE
Deprecate Kokkos::Profiling::ProfilingSection::{getName,getSectionID}

### PR DESCRIPTION
**Pull request by dalg24**
Rational:  These accessors are pointless.  There is nothing really useful that can be done with them.

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
I don't see much of a problem with storing the name. It might be useful to be able to retrieve it.

**Comment by dalg24** [comment]
> I don't see much of a problem with storing the name. It might be useful to be able to retrieve it.

Can you think of one example where that is useful?

**Comment by masterleinad** [comment]
> Can you think of one example where that is useful?

Something like creating a section name in a complicated way and you want to query the name of the section you are going to start/stop to do something with it (like printing). Of course, you could just store the section name somewhere else and I would probably have agreed with not adding it to the interface in the first place. I just don't know if we have a good enough reason to deprecated/remove it now.

**Comment by dalg24** [comment]
> > Can you think of one example where that is useful?
> 
> Something like creating a section name in a complicated way and you want to query the name of the section you are going to start/stop to do something with it (like printing). Of course, you could just store the section name somewhere else and I would probably have agreed with not adding it to the interface in the first place. I just don't know if we have a good enough reason to deprecated/remove it now.

Not convincing IMO.  We will see what others think.

**Review by DavidPoliakoff — APPROVED** [review]
Looks good to me

**Comment by DavidPoliakoff** [comment]
Retest this please

**Review by crtrott — APPROVED** [review]

**Pull request merged**
