### PR TITLE
Policy performance tests: Added test and sample scripts

### PR DESCRIPTION
**Pull request by ndellingwood**
This commit address Github issue #737
RangePolicy and TeamPolicy tests with nested parallelism added for
benchmarking performance - e.g. compare master vs develop prior

TODO The parallel_scan test fails to compile with Cuda 7.5; this is
either a bug in Kokkos or shortcoming of Cuda 7.5's lambda support.
Depending on which will determine resolution, if necessary.

### CODE REVIEW

**Comment by hcedwar** [comment]
Is this test included or not included in the nightly testing?

**Comment by ndellingwood** [comment]
Not included in the nightlies, followed same pattern of the bytes_and_flops benchmark. To compile and run just use the Makefile within the directory - pass the appropriate KOKKOS_DEVICES= etc on the command line to build for Cuda, OpenMP...
Then run the executable either by passing the 10 command-line arguments (./policy_performance will output what these should be) or using/modifying one of the scripts.

**Comment by ndellingwood** [comment]
On the host-side I added -Wall and -Werror flags to help make sure I was keeping things clean while compiling.

**Comment by ndellingwood** [comment]
@hcedwar I will revise the code and testing based on what should be provided via command line / script v.s. always run within the main.cpp source. As of now it is ready for maximum flexibility, i.e. user provides all arguments.

**Comment by ndellingwood** [comment]
@hcedwar I should have mentioned what I tested when I issued the PR: build and tested with cuda 8, intel 16, clang 3.9, gcc 4.9.3 and 5.3.0. 

cuda 7.5 will not compile the parallel_scan test (with RangePolicy) using the lambda, see issue #913 for isolated reproducer. It'll only take a moment to rewrite it using a functor, but wanted to wait to see if this was a Cuda vs Kokkos issue (I'd rather leave the lambdas if possible).

**Comment by hcedwar** [comment]
Need functor for parallel_scan test, see closing comment for #913

**Comment by ndellingwood** [comment]
@hcedwar Just pushed changes and squashed commits to a single commit.

**Pull request merged**
