### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by gsjaardema**

### CODE REVIEW

**Comment by crtrott** [comment]
I don't think we want to do this this way. I believe we decided that merge commits from develop to master are not going to be back merged into develop.

**Comment by gsjaardema** [comment]
Sorry, patch was supposed to be on develop only; I wasn't intending to merge from master back into develop.

**Comment by gsjaardema** [comment]
I can close this pull request and redo it correctly if that would help...

**Comment by hcedwar** [comment]
This pull request contains contains the 'master_history.txt' file which only appears on the master branch, never the develop branch.  Please apply just the CMake file change to the develop branch and issue a pull request.

**Pull request closed without merging**
