### PR TITLE
Rc 3.2.1 cherrypicks

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Addressing issue #3334

**Comment by ndellingwood** [comment]
@crtrott @dalg24 some PR commits corresponding to changes that should skip the unit test changes could not be cherry-picked directly due to intermix of fixes with unit test updates. For these cases I indicated this in the commit messages by beginning with "Manual changes ..." and indicated the files changed from the corresponding PR and associated commit of that PR. If this is satisfactory, I think the final step is to add the CHANGELOG the a PR with this branch can be prepped for Trilinos.

**Comment by masterleinad** [comment]
Apparently, you need to fix the formatting. :slightly_smiling_face:

**Comment by ndellingwood** [comment]
> Apparently, you need to fix the formatting

Darn it, just applied and pushed up the change.

**Comment by ndellingwood** [comment]
Also cherry-picked #3407

**Comment by ndellingwood** [comment]
OMPTARGET-CLANG build failed with `ERROR: Error fetching remote repo 'origin'`, retesting

**Comment by ndellingwood** [comment]
retest this please

**Comment by ndellingwood** [comment]
@dalg24 @crtrott testing passed, ready for merge?

**Comment by dalg24** [comment]
Changes from #3384 are missing

**Comment by dalg24** [comment]
Everything else was there.

**Comment by janciesko** [comment]
Confirming @dalg24 finding, let's PR #3384 into this branch?

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
