### PR TITLE
Increase support to detect local MPI ranks

### PR DESCRIPTION
**Pull request by dalg24**
Following up on https://github.com/kokkos/kokkos/pull/5570#issuecomment-1282893923

For now only proposing support for the Process Management Interface (PMI) since I could find multiple sources mentioning it.  I am not sure yet whether to also add `MPT_LRANK`.  Anyone knows more about this one?

### CODE REVIEW

**Comment by stanmoore1** [comment]
@dalg24 I can't find anything about `MPT_LRANK` either, so unless someone complains I'd say leave it out for now.

**Review by masterleinad — APPROVED** [review]

**Review by PhilMiller — APPROVED** [review]
Totally aside from this PR, I notice that the code doesn't make any attempt to handle `local_rank_str` not actually parsing as an integer

**Comment by dalg24** [comment]
> Totally aside from this PR, I notice that the code doesn't make any attempt to handle `local_rank_str` not actually parsing as an integer

Yes we only check if any of the environment variables is set and later do
https://github.com/kokkos/kokkos/blob/63399759a7dd38bff471ef2df58c423a46ce4cdd/core/src/impl/Kokkos_Core.cpp#L458
which would throw an exception if the conversion was to fail.  At the moment, I am not convinced we should explicitly handle the case when the conversion cannot actually be performed.  I think the exception from `std::stoi` is good enough.

**Comment by PhilMiller** [comment]
I see now that `std::stoi` throws an exception if it can't parse the input. That's more than sufficient, I think.

**Pull request merged**
