### PR TITLE
Add gcc toolchain to compiler and linker options if compiler is clang (Issue #2364)

### PR DESCRIPTION
**Pull request by jeffmiles63**
Issue #2364

### CODE REVIEW

**Comment by jeffmiles63** [comment]
This is really a matter of usability.  Kokkos version 2.9 and earlier versions set this automatically with the Makefile.kokkos.  If we say that the user must set this externally, then we are adding more work where it didn't exist previously.

**Comment by dalg24** [comment]
> This is really a matter of usability. Kokkos version 2.9 and earlier versions set this automatically with the Makefile.kokkos. If we say that the user must set this externally, then we are adding more work where it didn't exist previously.

Fair enough.

Can you confirm this fixed the issues we were seeing on the nightly builds?

We do not currently have a build that expose this issue on Travis nor Jenkins.  Is that something we want to change?  How would we go about testing for this?

**Comment by jeffmiles63** [comment]
I think that in the general cases, the only concern is that this doesn't break existing builds/envs.  

Because the larger script testing is being done manually, it is difficult to verify this one change by itself. Unfortunately, the Kokkos/Nightly jobs pull from develop and git doesn't have a mechanism to combine a bunch of branches to test a PR, so I don't know how to response to "Can you confirm this fixed the issues we were seeing on the nightly builds?", other than it was verified using jeffmiles63/kokkos.git -- branch test-result-apollo which contains all of the change for PRs #2386, #2384, #2380, and this one (#2379)

**Comment by dalg24** [comment]
I am mildly against the changes proposed here.  I feel like this logic belongs more to a toolchain file.  You could provide one for Clang and configure with `-DCMAKE_TOOLCHAIN_FILE=/path/to/file` when necessary.  I find the inconvenience if you built libc++ along with Clang and Kokkos detect some old ass GCC on your system which somehow makes the configuration or build fail to be potentially worse.

**Comment by jeffmiles63** [comment]
looks like this can be set with the CMAKE_CXX_FLAGS, so I am moving the gcc-toolchain logic to the cm_generate_makefile script

**Pull request closed without merging**
