### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kushal34712**

### CODE REVIEW

**Review by fnrizzi — CHANGES_REQUESTED** [review]
wrong branch

**Comment by PhilMiller** [comment]
Bluntly, I think the submitter is not actually trying to make a substantive contribution as such. Have a look at their Github history. I think they're trying to create the appearance of a broad portfolio of open source contributions, without meaningful engagement with any. They've forked 49 repositories of projects in a dozen different languages this month.

The change here is maybe marginally useful to have the `LICENSE` linked, but the others are not improvements. I don't think this PR is worth spending further time on, and the submitter should probably be treated with skepticism if they're not putting up something of substance.

**Comment by fnrizzi** [comment]
> Bluntly, I think the submitter is not actually trying to make a substantive contribution as such. Have a look at their Github history. I think they're trying to create the appearance of a broad portfolio of open source contributions, without meaningful engagement with any. They've forked 49 repositories of projects in a dozen different languages this month.
> 
> The change here is maybe marginally useful to have the `LICENSE` linked, but the others are not improvements. I don't think this PR is worth spending further time on, and the submitter should probably be treated with skepticism if they're not putting up something of substance.

i had the same skeptic thought TBH

**Comment by aprokop** [comment]
@PhilMiller Likely part of the DigitalOcean's Hacktoberfest, an infamous DDOS. Suggest closing both PRs with `invalid` or `spam`.

**Pull request closed without merging**
