### PR TITLE
Guard KOKKOS_ALL_COMPILE_OPTIONS if Cuda is not enabled

### PR DESCRIPTION
**Pull request by finkandreas**
I'm building trilinos, not Kokkos standalone, and I'm building with a clang compiler, where I enable OpenMP as parallel hostspace, and no device space (i.e. Cuda disabled).

Variable `KOKKOS_ALL_COMPILE_OPTIONS` is referenced in file `cmake/KokkosTrilinosConfig.cmake.in` (when building with Trilinos, this triggers a bug)
The installed `KokkosConfig.cmake` will contain the lines:
```
  set_target_properties(Kokkos::kokkos PROPERTIES
    INTERFACE_LINK_LIBRARIES "kokkosalgorithms;kokkoscontainers;kokkoscore;-fopenmp"
    INTERFACE_COMPILE_FEATURES "cxx_std_14"
    INTERFACE_COMPILE_OPTIONS "$<$<COMPILE_LANGUAGE:CXX>:-fopenmp;-x;cuda>"
    INTERFACE_INCLUDE_DIRECTORIES "${KOKKOS_IMPORT_PREFIX}/include"
  )
```

When I want to use trilinos in another project and link to trilinos, which will pull in Kokkos::Kokkos, which adds the compile flags `-x cuda`. Guarding `KOKKOS_ALL_COMPILE_OPTIONS` works fine for me.

### CODE REVIEW

**Comment by dalg24** [comment]
Alternative might be to guard
https://github.com/kokkos/kokkos/blob/593597c371eeb3485d01d1f8b34f5491fa80f9ea/cmake/kokkos_arch.cmake#L119-L157

The flag is added here https://github.com/kokkos/kokkos/blob/593597c371eeb3485d01d1f8b34f5491fa80f9ea/cmake/kokkos_arch.cmake#L140

Your solution looks fine to me but I want feedback from @jjwilke.
NOTE: Jenkins CI does not need to run for that PR.

**Review by masterleinad — APPROVED** [review]
This only affects Trilinos so guarding in the Trilinos-only part looks sensible to me and mirrors what we do for a regular build in https://github.com/kokkos/kokkos/blob/03ded4e816da5927b946065b005ebfdf38e5a438/cmake/kokkos_tribits.cmake#L269-L282.

**Comment by finkandreas** [comment]
But the problematic file is `cmake/KokkosTrilinosConfig.cmake.in`. This one, is a template and will ultimately install the file `$INSTALLDIR/lib/cmake/kokkos/KokkosConfig.cmake`. In this file the variable `KOKKOS_ALL_COMPILE_OPTIONS` is referenced. The compilation of trilinos works fine, but the installed cmake file is wrong.

**Comment by crtrott** [comment]
This bug is in Trilinos right now? I.e. its in the release?

**Comment by finkandreas** [comment]
I tested with Trilinos `master` branch, but looking at the source code of 13.0 release, it seems to be the same (did not try to compile it though)

**Comment by jjwilke** [comment]
This looks fine. This is working for nvcc because KOKKOS_CUDA_OPTIONS is empty. There is one spot with clang where we add a flag to KOKKOS_CUDA_OPTIONS even if CUDA isn't enabled.  This is why we haven't seen the error before (i.e. no one builds downstream Trilinos projects with clang-cuda).

I'm not sure if we care about consistent behavior, i.e. should KOKKOS_CUDA_OPTIONS always be empty if CUDA is not enabled? Or should KOKKOS_CUDA_OPTIONS contain all the expected CUDA options even if CUDA is not enabled.  Super picky, but nice to be clean and consistent.

**Comment by crtrott** [comment]
OK to test.

**Comment by dalg24** [comment]
Retest this please

**Pull request merged**
