### PR TITLE
Replace cancel-builds-on-update by concurrency feature in the GitHub CI

### PR DESCRIPTION
**Pull request by masterleinad**
it appears that there is now a native way to cancel builds on push in pull requests, see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]
Thank you

**Comment by dalg24** [comment]
@junghans please review

**Comment by fnrizzi** [comment]
If I understand correctly, this `cancel-in-progress: ${{github.event_name == 'pull_request'}}` means that canceling will trigger *only for PRs* right? 
But in my own branch, if I do multiple pushes, canceling won't happen, so all the jobs will be queued anyway and I have to manually cancel runs. Right>

**Comment by masterleinad** [comment]
> If I understand correctly, this `cancel-in-progress: ${{github.event_name == 'pull_request'}}` means that canceling will trigger _only for PRs_ right?

Yes, the intent is that we don't abort builds when merging.

**Review by junghans — APPROVED** [review]
I did exactly the same here: https://github.com/votca/votca/pull/883

**Pull request merged**
