### PR TITLE
Add Hopper support

### PR DESCRIPTION
**Pull request by crtrott**
Addresses issue #5524

### CODE REVIEW

**Review by dalg24 — CHANGES_REQUESTED** [review]
https://github.com/kokkos/kokkos/blob/61d7db55fceac3318c987a291f77b844fd94c165/core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp#L218-L232

**Comment by crtrott** [comment]
Added the shared config, and also the printconfig thing. Confirmed in tuning guide that it also can do 8kB shared memory.

**Review by masterleinad — COMMENTED** [review]
What about `cmake/compile_tests/cuda_compute_capability.cc`?

**Comment by crtrott** [comment]
Fixed: also now actually checked for each use of ARCH_AMPERE and ARCH_VOLTA in our code base and made the appropriate adjustments.

**Review by masterleinad — APPROVED** [review]

**Comment by crtrott** [comment]
Fixed the logic mistake in the half precision thing.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
