### PR TITLE
Revert "#4126 error on initialize after finalize"

### PR DESCRIPTION
**Pull request by crtrott**
Reverts kokkos/kokkos#4145

See discussion in https://github.com/kokkos/kokkos/issues/4294

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Comment by DavidPoliakoff** [comment]
I'm okay with reverting this, but we need to have a conversation about what it means for Kokkos to be properly initialized and finalized. I like the 4145 answer from a practical perspective, I'm worried about supporting all the use cases that could spring from this

**Comment by crtrott** [comment]
Note: I am not saying we allow reinitialization. I just think that it turns out to have been a mistake to use the initializer helper for this.

**Comment by masterleinad** [comment]
I agree with just reverting for the release bit otherwise I agree with @DavidPoliakoff that we need to define how to properly initialize and finalize `Kokkos` (also in the case of just initializing particular types of execution spaces):
- Does the initialization of individual execution space types mean that `Kokkos` is initialized as a whole?
- Should we allow calling `Kokkos::finalize` when only some execution space types (or none) have been initialized?

It seems that removing the check in `Kokkos::finalize()` (and called functions) that `Kokkos` has been initialized would solve (all?) the problem we are currently seeing as well.

**Comment by DavidPoliakoff** [comment]
Sure, but if 4145 _isn't_ right we should talk about what is right. Is the check "for each space enabled in the Kokkos _build_, all must be initialized and finalized?" Or is it "for each space initialized, it must be finalized?" Based on our thinking that

```c++
int main(){
  Kokkos::finalize();
}
```

Should be valid, it seems like it's the second. But now we have to think about every execution space being enabled in a build but not in the run. Also, what does `Kokkos::finalize` mean? I think right now it means "finalize every execution space in the build," but maybe it should mean "finalize any initialized spaces."

For our next pass at 4145, I'd like to start by saying "here's what's legal."

**Comment by crtrott** [comment]
I think there are two different situations: there is the official public situation: and that is Kokkos::initialize was called, and thus Kokkos is initialized. It initializes all the enabled spaces, and Kokkos::finalize ends them all. You can not call Kokkos;:initialize after Kokkos::finalize. The Legion stuff is something which is not fully public interface for integration of Kokkos into external runtimes which requires a collaboration with us. For that purpose Kokkos is initialized when the post space initialization call is done. We enable more selective initialization of Kokkos in that case, but explicitly don't consider it a iron clad backward/forward compatible interface and generally discourage people to ever use it.

**Comment by DavidPoliakoff** [comment]
Sure, but even if it isn't public and vegan/kosher, it's something _we_ need to know how to support, and so even if it's just for our own sake we should codify what these things should be.

**Comment by crtrott** [comment]
I agree I want to write a couple unit tests for our internal logic which codifies what is allowed and what isn't.

**Pull request merged**
