### PR TITLE
algorithms/unit_tests: Skip correctness checks for bhalf

### PR DESCRIPTION
**Pull request by e10harvey**
- Some of the unit tests are still failing in the "3-D histogram"
  with bhalf.

### CODE REVIEW

**Review by crtrott — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
I guess we just keep on bumping the factor until we don't see any test failures for a while without changes that can affect the test result...

**Comment by e10harvey** [comment]
> I guess we just keep on bumping the factor until we don't see any test failures for a while without changes that can affect the test result...

I'm more than happy to calculate these tolerances but I will need some guidance.

**Comment by crtrott** [comment]
OK: lets just NOT check the result of the test for bhalf. I don't think the test can give numerically meaningful results anyway considering the limited accuracy of bhalf. I.e. you can't actually calculate variance etc.

**Review by crtrott — CHANGES_REQUESTED** [review]
Lets just not test the actual output for actual bhalf.

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
