### PR TITLE
CI: icpx is now part of intel container

### PR DESCRIPTION
**Pull request by junghans**
related to https://github.com/kokkos/ci-containers/pull/17

We will need to merge this fix up into devel as well.

/cc @dalg24

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Review by dalg24 — CHANGES_REQUESTED** [review]
No do not target master.  Change it to develop plz

**Comment by junghans** [comment]
Where should it go now?

**Comment by dalg24** [comment]
develop

**Comment by dalg24** [comment]
it needs a rebase

**Comment by junghans** [comment]
> it needs a rebase

Done.

We will need to update it in all other branches using `intel-openapi` as well, like in #4004.

**Review by dalg24 — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by junghans** [comment]
Once merged, we should remove https://github.com/orgs/kokkos/packages/container/ci-containers%2Ffedora/2368320?tag=intel-oneapi

**Comment by dalg24** [comment]
> Once merged, we should remove https://github.com/orgs/kokkos/packages/container/ci-containers%2Ffedora/2368320?tag=intel-oneapi

Can you take of it?

**Pull request merged**
