### PR TITLE
add NVIDIA compiler flags for CPU options

### PR DESCRIPTION
**Pull request by jeffhammond**

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]
LGTM

**Comment by jeffhammond** [comment]
Apparently my patch is bad, because somehow the NV/PGI flags get used when I compile with GCC.

I have no idea how CMake manages to make life so hard.  Somebody else is going to have to figure this out.  I have lost too much of my life to its nonsense already.

```
jehammond@dgx-a100-math:~/PRK/gearbox/kokkos/build$ git clean -dfx ; cmake .. -DKokkos_ENABLE_CUDA=True -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ARCH_AMPERE80=ON -DKokkos_ARCH_ZEN=ON -DNVCC_WRAPPER_DEFAULT_COMPILER=ON -DCMAKE_CXX_COMPILER=$KOKKOS_DIR/kokkos/bin/nvcc_wrapper -DKokkos_ENABLE_SERIAL=ON
warning: failed to remove ./: Invalid argument
Removing ./CMakeFiles
Removing ./CMakeCache.txt
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/jehammond/PRK/gearbox/kokkos/bin/nvcc_wrapper - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Compiler Version: 11.2.152
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  AMPERE80
--  ZEN
-- Found CUDAToolkit: /usr/local/cuda-11.2/include (found version "11.2.152") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found TPLCUDA: TRUE  
-- Found TPLLIBDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jehammond/PRK/gpu-gearbox/kokkos/build
jehammond@dgx-a100-math:~/PRK/gearbox/kokkos/build$ make
[  3%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
g++: error: unrecognized command line option ‘-tp=zen’
make[2]: *** [core/src/CMakeFiles/kokkoscore.dir/build.make:76: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:953: core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by jeffhammond** [comment]
The issue here is that `-DCMAKE_CXX_COMPILER=$KOKKOS_DIR/kokkos/bin/nvcc_wrapper` activates the `NVIDIA` logic in cmake/kokkos_arch.cmake even when the host compiler inside of that wrapper is GCC.

The whole point of build systems is to query compilers and determine their behavior.  CMake needs to figure out what host compiler is wrapped and set the flags properly.

**Comment by masterleinad** [comment]
Is `-tp=...` a `nvcc` option? If it's only for `nvc++`, the compiler identification is either `PGI` or `NVHPC` (https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html).

**Comment by jeffhammond** [comment]
Ah, ok, I'll fix that.

**Comment by jeffhammond** [comment]
The problem of me not being able to use `nvc++` the host compiler behind `nvcc` remains.  How do I get the arch stuff to look at the host compiler inside of the wrapper, rather than the wrapper?

**Comment by masterleinad** [comment]
> The problem of me not being able to use nvc++ the host compiler behind nvcc remains. How do I get the arch stuff to look at the host compiler inside of the wrapper, rather than the wrapper?

We have `KOKKOS_CXX_HOST_COMPILER_ID` for that, see, e.g., https://github.com/kokkos/kokkos/blob/9cf0d5bc02513aece0a79c12d717714cf9345700/cmake/kokkos_enable_devices.cmake#L61-L69

**Comment by jeffhammond** [comment]
How I use that?

```
kokkos/build$ git clean -dfx ; cmake .. -DKokkos_ENABLE_CUDA=True -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ARCH_AMPERE80=ON -DKokkos_ARCH_ZEN=ON -DNVCC_WRAPPER_DEFAULT_COMPILER=ON -DCMAKE_CXX_COMPILER=/home/jehammond/PRK/gpu-gearbox/kokkos/bin/nvcc_wrapper -DKOKKOS_CXX_HOST_COMPILER_ID=NVHPC && make 
warning: failed to remove ./: Invalid argument
Removing ./cmake_install.cmake
Removing ./KokkosCore_Config_FwdBackend.hpp
Removing ./KokkosCore_config.h
Removing ./core
Removing ./KokkosConfig.cmake
Removing ./CMakeFiles
Removing ./CTestTestfile.cmake
Removing ./KokkosCore_Config_DeclareBackend.hpp
Removing ./Testing
Removing ./containers
Removing ./KokkosConfigCommon.cmake
Removing ./example
Removing ./DartConfiguration.tcl
Removing ./KokkosCore_Config_PostInclude.hpp
Removing ./CMakeCache.txt
Removing ./KokkosConfigVersion.cmake
Removing ./Makefile
Removing ./algorithms
Removing ./corner_cases
Removing ./temp
Removing ./KokkosCore_Config_SetupBackend.hpp
-- Setting default Kokkos CXX standard to 14
-- The CXX compiler identification is NVHPC 21.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/jehammond/PRK/gpu-gearbox/kokkos/bin/nvcc_wrapper - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Compiler Version: 11.2.152
-- SERIAL backend is being turned on to ensure there is at least one Host space. To change this, you must enable another host execution space and configure with -DKokkos_ENABLE_SERIAL=OFF or change CMakeCache.txt
-- Using --c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  AMPERE80
--  ZEN
-- Found CUDAToolkit: /usr/local/cuda-11.2/include (found version "11.2.152") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found TPLCUDA: TRUE  
-- Found TPLLIBDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jehammond/PRK/gpu-gearbox/kokkos/build
Scanning dependencies of target kokkoscore
[  3%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o
nvcc-Warning-You are using a legacy version of NVCC with the NVC++ host compiler. In case of any incompatibilities, please upgrade to the latest CUDA toolchain included in this HPC SDK.
nvc++-Error-Switch -tp with unknown keyword znver1
-tp=px|bulldozer|piledriver|zen|zen2|sandybridge|haswell|knl|skylake|host|native
                    Select target processor
    px              Generic x86 Processor
    bulldozer       AMD Bulldozer processor
    piledriver      AMD Piledriver processor
    zen             AMD Zen architecture (Epyc, Ryzen)
    zen2            AMD Zen 2 architecture (Ryzen 2)
    sandybridge     Intel SandyBridge processor
    haswell         Intel Haswell processor
    knl             Intel Knights Landing processor
    skylake         Intel Skylake Xeon processor
    host            Link native version of HPC SDK cpu math library
    native          Alias for -tp host
make[2]: *** [core/src/CMakeFiles/kokkoscore.dir/build.make:75: core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_CPUDiscovery.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:953: core/src/CMakeFiles/kokkoscore.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by masterleinad** [comment]
I'm not too familiar with `nvc++`. Do you expect that you still need `nvcc_wrapper` and if so should it replace the host compiler or rather `nvcc` (I guess this one)?

If we identify the compiler to be `NVIDIA` (which means we are using `nvcc` as of now), we specify flags that we pass to `nvcc_wrapper`. This script forwards flags known to `nvcc` and only passes the remaining ones to the host compiler.
As I said before, you can add `COMPILER_ID KOKKOS_CXX_HOST_COMPILER_ID` if you want compiler flags to be determined based on the host compiler (instead of just asking if `nvcc` is used).

**Comment by crtrott** [comment]
This is a problem we recently identified. Since NVCC only forwards the host arch flags we need to add flags based on the host compiler not on the device compiler. We are currently not set up for taht.

**Comment by crtrott** [comment]
Closing this in favor of #4199

**Pull request closed without merging**
