### PR TITLE
Remove support for CUDA devices with compute capability less than 3.5

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://github.com/kokkos/kokkos/issues/3761. Since there was no one complaining for quite some time, it seems to be OK to just drop support for `Kepler30` and `Kepler32` instead of trying to find workarounds for these two architectures.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Review by Rombur — APPROVED** [review]
The code is fine but we still need to decide if we want to fix the bugs or drop the oldest architectures. I think that's fine to remove support for these old architectures, especially since we don't have easily access to cards this old.

**Review by dalg24 — CHANGES_REQUESTED** [review]
Blocking until we discuss at the developer meeting

**Comment by janciesko** [comment]
Adding fallback for atomic min and max for Kepler: https://github.com/kokkos/kokkos/pull/3780

**Comment by masterleinad** [comment]
Let's close then if that works.

**Pull request closed without merging**
