### PR TITLE
Initial stab at supporting PGI as host compiler for NVCC

### PR DESCRIPTION
**Pull request by crtrott**
Also updates nvcc_wrapper

### CODE REVIEW

**Comment by crtrott** [comment]
Restarted SpotCheck

**Comment by crtrott** [comment]
Confirmed: we are using 8GB of memory in the memory pool test, and are doing so on master too.

**Comment by crtrott** [comment]
```
Running on machine: apollo
WARNING!! THE FOLLOWING CHANGES ARE UNCOMMITTED!! :
?? core/unit_test/standalone/out

Repository Status:  7b84b2826c35deb222eef66910ea23bb54027442 Merge pull request #1826 from jschueller/mingw


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=128 run_time=438
clang-6.0-Cuda_Pthread-release build_time=223 run_time=319
clang-6.0-OpenMP-release build_time=112 run_time=84
cuda-9.1-Cuda_OpenMP-release build_time=309 run_time=204
gcc-4.8.4-OpenMP-release build_time=105 run_time=104
gcc-4.8.4-Pthread-release build_time=98 run_time=338
gcc-5.3.0-Serial-release build_time=112 run_time=177
intel-16.0.1-OpenMP-release build_time=331 run_time=134
```

**Comment by crtrott** [comment]
Running new spotcheck.

**Comment by crtrott** [comment]
```
Repository Status:  da108b2fed4fd1eadb3962c9854c2de2a6c70e91 Merge branch 'develop' into issue-1828


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=127 run_time=420
clang-6.0-Cuda_Pthread-release build_time=223 run_time=320
clang-6.0-OpenMP-release build_time=112 run_time=83
cuda-9.1-Cuda_OpenMP-release build_time=307 run_time=210
gcc-4.8.4-OpenMP-release build_time=104 run_time=97
gcc-4.8.4-Pthread-release build_time=97 run_time=318
gcc-5.3.0-Serial-release build_time=113 run_time=161
intel-16.0.1-OpenMP-release build_time=330 run_time=133
```

**Comment by ndellingwood** [comment]
@crtrott is this PR complete for the PGI host support and ready for merge?

**Comment by crtrott** [comment]
This is ready for merge. Somebody just needs to approve this.

**Comment by ndellingwood** [comment]
@crtrott approved.

**Pull request merged**
