### PR TITLE
SYCL: Fix range in subgroup scan for workgroup_scan

### PR DESCRIPTION
**Pull request by masterleinad**
After https://github.com/kokkos/kokkos/pull/6750, https://github.com/kokkos/kokkos/blob/55c5757502bdc5d5f6b9658a91114dcf56df6a4b/core/src/SYCL/Kokkos_SYCL_ParallelScan_Range.hpp#L51 triggers in `Debug` mode. This has been wrong before but we never noticed. We must only run over the strides that can possibly happen in a subgroup, not the strides possible in the full workgroup.
After this pull request, the implementation matches `workgroup_reduce` better.

### CODE REVIEW

**Comment by crtrott** [comment]
so why did we never get a wrong answer in our testing?

**Comment by masterleinad** [comment]
> so why did we never get a wrong answer in our testing?

Because we still have a
```
if (id_in_sg >= stride) final_reducer.join(&local_value, &tmp);
```
guard which prevented these (garbage) values from ever being used.

**Comment by dalg24** [comment]
Your description refers twice to the same PR.

**Comment by masterleinad** [comment]
> Your description refers twice to the same PR.

Removed the duplication.

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Unrelated HIP runtime failures.

**Comment by masterleinad** [comment]
The `SYCL` build passed.

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
Does this merit a changelog entry for 4.4 #6914 ?

**Comment by masterleinad** [comment]
> Does this merit a changelog entry for 4.4 #6914 ?

No, it's a fix for a pull request that is already in the changelog.

**Pull request merged**
