### PR TITLE
Unify IterateTile.hpp for HIP and CUDA

### PR DESCRIPTION
**Pull request by masterleinad**
AFAICT, we use the same implementation and I don't see a reason to duplicate it.
This just takes the HIP implementation and replaces the implicit `threadIdx` and `blockIdx` variables by passing `global_x/y/z` and `local_x/y/z`. This should also allow to use it for SYCL (probably with minor modifications).

### CODE REVIEW

**Review by DavidPoliakoff — APPROVED** [review]
This is great stuff, seems well implemented. If it passes CI I'm in favor

**Comment by crtrott** [comment]
Can I get a register count analysis? Not using the build-ins may increase register count which would be bad.

**Review by crtrott — CHANGES_REQUESTED** [review]
I want to see a register usage analysis.

**Comment by masterleinad** [comment]
Actually, we can just use the implicit variables and provide them as member variables for `SYCL`.

**Comment by crtrott** [comment]
> Actually, we can just use the implicit variables and provide them as member variables for `SYCL`.

Thats a good idea!

**Review by crtrott — APPROVED** [review]

**Pull request merged**
