### PR TITLE
Disable travis coverage check for linux/clang

### PR DESCRIPTION
**Pull request by crtrott**
This is probably not a good way of doing it. But I want to at least see that it works.

### CODE REVIEW

**Comment by crtrott** [comment]
@junghans you may wanna take a look at this.

**Comment by junghans** [comment]
Hmm, I think it is a bit confusing to have `COVERAGE=yes` not actually triggering a coverage build, why didn’t you add the coverage for clang to the `exclude:` block?

**Comment by crtrott** [comment]
ok looks like this was not it :-(

**Comment by crtrott** [comment]
No idea what to do. I can't reproduce this locally so far ...

**Comment by masterleinad** [comment]
I tried building with `clang-7.0.0`, too, and didn't see the issue...

**Comment by masterleinad** [comment]
There seems no reason to keep this open since the pure purpose was to check if it fixes the failing tests which it doesn't.

**Pull request closed without merging**
