### PR TITLE
removed const references to integral parameters in several places

### PR DESCRIPTION
**Pull request by dhollman**
This should address #1733

### CODE REVIEW

**Comment by dhollman** [comment]
```
Running on machine: apollo
Repository Status:  4abd4ccde14f1baef666ec66187148a7dde965fb removed const references to integral types in several places


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=135 run_time=476
clang-6.0-Cuda_Pthread-release build_time=236 run_time=327
clang-6.0-OpenMP-release build_time=116 run_time=94
cuda-9.1-Cuda_OpenMP-release build_time=321 run_time=182
gcc-4.8.4-OpenMP-release build_time=106 run_time=116
gcc-4.8.4-Pthread-release build_time=98 run_time=353
gcc-5.3.0-Serial-release build_time=115 run_time=183
intel-16.0.1-OpenMP-release build_time=334 run_time=152
```

**Comment by ndellingwood** [comment]
@crtrott @ibaned this should be ready for merge.

**Comment by ibaned** [comment]
@dhollman for my own education, if I want a class and its methods to be used in a fully constexpr context, I should avoid const reference where pass-by-value would do?

**Comment by dhollman** [comment]
@ibaned No, just non-`const` references and non-`const` rvalue references ([godbolt link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5BwAMAQW4BmPC2QMRWANQclAYQIBPAA6YA%2BgWJNCg3djmKFAeie6AIu89KP3rz/9%2Bgb7BASFBoRHhUWExkbHRcYkJgQoOaCyCBJgAHsbEWqoEWoIAjiJMxJgQhVosIgC2AJQ6AOx8ClqdWpUEYiy1DVoAVAP1uu2KLR6pCumZOXkFLEWl5ZVmcwRmlQBm1ctam9wAbKPNHG0OXd2YvcT9dfXDo%2BMOF9OO8psL%2BTWrFeZdvsCCctNlzpcOjc7v1ss9sq9UlM3rNUBksrlfgd/utiEDCidQeDWhNOj0%2BmD4YjJh8XMl4gykoz6UzWSz2czOWzmTN5Fl6sZmFkdPp1ExBIItAAVUiHZgS9wAN1QeHQdgcmWIImQRSymQ2aPmmJYmAlWhAxQI6BAIB2TAYgnMRlMJNaPgmDn5gqYwt0ejFZql6oUmu1utNW2%2BxtNtn0MqulutIEwLCYACMGOY8DsLH6cVUpTbFfaRJhziEtABOYOKJTYc2Jm2WUsWEyYV3vamezACoXtv0ByVBusa5s6rR6yOGjF5E0KuOkBOZJMp9OZszZ3P6fMG9HbTB7QsgYsaMsi/xaWjHGt2BvLptap1tjvIpQehRevsi/3yoc10PjpOu5GrOMZ%2BvGUL3smqYZlmOYgtuZQAvuh5FiWZ5%2BFoXAAKw3nWd5Wg%2BLbOv2bRul2H49t6vqir%2B0r/mO4b6lGoHznoEHyJ0UGrrBG7wXmSG4kCR4nqW5YXko14jqk%2BEWlBzZPi6Fw8ORb4ovIdJchy3I6dpelaQZumGVEvJpqgqAMBOEYQBCpLQhSQEsfcYHboRICFJgwBWAwwEEKwCF6IUspKOqdZoae4ydG8yKmeZlmOdOKE2SSCbkvcVnMdOPxzrGehQR5Xn2r5/l%2BkFWgACyhdg4WlpFOhIh8DhmRZGVbECtmpbcDkRr52UuXlbkFd5xXLKVyyyrhI5hce6F1dFjUKM18U9XiB7JcpnUwq1vXRmx%2BXLJ5w2bCV%2BhlVJ9jTaJmBzQ16maUZD36Y9xkvc9b3sgoUiNIw0jYVIpAsNIsj/ag0h6Pw/DFKI4j9lwSi0P9BBA1930ANYgNhsg/VI5X/YDUjA6QoNSP9gggFjSME19pBwLAMCICgqACngmZkBQEBoMzrMgMAAAcSikDsLNZMQZMQGmyOkGmqgVIY0gI6QnP1CmBAAPIsAwctU6QWD1KwwCZpL%2BCVDqeCKqaks5JgyAiFk8v/R5DCSwweBplYxCGHoGCSFICuWHg9T299zBsCgEO8Iwrtk5A32oMYBB4Ia0gALTLu4nC8PwXBMFoycAOr2pZ%2BeYHiJC56rSik9DEh0MHv145LxPZLzxzJ8c5VaMAyDIFovMAHRKFoEC4IQZfKPQWhe1zJc6HDXDNODme8IjyONGjGNY07OP/YHmMA430ik%2BTpCU8D320wznPGCzJfkJQV838QPP84Lwsl2LEva9LqYe/bitM8rZY6tNZGx7PrQ22tjbWwTubMm2srY2ztr7B2B0t6Exdm7WWXssB/39oHZB30dhogIAAZWQPaSQtA%2B5cF5pWSs5VMa8xaHQlhdDGD6zDkvAQGDo42SJvHROGQU5p28BnPgvBs65wLgwIuecS7EDLsnCuVcxA11oHXKQf197aybi3NuHcu4937oPYe%2BAiD5HHrKKe19Waz3hgvcOPAV5UzXqQBAmAmBYCfnwreuNSC7yxvjQmxMj4U1XuvPeW9K7aOCYfE%2B4TsZcAbjouJp8UakHNqLQRIBypAA%3D)).  The problem comes with perfect forwarding and universal references, where something in the stack will deduce a non-const reference.  But in this case, I think the problem was related to `constexpr` on the device versus on the host (and the `const` reference to it not being reachable on the device, with the interprocedural analysis to resolve it to a constant value not being supported across ISA boundaries).  Also, when you expect the type to be on the order of the size of a pointer in most cases that matter, it's better to pass by value anyway, since in cases where the compiler can't do interprocedural analysis the `const` reference parameter gets implemented as a pointer anyway, so the `const int&` in the places that this patch replaced didn't make sense anyway.

**Pull request merged**
