### PR TITLE
Create 'format' target for running clang-format

### PR DESCRIPTION
**Pull request by jrmadsen**
- this is quite useful for when multiple clang-format versions are installed and the default `clang-format` is not v8
- Execute `make format` or `ninja format`
- By default, targets added via `add_custom_target` are not part of the `all` target 
- Set `Kokkos_FORMAT_TARGET` to OFF to disable creating this target
- `format` target is not generated when a subproject

### CODE REVIEW

**Comment by masterleinad** [comment]
This does not cover everything we check with `scripts/apply-clang-format`. I would very much prefer if we just call that executable (possibly improving it) in the new target instead.

**Comment by jrmadsen** [comment]
@masterleinad what is this missing that is included in the apply-clang-format? Other than the sed stuff. That script tends to generate an intermediate file. This is actually a more portable solution since it doesn't depend on a shell (allowing you to run it on Windows). It's also not intended to fully replicate that script, it's just an easier way to run clang format _on the source_.

**Comment by jrmadsen** [comment]
Also, there is no way (to my knowledge) to set an environment variable for a custom target so you wouldn't be able to run it with a specific clang-format exe

**Comment by masterleinad** [comment]
> what is this missing that is included in the apply-clang-format? Other than the sed stuff. That script tends to generate an intermediate file. This is actually a more portable solution since it doesn't depend on a shell (allowing you to run it on Windows). It's also not intended to fully replicate that script, it's just an easier way to run clang format on the source.

Basically, checking for trailing whitespace and checking the copyright header. My main motivation is to have a single place in the codebase that is responsible for checking/fixing whatever we test in the CI. What we are currently doing there is to call `./scripts/apply-clang-format` and check that `git diff` has empty output. Defining a target that only does the main part might be confusing since it is not sufficient.

> Also, there is no way (to my knowledge) to set an environment variable for a custom target so you wouldn't be able to run it with a specific clang-format exe

Apparently, there is a possibility: https://stackoverflow.com/a/35042808 I haven't tried it myself.

**Comment by jrmadsen** [comment]
> What we are currently doing there is to call ./scripts/apply-clang-format and check that git diff has empty output.

Why not just `git-clang-format --diff HEAD~2`? 

> checking for trailing whitespace

Since when does clang-format not trim trailing whitespace?

> checking the copyright header

I guess we could add running that script. As I said, this was intended to be just an easy way to pick up the right clang-format exe and running clang-format, since can run in from any build directory and it's easy to just do `make format && make` instead of looking up the environment variable, setting the environment variable, running the script and getting 100 lines of:

```console
sed: 1: "tmp": undefined label 'mp'
sed: 1: "tmp": undefined label 'mp'
sed: 1: "tmp": undefined label 'mp'
sed: 1: "tmp": undefined label 'mp'
...
```

This would basically work as a starting point `cmake -P cmake/kokkos_clang_format.cmake`:

```cmake
if(CMAKE_SCRIPT_MODE_FILE)

    # prefer clang-format 8.0
    FIND_PROGRAM(KOKKOS_CLANG_FORMATTER
        NAMES
            git-clang-format-8
            git-clang-format-8.0
            git-clang-format-mp-8.0)

    IF(NOT KOKKOS_CLANG_FORMATTER)
        MESSAGE(FATAL_ERROR "git-clang-format is required")
    ENDIF()

    EXECUTE_PROCESS(
        COMMAND             ${KOKKOS_CLANG_FORMATTER} --diff HEAD~2
        WORKING_DIRECTORY   ${CMAKE_CURRENT_LIST_DIR}
        OUTPUT_VARIABLE     _OUT
        RESULT_VARIABLE     _RET
        OUTPUT_STRIP_TRAILING_WHITESPACE)

    IF(_RET OR (_OUT AND NOT "${_OUT}" MATCHES "no modified files to format"))
        MESSAGE(FATAL_ERROR "Error: not formatted:\n${_OUT}")
    ENDIF()
    RETURN()
endif()

# ...current contents when building...
```

**Comment by crtrott** [comment]
Note we need 8.0.0 not 8.0.1

**Comment by dalg24** [comment]
There was no interest at last developer meeting.

**Pull request closed without merging**
