### PR TITLE
Deprecate View APIs

### PR DESCRIPTION
**Pull request by ibaned**
This pull request puts `#ifdef KOKKOS_ENABLE_DEPRECATED_CODE` around:
 - `View::dimension_?()`
 - `View::dimension(?)`
 - `View::is_contiguous()`
 - `View::ptr_on_device()`

It also goes through the large amounts of code in Kokkos itself that use them and replaces these deprecated functions with calls to their new counterparts. Finally, it fixes an issue where `DualView::resize` was relying on the deprecated support for `deep_copy` between views of different extents.

I recommend this NOT be merged until @dsunder 's expected changes are merged.

### CODE REVIEW

**Comment by ibaned** [comment]
@dsunder said this is okay to merge before his changes.

**Comment by crtrott** [comment]
Whats actually up with is_contiguous. Can you remind me why we deprecate this?

**Comment by ibaned** [comment]
I did that based on this existing comment:
```cpp
// Deprecated, use 'span_is_contigous()' instead
```

**Comment by ibaned** [comment]
This can be traced all the way back to summer 2015 with @hcedwar 's changes:

https://github.com/kokkos/kokkos/commit/1651c2b4bde08a0cf27484b6c48c80565231c79f
https://github.com/kokkos/kokkos/commit/9816365ceb40cf015ca7fc9d23c8d81b16bc26db

**Comment by crtrott** [comment]
ah ok makes sense (the span_is_contiguous)

**Comment by swbova** [comment]
I have gotten the tests to pass with --disable_deprecated_code.  After pulling this merge into my branch, it introduced some brokenness because View::dimension_*() is now guarded with DISABLE_DEPRECATED_CODE.  This is just a heads-up that I am going through and fixing these issues as part of my View task #1286. If anyone else is doing this, we are going to conflict a lot...

**Pull request merged**
