### PR TITLE
Fix CMake deduplication issue when linking with hip::device

### PR DESCRIPTION
**Pull request by etiennemlb**
Related to #5898; the TLDR being that one does not seem able to link against both `Kokkos::kokkos` and `hip::device`.

I maintain that its more a hack than a complete fix for the issue. An alternative would have been to use `"SHELL:-x hip"`.

### CODE REVIEW

**Comment by crtrott** [comment]
Oh are we appending `-x hip` unnecessarily when we build with CMake language support?

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
Yeah just confirmed with Clang as compiler we also append "-x cuda" even when using CMake's language support.

**Comment by dalg24** [comment]
What prevent us from implementing the suggested `"SHELL:-x hip"` alternative?

**Comment by crtrott** [comment]
> What prevent us from implementing the suggested `"SHELL:-x hip"` alternative?

Nothing, but I am also not sure that it is better/more helpful?

**Review by Rombur — APPROVED** [review]

**Pull request merged**
