### PR TITLE
DynamicView: Address issue #1206

### PR DESCRIPTION
**Pull request by ndellingwood**
Commit to modify DynamicView such that:
1. remove need for memory pool by...
2. resize only functions from the host outside of parallel_* regions
     reason - remove need for memory pool

Due to removing the memory pool, the ptr-array-to-chunks, i.e. m_chunks,
is now allocated in CudaUVM space when CudaSpace is enabled; chunks are
still allocated in CudaSpace.

Current impl API asks for (label, min_chunk_size, max_extent)
Max extent is asked for to avoid resizing the m_chunks array, which
could lead to possible issues if multiple DynamicViews are copies of
each other, sharing the allocation, and one of them requires resize of
the m_chunks array (to pointers of chunks)

### CODE REVIEW

**Comment by ndellingwood** [comment]
@crtrott Initial tests with serial, openmp and cuda backends pass (just from the containers/unit_tests built with generate_makefile script)
Some cleanup for printf statements needed, leaving for now in anticipation of changes.

**Comment by crtrott** [comment]
Here is another thing. There is no good reason why we can't grow the chunk array either. We just do a old fashioned resize on the host (i.e. create a new chunk array and deep copy the content into the new larger one). This way the max_extent is a just a current max extent. The cost of doing that is probably very manageable. Just do the copy on the host so you don't spin up a GPU kernel if CUDA is enabled.

**Comment by hcedwar** [comment]
Growing the array of chunk pointers during a resize is problematic because only the DynamicView on which the resize is called with have the new array.  Thus the behavior would be radically different if the resize did / did not need to reallocate the array of chunk pointers.

**Comment by ndellingwood** [comment]
@crtrott Pushed a fix for the broken algorithms test (though unsure what a good min chunk size should be), did a quick check for all unit tests with OpenMP backend and tests are building+passing. 

@crtrott @hcedwar Like Carter mentioned, 
Will move on to some test_all_sandia runs for bookkeeping. 

the resize on the chunk of arrays can be an issue when there are multiple copies of the DynamicView and one of them calls resize requiring the new array of chunk pointers

**Comment by crtrott** [comment]
Can you post output from test_all_sandia? After that this can be merged.

**Comment by ndellingwood** [comment]
Will push a couple changes shortly and then test_all_sandia after that finishes

**Comment by ndellingwood** [comment]
Made changes to how the extent is stored and returned, cleaned up messy comments added another unit test. Separate commit added deprecate macro around `dimension_*()` routines. 
Running spot-check now...

**Comment by ndellingwood** [comment]
The Cuda test broke because I didn't guard the lambda usage in the unit tests:

```
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=191 run_time=84
clang-3.9.0-Pthread_Serial-release build_time=197 run_time=208
gcc-5.3.0-OpenMP-hwloc-release build_time=254 run_time=103
gcc-5.3.0-OpenMP-release build_time=254 run_time=107
gcc-6.1.0-Serial-hwloc-release build_time=195 run_time=123
gcc-6.1.0-Serial-release build_time=201 run_time=124
intel-17.0.1-OpenMP-hwloc-release build_time=546 run_time=191
intel-17.0.1-OpenMP-release build_time=552 run_time=187
#######################################################
FAILED TESTS
#######################################################
cuda-8.0.44-Cuda_OpenMP-release (build failed)
```

**Comment by ndellingwood** [comment]
Will fix the lambda stuff then rerun test_all_sandia but only with Cuda

**Comment by ndellingwood** [comment]
Running on machine: sems
Repository Status:  da8f4d6ae35dd9ad21752b9c5f6e9013d15fe9f7 TestSort, DynamicView: Add fence to fix failing sort test


Going to test compilers:  cuda/8.0.44
Testing compiler cuda/8.0.44
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
cuda-8.0.44-Cuda_OpenMP-release build_time=482 run_time=562

**Comment by ndellingwood** [comment]
Added guards around the lambdas in the unit tests, had to add fence to the sort test that uses `DynamicView`

**Comment by ndellingwood** [comment]
I'm not able to reproduce the clang + Serial failed test from travis-ci. Followed the config output on my Mac laptop to try to reproduce but everything built and passed.

**Comment by crtrott** [comment]
Running SpotCheck now. The Travis fail was a system error in travis not an issue with this code. I will merge if and when the spot-check comes back clean.

**Comment by crtrott** [comment]
Test are not passing:
```
/home/crtrott/Kokkos/kokkos/containers/src/Kokkos_DynamicView.hpp:351:11: error: reference to __host__ function 'CudaUVMSpace' in __host__ __device__ function
          typename traits::memory_space().deallocate( m_chunks[i], m_chunk_size );
          ^
```

```
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=154 run_time=196
cuda-8.0.44-Cuda_OpenMP-release build_time=316 run_time=252
gcc-4.8.4-OpenMP-release build_time=142 run_time=112
gcc-4.8.4-Pthread-release build_time=124 run_time=211
gcc-5.1.0-Serial-release build_time=132 run_time=121
intel-16.0.1-OpenMP-release build_time=408 run_time=143
#######################################################
FAILED TESTS
#######################################################
clang-4.0.0-Cuda_Pthread-release (build failed)
```

**Comment by crtrott** [comment]
Running spot check again on fixed pull request.

**Comment by crtrott** [comment]
Ok now this works:
```
Running on machine: apollo
Repository Status:  03d4e93cb077f4918bf04af9635d15c58eef440b FIx algorithms unit test to use Kokkos::initialize


        ERROR loading module sems-tex/2015
        Module points to path  /projects/sems/install/rhel6-x86_64/sems/utility/tex/2015  which does not exist
        Please contact SEMS team
Going to test compilers:  gcc/4.8.4 gcc/5.1.0 intel/16.0.1 clang/3.9.0 clang/4.0.0 cuda/8.0.44
Testing compiler gcc/4.8.4
Testing compiler gcc/5.1.0
  Starting job gcc-4.8.4-OpenMP-release
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler intel/16.0.1
  Starting job gcc-5.1.0-Serial-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED gcc-5.1.0-Serial-release
Testing compiler clang/4.0.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-4.0.0-Cuda_Pthread-release
  PASSED intel-16.0.1-OpenMP-release
  PASSED clang-4.0.0-Cuda_Pthread-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=158 run_time=203
clang-4.0.0-Cuda_Pthread-release build_time=280 run_time=270
cuda-8.0.44-Cuda_OpenMP-release build_time=315 run_time=249
gcc-4.8.4-OpenMP-release build_time=142 run_time=111
gcc-4.8.4-Pthread-release build_time=123 run_time=218
gcc-5.1.0-Serial-release build_time=133 run_time=119
intel-16.0.1-OpenMP-release build_time=407 run_time=134
```

**Pull request merged**
