### PR TITLE
Try to address issue #1166

### PR DESCRIPTION
**Pull request by ibaned**

### CODE REVIEW

**Comment by ibaned** [comment]
book-keeping #1166

**Comment by ibaned** [comment]
@stanmoore1 seems okay with this

**Comment by stanmoore1** [comment]
But would something like this be a lot simpler:

<pre>
ifneq (KOKKOS_INTERNAL_COMPILER_NVCC,1)
  ifneq ($(OMPI_CXX),)
    KOKKOS_INTERNAL_COMPILER_NVCC      = $(strip $(shell $(OMPI_CXX) --version       2>&1 | grep nvcc                | wc -l))
  endif
  ifneq ($(MPICH_CXX),)
    KOKKOS_INTERNAL_COMPILER_NVCC      = $(strip $(shell $(MPICH_CXX) --version       2>&1 | grep nvcc                | wc -l))
  endif
endif
</pre>

**Comment by ibaned** [comment]
It would still work for these two cases, but it seems more dangerous to me. Someone may be compiling a Kokkos code that doesn't use MPI, so that `$(CXX)` is `g++`, in an environment where there exists an OpenMPI with `OMPI_CXX` pointing to `nvcc`, and then the detection would fail again.

**Comment by stanmoore1** [comment]
That seems like a stretch...

**Comment by ibaned** [comment]
"For every unreasonable way to build your code, there exists a user who is doing that"

**Comment by stanmoore1** [comment]
>Someone may be compiling a Kokkos code that doesn't use MPI, so that $(CXX) is g++, in an environment where there exists an OpenMPI with OMPI_CXX pointing to nvcc, and then the detection would fail again.

Are you sure? The previous issue was that "The result is that KOKKOS_INTERNAL_COMPILER_NVCC starts out being 1, then becomes 0 due to the OMPI_CXX [change]." That can't happen now.

**Comment by ibaned** [comment]
> Are you sure? The previous issue was that "The result is that KOKKOS_INTERNAL_COMPILER_NVCC starts out being 1, then becomes 0 due to the OMPI_CXX [change]." That can't happen now.

But thats not the only way to output the wrong answer. I pointed out another case already where your code gets the wrong answer and mine doesn't.

Frankly, it is the LAMMPS way of building Kokkos that is broken. If `OMPI_CXX` were really set up properly then these extra checks wouldn't be needed. This is because LAMMPS sets `OMPI_CXX` in a Makefile and GNU make doesn't export it to `$(shell)` calls.

**Comment by stanmoore1** [comment]
>I pointed out another case already where your code gets the wrong answer and mine doesn't.

Which was that?

**Comment by stanmoore1** [comment]
There is nothing preventing a user from renaming their mpi compiler, in which case your code would fail too... even though that is unlikely.

**Comment by ibaned** [comment]
> >I pointed out another case already where your code gets the wrong answer and mine doesn't.

> Which was that?

Someone may be compiling a Kokkos code that doesn't use MPI, so that `CXX` is `g++`, in an environment where there exists an OpenMPI with `OMPI_CXX` pointing to `nvcc`, and then the detection would fail again. In particular, it would start out being `0` (the right answer already, `g++` is not `nvcc`), but then it would keep going and check `OMPI_CXX` even though `CXX` is *not* `mpicxx`, and at the end it would declare that the compiler is `nvcc` even though it isn't.

**Comment by ibaned** [comment]
> There is nothing preventing a user from renaming their mpi compiler, in which case your code would fail too... even though that is unlikely.

Yep, my code has failure cases too... without a perfectly robust way of determining "`CXX` is `mpicxx` and would try to use `OMPI_CXX` if it were set up properly", I think failure cases are inevitable.

**Comment by stanmoore1** [comment]
>Frankly, it is the LAMMPS way of building Kokkos that is broken. If OMPI_CXX were really set up properly then these extra checks wouldn't be needed. This is because LAMMPS sets OMPI_CXX in a Makefile and GNU make doesn't export it to $(shell) calls.

If you know a way to improve the LAMMPS way of building Kokkos so that these checks aren't needed, I'm totally open to that.

**Comment by ibaned** [comment]
Yea its more like a "bug" in GNU make where variables are not exported to `$(shell)`... maybe there is a workaround based on:
https://www.linuxquestions.org/questions/programming-9/exporting-makefile-variables-to-%24-shell-environment-807422/
I'll look into this, it might be a much more robust solution...

**Comment by stanmoore1** [comment]
An even more likely failure mode for this PR (as is): a user will set `g++` as `CXX` and then manually link in a MPI library. Then the `KOKKOS_INTERNAL_COMPILER_MPI` check fails and `KOKKOS_INTERNAL_COMPILER_NVCC` isn't set. There is nothing that says a user has to use the `mpicxx` wrappers.

**Comment by stanmoore1** [comment]
>Someone may be compiling a Kokkos code that doesn't use MPI, so that CXX is g++, in an environment where there exists an OpenMPI with OMPI_CXX pointing to nvcc, and then the detection would fail again. In particular, it would start out being 0 (the right answer already, g++ is not nvcc), but then it would keep going and check OMPI_CXX even though CXX is not mpicxx, and at the end it would declare that the compiler is nvcc even though it isn't.

I don't think that matters. The `KOKKOS_INTERNAL_COMPILER_NVCC` is/should be guarded by `ifeq ($(KOKKOS_INTERNAL_USE_CUDA), 1)`, so it shouldn't matter if it is set when CUDA isn't turned on.

**Comment by ibaned** [comment]
> I don't think that matters. The KOKKOS_INTERNAL_COMPILER_NVCC is/should be guarded by ifeq ($(KOKKOS_INTERNAL_USE_CUDA), 1), so it shouldn't matter if it is set when CUDA isn't turned on.

Okay, replace `g++` with `clang`, where Clang is being used to compile CUDA code.

**Comment by stanmoore1** [comment]
And I'd argue if you are randomly setting environment variables like `OMPI_CXX` you are asking for trouble.

**Comment by ibaned** [comment]
> And I'd argue if you are randomly setting environment variables like OMPI_CXX you are asking for trouble.

Thats why using a modified `nvcc_wrapper` is better than setting `OMPI_CXX=nvcc`.

**Comment by stanmoore1** [comment]
Actually we set `OMPI_CXX=nvcc_wrapper`.

**Comment by stanmoore1** [comment]
>Thats why using a modified nvcc_wrapper is better than setting OMPI_CXX=nvcc.

If we set `CXX=nvcc_wrapper`, then we can't use the `mpicxx` wrapper, and the link fails unless we manually link in the MPI library, a huge pain. That is why we used `OMPI_CXX` in the first place. What is a modified `nvcc_wrapper`?

**Comment by stanmoore1** [comment]
>Okay, replace g++ with clang, where Clang is being used to compile CUDA code.

If the clang compiler has "mpi" in the name then your code fails...

**Comment by stanmoore1** [comment]
I'll see if I can't come up with a more robust solution. But at some point we have to put the onus on the user to not do contradictory things like setting environment variables and not really meaning it.

**Comment by stanmoore1** [comment]
@ibaned how about this: `KOKKOS_INTERNAL_COMPILER_NVCC := $(strip $(shell OMPI_CXX=$(OMPI_CXX); MPICH_CXX=$(MPICH_CXX); $(CXX) --version 2>&1 | grep nvcc | wc -l))` (see below for full diff). This works around the bug in `GNU Make` and allows the override of the `OMPI_CXX` variable if it is set in the Makefile. The change only persists for the one line call to set `KOKKOS_INTERNAL_COMPILER_NVCC` and then `OMPI_CXX` reverts back to the original value, so nothing is changed outside of the Makefile. LAMMPS builds fine with this change. For more info see (see http://savannah.gnu.org/bugs/?10593 and https://www.cmcrossroads.com/article/basics-getting-environment-variables-gnu-make).

<pre>
 git diff .
diff --git a/lib/kokkos/Makefile.kokkos b/lib/kokkos/Makefile.kokkos
index 4641232..2c73507 100644
--- a/lib/kokkos/Makefile.kokkos
+++ b/lib/kokkos/Makefile.kokkos
@@ -86,13 +86,7 @@ KOKKOS_INTERNAL_COMPILER_INTEL       := $(strip $(shell $(CXX) --version       2
 KOKKOS_INTERNAL_COMPILER_PGI         := $(strip $(shell $(CXX) --version       2>&1 | grep PGI                 | wc -l))
 KOKKOS_INTERNAL_COMPILER_XL          := $(strip $(shell $(CXX) -qversion       2>&1 | grep XL                  | wc -l))
 KOKKOS_INTERNAL_COMPILER_CRAY        := $(strip $(shell $(CXX) -craype-verbose 2>&1 | grep "CC-"               | wc -l))
-KOKKOS_INTERNAL_COMPILER_NVCC        := $(strip $(shell $(CXX) --version       2>&1 | grep nvcc                | wc -l))
-ifneq ($(OMPI_CXX),)
-  KOKKOS_INTERNAL_COMPILER_NVCC      := $(strip $(shell $(OMPI_CXX) --version       2>&1 | grep nvcc                | wc -l))
-endif
-ifneq ($(MPICH_CXX),)
-  KOKKOS_INTERNAL_COMPILER_NVCC      := $(strip $(shell $(MPICH_CXX) --version       2>&1 | grep nvcc                | wc -l))
-endif
+KOKKOS_INTERNAL_COMPILER_NVCC        := $(strip $(shell OMPI_CXX=$(OMPI_CXX); MPICH_CXX=$(MPICH_CXX); $(CXX) --version       2>&1 | grep nvcc                | wc -l))
 KOKKOS_INTERNAL_COMPILER_CLANG       := $(strip $(shell $(CXX) --version       2>&1 | grep clang               | wc -l))
 KOKKOS_INTERNAL_COMPILER_APPLE_CLANG := $(strip $(shell $(CXX) --version       2>&1 | grep "apple-darwin"      | wc -l))
 KOKKOS_INTERNAL_COMPILER_HCC         := $(strip $(shell $(CXX) --version       2>&1 | grep HCC                 | wc -l))
</pre>

**Comment by ibaned** [comment]
I like that idea! Seems better all around. I can make a PR in a bit, unless you want to.

**Comment by stanmoore1** [comment]
Sounds good, thanks

**Comment by ibaned** [comment]
Actually, I just changed this PR with a new commit. I think it does exactly what you proposed. Once we get approval from another Kokkos core dev this should go in.

**Comment by hcedwar** [comment]
@crtrott : please review

**Comment by crtrott** [comment]
Doesn't look like it works. When I add 
```
export OMPI_CXX = /home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper
```
to the Makefile of kokkos/benchmarks/bytes_and_flops and
```
$(warning "NVCC: " $(KOKKOS_INTERNAL_COMPILER_NVCC))
```
To Makefile.kokkos and use
```
make CXX=mpicxx KOKKOS_PATH=/home/crtrott/Kokkos/kokkos
```

I get:
```
/home/crtrott/Kokkos/kokkos/Makefile.kokkos:90: "NVCC: " 0
```

While doing on the command line:
```
export OMPI_CXX=/home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper
```
Gives the expected answer of 1.

I think I have a fix see next post:

**Comment by crtrott** [comment]
OK with the push I will do I get the following:

  | CXX | env OMPI_CXX | Makefile OMPI_CXX | KOKKOS_INTERNAL _COMPILER_NVCC | Expected |
  | --- | --- | --- | --- | --- |
  | g++ | NA | NA | 0 | 0 |
  | g++ | g++ | NA | 0 | 0 |
  | g++ | NA | g++ | 0 | 0 |
  | g++ | g++ | g++ | 0 | 0 |
  | g++ | nvcc_wrapper | NA | 0 | 0 |
  | g++ | NA | nvcc_wrapper | 0 | 0 |
  | g++ | nvcc_wrapper | nvcc_wrapper | 0 | 0 |
  | g++ | g++ | nvcc_wrapper | 0 | 0 |
  | g++ | nvcc_wrapper | g++ | 0 | 0 |
  | nvcc_wrapper | NA | NA | 1 | 1 |
  | nvcc_wrapper | g++ | NA | 1 | 1 |
  | nvcc_wrapper | NA | g++ | 1 | 1 |
  | nvcc_wrapper | g++ | g++ | 1 | 1 |
  | nvcc_wrapper | nvcc_wrapper | NA | 1 | 1 |
  | nvcc_wrapper | NA | nvcc_wrapper | 1 | 1 |
  | nvcc_wrapper | nvcc_wrapper | nvcc_wrapper | 1 | 1 |
  | nvcc_wrapper | g++ | nvcc_wrapper | 1 | 1 |
  | nvcc_wrapper | nvcc_wrapper | g++ | 1 | 1 |
  | mpicxx | NA | NA | 0 | 0 |
  | mpicxx | g++ | NA | 0 | 0 |
  | mpicxx | NA | g++ | 0 | 0 |
  | mpicxx | g++ | g++ | 0 | 0 |
  | mpicxx | nvcc_wrapper | NA | 1 | 1 |
  | mpicxx | NA | nvcc_wrapper | 1 | 1 |
  | mpicxx | nvcc_wrapper | nvcc_wrapper | 1 | 1 |
  | mpicxx | g++ | nvcc_wrapper | 1 | 1 |
  | mpicxx | nvcc_wrapper | g++ | 0 | 0 |

I think this is what we want, if you explicitly use nvcc_wrapper as CXX you get a 1, and the Makefile OMPI_CXX is prioritized over the environment OMPI_CXX, but either OMPI_CXX does not factor in if mpicxx is not the compiler.

**Pull request merged**
