### PR TITLE
Remove `Experimental::LayoutTiled` class template and deprecate `is_layouttiled` trait

### PR DESCRIPTION
**Pull request by dalg24**
Rational: Currently not usable (see https://godbolt.org/z/K7q6zz8Pc) because the `ViewMapping` implementation is only provided in a private header that is never included in Kokkos internals.  Removing reduces complexity before the `mdspan` view refactor.

I marked the `Kokkos::is_layouttiled` trait as deprecated and I just removed the `Experimental::LayoutTiled` class template (instead of going through deprecation) because, even though one could use that type directly, there is really noting useful that can be done with it (that is cannot use it as View template argument).  Let me know if you think that is too aggressive.

### CODE REVIEW

**Comment by dalg24** [comment]
I forgot to mention neither the trait nor the layout are used in Trilnos outside Kokkos

**Comment by crtrott** [comment]
I pinged Victor to see if there is any use of this he can find, but generally I am ok to rip it out for now. We could ask for feedback at the release briefing.

**Comment by dalg24** [comment]
If that helps deciding, since its introduction in https://github.com/kokkos/kokkos/pull/1731, the `Experimental::LayoutTiled` implementation has never been included outside in the tests.

**Comment by crtrott** [comment]
We couldn't identify any use. Its in experimental namespace. And you had to include a impl/ header, which didn't even work anymore since we made the private/public header distinction. So yank it.

**Review by crtrott — APPROVED** [review]
Follow up we should move the `layout_iterate_type_selector` into `Impl` namespace. There is no reason it should be public. Note this thing is used in stuff like ViewCopy to figure out the type of the `MDRangePolicy`.

**Review by ldh4 — APPROVED** [review]

**Comment by dalg24** [comment]
CUDA failures were unrelated (machine issues)

**Pull request merged**
