### PR TITLE
Added Kokkos_Types_fwd.hpp header

### PR DESCRIPTION
**Pull request by jrmadsen**
- forward declare execution and memory-spaces
- Added `Kokkos::IsAvailable` type-trait, e.g.

```cpp
class Foo
{
     static_assert(Kokkos::IsAvailable<Kokkos::Cuda>::value || Kokkos::IsAvailable<Kokkos::HIP>::value, 
                   "Error! Cuda or HIP backend required");
     // ... etc.
};

class Bar
{
     static_assert(Kokkos::IsAvailable<Kokkos::CudaUVMSpace>::value, "Error! Bar requires CUDA UVM space");
     // ... etc.
};
```

### CODE REVIEW

**Comment by jrmadsen** [comment]
Come to think of it, out of habit, I set the default for `Kokkos::IsAvailable<T>` as true. It should probably be the other way around for Kokkos.

**Review by dhollman — CHANGES_REQUESTED** [review]
How is this different from `Kokkos_Core_Fwd.hpp`? Why do we also need this?

**Comment by jrmadsen** [comment]
None of these:

https://github.com/kokkos/kokkos/blob/03ded4e816da5927b946065b005ebfdf38e5a438/core/src/Kokkos_Core_fwd.hpp#L97

Types are always declared and not ifdeffed out to enable enable_if, etc. w/o pre-processor guards

**Comment by jrmadsen** [comment]
It's essentially the opposite of `Kokkos_Core_fwd.hpp` actually.

**Review by masterleinad — COMMENTED** [review]
I like this as an opt-in option.

**Comment by masterleinad** [comment]
Can you please rebase? We should have fixed all the CI issues in `develop`.

**Comment by masterleinad** [comment]
The latest discussion concluded that we want to always forward declare execution spaces.

**Comment by crtrott** [comment]
Shouldn't we just have these forward declarations inside of Kokkos_Core_fwd.hpp?

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Why did you close? Didn't we agree that want this (always)?

**Pull request closed without merging**
