### PR TITLE
Make DynRankView::layout() return the same as a View of the same rank

### PR DESCRIPTION
**Pull request by PhilMiller**

### CODE REVIEW

**Comment by PhilMiller** [comment]
Ugh, even this doesn't actually fix things for the ultimate use case.

**Comment by PhilMiller** [comment]
The underlying values in a `View` layout are getting munged, even before reach DRV.

**Comment by PhilMiller** [comment]
A rank-1 `View` returns a layout that appears to be rank-7:
```
(gdb) l
57	template <typename VIEWOUT, typename VIEWIN> 
58	void setAndCopyDynamicView(VIEWOUT &out, const VIEWIN &in) {
59	  auto props = Kokkos::view_alloc(Kokkos::WithoutInitializing, in.label(), kokkos_control::getDeviceSpace());
60	  out = VIEWOUT(props, in.layout());
61	  empire::deep_copy_blocking("ViewHelperUVM.hpp: setAndCopyDynamicView", out, in);
62	}
63	

(gdb) p in
$5 = (const View<double*> &) @0x7fffffff3f58: {<> = {<No data fields>}, m_track = {m_tracker = {m_record_bits = 1, m_record = 0x1}}, m_map = {m_impl_handle = 0x16813580, m_impl_offset = {m_dim = {<> = {static ArgN0 = 0, 
          N0 = 49}, <> = {static ArgN1 = 0, static N1 = 1}, <> = {static ArgN2 = 1, static N2 = 1}, <> = {static ArgN3 = 1, static N3 = 1}, <> = {static ArgN4 = 1, static N4 = 1}, <> = {static ArgN5 = 1, 
          static N5 = 1}, <> = {static ArgN6 = 1, static N6 = 1}, <> = {static ArgN7 = 1, static N7 = 1}, <No data fields>}}}, static is_layout_left = false, static is_layout_right = true, static is_layout_stride = false, 
  static is_default_map = true}

(gdb) p in.layout()
$6 = {dimension = {49, 1, 1, 1, 1, 1, 1, 1}}

(gdb) p out.rank()
$7 = 7
```
At that point, there's no way for the `DynRankView` to tell what it's being asked to do. The problem lies in `View`

**Comment by PhilMiller** [comment]
So I'm exploring a bit of test code that just exercises `View` and its supports:

```c++
    Kokkos::View<double****> u("foo", 1, 2, 3, 4);

    auto ulayout = u.layout();
    ASSERT_EQ(ulayout.dimension[0], 1);
    ASSERT_EQ(ulayout.dimension[1], 2);
    ASSERT_EQ(ulayout.dimension[2], 3);
    ASSERT_EQ(ulayout.dimension[3], 4);
    ASSERT_EQ(ulayout.dimension[4], KOKKOS_INVALID_INDEX);
    ASSERT_EQ(ulayout.dimension[5], KOKKOS_INVALID_INDEX);
    ASSERT_EQ(ulayout.dimension[6], KOKKOS_INVALID_INDEX);
    ASSERT_EQ(ulayout.dimension[7], KOKKOS_INVALID_INDEX);
```

So far, I've checked that the constructor for the underlying `LayoutRight` does see the `~0` values, and not 1

**Review by nliber — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
