### PR TITLE
Check size in Containers WithoutInitializing test

### PR DESCRIPTION
**Pull request by masterleinad**
Follow-up to https://github.com/kokkos/kokkos/pull/5275#issuecomment-1196677436.

### CODE REVIEW

**Comment by PhilMiller** [comment]
It feels weird to be comparing `size()` rather than `extent()`, given our semantics. I agree that this is sensitive to the earlier defects we just addressed, though.

**Comment by ajpowelsnl** [comment]
@masterleinad , @PhilMiller - In all of the new testing statements, you assert expectation of equality (amongst Views, mirrors, etc.).  Would it be important to test for conditions of expected non-equality?

**Review by ajpowelsnl — APPROVED** [review]

**Comment by masterleinad** [comment]
> @masterleinad , @PhilMiller - In all of the new testing statements, you assert expectation of equality (amongst Views, mirrors, etc.). Would it be important to test for conditions of expected non-equality?

@ajpowelsnl What do you mean? Whenever we create a mirror, we expect the extents to be equal to the ones of the original object, right?

**Comment by masterleinad** [comment]
In one `Cuda` CI test we are running out of disk space and `KokkosCore_IncrementalTest_OPENACC` is failing both should be safe to ignore.

**Review by ldh4 — APPROVED** [review]

**Review by PhilMiller — APPROVED** [review]

**Pull request merged**
