### PR TITLE
Ignore unused param warning intel15

### PR DESCRIPTION
**Pull request by jeffmiles63**
turn off unused parameter warnings for intel 15 due to intel issue [DPD200239284](https://software.intel.com/en-us/forums/intel-c-compiler/topic/345355)

team broadcast test still failed after fixing compile issue, which is why I added the barriers to Kokkos_ThreadsTeam.hpp

### CODE REVIEW

**Comment by jeffmiles63** [comment]
@ndellingwood 
I am going to close this temporarily...I just noticed that the Pthreads test didn't run even though the script tried...

`
cmake -DCMAKE_CXX_COMPILER=/projects/sems/install/rhel6-x86_64/sems/compiler/intel/15.0.2/base/bin/icpc -DCMAKE_CXX_FLAGS=-O3 -Wall -Wno-unused-variable -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_INSTALL_PREFIX= -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_PTHREADS=ON -DKokkos_ARCH_KEPLER35=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DKokkos_ENABLE_LARGE_MEM_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=RELEASE -DKokkos_ENABLE_HWLOC=ON -DHWLOC_ROOT=/projects/sems/install/rhel6-x86_64/kokkos/tpl/hwloc/1.10.1/intel/15.0.2/base /ascldap/users/jsmiles/Development/working/fix-kokkos-dev-spot-check/kokkos


...


-- Execution Spaces:
--     Device Parallel: NONE
--     Host Parallel: NONE
--       Host Serial: SERIAL

`

I will re-open when I figure this out...

**Comment by ndellingwood** [comment]
Cross-referencing #2898 efforts in to also address pthreads race condition issues

**Comment by jeffmiles63** [comment]
@ndellingwood @crtrott So, #2898 fixes the segfault in workgrap_fib, the changes in Kokkos_ThreadsTeam.hpp (here) fix the correctness failure in team_broadcast.

I could get all of the intel 15 tests to pass only when I locally merged both PRs

**Comment by crtrott** [comment]
Retest this please

**Comment by crtrott** [comment]
I ignored the last checks in Travis since it hasn't anything to do with this PR

**Pull request merged**
