### PR TITLE
Task multi queue implementation ready to merge

### PR DESCRIPTION
**Pull request by dhollman**
Please let me know if there are any issues.

### CODE REVIEW

**Comment by dhollman** [comment]
Ummm... does the testing infrastructure assume deprecated code is enabled? Do I need to go through and put the hooks to the deprecated interfaces in all of the right places?

**Comment by mhoemmen** [comment]
@theguruat12 @rrdrake Could this may be relevant to CUDA task queue link errors we've been seeing?

**Comment by crtrott** [comment]
@mhoemmen How so? This is not in Kokkos proper yet ...

**Comment by mhoemmen** [comment]
@crtrott Never mind, I think we figured that out -- not a Kokkos thing.

**Comment by dhollman** [comment]
```
Running on machine: apollo
Repository Status:  c5f79926d591406edd2a4ee188627ce13547b336 Fixed a constexpr consistency bug that only showed up in the intel compiler


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=130 run_time=429
clang-6.0-Cuda_Pthread-release build_time=226 run_time=290
clang-6.0-OpenMP-release build_time=116 run_time=86
cuda-9.1-Cuda_OpenMP-release build_time=307 run_time=171
gcc-4.8.4-OpenMP-release build_time=106 run_time=104
gcc-4.8.4-Pthread-release build_time=98 run_time=312
gcc-5.3.0-Serial-release build_time=113 run_time=168
intel-16.0.1-OpenMP-release build_time=333 run_time=143
```

**Pull request merged**
