### PR TITLE
[3.5] Cherry-pick #4520 Kokkos_CopyViews: update local_deep_copy_contiguous signature

### PR DESCRIPTION
**Pull request by ndellingwood**
Kokkos_CopyViews: update local_deep_copy_contiguous signature

(cherry picked from commit d35e42a5d82a1ddc246d86ec55284a62971915a5)

### CODE REVIEW

**Comment by ndellingwood** [comment]
Cross-reference #4520

**Comment by ndellingwood** [comment]
Failure appears due to out-of-space issue on the system `stderr: error: could not lock config file .git/config: No space left on device`

**Comment by ndellingwood** [comment]
retest this please

**Comment by masterleinad** [comment]
The only test failures here are in the `icpc` CI disabled on `develop`.

**Pull request merged**
