### PR TITLE
Feature rendezvous

### PR DESCRIPTION
**Pull request by dsunder**
Improve the performance of the rendezvous algorithm and make it work with Big Endian machines.

Spot tested on kokkos-dev, bowman and white.

### CODE REVIEW

**Comment by crtrott** [comment]
Dan just said there is a random testfailure , not sure if its the change ...

**Comment by stanmoore1** [comment]
Fixes #1234 and #1235. May also fix #995.

**Comment by dsunder** [comment]
The store fence works!!!  I needed a few others to protect the rendezvous initialize too.

**Comment by dsunder** [comment]
Bowman timings: parallel_for/parallel_reduce/parallel_reduce benchmark
   Master 
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.899252
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.897565
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.929234
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.897647
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.905305
   Feature-Rendezvous
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.072020
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.072167
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.072610
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.072230
   1000    1 32       100  100  100    1  1 1 122 0.000000e+00 0.000000e+00 0.072350

**Pull request merged**
