### PR TITLE
team-level stdalgos: improve tests, check intra-team result matching (part 1/7)

### PR DESCRIPTION
**Pull request by fnrizzi**
This PR improves the tests for team-level algorithms `Kokkos_{MinElement, MaxElement, MinMaxElement}.hpp` that were merged in #6208 to verify that when doing:
```cpp
auto returnValue = Kokkos::Experimental::std_algo_function_name(...)
```
the return value is the *same* for every member of the team. 

This is the first in a series of PRs to cover all team level algos currently in develop. 
Note that this PR introduces `team_members_have_matching_result` which is scoped inside the test to help avoiding duplicating code. This will be used in all the subsequent PRs so this should be merged first. 

Scope: this/these PRs are meant to address the concern raised here https://github.com/kokkos/kokkos/pull/6212

### CODE REVIEW

**Comment by fnrizzi** [comment]
gcc timed out

**Comment by cz4rs** [comment]
Retest this please.

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Comment by fnrizzi** [comment]
retest this please

**Comment by crtrott** [comment]
Kokkos_CoreUnitTest_OpenMPTarget failed ... so it's unrelated.

**Pull request merged**
