### PR TITLE
Fix issue with cray compiles (Issue#2390)

### PR DESCRIPTION
**Pull request by jeffmiles63**
- fix problem with KOKKOS_ARCH and ""  (picks default automatically if option is "" -- something there means don't pick the default)
  - fix problem with cray version string
  - turn off examples by default
  - use location of cm_generate script for kokkos path

Issue #2390

### CODE REVIEW

**Comment by crtrott** [comment]
Looks good to me? @dalg24 @jjwilke any concerns regarding the "I need a space string here" solution?

**Comment by jjwilke** [comment]
Yeah, the space thing is fine. Sorry, bad mistake on my part. The "best" thing to do would be have a sentinel value "NO_KOKKOS_FLAGS" that's a space (or even something else) to make it even clearer and also make sure the arch function is consistent.

**Comment by jjwilke** [comment]
I'm a bit confused on the Cray compiler.  Is this issue that CMake is reporting the wrong version? Or is CMake's version different than Makefile.kokkos?

**Comment by jeffmiles63** [comment]
Without the change, the Version String is missing something such that VERSION_LIST has the
wrong number of entries.  I think that the string format is different enough that is needs preprocessing.
----------------------------------------------------------------------------------------------
STRING(REPLACE "." ";" VERSION_LIST ${KOKKOS_CXX_COMPILER_VERSION})
LIST(GET VERSION_LIST 0 KOKKOS_VERSION_MAJOR)
LIST(GET VERSION_LIST 1 KOKKOS_VERSION_MINOR)
LIST(GET VERSION_LIST 2 KOKKOS_VERSION_PATCH)
---------------------------------------------------------
One of the list entries fails with invalid index

**Comment by jjwilke** [comment]
Is this just an issue with Cray only using MAJOR and MINOR? Or is this a more serious issue like https://cmake.org/Bug/view.php?id=15664

**Comment by jeffmiles63** [comment]
That issue implies that the version is incorrectly reported...The number is correct, but not complete.  So the statement only using MAJOR and MINOR (not revision) is accurate.  Here is the output with the change commented out.

--------------------------------------------------------------------------------------
cmake -DCMAKE_CXX_COMPILER=$COMPILER -DKokkos_CXX_FLAGS= -DKokkos_LINK_FLAGS= -DCMAKE_INSTALL_PREFIX= -DKokkos_ENABLE_OPENMP=ON -DKokkos_ARCH_HSW=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_EXAMPLES=OFF -DCMAKE_CXX_COMPILER=/opt/cray/pe/craype/2.5.16/bin/CC -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_EXTENSIONS=OFF -DKokkos_CUDA_DIR= -DKokkos_CXX_STANDARD= /home/jsmiles/Development/cray-cmake-build/kokkos
-- Setting default Kokkos CXX standard to 11
-- The CXX compiler identification is Cray 8.7
-- Cray Programming Environment 2.5.16 CXX
-- Check for working CXX compiler: /opt/cray/pe/craype/2.5.16/bin/CC
-- Check for working CXX compiler: /opt/cray/pe/craype/2.5.16/bin/CC -- works
...
CMake Error at cmake/kokkos_compiler_id.cmake:80 (LIST):
  LIST index: 2 out of range (-2, 1)
...
------------------------------------------
Note that CMake identifies only 8.7 as the version and list index 2 is out of range (revision number)

For the case that works, the version string is correctly identified as 8.7.7
from CMakeCache.txt: KOKKOS_CXX_COMPILER_VERSION:STRING=8.7.7

**Comment by jjwilke** [comment]
Gotcha. Weird that CMake doesn't give a full version number.

**Comment by jeffmiles63** [comment]
updated " " to NO-VALUE-SPECIFIED

**Comment by crtrott** [comment]
NO-VALUE-SPECIFIED is something we could use in other places too for similar situations so I think we are good.

**Pull request merged**
