### PR TITLE
Cleanup C++11 workarounds

### PR DESCRIPTION
**Pull request by masterleinad**
This pull request replaces features that are now part of C++11.

### CODE REVIEW

**Review by mhoemmen — APPROVED** [review]
Thanks for not getting rid of `Kokkos::Impl::if_c`; that can't just be replaced by `std::conditional`, due to the (useful!) `select` method.

**Comment by crtrott** [comment]
Can we wait till openmp is in?

**Comment by crtrott** [comment]
I think resolving conflicts here is easier than in the openmp pr

**Comment by masterleinad** [comment]
> Can we wait till openmp is in?

Sure, there is no reason to rush here.

**Comment by dalg24** [comment]
These changes broke the HIP backend :@

**Comment by dmcdougall** [comment]
@dalg24 Yep.  Here's the compiler error I get:

```
/home/damon/git/kokkos/core/src/Kokkos_HIP_Space.hpp:477:10: error: no template named 'is_same'; did you mean 'std::is_same'?
        !is_same<Kokkos::Experimental::HIPSpace, OtherSpace>::value,
```

**Pull request merged**
