### PR TITLE
OpenMPTarget: Update CI to use llvm/15.0.0 and enable corresponding unit tests

### PR DESCRIPTION
**Pull request by rgayatri23**

### CODE REVIEW

**Review by cz4rs — APPROVED** [review]
_please ignore this_

**Review by cz4rs — CHANGES_REQUESTED** [review]
Looks promising except for the warnings:
```
Kokkos/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp:1596:14: error: unused variable 'team_size' [-Werror,-Wunused-variable]
```

**Comment by cz4rs** [comment]
By the way, is there any hope for re-enabling perf tests? (different issue / PR of course)
https://github.com/kokkos/kokkos/blob/05cef203c2348bd6b2394105691ae9713b02574c/core/perf_test/CMakeLists.txt#L12-L16

**Review by masterleinad — COMMENTED** [review]
Looks good if you get the CI to pass.

**Comment by masterleinad** [comment]
The indentation is still off:
```
diff --git a/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp b/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
index cb6fe1ac4..c9f2a6374 100644
--- a/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
+++ b/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
@@ -1606,8 +1606,8 @@ KOKKOS_INLINE_FUNCTION void parallel_scan(
 #pragma omp barrier
 #else
   const auto team_size = member.team_size();
-  const auto nchunk = (end - start + team_size - 1) / team_size;
-  value_type accum  = 0;
+  const auto nchunk    = (end - start + team_size - 1) / team_size;
+  value_type accum     = 0;
   // each team has to process one or
   //      more chunks of the prefix scan
   for (iType i = 0; i < nchunk; ++i) {
```

**Comment by rgayatri23** [comment]
> By the way, is there any hope for re-enabling perf tests? (different issue / PR of course)
> 
> https://github.com/kokkos/kokkos/blob/05cef203c2348bd6b2394105691ae9713b02574c/core/perf_test/CMakeLists.txt#L12-L16

For the OpenMPTarget, this is just 

> The indentation is still off:
> 
> ```diff
> diff --git a/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp b/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
> index cb6fe1ac4..c9f2a6374 100644
> --- a/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
> +++ b/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
> @@ -1606,8 +1606,8 @@ KOKKOS_INLINE_FUNCTION void parallel_scan(
>  #pragma omp barrier
>  #else
>    const auto team_size = member.team_size();
> -  const auto nchunk = (end - start + team_size - 1) / team_size;
> -  value_type accum  = 0;
> +  const auto nchunk    = (end - start + team_size - 1) / team_size;
> +  value_type accum     = 0;
>    // each team has to process one or
>    //      more chunks of the prefix scan
>    for (iType i = 0; i < nchunk; ++i) {
> ```

Yes justf ixed it.

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
Failure is unrelated

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
