### PR TITLE
Fix -Wshadow warnings

### PR DESCRIPTION
**Pull request by masterleinad**
This pull request fixes the `-Wshadow` errors I got when compiling and running the unit tests using `gcc-8.2.0`.

### CODE REVIEW

**Review by crtrott — APPROVED** [review]
Looks good.

**Comment by crtrott** [comment]
Needs spot-check.

**Comment by ndellingwood** [comment]
Spot-check on apollo:

```
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git'
Running on machine: apollo
Repository Status:  ed5411e646e2855796fc3dd98621df7a4fd39dc6 Fix -Wshadow warnings


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
Testing compiler cuda/9.1
  Starting job clang-6.0-OpenMP-release
  PASSED clang-6.0-OpenMP-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=137 run_time=472
clang-6.0-Cuda_Pthread-release build_time=237 run_time=326
clang-6.0-OpenMP-release build_time=115 run_time=96
cuda-9.1-Cuda_OpenMP-release build_time=321 run_time=182
gcc-4.8.4-OpenMP-release build_time=108 run_time=117
gcc-4.8.4-Pthread-release build_time=99 run_time=365
gcc-5.3.0-Serial-release build_time=113 run_time=182
intel-16.0.1-OpenMP-release build_time=337 run_time=146
```

**Comment by ndellingwood** [comment]
@crtrott spot-check finished, I don't think I have access to a testbed with gcc/8

**Pull request merged**
