### PR TITLE
Fix fences in DynRankView

### PR DESCRIPTION
**Pull request by dalg24**
Amendment to #3244 
I did not have permissions to push directly to the branch

### CODE REVIEW

**Comment by ndellingwood** [comment]
Can this be cherry-picked to the release-candidate-3.2 branch as well?

**Comment by MicheldeMessieres** [comment]
@ndellingwood @dalg24 Could you confirm when these changes would be in Trilinos? If it will be a while I may manually sync it for some ongoing work. Thanks.

**Comment by ndellingwood** [comment]
Cherry-picked to release-candidate-3.2 via
`git cherry-pick -m 1 -x 9a127fa6ba684034da7d762572f1ecef3d6d1e31`

**Comment by ndellingwood** [comment]
@MicheldeMessieres I've been actively working on the 3.2 release integration testing and just cherry picked a needed fix and updates (including this PR) for next round of testing, will have a better sense of status tomorrow whether to be optimistic about completion this week or not

**Comment by ndellingwood** [comment]
@MicheldeMessieres PR issued to Trilinos with 3.2.00 release including this PR

**Pull request merged**
