### PR TITLE
Delete disused parallel_reduce functors' join(volatile) overloads

### LINKED ISSUE #4077: Remove need for volatile overloads for types in Kokkos reductions
- [ ] identify where reductions are implemented
- [ ] remove volatile overloads
- [ ] ensure all tests work 

@PhilMiller commented: the tests should ideally not just pass, but also exhibit no errors from ThreadSanitizer or a comparable dynamic data race analysis. This may be complicated by the fact that ThreadSanitizer doesn't directly support atomic fence operations, only actual atomic loads and stores (cf https://github.com/google/sanitizers/issues/1352 since this deficiency isn't actually documented otherwise!)

### PR DESCRIPTION
**Pull request by PhilMiller**
Closes #4077

### CODE REVIEW

**Comment by masterleinad** [comment]
I think you could split this up some more. There are clearly some commits that are not related to the failing tests, like [`c59c7f3` (#4187)](https://github.com/kokkos/kokkos/pull/4187/commits/c59c7f3b18dd1005d83775720ce43f136df72680).

**Comment by PhilMiller** [comment]
> I think you could split this up some more. There are clearly some commits that are not related to the failing tests, like [`c59c7f3` (#4187)](https://github.com/kokkos/kokkos/pull/4187/commits/c59c7f3b18dd1005d83775720ce43f136df72680).

The trivial stuff is now in https://github.com/kokkos/kokkos/pull/4189 which I'll rebase on and work to resolve the hard stuff.

**Comment by crtrott** [comment]
Looks like this totally broke some stuff in cuda.

**Comment by crtrott** [comment]
OK I read through the code, the functors volatile overloads are always used right now on develop via the FunctorValueJoin etc wrapper class which ONLY had volatile overloads of join etc. before. These guys were the ones which were passed to cuda_inter_block_reduction etc. in Kokkos_Cuda_Parallel.hpp (see the define for the ValueJoin type for example) and thus all the join function called in CUDA operations were using the volatile overloads. As the testing effectively showed those volatile markings are critical for the reductions to work since they now all fail :-)

**Comment by PhilMiller** [comment]
Obviated by #4901

**Pull request closed without merging**
