### PR TITLE
CI: fix builds on rawhide

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Comment by junghans** [comment]
@dalg24 you might need to a similar fix to all other branches using github actions....

**Comment by dalg24** [comment]
Damned it was `master` I messed up

**Comment by dalg24** [comment]
Please open against `develop`

**Comment by junghans** [comment]
@dalg24 https://github.com/kokkos/kokkos/pull/4362

**Pull request merged**
