### PR TITLE
Workaround Intel compiler bug in string manipulation test

### LINKED ISSUE #4926: Nightly Serial build failure, TestStringManipulation.cpp: error: static assertion failed
Nightly Serial build of Trilinos with Kokkos' develop branch failed to compile with intel/18 with the following message

```
[ 23%] Building CXX object kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_KokkosP.dir/UnitTestMainInit.cpp.o
<https://jenkins-son.sandia.gov/job/KokkosEco_Trilinos_Blake_Intel181163_Serial_Cplx/ws/Trilinos/kokkos/core/unit_test/TestStringManipulation.cpp(71)>: error: static assertion failed with ""
    STATIC_ASSERT(strcmp(cat1, cat2) < 0);
```

I'll update the issue as more testing completes to give a better scope of which builds are affected

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4926
https://godbolt.org/z/G879478a8
It was fine will all icx versions I could try, failing with icc 2021.1.2 and fine from 2021.2.0.  Fun stuff...

### CODE REVIEW

**Comment by ndellingwood** [comment]
> failing with icc 2021.1.2 and fine from 2021.2.0. Fun stuff...

yuck, thanks for the fast fix!

**Review by ndellingwood — APPROVED** [review]

**Review by ndellingwood — CHANGES_REQUESTED** [review]
@dalg24 the gcc/5.3.0 build also failed with the same issue, 

```
18:41:36 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_530_deprecated_off/kokkos/core/unit_test/TestStringManipulation.cpp:50:29: error: non-constant condition for static assertion
18:41:36  #define STATIC_ASSERT(cond) static_assert(cond, "")
```

I'm assuming some extra work will be needed for the macro guards

**Comment by ndellingwood** [comment]
@dalg24 Nightly gcc/6.4.0 also failed

**Comment by dalg24** [comment]
Please confirm what lines cause compilation to fail

**Comment by ndellingwood** [comment]
@dalg24 here is a more detailed error snip from the gcc/5.3.0 build
```
18:41:36 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_530_deprecated_off/kokkos/core/unit_test/TestStringManipulation.cpp: In function ‘constexpr bool {anonymous}::test_to_chars()’:
18:41:36 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_530_deprecated_off/kokkos/core/unit_test/TestStringManipulation.cpp:50:29: error: non-constant condition for static assertion
18:41:36  #define STATIC_ASSERT(cond) static_assert(cond, "")
18:41:36                              ^
18:41:36 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_530_deprecated_off/kokkos/core/unit_test/TestStringManipulation.cpp:193:3: note: in expansion of macro ‘STATIC_ASSERT’
18:41:36    STATIC_ASSERT(to_chars_helper(123, "123"));
18:41:36    ^
18:41:36 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_530_deprecated_off/kokkos/core/unit_test/TestStringManipulation.cpp:193:3:   in constexpr expansion of ‘{anonymous}::to_chars_helper<int>(123, ((const char*)"123"))’
18:41:36 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_530_deprecated_off/kokkos/core/unit_test/TestStringManipulation.cpp:187:21:   in constexpr expansion of ‘Kokkos::Impl::to_chars_i<int>(((char*)(& buffer)), (((char*)(& buffer)) + 21u), val)’
```

**Comment by dalg24** [comment]
What about 6.1 and 6.4?

**Comment by dalg24** [comment]
https://godbolt.org/z/53aje61b5

**Comment by ndellingwood** [comment]
@dalg24 

Here is first error occurrence from gcc/6.4:
```
18:27:00 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_gcc_640/kokkos/core/unit_test/TestStringManipulation.cpp: In function ‘constexpr bool {anonymous}::test_strncmp()’:
18:27:00 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_gcc_640/kokkos/core/unit_test/TestStringManipulation.cpp:50:29: error: non-constant condition for static assertion
18:27:00  #define STATIC_ASSERT(cond) static_assert(cond, "")
18:27:00                              ^
18:27:00 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_gcc_640/kokkos/core/unit_test/TestStringManipulation.cpp:96:3: note: in expansion of macro ‘STATIC_ASSERT’
18:27:00    STATIC_ASSERT(strncmp(&greet2[12], &greet3[11] + 11, 5) == 0);
18:27:00    ^~~~~~~~~~~~~
18:27:00 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_gcc_640/kokkos/core/unit_test/TestStringManipulation.cpp:96:3:   in constexpr expansion of ‘Kokkos::Impl::strncmp((& greet2[12]), ((& greet3[11]) + 11u), 5ul)’
18:27:00 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_gcc_640/kokkos/core/unit_test/TestStringManipulation.cpp:50:29: error: array subscript value ‘22’ is outside the bounds of array type ‘const char [17]’
18:27:00  #define STATIC_ASSERT(cond) static_assert(cond, "")
18:27:00                              ^
18:27:00 /home/jenkins/weaver-new/workspace/Kokkos_develop_weaver_gcc_640/kokkos/core/unit_test/TestStringManipulation.cpp:96:3: note: in expansion of macro ‘STATIC_ASSERT’
18:27:00    STATIC_ASSERT(strncmp(&greet2[12], &greet3[11] + 11, 5) == 0);
18:27:00    ^~~~~~~~~~~~~
```

Here is gcc/6.1
```
18:26:43 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_610/kokkos/core/unit_test/TestStringManipulation.cpp: In function ‘constexpr bool {anonymous}::test_strncmp()’:
18:26:43 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_610/kokkos/core/unit_test/TestStringManipulation.cpp:50:29: error: non-constant condition for static assertion
18:26:43  #define STATIC_ASSERT(cond) static_assert(cond, "")
18:26:43                              ^
18:26:43 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_610/kokkos/core/unit_test/TestStringManipulation.cpp:96:3: note: in expansion of macro ‘STATIC_ASSERT’
18:26:43    STATIC_ASSERT(strncmp(&greet2[12], &greet3[11] + 11, 5) == 0);
18:26:43    ^~~~~~~~~~~~~
18:26:43 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_610/kokkos/core/unit_test/TestStringManipulation.cpp:96:3:   in constexpr expansion of ‘Kokkos::Impl::strncmp((& greet2[12]), ((& greet3[11]) + 11u), 5ul)’
18:26:43 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_610/kokkos/core/unit_test/TestStringManipulation.cpp:50:29: error: array subscript value ‘22’ is outside the bounds of array type ‘const char [17]’
18:26:43  #define STATIC_ASSERT(cond) static_assert(cond, "")
18:26:43                              ^
18:26:43 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_gcc_610/kokkos/core/unit_test/TestStringManipulation.cpp:96:3: note: in expansion of macro ‘STATIC_ASSERT’
18:26:43    STATIC_ASSERT(strncmp(&greet2[12], &greet3[11] + 11, 5) == 0);
```

**Comment by dalg24** [comment]
Would you test with 43502b9?

**Comment by ndellingwood** [comment]
@dalg24 I tested the PR and confirm with these changes we have successful compilation with gcc/6.4.0, gcc/6.1.0, gcc/5.3.0

**Review by ndellingwood — APPROVED** [review]

**Review by fnrizzi — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
