### PR TITLE
Add missing gfx940

### PR DESCRIPTION
**Pull request by rbberger**
This MR adds the missing architecture support for gfx940 into Kokkos. This was a requirement for getting things working at the LLNL COE hackathon in December. It also fixes some missing parts for gfx942.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Comment by dalg24** [comment]
What's the difference between gfx940 and gfx942?
Also there seems to also be a gfx941?  Do we also need support for that architecture?

**Comment by rbberger** [comment]
@dalg24 sry, can't go into specifics. But we only need gfx940 at the moment.

**Comment by Rombur** [comment]
@IanBogle any guideline from AMD on whether we should also add support for gfx941 in our build system?

**Comment by IanBogle** [comment]
@Rombur You should not need to add support for gfx941.

**Comment by Rombur** [comment]
Great. Thanks @IanBogle

**Pull request merged**
