### PR TITLE
Use -fsycl-device-code-split=per_kernel for SYCL CI

### PR DESCRIPTION
**Pull request by masterleinad**
Let's see if this makes a difference in compile and run time, see https://www.intel.com/content/www/us/en/develop/documentation/oneapi-dpcpp-cpp-compiler-dev-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/offload-openmp-and-parallel-processing-options/fsycl-device-code-split.html for an explanation of the flag.

### CODE REVIEW

**Comment by masterleinad** [comment]
With this option I see: "Total Test time (real) = 1350.53 sec" whereas other builds without this option show "Total Test time (real) = 397.90 sec" but the overall time decreases from 1h 3m to 48m.

**Comment by masterleinad** [comment]
With `per_source`, I'm back to "Total Test time (real) = 367.40 sec" and overall time 1h.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
`OPENMPTARGET-Clang` failing is clearly unrelated.

**Review by dalg24 — APPROVED** [review]

**Review by cz4rs — APPROVED** [review]

**Pull request merged**
