### PR TITLE
Suppress class/struct mismatch warning from Clang

### LINKED ISSUE #4968: Nightly clang/7+cuda/9.2 compilation errors with -Werror: Kokkos_Array.hpp:354:1: error: 'tuple_size' defined as a struct template here but previously declared as a class template
Following merge of #4962 the clang/7+cuda/9.2 nightly job showed compilation errors:

```
22:23:31 In file included from /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/core/src/impl/Kokkos_ViewArray.hpp:48:
22:23:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/core/src/Kokkos_Array.hpp:354:1: error: 'tuple_size' defined as a struct template here but previously declared as a class template [-Werror,-Wmismatched-tags]
22:23:31 struct std::tuple_size<Kokkos::Array<T, N>>
22:23:31 ^
22:23:31 /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../include/c++/7.2.0/array:342:5: note: did you mean struct here?
22:23:31     class tuple_size;
22:23:31     ^
22:23:31 In file i
```

**Reproducer**:
```
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/7.2.0 sems-archive-cuda/9.2 sems-archive-clang/7.0.1

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Kepler35 --compiler=clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples
```

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4968

### CODE REVIEW

**Comment by PhilMiller** [comment]
Hopefully this fixes it. I've seen some instances of warnings that were massively hard to suppress, because the diagnostic pragma had to be active at the point of instantiation, not template declaration/definition.

**Comment by dalg24** [comment]
I expect this works.  I found this in GTest
https://github.com/google/googletest/blob/80600e56cc9afe7ee02737429f9177aa87025054/googletest/include/gtest/internal/gtest-internal.h#L1329-L1343

**Comment by dalg24** [comment]
https://godbolt.org/z/dh3f6oYha

**Comment by dalg24** [comment]
Same unrelated failure type that I had seen on #4950 
```
4: [ RUN      ] openmptarget.int64_t_reduce_dynamic
4: CUDA error: an illegal memory access was encountered 
4: Libomptarget error: Call to targetDataEnd failed, abort target.
4: Libomptarget error: Failed to process data after launching the kernel.
4: Libomptarget error: Consult https://openmp.llvm.org/design/Runtimes.html[](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/8620/#step-207-log-185) for debugging options.
4: Kokkos_OpenMPTarget_Parallel.hpp:333:1: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
```
@rgayatri23 have you seen this before

**Comment by rgayatri23** [comment]
> Same unrelated failure type that I had seen on #4950
> 
> ```
> 4: [ RUN      ] openmptarget.int64_t_reduce_dynamic
> 4: CUDA error: an illegal memory access was encountered 
> 4: Libomptarget error: Call to targetDataEnd failed, abort target.
> 4: Libomptarget error: Failed to process data after launching the kernel.
> 4: Libomptarget error: Consult https://openmp.llvm.org/design/Runtimes.html for debugging options.
> 4: Kokkos_OpenMPTarget_Parallel.hpp:333:1: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
> ```
> 
> @rgayatri23 have you seen this before

Yes I think this test fails with  earlier versions of LLVM.  I think this was fixed with llvm/13 and we are now using llvm/14.

**Comment by ndellingwood** [comment]
@dalg24 these changes allowed the failing build from #4968 to compile successfully for me

**Review by ndellingwood — APPROVED** [review]
Approval based on the failing nightly build, will let @rgayatri23 follow up based on the CI OMPTarget stuff

**Review by cz4rs — APPROVED** [review]

**Pull request merged**
