### PR TITLE
[4.5.0] Fix DynRankView in ScratchSpace (#7517)

### PR DESCRIPTION
**Pull request by crtrott**
Cherry-pick of #7517 fixing DynRankView issues for scratch space.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Comment by ndellingwood** [comment]
Before we fast track this, an error is occurring in the Trilinos builds (AT2):

```
/home/Trilinos/build/packages/kokkos/containers/unit_tests/serial/TestSerial_DynRankView_TeamScratch.cpp:2:10: fatal error: TestDynRankView_TeamScratch.hpp: No such file or directory
 #include <TestDynRankView_TeamScratch.hpp>
```

I only cherry-picked this PR to the Trilinos tester PR, did I miss an auxiliary commit?

**Comment by ndellingwood** [comment]
Or, could including this change be problematic with use of ccache? I think the jobs uses ccache to improve rebuild times, but I'm not familiar enough with ccache to know what changes can leave a "corrupted" type of state

**Comment by ndellingwood** [comment]
I didn't reproduce the Trilinos issue in a local build

**Review by ndellingwood — APPROVED** [review]

**Comment by crtrott** [comment]
Yeah could be ccache or something like that.

**Pull request merged**
