### PR TITLE
Disable in-source builds

### PR DESCRIPTION
**Pull request by dalg24**
Alternate resolution of #2298

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
This PR helps other things, but not the problem it references. I can do an in-source CMake build and not interrupt the out-of-source CMake build. 

That said, an in-source CMake build overwrites the Makefile we provide with Kokkos, which might be a different problem.

I'd see this as a good idea if we want to keep providing the built-in Makefile, but orthogonal to the issue it references

**Comment by crtrott** [comment]
Does this disable:
```
cd kokkos
mkdir build
cd build
cmake ..
```
?

**Comment by Rombur** [comment]
@crtrott no, it's still allowed. It disallow
```
cd kokkos
cmake .
```

**Comment by dalg24** [comment]
> Does this disable:
> 
> ```
> cd kokkos
> mkdir build
> cd build
> cmake ..
> ```
> 
> ?

No this is still allowed and this is how it is done in the CI on Jenkins.

**Pull request merged**
