### PR TITLE
Remove redundant CMake variable definition

### PR DESCRIPTION
**Pull request by masterleinad**
Without this patch, I am seeing

```
CMake Warning (dev) at cmake/kokkos_enable_devices.cmake:138 (SET):
  Cannot set "DEVICE_SETUP_LIST": current scope has no parent.
```

In fact, we `INCLUDE` the file directly so there is no parent scope indeed.

### CODE REVIEW

**Review by DavidPoliakoff — APPROVED** [review]
I'd like to see what @jeffmiles63 or whoever last changed the file said. That said, this looks good to me

**Review by jeffmiles63 — APPROVED** [review]

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
This is annoying. Any objections to merging it?

**Comment by jeffmiles63** [comment]
I don't see why not

**Pull request merged**
