### PR TITLE
Fix building with NVCC as the CXX compiler while the CUDA backend is not enabled

### LINKED ISSUE #5093: Compilation with NVCC without CUDA
I have a bit of an unusual setup where I compile my code multiple times for multiple kokkos targets to create multiple shared libraries. This worked just fine but fails now with the recent update to 3.6. The root cause being the definition of `KOKKOS_IF_ON_DEVICE`.

https://github.com/kokkos/kokkos/blob/b52f8c835f4df003954dad66d9761094f8baa66c/core/src/Kokkos_Macros.hpp#L567-L578

When I'm compiling my code with an OpenMP version of Kokkos using NVCC `__CUDA_ARCH__` will be set resulting in a non-empty definition of `KOKKOS_IF_ON_DEVICE`. Thus, the initial `#if` should be at least something like

```
#if (defined(__CUDA_ARCH__) && defined(KOKKOS_ENABLE_CUDA)) || \
    defined(__HIP_DEVICE_COMPILE__) || \
    defined(__SYCL_DEVICE_ONLY__)
```

maybe similar guards are needed for HIP and SYCL, but since I'm not familiar with them, I don't want to add any wrong code to my suggestion.

### PR DESCRIPTION
**Pull request by dalg24**
Fix #5093

@ndellingwood would you please add a nightly build with `-DCMAKE_CXX_COMPILER=<prefix>/bin/nvcc_wrapper -DKokkos_ENABLE_CUDA=OFF`?

### CODE REVIEW

**Review by JBludau — COMMENTED** [review]
Is the guard in the TestNumericTraits.hpp really related to the issue or something that came up along the way?

**Review by JBludau — APPROVED** [review]
Looks good to me

**Comment by ndellingwood** [comment]
> @ndellingwood would you please add a nightly build with `-DCMAKE_CXX_COMPILER=<prefix>/bin/nvcc_wrapper -DKokkos_ENABLE_CUDA=OFF`?

Will do

**Comment by ndellingwood** [comment]
@dalg24 I'm testing a local build with the desired config (compile with nvcc_wrapper, cuda backend disabled) to prep for the new nightly build.
Successful compilation (tested with cuda/10.1+gcc/7.3.0), I encountered warning messages related to desul:
```
/ascldap/users/ndellin/kokkos/core/src/../../tpls/desul/include/desul/atomics/Compare_Exchange_ScopeCaller.hpp(39): warning: calling a constexpr __host__ function("operator==") from a __host__ __device__ function("atomic_compare_exchange") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during:
            instantiation of "T desul::atomic_compare_exchange(T *, T, T, desul::MemoryOrderRelaxed, desul::MemoryScopeCaller) [with T=Kokkos::Impl::HostThreadTeamData::pair_int_t]" 
/ascldap/users/ndellin/kokkos/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(227): here
            instantiation of "T Kokkos::atomic_compare_exchange(T *, desul::Impl::dont_deduce_this_parameter_t<const T>, desul::Impl::dont_deduce_this_parameter_t<const T>) [with T=Kokkos::Impl::HostThreadTeamData::pair_int_t]" 
/ascldap/users/ndellin/kokkos/core/src/impl/Kokkos_HostThreadTeam.cpp(225): here

/ascldap/users/ndellin/kokkos/core/src/../../tpls/desul/include/desul/atomics/Compare_Exchange_ScopeCaller.hpp(39): warning: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during:
            instantiation of "T desul::atomic_compare_exchange(T *, T, T, desul::MemoryOrderRelaxed, desul::MemoryScopeCaller) [with T=Kokkos::Impl::HostThreadTeamData::pair_int_t]" 
/ascldap/users/ndellin/kokkos/core/src/Kokkos_Atomics_Desul_Wrapper.hpp(227): here
            instantiation of "T Kokkos::atomic_compare_exchange(T *, desul::Impl::dont_deduce_this_parameter_t<const T>, desul::Impl::dont_deduce_this_parameter_t<const T>) [with T=Kokkos::Impl::HostThreadTeamData::pair_int_t]" 
/ascldap/users/ndellin/kokkos/core/src/impl/Kokkos_HostThreadTeam.cpp(225): here
```
Should I open an issue (and if so does this go to the kokkos repo or an external desul repo)?

**Pull request merged**
