### PR TITLE
Replace CL/sycl.hpp

### PR DESCRIPTION
**Pull request by masterleinad**
`CL/sycl.hpp` is deprecated in favor of `sycl/sycl.hpp`.

### CODE REVIEW

**Comment by dalg24** [comment]
Please confirm that does not change anything in terms of minimum SYCL requirements

**Comment by TApplencourt** [comment]
>The SYCL runtime moved from namespace cl::sycl provided by #include <CL/sycl.hpp> to namespace sycl provided by #include <sycl/sycl.hpp> as explained in [Section 4.3](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:headers-and-namespaces). The old header file is still available for compatibility with SYCL 1.2.1 applications.

It changed from SYCL 1.2.1 to SYCL 2020, so no new SYCL requirement if you are already use SYCL2020 (as I think you are)

**Comment by dalg24** [comment]
Thank you Thomas

**Review by dalg24 — APPROVED** [review]

**Comment by masterleinad** [comment]
> Please confirm that does not change anything in terms of minimum SYCL requirements

I thought "surely, the latest release would have it" but it doesn't seem to be there for the 2022.2.0 toolkit (Intel(R) oneAPI DPC++/C++ Compiler 2022.1.0 (2022.1.0.20220316)

**Comment by crtrott** [comment]
So its not there?

**Review by crtrott — APPROVED** [review]

**Comment by masterleinad** [comment]
> So its not there?

No, https://github.com/intel/llvm/pull/6407 added it but that doesn't seem to be in the latest public release.

**Comment by masterleinad** [comment]
https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/Kokkos/detail/Kokkos/10273/pipeline ran successfully. It just doesn't show here.

**Comment by masterleinad** [comment]
Retest this please.

**Review by masterleinad — COMMENTED** [review]
Relies on https://github.com/desul/desul/pull/68 being merged first.

**Review by crtrott — CHANGES_REQUESTED** [review]
Can we have the same comments as on the desul side

**Comment by masterleinad** [comment]
> Can we have the same comments as on the desul side

@crtrott Done.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
