### PR TITLE
Fix typo in comment: specififed -> specified.

### PR DESCRIPTION
**Pull request by ArchRobison**
Small nit I noticed while perusing the sources.

### CODE REVIEW

**Comment by crtrott** [comment]
Thanks for the fix. Unfortunately I can't apply the pull request directly since we have to push things into the develop branch first. I can either fix this manually in develop, or you can reissue the pull request against develop (in which case github will show the commit coming from your account).  

Let me know how you want to do this, I don't have a preference really.

**Comment by ArchRobison** [comment]
I'll reissue it, since part of the reason for creating such a small PR was for me to learn the right way to do it.

**Comment by hcedwar** [comment]
PR must be to 'develop' branch, not 'master' branch.

**Comment by ArchRobison** [comment]
Closing to reissue.

**Pull request closed without merging**
