### PR TITLE
[skipci] generate_makefile updates

### PR DESCRIPTION
**Pull request by ndellingwood**
* Replace KOKKOS_CXX_STANDARD with CMAKE_CXX_STANDARD on the cmake line
* Update modules for kokkos-dev testbed

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
LGTM.

**Comment by jrmadsen** [comment]
Why do we not just have this in our CMake:

```
# cache variable
set(Kokkos_CXX_STANDARD ... CACHE ...)
# optional local override cache variable
if(DEFINED CMAKE_CXX_STANDARD)
    set(Kokkos_CXX_STANDARD ${CMAKE_CXX_STANDARD})
endif()
# local variable
set(CMAKE_CXX_STANDARD ${Kokkos_CXX_STANDARD})
```

This will provide the same effect within the scope of the Kokkos CMake projecta

**Comment by ndellingwood** [comment]
@jrmadsen I'll add @jjwilke to the thread to comment on the suggested CMake change. I'd prefer that change go into a different PR separate from the testing script changes, though it sounds like the plan is to deprecate public/user usage of `KOKKOS_CXX_STANDARD` based on the follow up discussion in #3423

**Comment by jjwilke** [comment]
I'm sure there are cleaner ways of doing things than what I starting writing back in 2018. I think it's probably a good idea to allow `CMAKE_CXX_STANDARD` and `Kokkos_CXX_STANDARD` to both be given.  However, I think `Kokkos_CXX_STANDARD` should take precedence inside Kokkos.  I'm all for cleaning this up, but I would remove the:

````
# optional local override cache variable
if(DEFINED CMAKE_CXX_STANDARD)
    set(Kokkos_CXX_STANDARD ${CMAKE_CXX_STANDARD})
endif()
````

**Pull request merged**
