### PR TITLE
Fix MSVC build on AppVeyor (Drop no except specification for ObjectWithVLAEmulation's destructor)

### PR DESCRIPTION
**Pull request by dalg24**
Failure followed update from MSVC 19.27.29112.0 to 19.28.29333.0

### CODE REVIEW

**Comment by dalg24** [comment]
This is awesome, `[skip ci]` was ignored by Jenkins and of course it is a command for AppVeyor too and it worked there :/ https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message

**Review by DavidPoliakoff — CHANGES_REQUESTED** [review]
To further ensure we don't merge

**Review by nliber — CHANGES_REQUESTED** [review]
The fix certainly applies (as in doesn't change what happens).

However, the bigger issue is that if one of the value destructors actually throws, the remaining objects are never destroyed.

Probably better to just make it `noexcept` (which IIRC what all destructors if `noexcept` isn't specified).

**Review by nliber — APPROVED** [review]
Looks good.

**Comment by dalg24** [comment]
Tavis failures are unrelated.  Merging.

**Pull request merged**
