### PR TITLE
Add environment option to tests [WIP]

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Review by DavidPoliakoff — APPROVED** [review]
With my limited ability to read CMake this looks good, and I can confirm it solves my problem

**Comment by crtrott** [comment]
Why [WIP}?

**Comment by jjwilke** [comment]
There are no tests currently using this so I didn't necessarily want to commit this.  @DavidPoliakoff has tests that will actually use this so it might be better to just merge it when his changes get merged.

**Comment by DavidPoliakoff** [comment]
My changes need this PR though? Should I put a PR up (based on this one)?

**Comment by jjwilke** [comment]
Yeah, I would just pull or rebase this branch in. That way the new CMake is actually getting used and tested.

**Pull request closed without merging**
