### PR TITLE
OpenMPTarget Index range fix for MDRange. 

### PR DESCRIPTION
**Pull request by rgayatri23**
This fixes the inconsistency in the OpenMPTarget backend observed here #4912

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
I think we should update 
https://github.com/kokkos/kokkos/blob/cdcd6904a4cd1c41e047b217053357371bdb9ee9/core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_MDRange.hpp#L140-L157
and alike also (code path guarded by `#ifndef KOKKOS_IMPL_MDRANGE_USE_NO_TILES `)

**Comment by dalg24** [comment]
Is this 
https://github.com/kokkos/kokkos/pull/5089/files#diff-0fd278d1f633c666a6370086e621cd846a3ba1921e62b2b99ce0e839716d958aR52-R55
still an issue?

**Review by masterleinad — APPROVED** [review]
This is progress.

**Comment by dalg24** [comment]
> This is progress.

Agreed.  OK I'll merge as is and we can fix the alternate code path as a follow-up.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
