### PR TITLE
Unifying Host Thread Team

### PR DESCRIPTION
**Pull request by dsunder**
Carter's work cleaning up the Host backends with some compiler fixes for clang and IBM.  This is a precursor for multiple execution space instances.

### CODE REVIEW

**Comment by crtrott** [comment]
Before we merge all of this lets do some extensive performance testing please.

**Comment by hcedwar** [comment]
@crtrott , if you do it, do it in the next day or two so this merge can be done by Wednesday.

**Comment by crtrott** [comment]
Some Spot Checking with bytest_and_flops: 

KNL OpenMP 256 threads (CONFIG: OLD NEW):
2 100000 1024 64 1 1 1 1 0: 267 273
2 100000 1024 64 1 1 1 4 0: 268 269
2 100000 1024 64 1 1 1 1 20000: 264 272
2 100000 1024 64 1 1 1 4 20000: 265 268
2 100 128 1 1 1 1 1 0: 0.6 0.4
2 100 128 1 1 1 1 4 0: 0.6 0.5
2 100 128 1 1 1 1 1 20000: 0.05 0.4
2 100 128 1 1 1 1 4 20000: 0.05 0.5

KNL OpenMP 32 threads (compact) (CONFIG: OLD NEW):
2 10000 1024 64 1 1 1 1 0: 34.2 34.8
2 10000 1024 64 1 1 1 4 0:  34.0 34.4
2 10000 1024 64 1 1 1 1 20000: 34.2 34.8
2 10000 1024 64 1 1 1 4 20000: 34.0 34.4
2 100 128 1 1 1 1 1 0: 3.0 1.8
2 100 128 1 1 1 1 4 0: 2.8 1.2
2 100 128 1 1 1 1 1 20000: 1.0 1.8
2 100 128 1 1 1 1 4 20000: 1.0 1.2

KNL OpenMP 1 thread (compact) (CONFIG: OLD NEW):
2 10000 1024 64 1 1 1 1 0: 4.4 4.4
2 10000 1024 64 1 1 1 1 20000: 4.4 4.4
2 100 128 1 1 1 1 1 0: 0.6 1.2
2 100 128 1 1 1 1 1 20000: 0.6 1.2

**Comment by crtrott** [comment]
I still have to run the pthreads one. Mostly it looks good, but there is a sign of launch overhead being increased compared to before. The numbers are: (size of scalar) (num teams) (inner loop size) (repeat of inner loops) (XX) (XX) (XX) (team size) (scratch size): (Old Bandwidth) (New Bandwidth)

The 2 100 128 1 1 1 1 1 0 configurations is the closest to simply measuring launch overhead. There is not much work to be done each physical team does only a single thing, and no scratch memory gets used (or rather initialized). The fact that the old implementation

**Comment by crtrott** [comment]
Pthreads with Hwloc on KNL
100 128 1 1 1 1 0: 1.5 1.5
100 128 1 1 1 4 0: 1.5 1.5
100 128 1 1 1 1 20000: 0.017 0.017
100 128 1 1 1 4 20000: 0.017 0.017

**Comment by hcedwar** [comment]
Make sense.  Launch-start should be about the same, team collectives faster, but there is a new "launch-end" operation that disbands the thread teams (cleans up state data).  Previously the thread teams state data was left as "garbage" that was not a problem because it was reset at the next launch-start.  Revision adds a small overhead but is cleaner in managing thread team state data.

**Comment by crtrott** [comment]
I am preparing merge now.

**Pull request merged**
