### PR TITLE
cmake: use GNUInstallDirs

### PR DESCRIPTION
**Pull request by junghans**
Related to #2283.

### CODE REVIEW

**Comment by dalg24** [comment]
Add to whitelist

**Comment by crtrott** [comment]
Couple questions: what is this? Why do we want this? And where is GNUInstallDirs coming from and how would that interact with a Windows build? This is not saying we can't accept this, it is just that I don't understand the purpose.

**Comment by dalg24** [comment]
The GNUInstallDirs module is distributed with CMake (see [here](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html))

**Comment by dalg24** [comment]
I do not understand how well this would play with other operating systems but I believe this is an improvement on the current state of things in Kokkos.

**Comment by junghans** [comment]
@crtrott this is to make all install locations configurable, this will also fix the `lib` vs. `lib64` issue pointed out in #2283.

Windows support-wise, I don't know, but the defaults in https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake seem reasonable for Windows as well.

**Comment by junghans** [comment]
@crtrott plus adding to what @dalg24 said, currently the install location are hard-coded in multiple places, so this (even if it isn't perfect) is a big improvement.

**Pull request merged**
