### PR TITLE
Improve spinwait

### PR DESCRIPTION
**Pull request by dsunder**
Improve spinwait performance and address #953.

Using a std::atomic_thread_fence instead of compiler primitives or assembly fixes bugs in the current rendezvous algorithm which could causes hangs when quickly issuing barriers across NUMA regions.

### CODE REVIEW

**Comment by hcedwar** [comment]
If the performance matches (or improves) better to use vendor-supported mechanisms.
Also Dan was experience memory consistency problems across NUMA regions when tight-looping on the rendezvous barrier.  This problem was resolved when replacing with the std::atomic_thread_fence version of the memory fence.

**Comment by nmhamster** [comment]
@hcdewar - you are testing this across compilers (statement about performance)? That may indicate a heavier fence is being used in this code than before. In general I'd agree with the assessment, that said, sometimes we might want lightweight barriers and the assembly may be useful there.

**Comment by hcedwar** [comment]
@nmhamster - Should we create a ticket for suite of memory fences?
The guidance I have learned is, with C++11 compliance, to begin with sequentially-consistent and then back off to other memory model synchronization mechanisms to performance tune in special cases.

**Comment by nmhamster** [comment]
@hcedwar - I am wondering if we should try to provide a heavyweight and lightweight version then, as you say, start with the heavyweight and slowly back off. My guess is that this will make more of a difference on the POWER and ARM systems where memory ordering is utilized more aggressively by the hardware. The advice you have makes a lot of sense.

**Comment by hcedwar** [comment]
Created issue #1121 to continue the memory fence conversation beyond this PR.

**Pull request merged**
