### PR TITLE
Reenable TestHIP_Memory_Requirements

### PR DESCRIPTION
**Pull request by Rombur**
Updating the OS and re-installing the drivers seem to have fixed the issue.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by Rombur** [comment]
Retest this please

**Review by dalg24 — APPROVED** [review]

**Comment by Rombur** [comment]
Retest this please

**Comment by dalg24** [comment]
Is it ready?  Do you want me to merge?

**Comment by Rombur** [comment]
No it's not ready. Only ROCm 5.6 passed

**Comment by Rombur** [comment]
> I thought these may be machine issues. Many tests failed at runtime.

Right that's why I don't know if works or not. A new version of docker that fixes bugs on Centos was just released.  Hopefully it fixes the issue.

**Comment by Rombur** [comment]
Retest this please

**Comment by crtrott** [comment]
Retest this please.

**Comment by dalg24** [comment]
I see some presumably unrelated runtime failures on the HIP ROCm 5.2 build.
Do you want me to merge @Rombur ?

**Comment by Rombur** [comment]
Yes, we can merge this.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
