### PR TITLE
MDRangePolicy: Lambda fix

### PR DESCRIPTION
**Pull request by ndellingwood**
Commit addresses issue #1379 and #1054
Fix to allow lambda with MDRangePolicy within parallel_for and
parallel_reduce
Unit test with lambda added for ranks 1 to 6

### CODE REVIEW

**Comment by ndellingwood** [comment]
Tested on laptop with Serial and OpenMP backends, will test Cuda and run test_all_sandia tomorrow

**Comment by ibaned** [comment]
@ndellingwood this looks great!
Note that I think `test_all_sandia` with Cuda doesn't fully enable lambdas, so you may want to protect your lambda-using tests with the right macro (`CXX11_DISPATCH_LAMBDA` or something like that).

**Comment by ibaned** [comment]
Please post the output of `test_all_sandia --spot-check` for a machine that has GPUs

**Comment by ndellingwood** [comment]
@ibaned Thanks for the lambda catch, have an error with Cuda I'm working through hopefully push the changes soon.

**Comment by ndellingwood** [comment]
Spot check running now

**Comment by ndellingwood** [comment]
Spot check passed on kokkos-dev:
```
Running on machine: sems
Repository Status:  c2fbdb135b13d7491b7f25f79faf690714c13b24 MDRangePolicy: Guard lambda tests


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/6.1.0
  Starting job gcc-6.1.0-Serial-release
  Starting job gcc-5.3.0-OpenMP-release
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-5.3.0-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-release
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=196 run_time=84
clang-3.9.0-Pthread_Serial-release build_time=213 run_time=207
cuda-8.0.44-Cuda_OpenMP-release build_time=495 run_time=545
gcc-5.3.0-OpenMP-hwloc-release build_time=262 run_time=103
gcc-5.3.0-OpenMP-release build_time=261 run_time=103
gcc-6.1.0-Serial-hwloc-release build_time=216 run_time=122
gcc-6.1.0-Serial-release build_time=205 run_time=121
intel-17.0.1-OpenMP-hwloc-release build_time=587 run_time=183
intel-17.0.1-OpenMP-release build_time=587 run_time=184
```

**Comment by ndellingwood** [comment]
Pushed one more quick changes to cleanup stray comment I missed

**Pull request merged**
