### PR TITLE
GitHub CI: Use hashes for versions

### PR DESCRIPTION
**Pull request by masterleinad**
This should improve our score at https://securityscorecards.dev/viewer/?uri=github.com/kokkos/kokkos by addressing https://github.com/ossf/scorecard/blob/ea7e27ed41b76ab879c862fa0ca4cc9c61764ee4/docs/checks.md#pinned-dependencies for GitHub actions.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
Will Dependatbot be able to update these?

**Comment by masterleinad** [comment]
> Will Dependatbot be able to update these?

Yes, see https://github.com/dependabot/dependabot-core/issues/4691.

**Comment by dalg24** [comment]
Excellent

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
Did you run it w/o the [ci skip] to be sure?

**Comment by masterleinad** [comment]
> Did you run it w/o the [ci skip] to be sure?

I removed the tag now to make sure.

**Review by aprokop — APPROVED** [review]

**Pull request merged**
