### PR TITLE
Also filter out `-pedantic-errors` from nvcc options

### PR DESCRIPTION
**Pull request by ocaisa**
See https://github.com/lammps/lammps/issues/3353 and https://github.com/jbeder/yaml-cpp/issues/831 for some context.

### CODE REVIEW

**Comment by dalg24** [comment]
Can one of the admins verify this patch?

**Review by masterleinad — COMMENTED** [review]
Other than targeting the wrong branch, this looks OK to me.

**Comment by crtrott** [comment]
Same as what Daniel, said, if you can retarget this on develop, we will approve.

**Comment by ocaisa** [comment]
Urgh, let me rebase, sorry

**Review by masterleinad — APPROVED** [review]

**Review by dalg24 — APPROVED** [review]

**Comment by dalg24** [comment]
OK to test

**Comment by crtrott** [comment]
Thanks for the contribution.

**Pull request merged**
