### PR TITLE
make languages given to CMake project unique

### PR DESCRIPTION
**Pull request by ibaned**
~This is very important I feel because it fixes a subtle bug that I think is happening today in the most common use cases of Kokkos.~
Edit: as @masterleinad points out below, this does not affect folks who don't use `COMPILE_AS_CMAKE_LANGAUGE`.

I ran into a very subtle issue where the
CXX language was listed twice in the
CMake project command (which I think is
the normal use case) and this caused
CMAKE_CXX_OUTPUT_EXTENSION to somehow
come through as empty, meaning that
if you compiled foo.cpp, the compiled
object file would also be named foo.cpp
instead of the desired foo.cpp.o
This would in turn cause nasty compile
failures that were also a bit unpredictable.
Sometimes Kokkos would still link okay
but other times (after a rebuild for example)
the object file would be interpreted as
a source file.

### CODE REVIEW

**Comment by ibaned** [comment]
Fixes #5092

**Review by masterleinad — APPROVED** [review]
Thanks for catching this!

Normally, people don't set `Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON`, especially not without also enabling `CUDA`. :slightly_smiling_face: 

The following would also seems to fix the problem:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 32fdf1764..5e6b4c3d5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -75,8 +75,7 @@ IF(NOT KOKKOS_HAS_TRILINOS)
   # downstream dependencies need to match this!
   SET(KOKKOS_COMPILE_LANGUAGE CXX)
   # use lower case here since we didn't parse options yet
-  IF (Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE)
-
+  IF (Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE AND Kokkos_ENABLE_CUDA)
     # Without this as a language for the package we would get a C++ compiler enabled.
     # but we still need a C++ compiler even if we build all our cpp files as CUDA only
     # because otherwise the C++ features don't work etc.
@@ -84,10 +83,7 @@ IF(NOT KOKKOS_HAS_TRILINOS)
     # though it is a C++ extension ... (but I guess it didn't use to be back in CUDA 4 or 5
     # days.
     SET(KOKKOS_INTERNAL_EXTRA_COMPILE_LANGUAGE CXX)
-
-    IF (Kokkos_ENABLE_CUDA)
-      SET(KOKKOS_COMPILE_LANGUAGE CUDA)
-    ENDIF()
+    SET(KOKKOS_COMPILE_LANGUAGE CUDA)
   ENDIF()
 
   IF (Spack_WORKAROUND)
```
which I would slightly prefer but I would also be fine with the pull request as-is.

**Comment by dalg24** [comment]
Please apply the changes suggested by Daniel

**Comment by ibaned** [comment]
@dalg24 Are you sure we should switch @masterleinad 's approach? the `REMOVE_DUPLICATES` approach is scalable to all backends that need their own language plus `CXX`, I don't want that `IF` statement to keep growing out to
```cmake
IF (Kokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE AND (Kokkos_ENABLE_CUDA OR Kokkos_ENABLE_HIP OR Kokkos_SOME_INTEL_GPU_THING))
```

**Comment by ibaned** [comment]
I'm not sure why the `jenkins-ci/pr` thing failed... all I can see is this:
```
ERROR: The container started but didn't run the expected command. Please double check your ENTRYPOINT
```

**Comment by dalg24** [comment]
The failure is
```
4: /var/jenkins/workspace/Kokkos/core/unit_test/TestUniqueToken.hpp:151: Failure
4: Expected equality of these values:
4:   sum
4:     Which is: 9999980
4:   int64_t(N) * R
4:     Which is: 10000000

```
on the OPENMPTARGET-Clang build which is clearly unrelated.  You don't need to do anything.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
