### PR TITLE
Unconditionally define KOKKOS_ENABLE_PROFILING

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
The comment in the code says it all. Thoughts?

### CODE REVIEW

**Comment by masterleinad** [comment]
I would prefer if we can mark the macro as deprecated similar to the suggestiopn in https://stackoverflow.com/a/57479189.

**Comment by crtrott** [comment]
Other then the "print message" variant I don't see any of the suggestions working. Apps are not instantiating the macro. They just ask whether its defined. Which means you won't get a deprecation warning in the right place.

**Review by dalg24 — CHANGES_REQUESTED** [review]
I am weakly against this.  This is something that should have been argued before Kokkos 3.2.
Any code that does
```C++
#ifdef KOKKOS_ENABLE_PROFILING
Kokkos::Profiling::pushRegion("Label");
#endif
```
is broken.  I think changing our mind makes more harm than it helps.

**Comment by DavidPoliakoff** [comment]
Any opposition to my closing this?

**Pull request closed without merging**
