### PR TITLE
VERSION_GREATER_EQUAL is only in CMake 3.7

### PR DESCRIPTION
**Pull request by ibaned**

### CODE REVIEW

**Comment by mhoemmen** [comment]
@ibaned ugh, seriously? sorry about that. Thanks for fixing this! :D

**Comment by mhoemmen** [comment]
@ibaned Oops, I thought this was Trilinos, never mind ;-)

**Comment by ibaned** [comment]
Haha yea I wrote this code :)
Still, might want to look over the Tpetra checks and see if they use this feature

**Comment by mhoemmen** [comment]
@ibaned Looks like Trilinos is free of `VERSION_GREATER_EQUAL`; thanks!

**Pull request merged**
