### PR TITLE
Add implementations of create_mirror* taking execution space parameters

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes: #4604

### CODE REVIEW

**Comment by PhilMiller** [comment]
This doesn't cover the overloads that currently take no memory space parameter, since likely arguments would potentially be ambiguous

**Review by crtrott — CHANGES_REQUESTED** [review]
Ah I think we need to do this differently: i.e. make Kokkos::Device<E,M> actually be able to hold two members (an ExecutionSpace instance and MemorySpace instance) not handing two different ones. In particular since currently you can already hand an execution space to create_mirror* I think.

**Comment by PhilMiller** [comment]
I don't think a single `Device` argument would really make sense here, though I agree that the implementation I've given is also unfortunate.

The challenge is that there's a distinction of the memory space parameter, indicating where the data is supposed to end up, from the execution spaces parameter, indicating who's responsible for getting it there, and how any transfer would be synchronized and sequenced.

**Comment by PhilMiller** [comment]
There's a quasi-philosophical question that comes with this. Two instances of an execution space can clearly be meaningfully distinct, in having e.g. different CUDA streams. Does Kokkos currently support, and/or want to support, distinct instances of memory spaces? That would seem to be necessary if there's a desire to support multiple devices in a single process, for instance. I don't know how the remote space or resilience research projects approach this. It would also help someone wanting to implement a more hands-on approach to NUMA

**Comment by PhilMiller** [comment]
From discussion
- the allocation must be synchronous to return a `View` with a `data` pointer
- Given `WithoutInitializing`, the subsequent copy can be done asynchronously with `deep_copy(exec, copy, source)`

**Pull request closed without merging**
