### PR TITLE
Release 4.5.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Trilinos snapshot PR: https://github.com/trilinos/Trilinos/pull/13679

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Comment by ndellingwood** [comment]
CI failure summary:

**jenkins/pr-merge CUDA-11.0-NVCC-RDC** - pipeline issue unrelated to PR, but occurred during Build-1 stage
```
Found unhandled java.io.IOException exception:

Failed to run image '0b9fa197e82ccfad593e00da77c11eaf95686fc4'. Error: docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running prestart hook #1: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'

nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.
...
```

**ci/gitlab-ci INTEL-DATA-CENTER-MAX-1100**: - various `Native API failed` test failures, unrelated to PR
```
6: [ RUN      ] sycl.mdrange_parallel_reduce_primitive_types
6: unknown file: Failure
6: C++ exception with description "There was a synchronous SYCL error:
6: Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)" thrown in the test body.
6: [  FAILED  ] sycl.mdrange_parallel_reduce_primitive_types (9785 ms)
...
```

**Comment by ndellingwood** [comment]
This will need update from PR https://github.com/kokkos/kokkos/pull/7626 after it is merged

**Comment by ndellingwood** [comment]
Updated to include https://github.com/kokkos/kokkos/pull/7626

**Comment by ndellingwood** [comment]
**jenkins/pr-merge HIP-ROCm-5.2** - docker build failed, unrelated to this PR
```
E: The repository 'https://repo.radeon.com/amdgpu/22.20/ubuntu focal Release' does not have a Release file.

The command '/bin/sh -c apt-get update && apt-get install -y         kmod         wget         ccache         file         &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by ndellingwood** [comment]
Trilinos PR https://github.com/trilinos/Trilinos/pull/13679 with snapshots passed, this is ready for final approvals, merge, tagging

**Pull request merged**
