### PR TITLE
Compile check for LayoutStride View construction

### PR DESCRIPTION
**Pull request by vqd8a**
Address #1597.
Very first solution: added a ```static_assert``` in Kokkos_View.hpp to resolve the issue.
@crtrott Please remind me what you mentioned about adding a check of regular and irregular layout. Thanks.

### CODE REVIEW

**Comment by ibaned** [comment]
According to Travis, this `static_assert` fails in some of our unit tests. Either the unit tests are wrong or the assert is wrong:
```
In file included from /home/travis/build/kokkos/kokkos/core/src/Kokkos_Parallel.hpp:52:0,
                 from /home/travis/build/kokkos/kokkos/core/src/Kokkos_Serial.hpp:55,
                 from /home/travis/build/kokkos/kokkos/core/src/Kokkos_Core.hpp:53,
                 from /home/travis/build/kokkos/kokkos/core/unit_test/TestTemplateMetaFunctions.hpp:44,
                 from /home/travis/build/kokkos/kokkos/core/unit_test/serial/TestSerial_Other.cpp:46:
/home/travis/build/kokkos/kokkos/core/src/Kokkos_View.hpp: In instantiation of ‘Kokkos::View<DataType, Properties>::View(const Label&, typename std::enable_if<Kokkos::Impl::is_view_label<Label>::value, const long unsigned int>::type, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with Label = char [1]; DataType = long int**; Properties = {Kokkos::LayoutTileLeft<1u, 1u, true>, Kokkos::Serial}; typename std::enable_if<Kokkos::Impl::is_view_label<Label>::value, const long unsigned int>::type = const long unsigned int; size_t = long unsigned int]’:
/home/travis/build/kokkos/kokkos/core/unit_test/TestTile.hpp:129:59:   required from ‘void TestTile::test(size_t, size_t) [with Space = Kokkos::Serial; unsigned int N0 = 1u; unsigned int N1 = 1u; size_t = long unsigned int]’
/home/travis/build/kokkos/kokkos/core/unit_test/TestTile.hpp:145:48:   required from here
/home/travis/build/kokkos/kokkos/core/src/Kokkos_View.hpp:2203:7: error: static assertion failed: Layout input was not provided for LayoutStride. Pass a LayoutStride object instead!
       static_assert ( is_layout_left || is_layout_right , "Layout input was not provided for LayoutStride. Pass a LayoutStride object instead!\n" );
       ^
```

**Comment by crtrott** [comment]
I think what is a "is_regular" tag or bool enum. Which means it is fully defined by just dimensions.

**Comment by crtrott** [comment]
`is_regular`
`is_normal`
`is_extent_constructible`
???

**Comment by vqd8a** [comment]
Using is_regular in [Kokkos_Layout.hpp](https://github.com/kokkos/kokkos/blob/issue-1597/core/src/Kokkos_Layout.hpp) for now.

**Comment by crtrott** [comment]
We need a unit test for this.

**Comment by crtrott** [comment]
Never mind this was the wrong pull request.

**Comment by crtrott** [comment]
SpotCheck passed:
```
Running on machine: apollo
Repository Status:  30132573f0cd69b9172beab9c962a5190229c8d9 Merge branch 'develop' into issue-1597


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/9.1
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=124 run_time=460
clang-6.0-Cuda_Pthread-release build_time=212 run_time=301
cuda-9.1-Cuda_OpenMP-release build_time=265 run_time=188
gcc-4.8.4-OpenMP-release build_time=95 run_time=142
gcc-4.8.4-Pthread-release build_time=90 run_time=309
gcc-5.3.0-Serial-release build_time=104 run_time=182
intel-16.0.1-OpenMP-release build_time=302 run_time=171
```

is_regular is probably not a good name. I just figured out that "regular" is a concept with meaning in C++. How about:
```
is_trivially_constructible
is_dimension_constructible
is_basic_constructible
```

Or full alternative: can we do a static assert on something like decltype(Layout(dimensions...)) or so.

**Comment by mhoemmen** [comment]
I vote for `is_extent_constructible` -- e.g., it's possible to construct one of those Hilbert curve layouts just from its dimensions

**Comment by crtrott** [comment]
Vote came out for is_extent_constructible

**Comment by vqd8a** [comment]
```is_extent_constructible``` has been updated.

**Comment by ibaned** [comment]
Will be merged after a new spot check

**Pull request merged**
