### PR TITLE
Setup docker environment for developers

### PR DESCRIPTION
**Pull request by lifflander**
I have found that using docker for development really increases my productivity as the environmental management becomes easier. I've written a baseline GNU, ubuntu 18.04 docker file that fetches the required packages, installs cmake, and then builds/tests kokkos. I noticed that the docker files that currently exist don't actually build/install kokkos and aren't set up to be good for development.

After writing the docker file, I wrote a docker-compose yaml file that can run the docker container interactively with the host using delegated volumes, which keeps the "kokkos" directory on the host in sync with the container's file system. This allows you to easily edit on the host and then build/test/debug inside the container. 

The `docker-compose.yml` uses a `.env` file to set some default variables. I realize that having these in the top directory might not be desired, but if we put them there it's much easily to run without having the specify the path for them every time when running docker-compose. Any comments on whether that's acceptable would be great to hear.

Finally, in my other project, we have docker files with several linux distros, across clang/intel/gnu/cuda and on different architectures (using emulation). If it's helpful, I can expand the options or work across a lot of other platforms.

### CODE REVIEW

**Comment by dalg24** [comment]
Add to whitelist

**Review by dalg24 — CHANGES_REQUESTED** [review]
Please edit your PR and make it against the `develop` branch

**Comment by lifflander** [comment]
> Please edit your PR and make it against the `develop` branch

Done, sorry about that... didn't realize I was wasn't on develop by default on my fork!

**Review by dalg24 — COMMENTED** [review]
Generally we don't add to the main repo individual developer config files.  While I do see how these can be useful, they are opinionated and do not fit all.

**Comment by junghans** [comment]
Doesn't https://github.com/orgs/kokkos/packages/container/ci-containers%2Fubuntu/2368174?tag=latest already provide a pretty good container for development?

**Comment by lifflander** [comment]
@dalg24 I think the compose functionality is very useful beyond a plain container, but I'll just keep it in my own fork.

**Pull request closed without merging**
