### PR TITLE
PGI Compiler fix

### PR DESCRIPTION
**Pull request by ndellingwood**
This PR is an attempt to fix build errors on SKX arch with
PGI 17.10 and 18.7 compilers due to problems with intrisics.

### CODE REVIEW

**Comment by ndellingwood** [comment]
When trying to compile with Skylake SKX arch and PGI 17.10 and 18.7 compilers I ran into errors like this:

```
/home/projects/x86-64/pgi/2017/17.10.0/linux86-64/17.10/bin/pgc++  -I./ -I/ascldap/users/ndellin/kokkos-testing/core/src -I/ascldap/users/ndellin/kokkos-testing/containers/src -I/ascldap/users/ndellin/kokkos-testing/algorithms/src -I/ascldap/users/ndellin/kokkos-testing/core/src/eti --c++11 -I/ascldap/users/ndellin/kokkos-testing/tpls/gtest -I/ascldap/users/ndellin/kokkos-testing/core/unit_test -O3  -c /ascldap/users/ndellin/kokkos-testing/core/src/impl/Kokkos_HostSpace.cpp
"/home/projects/x86-64/pgi/2017/17.10.0/linux86-64/17.10/include/immintrin.h",
          line 47: error: expected an identifier
  ATTRIBUTE "C"
            ^

"/home/projects/x86-64/pgi/2017/17.10.0/linux86-64/17.10/include/immintrin.h",
          line 47: error: inline specifier allowed on function declarations
          only
  ATTRIBUTE "C"
  ^

"/home/projects/x86-64/pgi/2017/17.10.0/linux86-64/17.10/include/immintrin.h",
          line 70: error: expected an expression
    typedef struct {
    ^

"/home/projects/x86-64/pgi/2017/17.10.0/linux86-64/17.10/include/immintrin.h",
          line 73: error: expected a "}"
    } __attribute__((aligned(32))) __m256;
                                         ^

"/home/projects/x86-64/pgi/2017/17.10.0/linux86-64/17.10/include/immintrin.h",
          line 131: error: inline specifier allowed on function declarations
          only
    ATTRIBUTE __m256 __ATTR_AVX__ _mm256_add_ps(__m256, __m256);
    ^
```

Apparently this issue with `immintrin.h` was documented with an issue number according to this [PGI user forum thread](https://www.pgroup.com/userforum/viewtopic.php?t=5857&sid=03b93828595af6797e10f865b8ed0e11)

@nmhamster do the changes in this PR seem reasonable for a fix?

**Comment by ndellingwood** [comment]
Adding @crtrott

**Comment by dalg24** [comment]
@nmhamster Please review

@ndellingwood Please resolve the conflicts (clang-format...)

**Comment by crtrott** [comment]
@nmhamster thanks. @ndellingwood if you can resolve the conflicts we can merge this.

**Comment by ndellingwood** [comment]
I'm closing this PR in favor of #2261 which has the changes applied on top of the develop branch post-clang-format.

**Pull request closed without merging**
