### PR TITLE
Kokkos:  Fix SFINAE logic for create_mirror() for specialized types

### PR DESCRIPTION
**Pull request by etphipp**
This reintroduces the SFINAE logic of only allowing the base implementations of
create_mirror() work where ViewTraits<>::specialize == void, to resolve
ambiguous overload errors in Sacado/Stokhos.  Goes along with changes in Sacado/Stokhos
to mirror the SFINAE logic here, as well as add overloads for Kokkos::Impl::WithoutInitializing_t.

This partially reverts changes in PR #4562, so its effects will have to be tested on the builds
giving rise to that PR.

### CODE REVIEW

**Comment by etphipp** [comment]
For @ndellingwood

**Comment by masterleinad** [comment]
@etphipp Do the changes here and the ones to `Sacado/Stokhos` (is there a pull request for those) resolve #4662?

**Comment by ndellingwood** [comment]
@masterleinad the corresponding sacado+stokhos changes will be pushed to the kokkos-promotion branch of Trilinos

The builds are failing with output:
```
/Users/runner/work/kokkos/kokkos/core/src/Kokkos_CopyViews.hpp:3213:40: error: no type named 'memory_space' in 'Kokkos::Impl::WithoutInitializing_t'
  using memory_space = typename Space::memory_space;
                       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/runner/work/kokkos/kokkos/core/src/Kokkos_CopyViews.hpp:3314:20: note: in instantiation of template class 'Kokkos::Impl::MirrorType<Kokkos::Impl::WithoutInitializing_t, int *, Kokkos::Threads>' requested here
    typename Impl::MirrorType<Space, T, P...>::view_type>
                   ^
/Users/runner/work/kokkos/kokkos/core/unit_test/tools/TestWithoutInitializing.cpp:60:13: note: while substituting deduced template arguments into function template 'create_mirror' [with Space = Kokkos::Impl::WithoutInitializing_t, T = int *, P = <Kokkos::Threads>]
            Kokkos::create_mirror(Kokkos::WithoutInitializing, device_view);
            ^
```

@masterleinad do you have a suggestion to reconcile the changes to reintroduce the sfinae logic with the build errors here?

**Comment by masterleinad** [comment]
```
index 2a6b3a1f8..6acfc9e03 100644
--- a/core/src/Kokkos_CopyViews.hpp
+++ b/core/src/Kokkos_CopyViews.hpp
@@ -3307,11 +3307,11 @@ create_mirror(
   return Impl::create_mirror(v, wi);
 }
 
-template <class Space, class T, class... P>
-std::enable_if_t<
+template <class Space, class T, class... P, 
+  typename Enable = std::enable_if_t<
     Kokkos::is_space<Space>::value &&
-    std::is_same<typename ViewTraits<T, P...>::specialize, void>::value,
-    typename Impl::MirrorType<Space, T, P...>::view_type>
+    std::is_same<typename ViewTraits<T, P...>::specialize, void>::value>>
+typename Impl::MirrorType<Space, T, P...>::view_type
 create_mirror(
     Space const& space, Kokkos::View<T, P...> const& v) {
   return Impl::create_mirror(space, v);
```
seems to work. We still need to fix indentation, though.

**Comment by etphipp** [comment]
I'm working on fixing those errors.

**Comment by etphipp** [comment]
> @etphipp Do the changes here and the ones to `Sacado/Stokhos` (is there a pull request for those) resolve #4662?

Yes, I believe so.

**Review by masterleinad — APPROVED** [review]
Looks good to me. I could verify that my Trilinos reproducer from #4662 works with this (and types in `Kokkos` are not `specialized` anyway).

**Comment by masterleinad** [comment]
The indentation we need is
``` diff
diff --git a/core/src/Kokkos_CopyViews.hpp b/core/src/Kokkos_CopyViews.hpp
index fb423683e..827d001ef 100644
--- a/core/src/Kokkos_CopyViews.hpp
+++ b/core/src/Kokkos_CopyViews.hpp
@@ -3302,8 +3302,8 @@ template <class T, class... P>
 std::enable_if_t<
     std::is_same<typename ViewTraits<T, P...>::specialize, void>::value,
     typename Kokkos::View<T, P...>::HostMirror>
-create_mirror(
-    Kokkos::Impl::WithoutInitializing_t wi, Kokkos::View<T, P...> const& v) {
+create_mirror(Kokkos::Impl::WithoutInitializing_t wi,
+              Kokkos::View<T, P...> const& v) {
   return Impl::create_mirror(v, wi);
 }
 
@@ -3312,8 +3312,7 @@ template <class Space, class T, class... P,
 std::enable_if_t<
     std::is_same<typename ViewTraits<T, P...>::specialize, void>::value,
     typename Impl::MirrorType<Space, T, P...>::view_type>
-create_mirror(
-    Space const& space, Kokkos::View<T, P...> const& v) {
+create_mirror(Space const& space, Kokkos::View<T, P...> const& v) {
   return Impl::create_mirror(space, v);
 }

@@ -3322,9 +3321,8 @@ template <class Space, class T, class... P,
 std::enable_if_t<
     std::is_same<typename ViewTraits<T, P...>::specialize, void>::value,
     typename Impl::MirrorType<Space, T, P...>::view_type>
-create_mirror(
-    Kokkos::Impl::WithoutInitializing_t wi, Space const& space,
-    Kokkos::View<T, P...> const& v) {
+create_mirror(Kokkos::Impl::WithoutInitializing_t wi, Space const& space,
+              Kokkos::View<T, P...> const& v) {
   return Impl::create_mirror(space, v, wi);
 }
```

**Comment by dalg24** [comment]
Retest this please

**Review by crtrott — APPROVED** [review]

**Pull request merged**
