### PR TITLE
Make KOKKOS_OPENMPTARGET_FEATURE_LEVEL a cached variable

### PR DESCRIPTION
**Pull request by scottbiersdorff**
Elevate the variable KOKKOS_OPENMPTARGET_FEATURE_LEVEL to a cached variable to
allow the user to configure which feature level should be tested.

### CODE REVIEW

**Comment by masterleinad** [comment]
What is the motivation for this pull request?

**Comment by dalg24** [comment]
> Elevate the variable KOKKOS_OPENMPTARGET_FEATURE_LEVEL to a cached variable to
> allow the user to configure which feature level should be tested.

THE `<BACKEND>_FEATURE_LEVEL` variable are not intended to be changed at configure time.  They are a way for backend developers to incrementally enable a number of tests because our main test suite is virtually impossible to use at early stages of development.

**Comment by scottbiersdorff** [comment]
@dalg24 For the same reason this as this variable is helpful for backend developers to enable different tests, external developer can use it to select the OpenMP Feature level supported by their given compiler or runtime and build the appropriate tests.

**Comment by dalg24** [comment]
> @dalg24 For the same reason this as this variable is helpful for backend developers to enable different tests, external developer can use it to select the OpenMP Feature level supported by their given compiler or runtime and build the appropriate tests.

You may re-open to see if you get more traction with other developers.  One other issue I see with the changes you suggest is an asymmetry because you expose that variable for on backend but not the others.

Also.  To make sure I understand your motivation.  Did you have to lower the feature level because your compiler did not support the level we had set?

**Comment by DavidPoliakoff** [comment]
I'd say rename them IMPL to show they're not for standard users, but I don't think it's unreasonable to expose this for compiler/runtime developers and the like. So rename them IMPL, do the same thing for every backend, and I'd be in favor.

**Pull request closed without merging**
