### PR TITLE
Use different EBO workaround for MSVC (rebased)

### PR DESCRIPTION
**Pull request by masterleinad**
#3932 rebased on top of #3832.

### CODE REVIEW

**Comment by masterleinad** [comment]
Seems to work on `Summit` for me.

**Comment by ndellingwood** [comment]
Serial xl/16.1.1 build compiled for me without errors. Unrelated to changes in this PR, this warning was output which will error with `-Werror`:

```
/ascldap/users/ndellin/kokkos-testing/core/unit_test/tools/printing-tool.cpp:11:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto _pos        = _cmd.find_last_of('/');
```

**Comment by masterleinad** [comment]
> Unrelated to changes in this PR, this warning was output which will error with `-Werror`: [...]

Can you try adding
```diff
diff --git a/core/unit_test/CMakeLists.txt b/core/unit_test/CMakeLists.txt
index b16764f97..5e6e56917 100644
--- a/core/unit_test/CMakeLists.txt
+++ b/core/unit_test/CMakeLists.txt
@@ -704,6 +704,7 @@ KOKKOS_ADD_ADVANCED_TEST( UnitTest_PushFinalizeHook_terminate
       kokkosprinter-tool SHARED
       SOURCES tools/printing-tool.cpp
     )
+    TARGET_COMPILE_FEATURES(kokkosprinter-tool PUBLIC cxx_std_14)
 
     KOKKOS_ADD_TEST_EXECUTABLE(
       ProfilingAllCalls
```
?

**Comment by ndellingwood** [comment]
@masterleinad your suggested change resolved the warning, thanks. When I added `-Werror` it triggered another pre-existing issue 

```
/ascldap/users/ndellin/kokkos-testing/core/unit_test/TestComplex.hpp:417:9: error: unused type alias 'RealType' [-Werror,-Wunused-local-typedef]
  using RealType = double;
```

resolved by moving the `using` statement within the if-guard

```diff
diff --git a/core/unit_test/TestComplex.hpp b/core/unit_test/TestComplex.hpp
index 8ec2dc7..1218170 100644
--- a/core/unit_test/TestComplex.hpp
+++ b/core/unit_test/TestComplex.hpp
@@ -414,13 +414,13 @@ TEST(TEST_CATEGORY, complex_special_funtions) {
 TEST(TEST_CATEGORY, complex_io) { testComplexIO(); }
 
 TEST(TEST_CATEGORY, complex_trivially_copyable) {
-  using RealType = double;
 
   // Kokkos::complex<RealType> is trivially copyable when RealType is
   // trivially copyable
   // Simply disable the check for IBM's XL compiler since we can't reliably
   // check for a version that defines relevant functions.
 #if !defined(__ibmxl__)
+  using RealType = double;
   // clang claims compatibility with gcc 4.2.1 but all versions tested know
   // about std::is_trivially_copyable.
   ASSERT_TRUE(std::is_trivially_copyable<Kokkos::complex<RealType>>::value ||
```

**Comment by masterleinad** [comment]
@ndellingwood You should create a pull request since you already have the necessary changes. :slightly_smiling_face:

**Comment by ndellingwood** [comment]
I put in #3927 with the warning fixes

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Review by nmm0 — APPROVED** [review]
Looks good to me. This actually seems to solve #3936 but I need to test on more compilers to be sure before closing that issue. Also the code is much more readable without having to do the MSVC workaround.

**Pull request merged**
