### PR TITLE
Master release 4.4.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Comment by ndellingwood** [comment]
'CUDA-12.2-NVHPC-AS-HOST-COMPILER' failure:
```
/var/jenkins/workspace/Kokkos_PR-7333/bin/nvcc_wrapper: line 659: 28572 Segmentation fault      (core dumped) TMPDIR=${temp_dir} $nvcc_command
make[2]: *** [core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_OpenMP.dir/build.make:1070: core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_OpenMP.dir/openmp/TestOpenMP_SpaceAwareAccessor.cpp.o] Error 139
make[2]: *** Waiting for unfinished jobs....
[ 62%] Building CXX object core/unit_test/headers_self_contained/CMakeFiles/Kokkos_HeaderSelfContained_Kokkos_ScratchSpace_hpp.dir/tstHeader.cpp.o
[ 62%] Building CXX object core/unit_test/headers_self_contained/CMakeFiles/Kokkos_HeaderSelfContained_Kokkos_Swap_hpp.dir/tstHeader.cpp.o
/var/jenkins/workspace/Kokkos_PR-7333/bin/nvcc_wrapper: line 659: 28740 Segmentation fault      (core dumped) TMPDIR=${temp_dir} $nvcc_command
make[2]: *** [core/unit_test/headers_self_contained/CMakeFiles/Kokkos_HeaderSelfContained_Kokkos_Swap_hpp.dir/build.make:76: core/unit_test/headers_self_contained/CMakeFiles/Kokkos_HeaderSelfContained_Kokkos_Swap_hpp.dir/tstHeader.cpp.o] Error 139
make[1]: *** [CMakeFiles/Makefile2:3523: core/unit_test/headers_self_contained/CMakeFiles/Kokkos_HeaderSelfContained_Kokkos_Swap_hpp.dir/all] Error 2
```
I'm assuming the core dump might be due to `TMPDIR` filling up, in any case this should not be related to the PR changes?


'OPENACC-NVHPC-CUDA-12.2' failure
```
The following tests FAILED:

	  3 - Kokkos_CoreUnitTest_OpenACC (Subprocess aborted)
```

Added details
```
3: [ RUN      ] openacc.exec_space_thread_safety_range_reduce
3: Kokkos::Impl::SharedAllocationRecord '' failed decrement count = 0
3: terminate called after throwing an instance of 'std::runtime_error'
3:   what():  Kokkos::Impl::SharedAllocationRecord failed decrement count
 3/22 Test  #3: Kokkos_CoreUnitTest_OpenACC ..........................Subprocess aborted***Exception:  29.76 sec
```

The OpenACC thread-safety tests were recently disabled #7306 and #7318 , but those changes are not part of this PR

**Review by crtrott — CHANGES_REQUESTED** [review]
Need to update the README (version and link) don't care if we do it in the Trilinos snapshot

**Comment by dalg24** [comment]
> Need to update the README (version and link) don't care if we do it in the Trilinos snapshot

Really not worth the trouble

**Review by crtrott — APPROVED** [review]
Ok whatever :-) I don't really care about the release actually, if develop has it thats fine with me (though I guess not Damien ;-) )

**Comment by ndellingwood** [comment]
Trilinos PR https://github.com/trilinos/Trilinos/pull/13446 has passed

**Pull request merged**
