### PR TITLE
Fix HIP RDC build which results in duplicated symbols

### PR DESCRIPTION
**Pull request by crtrott**

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
I'd like to see this added in our CI

**Comment by crtrott** [comment]
One issue is that we get this:
```
"Cannot create GlobalVar Obj"
Aborted
```
when the lock arrays are copied over during initialization. Not sure whats going on with that.

**Comment by masterleinad** [comment]
> One issue is that we get this:
> 
> ```
> "Cannot create GlobalVar Obj"
> Aborted
> ```
> 
> when the lock arrays are copied over during initialization. Not sure whats going on with that.

MIght be related to https://github.com/ROCm-Developer-Tools/HIP/issues/2109.

**Comment by masterleinad** [comment]
You will need to run the indentation script.

**Comment by kmoza** [comment]
I checked out the `fix-hip-rdc` branch and tried to build it on my machine and it still fails with error as below.

Build cmd : `cmake -DKokkos_ARCH_ZEN2=ON -DKokkos_ARCH_VEGA906=ON -DCMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc -DKokkos_ENABLE_HIP=ON -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD=14 -DCMAKE_INSTALL_PREFIX=../install -DKokkos_ENABLE_HIP_RELOCATABLE_DEVICE_CODE=ON -DCMAKE_CXX_FLAGS="-O3 -DNDEBUG --amdgpu-target=gfx906" -DKokkos_ENABLE_EXAMPLES=ON ..`

image

**Comment by Rombur** [comment]
@kmoza Yes, this PR is not enough to compile the HIP backend with RDC. I have a branch that compiles with RDC but it seems that some atomic operations hang. I am still trying to debug it.

**Comment by dalg24** [comment]
Superseded by #4553

**Pull request closed without merging**
