### PR TITLE
Provide new public headers `<Kokkos_Clamp.hpp>` and `<Kokkos_MinMax.hpp>`

### PR DESCRIPTION
**Pull request by aprokop**
These are useful universal utility function that are helpful to downstream apps. Right now, the apps' choice is to either write one of their own, or bring the full `Kokkos_Core.hpp`.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks reasonable to me.

**Review by crtrott — DISMISSED** [review]
I want us to think about the header name if its public.

**Comment by ldh4** [comment]
Perhaps these functions can be moved to a related and already public header (i.e. `Kokkos_MathmaticalFunctions.hpp`).

**Comment by dalg24** [comment]
I implemented what got consensus at the developer meeting which was split it into a `<Kokkos_Clamp.hpp>` and a `<Kokkos_MinMax.hpp>` header.

**Review by ldh4 — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by dalg24** [comment]
Failures are unrelated (machines out of disk space)

**Pull request merged**
