### PR TITLE
Cleanup unnecessary changes to GLOBAL_SET usage to match develop

### PR DESCRIPTION
**Pull request by jjwilke**
@ndellingwood Cleans up my mess and better matches release candidate to develop

### CODE REVIEW

**Comment by ndellingwood** [comment]
I already updated the snapshot to the Trilinos PR with release-candidate-3.0, if test results indicate we need to make more changes in kokkos we can merge this in then, otherwise let's hold off for now.

**Comment by jjwilke** [comment]
Not necessary to merge. Everything is still functionally correct - just a bit messier to read.

**Comment by crtrott** [comment]
Then lets leave this out. This is already in develop right?

**Comment by ndellingwood** [comment]
> Then lets leave this out. This is already in develop right?

@crtrott yes. this should be closed, I can clean up any merge conflicts when we get to the final step of merging master back into develop.

**Pull request closed without merging**
