### PR TITLE
change restrict keyword to always be emitted per issue #1922

### PR DESCRIPTION
**Pull request by rfbird**

### CODE REVIEW

**Comment by crtrott** [comment]
Running spot check now.

**Comment by crtrott** [comment]
This seems to introduce tons of warnings related to ignored return type qualifier. I am checking if I can resolve those.

**Comment by crtrott** [comment]
Can you guys check whether this still does what you want?

**Comment by ibaned** [comment]
#1922

**Comment by ibaned** [comment]
Is it really necessary to change those return types?

**Comment by ndellingwood** [comment]
Testing on kokkos-dev now.

**Comment by ndellingwood** [comment]
@ibaned  spot-check passed on kokkos-dev.

The clang and gcc runtimes were especially long, will need to go back and look if this is preexisting...

```
Running on machine: kokkos-dev
Repository Status:  76cd481e2146e0fdf884641369ef56bba270b27c Fix warnings


Going to test compilers:  gcc/5.3.0 gcc/7.3.0 intel/17.0.1 clang/4.0.1 cuda/8.0.44
Testing compiler gcc/5.3.0
Testing compiler gcc/7.3.0
  Starting job gcc-5.3.0-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler intel/17.0.1
  Starting job gcc-7.3.0-Serial-release
  PASSED gcc-7.3.0-Serial-release
Testing compiler clang/4.0.1
  Starting job intel-17.0.1-OpenMP-release
  PASSED intel-17.0.1-OpenMP-release
Testing compiler cuda/8.0.44
  Starting job clang-4.0.1-Pthread_Serial-release
  PASSED clang-4.0.1-Pthread_Serial-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-release build_time=210 run_time=2001
cuda-8.0.44-Cuda_OpenMP-release build_time=614 run_time=643
gcc-5.3.0-OpenMP-release build_time=211 run_time=178
gcc-7.3.0-Serial-release build_time=156 run_time=1162
intel-17.0.1-OpenMP-release build_time=2594 run_time=1703
```

**Comment by rfbird** [comment]
> Can you guys check whether this still does what you want?

Per this file here: https://github.com/rfbird/Cabana/blob/performance_tests/core/performance_test/peakflops/02_kokkos_simple_view.cpp

The fix isn't recovering the performance we were hoping for, and it's slower than when we manually generate the restricts ourselves. A while back when we had a hacky fork of Kokkos we were able to get the above to perform well, but right now we're not seeing it (vec report is pretty clean, but it's not behaving the same as the manual restrict one, and the generated asm is writing back to memory when it doesn't strictly have to)

**Pull request merged**
