### PR TITLE
commit Christian's fix

### PR DESCRIPTION
**Pull request by ibaned**
to #1991

### CODE REVIEW

**Comment by ibaned** [comment]
```
Running on machine: sems
Repository Status:  d47fe48f2f7dff01cdc41481ebf7c5bac5b23d27 Merge remote-tracking branch 'origin/develop' into fix-1991


Going to test compilers:  gcc/5.3.0 gcc/7.3.0 intel/17.0.1 clang/4.0.1 cuda/8.0.44
Testing compiler gcc/5.3.0
  Starting job gcc-5.3.0-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler gcc/7.3.0
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-7.3.0-Serial-release
  PASSED gcc-7.3.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-7.3.0-Serial-hwloc-release
  PASSED gcc-7.3.0-Serial-hwloc-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED intel-17.0.1-OpenMP-release
Testing compiler clang/4.0.1
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  Starting job clang-4.0.1-Pthread_Serial-release
  PASSED clang-4.0.1-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-4.0.1-Pthread_Serial-hwloc-release
  PASSED clang-4.0.1-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-4.0.1-Pthread_Serial-hwloc-release build_time=203 run_time=271
clang-4.0.1-Pthread_Serial-release build_time=204 run_time=440
cuda-8.0.44-Cuda_OpenMP-release build_time=561 run_time=625
gcc-5.3.0-OpenMP-hwloc-release build_time=185 run_time=111
gcc-5.3.0-OpenMP-release build_time=183 run_time=106
gcc-7.3.0-Serial-hwloc-release build_time=155 run_time=189
gcc-7.3.0-Serial-release build_time=153 run_time=186
intel-17.0.1-OpenMP-hwloc-release build_time=2558 run_time=1189
intel-17.0.1-OpenMP-release build_time=2583 run_time=1188
```

**Comment by crtrott** [comment]
Args just a I approved I noticed the SHAs don't match ?

**Comment by ibaned** [comment]
Hmm it looks like I didn't push the merge of develop into the PR branch to bring in compile error fixes for the local deep copy stuff:
```
commit d47fe48f2f7dff01cdc41481ebf7c5bac5b23d27
Merge: 74f1c99 41fcf93
Author: Daniel Alejandro Ibanez <daibane@sandia.gov>
Date:   Thu Feb 21 14:18:21 2019 -0700

    Merge remote-tracking branch 'origin/develop' into fix-1991

```
Pretty safe since its merging from develop, but yes good catch

**Comment by dholladay00** [comment]
So am I correct assuming there is a specific reason that an `int64_t` is used on line 1539 instead of `ptrdiff_t`?

**Pull request merged**
