### PR TITLE
Fix some 32/64 bit index issues mainly for CUDA (issue #1583)

### PR DESCRIPTION
**Pull request by crtrott**
This addresses #1583

### CODE REVIEW

**Comment by crtrott** [comment]
Can someone run the spot-check on Apollo for me? Still at conference and will be leaving in a bit for lunch.

**Comment by ndellingwood** [comment]
I'll get it started right now.

**Comment by crtrott** [comment]
Nathan repull there was a warning on some compilers.

**Comment by ndellingwood** [comment]
Repulled and restarted the spot-check.

**Comment by ndellingwood** [comment]
Cuda builds failed, the rest passed:
```
#######################################################
FAILED TESTS
#######################################################
clang-6.0-Cuda_Pthread-release (test failed)
cuda-9.1-Cuda_OpenMP-release (build failed)
```

Cuda 9.1 errors of this type:
```
/home/ndellin/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp(386): error: The closure type for a lambda ("lambda [](const int64_t &, int64_t &)->void", defined at /home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp:55) cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is an 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelReduce<lambda [](const int64_t &, int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::InvalidType, Kokkos::Cuda::execution_space>>
(386): here
            instantiation of "Kokkos::Impl::CudaParallelLaunch<DriverType, Kokkos::LaunchBounds<0U, 0U>, false>::CudaParallelLaunch(const DriverType &, const dim3 &, const dim3 &, int, cudaStream_t) [with DriverType=Kokkos::Impl::ParallelReduce<lambda [](const int64_t &, int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::InvalidType, Kokkos::Cuda::execution_space>]"
/home/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(864): here
            instantiation of "void Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerType, Kokkos::Cuda>::execute() [with FunctorType=lambda [](const int64_t &, int64_t &)->void, ReducerType=Kokkos::InvalidType, Traits=<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>]"
/home/ndellin/kokkos/core/src/Kokkos_Parallel_Reduce.hpp(889): here
            instantiation of "void Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const std::string &, const PolicyType &, const FunctorType &, ReturnType &) [with PolicyType=Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, FunctorType=lambda [](const int64_t &, int64_t &)->void, ReturnType=int64_t]"
/home/ndellin/kokkos/core/src/Kokkos_Parallel_Reduce.hpp(972): here
            instantiation of "void Kokkos::parallel_reduce(const PolicyType &, const FunctorType &, ReturnType &, Kokkos::Impl::enable_if<Kokkos::is_execution_policy<PolicyType>::value, void>::type *) [with PolicyType=Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, FunctorType=lambda [](const int64_t &, int64_t &)->void, ReturnType=int64_t]"
/home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp(57): here
            instantiation of "void Test::test_64bit<Device>() [with Device=Kokkos::Cuda]"
/home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp(119): here

/home/ndellin/kokkos/core/src/Cuda/Kokkos_CudaExec.hpp(386): error: The closure type for a lambda ("lambda [](const int64_t &, int64_t &)->void", defined at /home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp:65) cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is an 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelReduce<lambda [](const int64_t &, int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::InvalidType, Kokkos::Cuda::execution_space>>
(386): here
            instantiation of "Kokkos::Impl::CudaParallelLaunch<DriverType, Kokkos::LaunchBounds<0U, 0U>, false>::CudaParallelLaunch(const DriverType &, const dim3 &, const dim3 &, int, cudaStream_t) [with DriverType=Kokkos::Impl::ParallelReduce<lambda [](const int64_t &, int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::InvalidType, Kokkos::Cuda::execution_space>]"
/home/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(864): here
            instantiation of "void Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits...>, ReducerType, Kokkos::Cuda>::execute() [with FunctorType=lambda [](const int64_t &, int64_t &)->void, ReducerType=Kokkos::InvalidType, Traits=<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>]"
/home/ndellin/kokkos/core/src/Kokkos_Parallel_Reduce.hpp(889): here
            instantiation of "void Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const std::string &, const PolicyType &, const FunctorType &, ReturnType &) [with PolicyType=Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, FunctorType=lambda [](const int64_t &, int64_t &)->void, ReturnType=int64_t]"
/home/ndellin/kokkos/core/src/Kokkos_Parallel_Reduce.hpp(972): here
            instantiation of "void Kokkos::parallel_reduce(const PolicyType &, const FunctorType &, ReturnType &, Kokkos::Impl::enable_if<Kokkos::is_execution_policy<PolicyType>::value, void>::type *) [with PolicyType=Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, FunctorType=lambda [](const int64_t &, int64_t &)->void, ReturnType=int64_t]"
/home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp(67): here
            instantiation of "void Test::test_64bit<Device>() [with Device=Kokkos::Cuda]"
/home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp(119): here

/home/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Internal.hpp(182): error: The closure type for a lambda ("lambda [](const int64_t &)->void", defined at /home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp:71) cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is an 'extended lambda' and the flag --expt-extended-lambda is specified
          detected during:
            instantiation of "Kokkos::Impl::cuda_parallel_launch_local_memory" based on template argument <Kokkos::Impl::ParallelFor<lambda [](const int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::Cuda::execution_space>>
(186): here
            instantiation of "int Kokkos::Impl::CudaGetOptBlockSize<DriverType, false>::get_block_size(const DriverType::functor_type &, size_t, size_t, size_t) [with DriverType=Kokkos::Impl::ParallelFor<lambda [](const int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::Cuda::execution_space>]"
(134): here
            instantiation of "int Kokkos::Impl::cuda_get_opt_block_size<DriverType,Large>(const DriverType::functor_type &, size_t, size_t, size_t) [with DriverType=Kokkos::Impl::ParallelFor<lambda [](const int64_t &)->void, Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, Kokkos::Cuda::execution_space>, Large=false]"
/home/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp(422): here
            instantiation of "void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits...>, Kokkos::Cuda>::execute() const [with FunctorType=lambda [](const int64_t &)->void, Traits=<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>]"
/home/ndellin/kokkos/core/src/Kokkos_Parallel.hpp(191): here
            instantiation of "void Kokkos::parallel_for(const ExecPolicy &, const FunctorType &, const std::string &, Kokkos::Impl::enable_if<Kokkos::is_execution_policy<ExecPolicy>::value, void>::type *) [with ExecPolicy=Kokkos::RangePolicy<Kokkos::Cuda::execution_space, Kokkos::IndexType<int64_t>>, FunctorType=lambda [](const int64_t &)->void]"
/home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp(73): here
            instantiation of "void Test::test_64bit<Device>() [with Device=Kokkos::Cuda]"
/home/ndellin/kokkos/core/unit_test/TestView_64bit.hpp(119): here
```

Clang6.0 test failures (build passed):
```
[ RUN      ] threads.view_64bit
:0: : block: [336,0,0], thread: [0,32,0] Assertion `Kokkos::View ERROR: attempt to access inaccessible memory space` failed.
... // many of these Assertion statements
:0: : block: [231,0,0], thread: [0,63,0] Assertion `Kokkos::View ERROR: attempt to access inaccessible memory space` failed.
unknown file: Failure
C++ exception with description "cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /home/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available
" thrown in the test body.
[  FAILED  ] threads.view_64bit (81730 ms)
```

**Comment by crtrott** [comment]
```
Going to test compilers:  gcc/5.4.0 ibm/13.1.6 cuda/8.0.44 cuda/9.0.103
Testing compiler gcc/5.4.0
  Starting job gcc-5.4.0-OpenMP-release
  PASSED gcc-5.4.0-OpenMP-release
  Starting job gcc-5.4.0-Serial-release
  PASSED gcc-5.4.0-Serial-release
Testing compiler ibm/13.1.6
  Starting job gcc-5.4.0-OpenMP_Serial-release
  PASSED gcc-5.4.0-OpenMP_Serial-release
  Starting job ibm-13.1.6-OpenMP-release
  PASSED ibm-13.1.6-OpenMP-release
  Starting job ibm-13.1.6-Serial-release
  PASSED ibm-13.1.6-Serial-release
```

**Comment by crtrott** [comment]
The test probably needs a protection for lambdas being enabled, not sure why its not there yet.

**Comment by ndellingwood** [comment]
@crtrott doesn't test_all_sandia enable lambda support for testing with Cuda? 
FWIW, I ran into similar errors when testing the BlockCrs unit tests in KokkosKernels, before replacing the lambda with a functor, but I'm not sure if lambda support is provided for KokkosKernels testing.

**Comment by ndellingwood** [comment]
Commenting out part of the tests see if I can triage it...

**Comment by ndellingwood** [comment]
@crtrott like you mentioned about the lambda guards, adding `#if defined( KOKKOS_ENABLE_CXX11_DISPATCH_LAMBDA )` fixes the Cuda compilation errors, but I cannot push directly to a PR, can you update the PR and I can retest?

**Comment by ndellingwood** [comment]
@crtrott think I chased down the test failure with threads - it looks like there is a copy/paste error in the backend/Test{Backend}_Category.hpp files, they are all if-guarded as 
```
#ifndef KOKKOS_TEST_THREADS_HPP
#define KOKKOS_TEST_THREADS_HPP
```

Changing `THREADS` to the appropriate backend fixed the issue for me. I can update this PR and resubmit, I can't push directly to this PR.

**Comment by ndellingwood** [comment]
If you want to give me permission to push to your fork I can try and do that, or you can update and push and I'll rerun the tests, let me know what you'd prefer.

**Comment by crtrott** [comment]
Uhh this is just on the public repo. You should have access.

**Comment by ndellingwood** [comment]
Ah, there we go. I had named my fetched branch from this PR something different (pr-1588) from the name of this PR branch (issue-1583), renaming it to match fixed it.

**Comment by ndellingwood** [comment]
Will post spot-check results from Apollo when its finished.

**Comment by ndellingwood** [comment]
Spot-check on Apollo passed
Output (nohup.out):
```
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=127 run_time=254
clang-6.0-Cuda_Pthread-release build_time=215 run_time=206
cuda-9.1-Cuda_OpenMP-release build_time=266 run_time=189
gcc-4.8.4-OpenMP-release build_time=99 run_time=107
gcc-4.8.4-Pthread-release build_time=92 run_time=207
gcc-5.3.0-Serial-release build_time=107 run_time=129
intel-16.0.1-OpenMP-release build_time=318 run_time=141
```

Branch: issue-1583 (this PR)
git log -1 (for SHA/commit info):
commit c469a4829b2a6e3c64169eaef098ee378a0d4c5c
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Wed Apr 25 17:26:42 2018 -0600

    pr-1588: Add lambda guard on test, rename Test*_Category header guards

**Comment by ibaned** [comment]
@ndellingwood are some of the tests still commented out? Is that intended?

**Comment by ndellingwood** [comment]
@ibaned no the comments are accidental from when I was looking into the threads test failure. Will push the fix and rerun spot-check, sorry for the slip.

**Comment by ndellingwood** [comment]
The clang+cuda threads test still fails...
```
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=126 run_time=438
cuda-9.1-Cuda_OpenMP-release build_time=268 run_time=194
gcc-4.8.4-OpenMP-release build_time=100 run_time=130
gcc-4.8.4-Pthread-release build_time=92 run_time=303
gcc-5.3.0-Serial-release build_time=106 run_time=168
intel-16.0.1-OpenMP-release build_time=318 run_time=163
#######################################################
FAILED TESTS
#######################################################
clang-6.0-Cuda_Pthread-release (test failed)
```

Failure:
```
[ RUN      ] threads.view_64bit
:0: : block: [279,0,0], thread: [0,32,0] Assertion `Kokkos::View ERROR: attempt to access inaccessible memory space` failed.
...
unknown file: Failure
C++ exception with description "cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered /home/ndellin/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available
" thrown in the test body.
[  FAILED  ] threads.view_64bit (86262 ms)
```

**Comment by ndellingwood** [comment]
Should have it actually fixed this time (there was missing execution_space to the RangePolicy in the new test which I accidentally had commented out testing yesterday when I checked). Did a bit more cleanup with the threads tests. The test time is pretty long:

```
[ndellin@apollo unit_test]$ ./KokkosCore_UnitTest_Threads --gtest_filter=*view_64*
Note: Google Test filter = *view_64*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from threads
[ RUN      ] threads.view_64bit
[       OK ] threads.view_64bit (104140 ms)
[----------] 1 test from threads (104140 ms total
```

**Comment by ibaned** [comment]
The same thing happened to me. It may just be because we both ran spot checks on Apollo and fought over the GPU.  I'll let you go first, hopefully with me not running then it will pass.

**Comment by ndellingwood** [comment]
@ibaned I retested just that particular test and it passed
```
[ndellin@apollo unit_test]$ ./KokkosCore_UnitTest_Cuda --gtest_filter=cuda.multi_level_scratch
Note: Google Test filter = cuda.multi_level_scratch
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from cuda
[ RUN      ] cuda.multi_level_scratch
[       OK ] cuda.multi_level_scratch (194 ms)
[----------] 1 test from cuda (194 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (194 ms total)
[  PASSED  ] 1 test.
```
Should I rerun the full spot-check? I'd rather rerun test_all_sandia for just this one case, then you can get to testing more quickly since it may be due our spot-checks fighting for resources like you mentioned.

**Comment by ibaned** [comment]
Yea, I think they were just fighting over the GPU.

**Comment by ndellingwood** [comment]
Okay, I'll kill off my spot-check restart.

**Pull request merged**
