### PR TITLE
Experimental: Restore old behavior of Trilinos_CXX_COMPILER_FLAGS

### PR DESCRIPTION
**Pull request by jjwilke**
Downstream projects now depend on incredibly fragile and specific behavior of the exported variable Trilinos_CXX_COMPILER_FLAGS from Trilinos. Rather than break this, this patch restores the behavior for now.

### CODE REVIEW

**Comment by ndellingwood** [comment]
@jjwilke can you check the CI error and confirm if it's due to this PR? 

`Failed in branch GCC-4.8.4`

Once that's resolved I'll rebuild the downstream app and relaunch integration testing.

**Comment by masterleinad** [comment]
Now, `jenkins` passes.

**Comment by ndellingwood** [comment]
@jjwilke this is breaking with Trilinos configures/builds, I'll email the configure scripts I am using for testing, here are some sample errors in case the issue is obvious based on output:

Trilinos Cuda+Serial build for downstream app (waterman):
configures fine
compilation errors like
`g++: error: unrecognized command line option ‘--diag_suppress=esa_on_defaulted_function_ignored’`

Trilinos Cuda build on Waterman (ATDM configuration)
Fails configuration
`CMakeError.log`
```
Detecting CXX [-std=c++1z] compiler features failed to compile with the following output:
Change Dir: /ascldap/users/ndellin/IntegrationTests/SubmittedTests-final/CMakeFiles/CMakeTmp

Run Build Command:"/ascldap/users/projects/ppc64le/ninja/1.7.2/bin/ninja" "cmTC_2e34f"
[1/2] Building CXX object CMakeFiles/cmTC_2e34f.dir/feature_tests.cxx.o
FAILED: CMakeFiles/cmTC_2e34f.dir/feature_tests.cxx.o
/home/projects/ppc64le-pwr9-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx    -std=c++1z -o CMakeFiles/cmTC_2e34f.dir/feature_tests.cxx.o -c /ascldap/users/ndellin/IntegrationTests/SubmittedTests-final/CMakeFiles/feature_tests.cxx
nvcc fatal   : Value 'c++1z' is not defined for option 'std'
ninja: build stopped: subcommand failed.

Performing C++ SOURCE FILE Test HAS_TPL_BINUNTILS_STACKTRACE failed with the following output:
Change Dir: /ascldap/users/ndellin/IntegrationTests/SubmittedTests-final/CMakeFiles/CMakeTmp

Run Build Command:"/ascldap/users/projects/ppc64le/ninja/1.7.2/bin/ninja" "cmTC_d9284"
[1/2] Building CXX object CMakeFiles/cmTC_d9284.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_d9284.dir/src.cxx.o
/home/projects/ppc64le-pwr9-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx   -I/ascldap/users/projects/ppc64le/binutils/2.30.0/include -DHAS_TPL_BINUNTILS_STACKTRACE -O3 -DNDEBUG -o CMakeFiles/cmTC_d9284.dir/src.cxx.o -c src.cxx
In file included from src.cxx:11:0:
/ascldap/users/projects/ppc64le/binutils/2.30.0/include/bfd.h:35:2: error: #error config.h must be included before this header
 #error config.h must be included before this header
  ^~~~~
ninja: build stopped: subcommand failed.
```

**Comment by ndellingwood** [comment]
@jjwilke I retested and was able to configure, user-error on my part (rushing too quickly to launch jobs with test branches). There is still a discrepancy in flags between the Trilinos develop branch and when configuring with these changes.

1. With the downstream app, it still looks like the non-kokkos cxx flags are being erased:
**TrilinosConfig_install.cmake**
Trilinos develop branch 
`SET(Trilinos_CXX_COMPILER_FLAGS "  -fPIC  --std=c++11 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-lambda -arch=sm_70   -O3 -DNDEBUG")`

Trilinos kokkos-promotion branch (using this PR for kokkos)
`SET(Trilinos_CXX_COMPILER_FLAGS " -std=c++11 -expt-extended-lambda -arch=sm_70 --diag_suppress=esa_on_defaulted_function_ignored -O3 -DNDEBUG")`

Note the missing `-fPIC` when using this PR, indicating that flags were erased.


2. Waterman ATDM build
**TrilinosConfig_install.cmake**
Trilinos develop branch 
`SET(Trilinos_CXX_COMPILER_FLAGS "     --std=c++11 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-lambda -arch=sm_70   -O3 -DNDEBUG")`

Trilinos kokkos-promotion branch (using this PR for kokkos)
`SET(Trilinos_CXX_COMPILER_FLAGS " -std=c++11 -expt-extended-lambda -arch=sm_70 --diag_suppress=esa_on_defaulted_function_ignored -O3 -DNDEBUG")`

With this ATDM build compilation failed partway through, not sure if it was a testbed issue and unrelated to these changes

```
...
[266/12706] Building CXX object kokkos/core/unit_test/CMakeFiles/KokkosCore_UnitTest_Cuda.dir/cuda/TestCuda_ViewLayoutStrideAssignment.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by ndellingwood** [comment]
@jjwilke I'm also seeing this error with a Cuda build, rdc enabled, on Ride:

```
/home/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx   -I. -Ipackages/teuchos/core/src -I/ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/core/src -Ikokkos/core/src -I/ascldap/users/ndellin/trilinos/Trilinos/kokkos/core/src -Ikokkos -I/ascldap/users/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/include -I/ascldap/users/projects/ppc64le-pwr8/boost/1.65.1/gcc/7.2.0/include --relocatable-device-code=true -std=c++11 -expt-extended-lambda -lineinfo -arch=sm_37 --diag_suppress=esa_on_defaulted_function_ignored -O3 -DNDEBUG   --relocatable-device-code=true -expt-extended-lambda -lineinfo -arch=sm_37 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -std=c++11 -MD -MT packages/teuchos/core/test/TwoDArray/CMakeFiles/TeuchosCore_TwoDArrayTests.dir/TwoDArray_UnitTests.cpp.o -MF packages/teuchos/core/test/TwoDArray/CMakeFiles/TeuchosCore_TwoDArrayTests.dir/TwoDArray_UnitTests.cpp.o.d -o packages/teuchos/core/test/TwoDArray/CMakeFiles/TeuchosCore_TwoDArrayTests.dir/TwoDArray_UnitTests.cpp.o -c /ascldap/users/ndellin/trilinos/Trilinos/packages/teuchos/core/test/TwoDArray/TwoDArray_UnitTests.cpp
nvcc_wrapper - *warning* you have set multiple optimization flags (-std=c++1* or --std=c++1*), only the first is used because nvcc can only accept a single std setting
nvcc fatal   : redefinition of argument 'relocatable-device-code'
```

**Comment by ndellingwood** [comment]
@jjwilke just to confirm, this PR can be closed in favor of #2660?

**Comment by jjwilke** [comment]
Closed!

**Pull request closed without merging**
