### PR TITLE
Explicity pass template params to ZeroMemset for intel icpc compilers

### PR DESCRIPTION
**Pull request by ndellingwood**
Avoid apparent CTAD issue with older icpc intel compilers
Resolves issue https://github.com/kokkos/kokkos/issues/6775

### CODE REVIEW

**Comment by ndellingwood** [comment]
I made the change to explicitly guard and deal with the older intel icpc ctad issues. If a cleaner change is preferred I can drop the guarded path and just pass the template parameters in all cases

**Review by masterleinad — COMMENTED** [review]
Are you not running into the same problem in `Kokkos_ViewMapping.hpp`?

**Comment by ndellingwood** [comment]
> Are you not running into the same problem in `Kokkos_ViewMapping.hpp`?

@masterleinad no, the compilation error only occurred with `ZeroMemset` calls in the `Kokkos_CopyViews.hpp` header. I can apply the same changes there for consistency if you'd like

**Comment by masterleinad** [comment]
> @masterleinad no, the compilation error only occurred with `ZeroMemset` calls in the `Kokkos_CopyViews.hpp` header. I can apply the same changes there for consistency if you'd like

I'd prefer that.

**Comment by dalg24** [comment]
I would prefer specifying template parameter only where strictly necessary.

**Review by dalg24 — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by ndellingwood** [comment]
HIP-ROCM-5.2 job failed in the unit tests (I think the driver or runtime still might have issues?)
SYCL-OneAPI job failed in Shell Script stage, unclear to me what the problem was (but hopefully unrelated to this PR?)
```
Total Test time (real) = 354.77 sec
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 78849b170a737dedc8e55eb7fefb460603c4ea69e32304603a34498d1ccdf0ac
$ docker rm -f --volumes 78849b170a737dedc8e55eb7fefb460603c4ea69e32304603a34498d1ccdf0ac
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] End of Pipeline
ERROR: script returned exit code 2

GitHub has been notified of this commit’s build result

Finished: FAILURE
```

**Comment by ndellingwood** [comment]
@dalg24 @masterleinad I don't think the CI fails are related to this PR, let me know if there are any concerns

**Comment by dalg24** [comment]
I do not agree with the changes requested by Daniel and the last two commits that were pushed afterI approved.  I am waiting on others to weigh in on this.

**Comment by crtrott** [comment]
In particular with all the ifdefing I agree: only do it where strictly necessary.

**Comment by ndellingwood** [comment]
@crtrott @dalg24 @masterleinad how about I revise and just unconditionally explicitly pass the template params to the ZeroMemset calls? The if-guard litter allowed leaving some "documentation" of what was problematic with the older intel/19 compiler in this case, but isn't really necessary

**Comment by crtrott** [comment]
It would still need a comment of why we are passing them explicitly even though they should be deducable. And I would still only do it in the place where it is actually needed.

**Comment by masterleinad** [comment]
> @crtrott @dalg24 @masterleinad how about I revise and just unconditionally explicitly pass the template params to the ZeroMemset calls? The if-guard litter allowed leaving some "documentation" of what was problematic with the older intel/19 compiler in this case, but isn't really necessary

Fine with me if you leave a FIXME explaining why using CTAD doesn't work here so we can change when we require newer compiler versions.

**Comment by ndellingwood** [comment]
Ready for review. Should I squash down to a single commit, or can that be during merge after approvals etc?

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
> Ready for review. Should I squash down to a single commit, or can that be during merge after approvals etc?

We can do a squash-merge

**Comment by dalg24** [comment]
Ignoring runtimes issues with the 2 HIP builds and the SYCL build that did not start.

**Pull request merged**
