### PR TITLE
add support to compile Kokkos for Ada generation (sm_89) consumer GPU…

### PR DESCRIPTION
**Pull request by janciesko**
Cherry-picking: https://github.com/kokkos/kokkos/pull/5867

### CODE REVIEW

**Review by ajpowelsnl — APPROVED** [review]
Looks good. Question for a future PR:  would it be possible to prune some of the older architectures in cmake/KokkosCore_config.h.in?  Some of these will undoubtedly be associated with CUDA versions we no longer support.

**Review by dalg24 — CHANGES_REQUESTED** [review]
Duplicate of #6022

**Comment by janciesko** [comment]
Closing in favor of https://github.com/kokkos/kokkos/pull/6022

**Comment by ajpowelsnl** [comment]
> Duplicate of #6022

We now have #5867, #6022 and #6024 (#5867 cherry-pick).  Which do we want in the Patch Release?

**Pull request closed without merging**
