### PR TITLE
Fix some more clang-tidy complains

### PR DESCRIPTION
**Pull request by masterleinad**
It seems we merged some changes between the last rebase of the "modernize type-traits" that were not fixed.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]

**Review by Rombur — APPROVED** [review]

**Review by aprokop — APPROVED** [review]

**Comment by aprokop** [comment]
> It seems we merged some changes between the last rebase of the "modernize type-traits" that were not fixed.

This is likely to continue to happen until all current PRs are either merged or rebased, if they add some of the usage.

**Comment by masterleinad** [comment]
> This is likely to continue to happen until all current PRs are either merged or rebased, if they add some of the usage.

Only in new code, though. Note that the `jenkins` CI merges in `develop` before testing so any retest should be sufficient to detect problems.

**Comment by dalg24** [comment]
> > It seems we merged some changes between the last rebase of the "modernize type-traits" that were not fixed.
> 
> This is likely to continue to happen until all current PRs are either merged or rebased, if they add some of the usage.

Only if the CI did not re-run

**Comment by dalg24** [comment]
```
[ 57%] Building CXX object core/unit_test/CMakeFiles/Kokkos_CoreUnitTest_Threads.dir/threads/TestThreads_ViewAPI_a.cpp.o
/__w/kokkos/kokkos/core/unit_test/TestViewAPI.hpp:958:19: error: use c++17 style variable templates [modernize-type-traits,-warnings-as-errors]
  958 |     static_assert(std::is_same<typename view_type::memory_space,
      |                   ^           
      |                               _v
  959 |                                typename mirror_type::memory_space>::value);
      |                                                                   ~~~~~~~
2548 warnings generated.
Suppressed 2574 warnings (2547 in non-user code, 27 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
1 warning treated as error

**Comment by crtrott** [comment]
Looks good to me, though there are some real failures from the view alloc stuff, but that is not touched here.

**Pull request merged**
