### PR TITLE
Add missing header in Kokkos_Array.hpp

### PR DESCRIPTION
**Pull request by dalg24**
KOKKOS_INLINE_FUNCTION is undefined

### CODE REVIEW

**Comment by ibaned** [comment]
This definitely looks like a legitimate bug fix. Running spot check now...

**Comment by dalg24** [comment]
Renamed some header in our code and `#includes` reordering with clang-format exposed that bug.

**Comment by dalg24** [comment]
```C++
#include <Kokkos_Macros.hpp> // does not compile if commented out
#include <Kokkos_Array.hpp>

int main()
{
  Kokkos::Array<int, 3> p = {1, 2, 3};
  return 0;
}

**Comment by dalg24** [comment]
(@ibaned I did `git commit --amend --reset-author`.  Everything else is the same.)

**Comment by ibaned** [comment]
@dalg24 yea that threw me off a bit, but its pretty clear the change is the same.

**Comment by dalg24** [comment]
Can't spell my email...

**Comment by ibaned** [comment]
Spot check passes:
```
Running on machine: sems
Repository Status:  e27f8a96ab420b720b67c231fec19fa15023ab0e Add missing header in Kokkos_Array.hpp


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
  Starting job gcc-5.3.0-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job intel-17.0.1-OpenMP-release

  PASSED intel-17.0.1-OpenMP-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=193 run_time=167
clang-3.9.0-Pthread_Serial-release build_time=192 run_time=359
cuda-8.0.44-Cuda_OpenMP-release build_time=538 run_time=628
gcc-5.3.0-OpenMP-hwloc-release build_time=176 run_time=118
gcc-5.3.0-OpenMP-release build_time=175 run_time=117
gcc-6.1.0-Serial-hwloc-release build_time=144 run_time=165
gcc-6.1.0-Serial-release build_time=141 run_time=165
intel-17.0.1-OpenMP-hwloc-release build_time=467 run_time=193
intel-17.0.1-OpenMP-release build_time=464 run_time=190
```

**Pull request merged**
