### PR TITLE
Array: Cast i to size_t to fix signed comparison warning/error

### PR DESCRIPTION
**Pull request by ndellingwood**
Fix Jenkins failure in debug mode with flags -Werror -Wsign-compare

### CODE REVIEW

**Comment by ndellingwood** [comment]
@swbova @ibaned A sign-comparison warning-as-error crept in during the debug check, showed up  with the Melvin Jenkins build. I added a cast during the `i <= N` comparison. 

Replicated issue then confirmed it fixed with makefile generated as follows:
` ../../generate_makefile.bash --with-serial --debug --cxxflags="-Werror -Wsign-compare"`

Since it's a simple cast that slipped through spot-checks I figured the above test should be sufficient, let me know if I should run full spot-check though.

**Comment by ibaned** [comment]
@ndellingwood this looks perfect, but we should keep doing full spot checks for all pull requests, no matter how mall.

**Comment by ndellingwood** [comment]
@ibaned good call, thanks for not letting me rush :)

**Comment by ndellingwood** [comment]
@ibaned spot-check passes, ready for merge
```
[ndellin@kokkos-dev TestAllSandia]$ ../../config/test_all_sandia --spot-check
Running on machine: sems
Repository Status:  e57143fd85db1b18ab9fcd78094b73e35d35fc21 Array: Cast i to size_t to fix signed comparison warning/error

Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=194 run_time=91
clang-3.9.0-Pthread_Serial-release build_time=199 run_time=231
cuda-8.0.44-Cuda_OpenMP-release build_time=500 run_time=556
gcc-5.3.0-OpenMP-hwloc-release build_time=261 run_time=275
gcc-5.3.0-OpenMP-release build_time=256 run_time=258
gcc-6.1.0-Serial-hwloc-release build_time=192 run_time=131
gcc-6.1.0-Serial-release build_time=206 run_time=301
intel-17.0.1-OpenMP-hwloc-release build_time=557 run_time=225
intel-17.0.1-OpenMP-release build_time=565 run_time=228
```

**Pull request merged**
