### PR TITLE
kokkos - DynRankView changes to op[]

### PR DESCRIPTION
**Pull request by ndellingwood**
Changes made for sacado compatibility

### CODE REVIEW

**Comment by hcedwar** [comment]
The property branching logic will not work when their is any memory trait other than unmanaged.
The `dimension_scalar` function does not belong in kokkos/core.

**Comment by crtrott** [comment]
Also the performance of the operator[] would be horrendous. I am sure we can find a better solution.

**Comment by etphipp** [comment]
The idea behind that approach was not to make it efficient, but rather create a simple implementation that worked for both double and Fad and allowed them to use operator[] while they refactored the code to not need it.

-Eric

**Comment by etphipp** [comment]
Where you put the code is not important, but Kokkos does need some type-generic way of extracting the hidden dimensions in a view.

-Eric

**Comment by rppawlo** [comment]
This is critical for progress on the L2 milestone. Whatever the correct paths are, can we get a resolution on this asap? Needs:
1. A bracket operator for DynRankView that works for rank >1 and also for FAD scalar types. This is temporary until we can refactor intrepid2 and remove all use cases. As Eric said - performance is not critical. Having something that works in the short term is.
 2. A way to query for hidden dimensions/extent values for both View and DynRankView objects.

**Comment by crtrott** [comment]
What is the purpose of the hidden dimension query?

**Comment by rppawlo** [comment]
We need the hidden dimension in order to create compatible Views in library functions. If the object is a fad type then the ctor needs the extra dimension.

```
void someLibraryFunction(View<...> A, View B<...>) {
View<...> tmp(cell,dim,scalar_dimension(A)); // Rank 2 view with hidden fad dimension that must be same as A's
parallel_for(...,Kernel(A,B,tmp);
}
```
Also take a look a the current bracket operator implementation in this pull request. Needed for that too.

**Comment by ndellingwood** [comment]
Modifications made for the bracket operator in Kokkos_DynRankView to remove need for changes to Kokkos_Core.hpp are copied below. Currently testing Kokkos, will snapshot into Trilinos after and test, expect testing complete and push to Trilinos master branch tomorrow. 

`  // Rank 1
  // This assumes a contiguous underlying memory (i.e. no padding, no striding...)
  template< typename iType >
  KOKKOS_INLINE_FUNCTION
  typename std::enable_if< std::is_same<value_type, scalar_array_type>::value && std::is_integral<iType>::value, reference_type>::type
  operator[](const iType & i0) const
    {
      return data()[i0];
    }

  // This assumes a contiguous underlying memory (i.e. no padding, no striding...
  // AND a Trilinos/Sacado scalar type )
  template< typename iType >
  KOKKOS_INLINE_FUNCTION
  typename std::enable_if< !std::is_same<value_type, scalar_array_type>::value && std::is_integral<iType>::value, reference_type>::type
  operator[](const iType & i0) const
    {
      auto map = implementation_map();

      const size_t dim_scalar = map.dimension_scalar();
      const size_t size = this->span() / dim_scalar;

      typedef Kokkos::View<DataType*, array_layout, device_type, Kokkos::MemoryTraits<Kokkos::Unmanaged | memory_traits::RandomAccess | memory_traits::Atomic> > tmp_view_type;
      tmp_view_type rankone_view(this->data(), size, dim_scalar);
      return rankone_view(i0);
    }`

**Comment by rppawlo** [comment]
Thanks Nathan! Will you be pushing the sacado commits as part of the kokkos snapshot into trilinos? If so, you will have to revert one of the sacado changes in the patch I sent. Since the default implementation of the scalar_dimension() function is not moving into Kokkos_Core, it needs to stay in sacado. We still use that function in other places.

**Comment by ndellingwood** [comment]
Thanks for the reminder, we removed dimension_scalar from Kokkos_Core and replaced it in Sacado where it was originally, and prior to Kokkos snapshot (with current bracket op tested) into Trilinos, so it should function as before for necessary use in other places. I left the other changes in Sacado from the patch as is.

**Comment by ndellingwood** [comment]
Hi @rppawlo , 
I did not account for getting the bracket op changes tested in the Kokkos nightly tests in my previous estimate before getting the changes pushed to Trilinos master, it will be another day before the Kokkos snapshot into Trilinos can be pushed (assuming unit tests pass, Kokkos and Sacado tests have passed). Sorry for the delay.

**Comment by rppawlo** [comment]
Thanks @ndellingwood !

**Pull request merged**
