### PR TITLE
Getting Rid of all the KOKKOS_HAVE Macros

### PR DESCRIPTION
**Pull request by crtrott**
OldMacros are deprecated

### CODE REVIEW

**Comment by crtrott** [comment]
Testing with Deprecated Code on:
```
Running on machine: apollo
Repository Status:  8e022ad7c662d7fad0dfe55870ca0677f9785d91 Getting Rid of all the KOKKOS_HAVE Macros


Going to test compilers:  gcc/4.8.4 gcc/5.3.0 intel/16.0.1 clang/3.9.0 clang/6.0 cuda/9.1
Testing compiler gcc/4.8.4
  Starting job gcc-4.8.4-OpenMP-release
  PASSED gcc-4.8.4-OpenMP-release
Testing compiler gcc/5.3.0
  Starting job gcc-4.8.4-Pthread-release
  PASSED gcc-4.8.4-Pthread-release
Testing compiler intel/16.0.1
  Starting job gcc-5.3.0-Serial-release
  PASSED gcc-5.3.0-Serial-release
Testing compiler clang/3.9.0
  Starting job intel-16.0.1-OpenMP-release
  PASSED intel-16.0.1-OpenMP-release
Testing compiler clang/6.0
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/9.1
  Starting job clang-6.0-Cuda_Pthread-release
  PASSED clang-6.0-Cuda_Pthread-release
  Starting job cuda-9.1-Cuda_OpenMP-release
  PASSED cuda-9.1-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=128 run_time=412
clang-6.0-Cuda_Pthread-release build_time=216 run_time=425
cuda-9.1-Cuda_OpenMP-release build_time=268 run_time=257
gcc-4.8.4-OpenMP-release build_time=99 run_time=128
gcc-4.8.4-Pthread-release build_time=92 run_time=283
gcc-5.3.0-Serial-release build_time=107 run_time=174
intel-16.0.1-OpenMP-release build_time=319 run_time=148
```

**Comment by crtrott** [comment]
Ok found the last issue. Test before the last commit is this:
```
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-release build_time=121 run_time=392
cuda-9.1-Cuda_OpenMP-release build_time=254 run_time=256
gcc-4.8.4-OpenMP-release build_time=94 run_time=130
gcc-4.8.4-Pthread-release build_time=88 run_time=274
gcc-5.3.0-Serial-release build_time=102 run_time=175
intel-16.0.1-OpenMP-release build_time=327 run_time=163
#######################################################
FAILED TESTS
#######################################################
clang-6.0-Cuda_Pthread-release (build failed)
```
Fixing the CUDA_CLANG_WORKAROUND thing made the clang-6.0 test also pass.

**Comment by mhoemmen** [comment]
oh dear you'll have fun in Trilinos making this work :(

**Comment by crtrott** [comment]
Also passes with deprecated code off now.

**Comment by ibaned** [comment]
@crtrott there is an issue here which is that the `HAVE` macros are gone even if deprecated code is on. `Kokkos_OldMacros.hpp` only converts `HAVE` macros into `ENABLE` macros, it doesn't convert `ENABLE` macros back into `HAVE` macros. Thus this is probably going to break a ton of downstream stuff. Maybe we should add a bunch of `HAVE`->`ENABLE` logic in `OldMacros.hpp` under `#ifdef DEPRECATED_CODE`?

This was found by @mndevec in kokkos/kokkos-kernels#218

**Comment by mhoemmen** [comment]
@ibaned PLEASE do this, unless y'all want your telephones to catch on fire ;-)

**Pull request merged**
