### PR TITLE
Readme: upgrade to 4.4.00

### PR DESCRIPTION
**Pull request by cedricchevalier19**
Link to the latest release, Kokkos 4.4.00.

### CODE REVIEW

**Comment by cedricchevalier19** [comment]
I agree. The problem is that Kokkos does not follow the GitHub way to do the tarballs, so it is not very easy to provide a one-liner that downloads the latest release.

The one-liner was added when we decided to make `develop` the default branch, to provide something simple for users to copy and paste in their scripts to get the latest release.

**Review by nmm0 — APPROVED** [review]
Looks good, agreed it's not ideal to have to keep updating but not sure if there is a better way

**Review by masterleinad — APPROVED** [review]
Fine with we. We should just make this part of the release checklist (or just making sure we update when we touch `KOKKOS_VERSION`.

**Comment by dalg24** [comment]
> I agree. The problem is that Kokkos does not follow the GitHub way to do the tarballs, so it is not very easy to provide a one-liner that downloads the latest release.

What is the GitHub way to do tarballs?

**Pull request merged**
