### PR TITLE
Issue 1108; WorkGraphPolicy

### PR DESCRIPTION
**Pull request by hcedwar**
Streamline WorkGraphPolicy for #1108.  The pop_work function does not wait for work to be pushed, that is the responsibility of the device-specific back-end.

### CODE REVIEW

**Comment by ibaned** [comment]
I guess my commits left some bad changes in there, namely commenting out tests in `core/unit_test/CMakeLists.txt` and including `unistd.h` in `core/unit_test/TestWorkGraph.hpp` (there was a call to `sleep` at some point during debugging). So those need to be taken out before merging. Spot checks on Pascal and the GCC 6.1.0 10-thread OpenMP config that hung before should also be done before merging.

**Comment by hcedwar** [comment]
Spot checks on Pascal and Haswell GCC 6.1 pending...

**Comment by hcedwar** [comment]
Pascal and GCC 6.1 verified.  Spot check on Pascal revealed need for memory_fence, good catch.
Ready to merge.

**Comment by hcedwar** [comment]
Ping @ibaned when you have a moment

**Comment by ibaned** [comment]
Good old pascal :)    approving

**Pull request merged**
