### PR TITLE
Release 3.3.0

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Cross-referencing:
kokkos/kokkos-kernels#862
trilinos/Trilinos#8490

**Review by masterleinad — APPROVED** [review]
The changelog entry looks reasonable to me.

**Comment by ndellingwood** [comment]
Travis failure output: `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by crtrott** [comment]
We ignore travis.

**Pull request merged**
