### PR TITLE
Release 4.2.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Snapshot to Trilinos part of https://github.com/trilinos/Trilinos/pull/12505

**Comment by ndellingwood** [comment]
HPX CI failure is a known issue that was resolved on the develop branch

**Comment by masterleinad** [comment]
Not sure if we want to cherry-pick #6608 (which would only change how we test).

**Comment by masterleinad** [comment]
Why is the source branch not https://github.com/kokkos/kokkos/tree/release-candidate-4.2.00?

**Comment by ndellingwood** [comment]
> Why is the source branch not https://github.com/kokkos/kokkos/tree/release-candidate-4.2.00?

@masterleinad to avoid a redundant PR and testing - here I submit one PR containing the merge of release-candidate to master; if I submit PR with the merge with master to release-candidate-x.y.z, that will require a follow up PR back to the master branch

If you'd prefer to keep the merge with master on the release-candidate-x.y.z branches we can start doing that, but I've not done that to avoid a redundant round of CI

**Comment by ndellingwood** [comment]
> No, it's fine. Were there any conflicts?

Yes, this was the list:
```
UU CHANGELOG.md
UU CMakeLists.txt
UU Makefile.kokkos
UU cmake/kokkos_arch.cmake *
UU simd/src/Kokkos_SIMD_AVX2.hpp
UU simd/src/Kokkos_SIMD_AVX512.hpp
UU simd/src/Kokkos_SIMD_Common.hpp
UU simd/src/Kokkos_SIMD_NEON.hpp
UU simd/unit_tests/TestSIMD.cpp
```

**Comment by ndellingwood** [comment]
> UU cmake/kokkos_arch.cmake *

@masterleinad I should point out the asterisk is a remnant marking I made; the version of that file post-merge had missed several changes from the release-candidate-4.2.00 (in addition to conflicts) that manually corrected (I checked diff comparison between the post-master-merge and release-candidate-4.2.00 of conflict-files after resolving conflicts )

**Review by crtrott — APPROVED** [review]

**Pull request merged**
