### PR TITLE
Attempt to compile all benchmarks, examples, and test with RTTI disabled

### PR DESCRIPTION
**Pull request by dalg24**
Partially addressing #7037

### CODE REVIEW

**Comment by dalg24** [comment]
HPX does not support disabling RTTI
```
In file included from /home/runner/work/kokkos/kokkos/kokkos/build/core/unit_test/serial/TestSerial_BlockSizeDeduction.cpp:2:
In file included from /home/runner/work/kokkos/kokkos/kokkos/core/unit_test/TestBlockSizeDeduction.hpp:20:
In file included from /home/runner/work/kokkos/kokkos/kokkos/core/src/Kokkos_Core.hpp:45:
In file included from /home/runner/work/kokkos/kokkos/kokkos/build/KokkosCore_Config_DeclareBackend.hpp:23:
In file included from /home/runner/work/kokkos/kokkos/kokkos/core/src/decl/Kokkos_Declare_HPX.hpp:21:
In file included from /home/runner/work/kokkos/kokkos/kokkos/core/src/HPX/Kokkos_HPX.hpp:45:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/barrier.hpp:9:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/collectives/barrier.hpp:13:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/collectives/detail/barrier_node.hpp:10:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/actions/transfer_action.hpp:14:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/actions/base_action.hpp:14:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/modules/datastructures.hpp:14:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/datastructures/any.hpp:22:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/datastructures/traits/supports_streaming_with_any.hpp:10:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/serialization/serialize_buffer.hpp:12:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/modules/errors.hpp:16:
In file included from /home/runner/work/kokkos/kokkos/hpx/install/include/hpx/errors/exception.hpp:16:
/home/runner/work/kokkos/kokkos/hpx/install/include/hpx/errors/exception_info.hpp:92:48: error: use of typeid requires -frtti
                entry_type const entries[] = {{typeid(typename Ts::tag),
                                               ^
/home/runner/work/kokkos/kokkos/hpx/install/include/hpx/errors/exception_info.hpp:95:42: error: cannot use incomplete type 'const entry_type[]' (aka 'const pair<const std::type_info &, const void *>[]') as a range
                for (auto const& entry : entries)
                                         ^
/home/runner/work/kokkos/kokkos/hpx/install/include/hpx/errors/exception_info.hpp:145:37: error: use of typeid requires -frtti
                data ? data->lookup(typeid(typename Tag::tag)) : nullptr);
                                    ^
/home/runner/work/kokkos/kokkos/hpx/install/include/hpx/errors/exception_info.hpp:174:42: error: use of typeid requires -frtti
              , exception_with_info_base(typeid(E), HPX_MOVE(xi))
                                         ^
/home/runner/work/kokkos/kokkos/hpx/install/include/hpx/errors/exception_info.hpp:180:42: error: use of typeid requires -frtti
              , exception_with_info_base(typeid(E), HPX_MOVE(xi))
                                         ^
```
Same for SYCL
```
In file included from /var/jenkins/workspace/Kokkos_PR-7338/core/unit_test/UnitTestMainInit.cpp:20:
In file included from /var/jenkins/workspace/Kokkos_PR-7338/core/src/Kokkos_Core.hpp:43:
In file included from /var/jenkins/workspace/Kokkos_PR-7338/core/src/Kokkos_Core_fwd.hpp:28:
In file included from /var/jenkins/workspace/Kokkos_PR-7338/core/src/Kokkos_Macros.hpp:110:
In file included from /var/jenkins/workspace/Kokkos_PR-7338/build/KokkosCore_Config_SetupBackend.hpp:22:
In file included from /var/jenkins/workspace/Kokkos_PR-7338/core/src/setup/Kokkos_Setup_SYCL.hpp:36:
In file included from /opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/sycl.hpp:11:
In file included from /opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/accessor.hpp:13:
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:181:61: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), nullptr, (const void *)typeid(T).name(),
                                                            ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:195:61: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), nullptr, (const void *)typeid(T).name(),
                                                            ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:208:62: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
                                                             ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:222:62: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
                                                             ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:237:62: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
                                                             ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:253:62: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
                                                             ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:270:23: error: use of typeid requires -frtti
        (const void *)typeid(T).name(), dimensions, sizeof(T),
                      ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:287:23: error: use of typeid requires -frtti
        (const void *)typeid(T).name(), dimensions, sizeof(T),
                      ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:303:23: error: use of typeid requires -frtti
        (const void *)typeid(T).name(), dimensions, sizeof(T),
                      ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:319:23: error: use of typeid requires -frtti
        (const void *)typeid(T).name(), dimensions, sizeof(T),
                      ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:352:57: error: use of typeid requires -frtti
                                          (const void *)typeid(T).name(),
                                                        ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:384:57: error: use of typeid requires -frtti
                                          (const void *)typeid(T).name(),
                                                        ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:404:23: error: use of typeid requires -frtti
        (const void *)typeid(T).name(), dimensions, sizeof(T), r);
                      ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:422:64: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), impl.get(), (const void *)typeid(T).name(),
                                                               ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:443:64: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), impl.get(), (const void *)typeid(T).name(),
                                                               ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:452:64: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), impl.get(), (const void *)typeid(T).name(),
                                                               ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:724:64: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), &MemObject, (const void *)typeid(T).name(),
                                                               ^
/opt/intel/oneapi/compiler/latest/linux/bin-llvm/../include/sycl/buffer.hpp:744:64: error: use of typeid requires -frtti
        CodeLoc, (void *)impl.get(), Impl.get(), (const void *)typeid(T).name(),
                                                               ^

**Comment by masterleinad** [comment]
> Same for SYCL

Should we make that a feature request for oneAPI?

**Review by masterleinad — COMMENTED** [review]
Is this an intermediate step before introducing an option to disable RTTI or do you expect the user to set flags accordingly?

**Comment by dalg24** [comment]
> Is this an intermediate step before introducing an option to disable RTTI or do you expect the user to set flags accordingly?

There will be no option.  We don't use RTTi and we check there are no regression, that's all.
Potentially we could have an IMPL_ option to prevent adding the `-fno-rtti` flag if we discover issues with some toolchains.

**Comment by dalg24** [comment]
There are issues with the sanitizers but I am not sure how to go about it yet.

**Comment by masterleinad** [comment]
> There are issues with the sanitizers but I am not sure how to go about it yet.

See https://stackoverflow.com/a/48322000 which suggests to use
```
-fsanitize=undefined -fno-sanitize=vptr
```

**Review by Rombur — APPROVED** [review]

**Review by aprokop — APPROVED** [review]

**Review by crtrott — APPROVED** [review]
Fine with me. That said how bad is it to turn of vptr sanitation? Probably not really for us. We aren't using vptrs heavily I guess?

**Comment by dalg24** [comment]
> Fine with me. That said how bad is it to turn of vptr sanitation? Probably not really for us. We aren't using vptrs heavily I guess?

We could add an IMPL_ option that bypasses adding the no-rtti flag if needed.

**Pull request merged**
