### PR TITLE
Add KOKKOS_INLINE_FUNCTION to Crs (2??)

### PR DESCRIPTION
**Pull request by jeffmiles63**
Added changes resulting from previous comments:
in Kokkos_Crs.hpp
   Remove unecessary {}
   Add KOKKOS_INLINE_FUNCTION to parameterized constructor

in TestCrs.hpp.
   Added 3 tests cases to exercise the different constructors/assignment operators
   Rearranged RunUpdateCrsTest to use tagged operators to identify function used by parallel for

below are the results of spot-check run on kokkos-dev:

<Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
  Starting job gcc-5.3.0-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED intel-17.0.1-OpenMP-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=182 run_time=188
clang-3.9.0-Pthread_Serial-release build_time=184 run_time=394
cuda-8.0.44-Cuda_OpenMP-release build_time=535 run_time=514
gcc-5.3.0-OpenMP-hwloc-release build_time=172 run_time=124
gcc-5.3.0-OpenMP-release build_time=171 run_time=122
gcc-6.1.0-Serial-hwloc-release build_time=138 run_time=166
gcc-6.1.0-Serial-release build_time=138 run_time=166
intel-17.0.1-OpenMP-hwloc-release build_time=420 run_time=182>

### CODE REVIEW

**Comment by mhoemmen** [comment]
Shouldn't we merge this into the `develop` branch, rather than `master`?

**Comment by ndellingwood** [comment]
@dalg24 there's a bug with cuda 9 that prevents doing the nicer thing you mentioned. I think device host markings aren't respected when `default` is used.

**Comment by ibaned** [comment]
@ndellingwood they are, they just emit a warning. We've added the right flags in Kokkos to silence that warning.

**Comment by jeffmiles63** [comment]
Adding reference to previous pull request: #1885 
Refer to that list for the changes addressed herein

**Comment by jeffmiles63** [comment]
Closing this request, the latest request with the reviewed changes is in #1903

**Pull request closed without merging**
