### PR TITLE
Use sycl::info::kernel_device_specific::preferred_work_group_size_multiple

### PR DESCRIPTION
**Pull request by masterleinad**
This pull request goes in the same direction as #4383 to use kernel introspection to find a good workgroup size. Unfortunately, this needs https://github.com/intel/llvm/pull/4457 and thus a version newer than the latest release.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
I completely missed that this was draft, my bad. But thanks for the replies. Will review when we're really looking at merging this

**Comment by masterleinad** [comment]
The point of this pull request is that the compiler chooses a workgroup size that is divisible by the total size. In particular, the workgroup size is 1 if the total range is a prime number. In this pull request, we take the largest multiple of the preferred group size that is not greater than the largest workgroup size instead.

**Comment by masterleinad** [comment]
Retest this please.

**Review by dalg24 — COMMENTED** [review]
Please elaborate why this code is better than what was there before.

It feels like it is something that belongs to SYCL internal implementation.

**Comment by masterleinad** [comment]
> Please elaborate why this code is better than what was there before.
> 
> It feels like it is something that belongs to SYCL internal implementation.

I only have https://github.com/kokkos/kokkos/pull/4405#issuecomment-961477141 and need to measure performance some more. Of course, I'm happy to apply this kind of adapting the workgroup size to all other policies in the end. For now, it's partly meant as a platform of discussion in particular with respect to #4383.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
So if I get your statement right, for prime numbers of lengths SYCL choses a workgroup size of 1 right now???

**Comment by crtrott** [comment]
Another thing: independent of whether we have the new compiler version: couldn't we fudge the range we give to sycl to make it a multiple of say 128 if it isn't? That way the bad heuristic will not hit us.

**Comment by joeatodd** [comment]
> Another thing: independent of whether we have the new compiler version: couldn't we fudge the range we give to sycl to make it a multiple of say 128 if it isn't? That way the bad heuristic will not hit us.

I have done this previously in our Kokkos branch and it works, FYI.

> So if I get your statement right, for prime numbers of lengths SYCL choses a workgroup size of 1 right now???

Yes!

**Comment by masterleinad** [comment]
Maybe, we just use #4593 for now but keep this open to discuss jointly with #4383.

**Pull request closed without merging**
