### PR TITLE
Use CUDA_SAFE_CALL for cudaFuncGetAttributes

### PR DESCRIPTION
**Pull request by masterleinad**
In respoense to https://github.com/kokkos/kokkos/pull/2499#discussion_r344857978.

### CODE REVIEW

**Review by DavidPoliakoff — APPROVED** [review]
Good catch. If this passes CI (and if it doesn't I'll be shocked) I approve

**Review by dhollman — CHANGES_REQUESTED** [review]
There are like five other overloads you're missing.

**Comment by masterleinad** [comment]
I fixed the other places as well.

**Review by dhollman — APPROVED** [review]
LGTM

**Pull request merged**
