### PR TITLE
fix exception resulting from 0 grain size (Issue #3460)

### PR DESCRIPTION
**Pull request by jeffmiles63**
This should resolve issue #3460

### CODE REVIEW

**Review by ndellingwood — APPROVED** [review]
lgtm

**Comment by dalg24** [comment]
I totally missed that when I opened #3512 
I pulled your changes and can confirm that the changes suggested here also resolve the UB I reported
@DavidPoliakoff please review.

**Comment by dalg24** [comment]
@ndellingwood Would you please check if this resolves #3497

**Comment by ndellingwood** [comment]
@dalg24 @jeffmiles63 : built Pthreads build with gcc/8.3.0:

```
[ndellin@kokkos-dev unit_test]$ ./KokkosCore_UnitTest_Threads --gtest_filter=threads.policy_converting_constructor_from_other_policy
Note: Google Test filter = threads.policy_converting_constructor_from_other_policy
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from threads
[ RUN      ] threads.policy_converting_constructor_from_other_policy
[       OK ] threads.policy_converting_constructor_from_other_policy (0 ms)
[----------] 1 test from threads (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```

Test from #3497 is passing again :)

**Review by DavidPoliakoff — APPROVED** [review]
Oof, good catch

**Pull request merged**
