### PR TITLE
Release candidate 3.7.00

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Hold merge until success of PR trilinos/Trilinos#10962

**Comment by PhilMiller** [comment]
https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1661358813427159?thread_ts=1661275456.786019&cid=C5BGU5NDQ
#5380 did that ultimately get resolved? I don't see any related pull request since then.

**Comment by crtrott** [comment]
We resolved #5380

**Comment by PhilMiller** [comment]
Retest this please

**Comment by Rombur** [comment]
Retest this please

**Comment by Rombur** [comment]
Retest this please

**Comment by PhilMiller** [comment]
Retest this please

**Comment by PhilMiller** [comment]
retest this please

**Comment by Rombur** [comment]
Retest this please

**Review by masterleinad — APPROVED** [review]
Since this was already merged in `Trilinos`and we don't have any other hold-ups (I'm aware of) this should be good as soon as tests pass.

**Review by crtrott — APPROVED** [review]

**Comment by crtrott** [comment]
I deleted a file which must have been accidentally readded. With this the diff to the origin/relase-candidate-3.7.00 looks ok (just some fixup in CHANGELOG and one change in cmake/kokkos_tribits.cmake which is also in Trilinos.

**Comment by crtrott** [comment]
```
   INSTALL(PROGRAMS
           "${CMAKE_CURRENT_SOURCE_DIR}/bin/nvcc_wrapper"
           "${CMAKE_CURRENT_SOURCE_DIR}/bin/hpcbind"
+          "${CMAKE_CURRENT_SOURCE_DIR}/bin/kokkos_launch_compiler"
           "${PROJECT_BINARY_DIR}/temp/kokkos_launch_compiler"
           DESTINATION ${CMAKE_INSTALL_BINDIR})
```

I assume this is intended?

**Comment by ndellingwood** [comment]
> ```
>    INSTALL(PROGRAMS
>            "${CMAKE_CURRENT_SOURCE_DIR}/bin/nvcc_wrapper"
>            "${CMAKE_CURRENT_SOURCE_DIR}/bin/hpcbind"
> +          "${CMAKE_CURRENT_SOURCE_DIR}/bin/kokkos_launch_compiler"
>            "${PROJECT_BINARY_DIR}/temp/kokkos_launch_compiler"
>            DESTINATION ${CMAKE_INSTALL_BINDIR})
> ```
> 
> 
>     
>   
> 
> I assume this is intended?

@crtrott no, I looked back at [release-candidate-3.7.00](https://github.com/kokkos/kokkos/blob/release-candidate-3.7.00/cmake/kokkos_tribits.cmake) and the added `"${CMAKE_CURRENT_SOURCE_DIR}/bin/kokkos_launch_compiler"` is a stray from the merge to master. I compared the release-candidate-3.7.00 merge to master with the https://github.com/kokkos/kokkos/blob/release-candidate-3.7.00 while resolve merge conflicts but must have made a mistake here, sorry for the mismatch

**Comment by ndellingwood** [comment]
The CUDA-11.0-NVCC-C++17-RDC `default_exec.overlap_mdrange_policy` failure in `KokkosCore_PerfTestExec` is spurious

**Comment by ndellingwood** [comment]
The github-OSX/osx-ci (SERIAL, Release) failure was system related, failure triggered cancellation of the other checks

```
Error: fatal: unable to access 'https://github.com/kokkos/kokkos/': The requested URL returned error: 429
```

**Pull request merged**
