### PR TITLE
Require NVIDIA GPU architecture when CUDA is enabled

### PR DESCRIPTION
**Pull request by dalg24**
Partially addressing #2624

### CODE REVIEW

**Comment by jjwilke** [comment]
I put a draft here in a PR into the fork:

https://github.com/dalg24/kokkos/pull/1/files

My concern is that the average citizen will struggle to know which architecture flags to use. This would provide suggestions and a way to validate before building Kokkos that everything is correct.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by dalg24** [comment]
I would prefer to merge this PR as is and explore suggesting the CUDA arch to the user elsewhere.  @jjwilke would that work with you?

**Comment by dalg24** [comment]
Done

**Comment by jjwilke** [comment]
> Done

So I'm an idiot and meant to say "give one" not "give at least one". We crash if you give more than one...

**Comment by dalg24** [comment]
Fixed and amended to the last commit.

**Pull request merged**
