### PR TITLE
Remove cmake options to change default spaces at configure time

### PR DESCRIPTION
**Pull request by JBludau**
It looks like these options are somewhat broken, as both `KOKKOS_DEVICE_SPACE_ACTIVE` and `KOKKOS_HOSTPARALLEL_SPACE_ACTIVE` seem to be unused.

Furthermore, it seems like the cmake options to change the default execution and memory space are undocumented.

### CODE REVIEW

**Comment by masterleinad** [comment]
This was introduced in https://github.com/kokkos/kokkos/pull/2941.

**Review by dalg24 — APPROVED** [review]
That code dates back from the refactor in #2941
It is not clear to me how that was supposed to work.  I am ok with removing it.

**Review by aprokop — APPROVED** [review]

**Review by nliber — APPROVED** [review]

**Comment by JBludau** [comment]
Some builds are failing but it seems unrelated. But a qualified second opinion would be good, as I have not followed CI problems recently

**Comment by dalg24** [comment]
CI failures unrelated
```
3: Failing in Thread:1
3: Accelerator Fatal Error: call to cuStreamSynchronize returned error 700: Illegal address during kernel execution
3:  File: (OpenACC API)
3:  Function: acc_copyout:1
3:  Line
```
and all unit test segfaulting in one of the HIP builds

**Pull request merged**
