### PR TITLE
Release 3.7.01

### PR DESCRIPTION
**Pull request by ndellingwood**

### CODE REVIEW

**Comment by ndellingwood** [comment]
Please hold PR until successful pass and merge of https://github.com/trilinos/Trilinos/pull/11347

**Comment by ndellingwood** [comment]
A test timed out in the hpx build, is this a known spurious failure?
```
 The following tests FAILED:
	  7 - KokkosCore_UnitTest_LogicalSpaces (Timeout)
```

**Comment by ndellingwood** [comment]
The `CUDA-11.6-NVHPC` build failed CI in the `KokkosCore_UnitTest_CudaTimingBased` which is spurious

**Comment by ndellingwood** [comment]
https://github.com/trilinos/Trilinos/pull/11347 passed testing, ready for merge

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Pull request merged**
