### PR TITLE
UniqueToken impl_acquire function should be device only

### PR DESCRIPTION
**Pull request by Rombur**
Part of #4783 that was reverted because it was too close to the release

### CODE REVIEW

**Review by dalg24 — CHANGES_REQUESTED** [review]
Please open a PR on the Desul-side and post a reference to it

**Review by dalg24 — COMMENTED** [review]
Looks good.  Will unblock when Desul PR is merged.

**Comment by Rombur** [comment]
The corresponding PR has been merged in desul. @dalg24 can you unblock the PR?

**Review by dalg24 — APPROVED** [review]

**Comment by crtrott** [comment]
Retest this please.

**Pull request merged**
