### PR TITLE
Use atomics for volatile store loads to fix Threads on ARM

### LINKED ISSUE #7090: Kokkos::Threads backend is broken on M2 MacBook (ARM) in develop
It still works in 4.3.01 but in develop a lot of the tests segfault when launched with more than one thread (export KOKKOS_NUM_THREADS=4). 

For example:
```
s1087574:build crtrott$ containers/unit_tests/Kokkos_ContainersUnitTest_Threads 
[==========] Running 65 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 65 tests from threads
[ RUN      ] threads.bitset
Segmentation fault: 11
```

Configured:

```
cmake -DKokkos_ENABLE_THREADS=ON -DKokkos_ENABLE_TESTS=ON
```

### PR DESCRIPTION
**Pull request by crtrott**
This should fix threads backend on ARM.
Fixes #7090

### CODE REVIEW

**Comment by masterleinad** [comment]
Still seeing
```
2: [ RUN      ] threads.team_scratch_request
2: /Users/6da/Software/kokkos_new/core/unit_test/TestTeam.hpp:908: Failure
2: Expected equality of these values:
2:   error_count
2:     Which is: 34
2:   0
```
after running a couple of times.

**Comment by masterleinad** [comment]
```
[ RUN      ] threads.unique_token_team_acquire
/tmp/kokkos/core/unit_test/TestUniqueToken.hpp:246: Failure
Expected equality of these values:
  host_errors(0)
    Which is: 1
  0
max reuse was 136
[  FAILED  ] threads.unique_token_team_acquire (0 ms)
```

**Comment by janciesko** [comment]
Still:
```
[ RUN      ] threads.unique_token_team_acquire
/Users/jciesko/RAndD/kokkos_round2/core/unit_test/TestUniqueToken.hpp:246: Failure
Expected equality of these values:
  host_errors(0)
    Which is: 1
  0
max reuse was 111
[  FAILED  ] threads.unique_token_team_acquire (7 ms)
```

**Comment by janciesko** [comment]
I glanced over the internal_fence and I wonder if we understand how we include the root thread in this fence. It seems that we set the state of the root thread to inactive in L306. The root thread (`s_threads_exec[0]`) then immediately enters the fence and likely proceeds before other workers reach that fence. 

```C++
// Wait for root thread to become inactive
void ThreadsInternal::internal_fence() {
  memory_fence();
  if (s_thread_pool_size[0]) {
    // Wait for the root thread to complete:
    Impl::spinwait_while_equal(s_threads_exec[0]->m_pool_state,
                               ThreadState::Active);
  }

  Kokkos::atomic_store(&s_current_function, nullptr);
  Kokkos::atomic_store(&s_current_function_arg, nullptr);

  // Make sure function and arguments are cleared before
  // potentially re-activating threads with a subsequent launch.
  memory_fence();
}
```

**Comment by janciesko** [comment]
Alternatively, get rid of more volatile types in favor of atomics.

**Pull request closed without merging**
