### PR TITLE
Error out at configuration time if attempting to disable desul atomics

### PR DESCRIPTION
**Pull request by dalg24**
First step in #5789 
Prevent disabling desul atomics.  I opted for a hard error at configuration time so this cannot be ignored.  The alternative would be to raise some kind of warning that the user-requested setting will be ignored.

Note that I did not attempt to warn the user if they explicitly configure with `-DKokkos_ENABLE_IMPL_DESUL_ATOMICS=ON`.

### CODE REVIEW

**Comment by dalg24** [comment]
> Note that I did not attempt to warn the user if they explicitly configure with `-DKokkos_ENABLE_IMPL_DESUL_ATOMICS=ON`.

A bit more on this.  I opted for that strategy because it makes the diff minimal.  In the next, PR I will prune configuration-time branches that consider whether desul atomics are enabled or not.  When I get to the final cleanup, as we discuss the removal of the `KOKKOS_ENABLE_IMPL_DESUL_ATOMICS` macro, we can revisit it.

**Comment by dalg24** [comment]
Makefile didn't like my appending `// deprecated` to the `KOKKOS_INTERNAL_*` lines...
Fixed now

**Comment by Rombur** [comment]
I would emit a warning instead of an error so users can keep the same script for multiple versions of Kokkos.

**Comment by dalg24** [comment]
> I would emit a warning instead of an error so users can keep the same script for multiple versions of Kokkos.

Proposed #5801 as an alternative resolution

**Review by masterleinad — APPROVED** [review]
I like this better. It's an `IMPL` variable and there shouldn't really be a good reason for people to use it. People tend to ignore configure-time warnings anyway.

**Comment by dalg24** [comment]
Closing in favor of #5801

**Pull request closed without merging**
