### PR TITLE
Changes required to build a view of CrsMatrices #1581

### PR DESCRIPTION
**Pull request by rppawlo**
Changes required to support a View of CrsMatrices on CUDA.

### CODE REVIEW

**Comment by rppawlo** [comment]
@mhoemmen @ndellingwood - I can't seem to set a reviewer once the PR is submitted, probably don't have right permissions. Could one of you take a look at this?

**Comment by ndellingwood** [comment]
@rppawlo what type of testing did you do for this? I'll pull this PR and run it through a spot-check, then it should be ready. 
See followup kokkos/kokkos-kernels#220

**Comment by rppawlo** [comment]
I don't have access to kokkos testing machinery. Only ran a cuda debug build on ride and OpenMP opt build on my workstation. It definitely needs more testing. Thanks!

**Comment by ndellingwood** [comment]
@rppawlo changes look reasonable, running a spot-check now. I'll work the other changes for #1581 to handle the memory traits in a separate PR.

**Comment by ndellingwood** [comment]
Passes spot-check on kokkos-dev:

```
[ndellin@kokkos-dev TestAllSandia]$ ../../config/test_all_sandia --spot-check
Running on machine: sems
Repository Status:  d3ad07421838de05a80c61f099f83b0979d2828c Changes required to build a view of CrsMatrices #1581


Going to test compilers:  gcc/5.3.0 gcc/6.1.0 intel/17.0.1 clang/3.9.0 cuda/8.0.44
Testing compiler gcc/5.3.0
  Starting job gcc-5.3.0-OpenMP-release
  PASSED gcc-5.3.0-OpenMP-release
Testing compiler gcc/6.1.0
  Starting job gcc-5.3.0-OpenMP-hwloc-release
  PASSED gcc-5.3.0-OpenMP-hwloc-release
  Starting job gcc-6.1.0-Serial-release
  PASSED gcc-6.1.0-Serial-release
Testing compiler intel/17.0.1
  Starting job gcc-6.1.0-Serial-hwloc-release
  PASSED gcc-6.1.0-Serial-hwloc-release
  Starting job intel-17.0.1-OpenMP-release
  PASSED intel-17.0.1-OpenMP-release
Testing compiler clang/3.9.0
  Starting job intel-17.0.1-OpenMP-hwloc-release
  PASSED intel-17.0.1-OpenMP-hwloc-release
  Starting job clang-3.9.0-Pthread_Serial-release
  PASSED clang-3.9.0-Pthread_Serial-release
Testing compiler cuda/8.0.44
  Starting job clang-3.9.0-Pthread_Serial-hwloc-release
  PASSED clang-3.9.0-Pthread_Serial-hwloc-release
  Starting job cuda-8.0.44-Cuda_OpenMP-release
  PASSED cuda-8.0.44-Cuda_OpenMP-release
#######################################################
PASSED TESTS
#######################################################
clang-3.9.0-Pthread_Serial-hwloc-release build_time=193 run_time=214
clang-3.9.0-Pthread_Serial-release build_time=195 run_time=408
cuda-8.0.44-Cuda_OpenMP-release build_time=527 run_time=638
gcc-5.3.0-OpenMP-hwloc-release build_time=178 run_time=123
gcc-5.3.0-OpenMP-release build_time=179 run_time=122
gcc-6.1.0-Serial-hwloc-release build_time=143 run_time=209
gcc-6.1.0-Serial-release build_time=142 run_time=198
intel-17.0.1-OpenMP-hwloc-release build_time=458 run_time=194
intel-17.0.1-OpenMP-release build_time=459 run_time=191
```

**Comment by ndellingwood** [comment]
@crtrott, @ibaned your merge power is requested :)

**Pull request merged**
