### PR TITLE
Clean up shift_{right, left}_team_impl

### PR DESCRIPTION
**Pull request by masterleinad**
I was running SonarCloud on my fork to try it out and one of the bugs reported was https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=masterleinad_kokkos&open=AY2p6YQlbq2DzqS7mbTl.
We basically use a unary minus operator on an unsigned type (std::size_t) and pass that to another signed type for iterator access to access an element before the one the iterator points to. With conversion between signed and unsigned types, this might not work correctly, see https://godbolt.org/z/6o3f4qY7T.
I also noticed that `StdShiftRightTeamSingleFunctor` isn't used at all.

### CODE REVIEW

**Comment by fnrizzi** [comment]
is it a draft bec waiting for CI?

**Comment by masterleinad** [comment]
> is it a draft bec waiting for CI?

Yes.

**Review by dalg24 — COMMENTED** [review]
Wanna update shift left for consistency?

**Comment by masterleinad** [comment]
> Wanna update shift left for consistency?

Sure, why not, see 89fcc46.

**Review by fnrizzi — APPROVED** [review]

**Review by ldh4 — APPROVED** [review]

**Comment by dalg24** [comment]
Ignoring failure of one of the HIP build

**Comment by dalg24** [comment]
Please add an entry to the 4.3 changelog for this

**Pull request merged**
