### PR TITLE
MD team policy common functions refactor

### PR DESCRIPTION
**Pull request by ldh4**
Refactoring MD team policies interfaces to have them be templated on the team member type and be available for all backends. This is to avoid redundancy in each backend impls when the template specialized implementations of these functions are essentially identical.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
Retest this please.

**Review by JBludau — APPROVED** [review]
makes sense

**Review by crtrott — APPROVED** [review]

**Comment by dalg24** [comment]
Please confirm that the changes are just dropping the `typename = std::enable_if_t<Impl::is_thread_team_member<Member>::value` (5 occurrences as far as I can tell).

**Comment by crtrott** [comment]
I checked again and its just dropping that. We may wanna reintroduce something like that (at least as a static assert) but lets gets this moving for now.

**Pull request merged**
