### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kushal34712**

### CODE REVIEW

**Comment by fnrizzi** [comment]
@kushal34712 can you please write in the description the purpose of your PR? thanks

**Review by dalg24 — CHANGES_REQUESTED** [review]
Targeting the wrong branch

**Comment by PhilMiller** [comment]
See my remarks on #6539

**Comment by fnrizzi** [comment]
> See my remarks on #6539

agree

**Comment by dalg24** [comment]
Targeting the wrong branch, no description, not a substantive improvement over the status quo.

**Pull request closed without merging**
