### PR TITLE
Finalize deep_copy_space early avoiding printing to std::cerr for Cuda

### PR DESCRIPTION
**Pull request by masterleinad**
We are currently printing an error message to `std::cerr` when finalizing `Cuda` execution spaces as the first commit shows.

The problem is that we are finalizing `deep_copy_space` since that needs to deallocate data which calls a fence on the default execution space and we check if the execution space has already unset `m_dev` at this point. Wd didn't see this so far, since we are only printing to `std::cerr` but not throwing an exception or aborting.
The proposed fix is to finalize `deep_copy_space` before unsettling `m_dev`.

While looking at this, I also found that some of the code in `finalize` is guarded by a check for scratch space which didn't make sense to me.

Throwing in `finalize` is debatable, of course, but makes the problem obvious (in the CI).

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
In general, I would say looks good.  (I would suggest we call `abort()` instead of throwing an exception though.)
But, I suppose you are looking into this because of @stanmoore1 report on Slack

> **Stan Moore**  [12:14 PM]
> I'm still seeing this error in LAMMPS:
> ```
> Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
> ```

and I don't quite follow how either of `Cuda::Cuda()` or `Cuda::Cuda(cudaStream_t, bool)` would get called.

Please elaborate.

**Comment by masterleinad** [comment]
The failing stacktrace looks like
```
abort@libc.so.6
Kokkos::Impl::CudaInternal::verify_is_initialized@../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:336
Kokkos::Cuda::Cuda@../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:880
Kokkos::Impl::HostInaccessibleSharedAllocationRecordCommon<Kokkos::CudaSpace>::get_record@../../lib/kokkos/core/src/impl/Kokkos_SharedAlloc_timpl.hpp:265
Kokkos::Impl::CudaInternal::finalize@../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:731
Kokkos::Impl::CudaInternal::finalize@../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:774
Kokkos::Cuda::impl_finalize@../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:875
Kokkos::Impl::CudaSpaceInitializer::finalize@../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:947
Kokkos::Impl::ExecSpaceManager::finalize_spaces@../../lib/kokkos/core/src/impl/Kokkos_Core.cpp:125
Kokkos::Impl::(anonymous@../../lib/kokkos/core/src/impl/Kokkos_Core.cpp:561
Kokkos::finalize@../../lib/kokkos/core/src/impl/Kokkos_Core.cpp:1033
LAMMPS_NS::KokkosLMP::finalize@../kokkos.cpp:350
main@../main.cpp:108
```

**Comment by dalg24** [comment]
Thanks so it is
https://github.com/kokkos/kokkos/blob/acb34347ac67dc55c5255c1f7dac39af47e11b5f/core/src/Cuda/Kokkos_Cuda_Instance.cpp#L745
which calls
https://github.com/kokkos/kokkos/blob/acb34347ac67dc55c5255c1f7dac39af47e11b5f/core/src/impl/Kokkos_SharedAlloc_timpl.hpp#L264-L271
and the issue is our default constructing an execution space on L265.
This is a release 3.6 defect (introduced in #4478)

I suppose we should use `Cuda::impl_static_fence(...)` after the deep copy instead of `fence()`.

**Comment by masterleinad** [comment]
> I suppose we should use Cuda::impl_static_fence(...) after the deep copy instead of fence().

I still think we should just fence the stream we are using for the copy.

**Review by crtrott — CHANGES_REQUESTED** [review]
Yeah lets abort.

**Review by dalg24 — APPROVED** [review]

**Review by crtrott — APPROVED** [review]

**Pull request merged**
