### PR TITLE
HIP: Use builtin atomic for compare_exchange

### PR DESCRIPTION
**Pull request by Rombur**
This PR reworks atomic_compare for the HIP backend. It uses the builtin functions in order to use the MemoryOrder. This simplifies the current code and aligns it with Compare_Exchange_GCC.hpp

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]
Please confirm that your PR is in sync with what we merged in desul

**Review by masterleinad — APPROVED** [review]

**Comment by Rombur** [comment]
> Please confirm that your PR is in sync with what we merged in desul

Yes

**Comment by ndellingwood** [comment]
Does this merit a changelog entry for 4.4?

**Comment by dalg24** [comment]
Done

**Pull request merged**
