### PR TITLE
Cherry-pick v3.7.02 changelog into develop

### PR DESCRIPTION
**Pull request by dalg24**
These are the changes from #6127, inserted between 3.7.01 and 4.0.00

### CODE REVIEW

**Comment by aprokop** [comment]
Likely a stupid question: why does this go into `develop` instead of `master`? Right now, the only way to get to the release notes is to go to the release page and click on the release commit. If you merge this PR into `develop`, this would be the state until you merge `develop` into `master`.

**Comment by masterleinad** [comment]
> Likely a stupid question: why does this go into `develop` instead of `master`? Right now, the only way to get to the release notes is to go to the release page and click on the release commit. If you merge this PR into `develop`, this would be the state until you merge `develop` into `master`.

`master` reflects the latest release which we consider to be 4.0.01 not 3.7.02. We will update `master` again for 4.1.00 and that will have the changelog including 3.7.02.

**Comment by aprokop** [comment]
> `master` reflects the latest release which we consider to be 4.0.01 not 3.7.02. We will update `master` again for 4.1.00 and that will have the changelog including 3.7.02.

That makes sense. But how would a user know where to get the release notes for 3.7.02?

**Comment by dalg24** [comment]
Either in the changelog distributed with the release or in `develop` which is the one single source of truth.

**Review by cz4rs — APPROVED** [review]

**Pull request merged**
