### PR TITLE
Drop constexpr C++11 workarounds

### LINKED ISSUE #4062: Get rid of KOKKOS_CONSTEXPR_14 macro
We require C++14 so there is no good reason to have it

https://github.com/kokkos/kokkos/blob/524a10e6f7ca38c832ba3317928f1d954ecc9f72/core/src/Kokkos_Macros.hpp#L525

NOTE: Make sure not to miss
https://github.com/kokkos/kokkos/blob/524a10e6f7ca38c832ba3317928f1d954ecc9f72/core/src/impl/Kokkos_EBO.hpp#L82-L94

### PR DESCRIPTION
**Pull request by dalg24**
Fix #4062 

NOTE: this PR drops the `KOKKOS_CONSTEXPR_14` macro

### CODE REVIEW

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Review by masterleinad — APPROVED** [review]
Looks good to me.

**Review by crtrott — CHANGES_REQUESTED** [review]
This is a public macro, at a minimum. I think we need to deprecate it instead of just removing it.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
