### PR TITLE
Bracket CUDA-Trilinos flags with ENABLE_CUDA

### PR DESCRIPTION
**Pull request by jjwilke**

### CODE REVIEW

**Comment by crtrott** [comment]
Guys we are done with the release branch what is this?

**Comment by jjwilke** [comment]
This ... is a gap in PR testing, apparently.

**Comment by jjwilke** [comment]
CUDA flags were getting added to Trilinos_CXX_FLAGS regardless of whether Kokkos_ENABLE_CUDA was on.

**Comment by crtrott** [comment]
Ok but now we need to hotfix this in trilinos?

**Comment by jjwilke** [comment]
Yeah, Nathan and I are on it.

**Comment by jjwilke** [comment]
Hotfix Trilinos. No more changes to this branch. PR to develop at PR #2714

**Pull request closed without merging**
