### PR TITLE
[3.5] Implement Kokkos::sort with execution space (#4490)

### PR DESCRIPTION
**Pull request by ndellingwood**
* Implement Kokkos::sort with execution space

* Use Kokkos::sort overloads with execution space in unit tests

* Use three-argument deep_copy in Kokkos_Sort

* Use execution_space instead of DefaultExecutionSpace

* Move fence() to versions not taking an execution space

* Use given execution space for view allocations

* Use default argument for create_permute_vector

* Use class execution_space

* Fence execution_space when using std::sort

(cherry picked from commit 72418c20bebc75db4e8cac19191ebc647397dd20)

 Conflicts:
	algorithms/src/Kokkos_Sort.hpp

### CODE REVIEW

**Comment by ndellingwood** [comment]
Cherry-pick of #4490 to master

**Comment by ndellingwood** [comment]
Cross-referencing #4526

**Review by masterleinad — COMMENTED** [review]
I think it's OK to cherry-pick the changes to `Kokkos::sort`. It shouldn't rely on anything merged in the meantime.
I don't have a strong opinion if it should be part of the release or not, though.

**Comment by crtrott** [comment]
retest this please

**Comment by masterleinad** [comment]
It should be safe to ignore the test failures here. The `icpc` CI checks are currently disabled on `develop` and `CUDA-9.2-NVCC` only fails for `default_exec.overlap_mdrange_policy`.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
