### PR TITLE
[3.7.02] Fixes Scratch allocation alignment issues

### LINKED ISSUE #4942: Cuda backend fails to allocate a single integer in the PerTeam scratch space.
```c++
#include <Kokkos_Core.hpp>

using ExecSpace = Kokkos::DefaultExecutionSpace;
using TeamPolicy = Kokkos::TeamPolicy<ExecSpace>;
using member_type = TeamPolicy::member_type;
using ScratchSpace = ExecSpace::scratch_memory_space;
using scratch_view_type =
    Kokkos::View<int*, ScratchSpace, Kokkos::MemoryTraits<Kokkos::Unmanaged>>;

int main(int argc, char** argv) {
    Kokkos::initialize(argc, argv);
    {
        TeamPolicy policy(1, 1);
        size_t scratch_size =  sizeof(int);
//        size_t scratch_size = scratch_view_type::shmem_size(1);

        Kokkos::parallel_for(
            policy.set_scratch_size(0, Kokkos::PerTeam(scratch_size)),
            KOKKOS_LAMBDA(const member_type& team) {
                scratch_view_type scratch_view(team.team_scratch(0),
                                               team.team_size());

                if (team.team_rank() == 0) {
                    scratch_view(0) = 1;
                }
            });
        Kokkos::fence();

    }
    Kokkos::finalize();

    return 0;
}
```

This fails with CUDA backend at runtime with illegal memory access errors. 
I need to either allocate 2 integers or use the `shmem_size` routine. 

I used cuda/11.2.1.

### PR DESCRIPTION
**Pull request by crtrott**
Cherry pick of #5687 with C++14 compatibility.

Fixes #4942

### CODE REVIEW

**Review by PhilMiller — APPROVED** [review]

**Review by fnrizzi — APPROVED** [review]

**Review by dalg24 — CHANGES_REQUESTED** [review]
Original PR hasn't been merged yet

**Comment by crtrott** [comment]
Retest this please.

**Comment by Rombur** [comment]
Retest this please

**Comment by masterleinad** [comment]
Retest this please.

**Comment by crtrott** [comment]
We are merging now and do manual testing

**Pull request merged**
