### PR TITLE
Call destructors in USMObjectMem

### PR DESCRIPTION
**Pull request by masterleinad**
This should fix #4254. I left the commits for that pull request here just to make sure that this is the case. If we want to merge this first, I am happy to remove them.

The problem #4254 revealed was that we placement new copy construct the functor we store in USMObjectMem (if we store in shared memory space) but never call the destructor. Making this work correctly is a bit cumbersome since the functor is expected to be executed asynchronously and can call the destructor once we know that it has finished. Thus, we need to register a deleted object and `std::unique_ptr` appears to be a natural choice. Unfortunately, we have to handle setting and resetting different deleted objects ourselves since we want to treat the object as a buffer and only allocate more space if necessary while the type we use the buffer for changes potentially with every kernel that is stored.

On top of these changes making sure that the destructor is eventually called, the test in #4254 requires that the destructor is called whenever we fence the corresponding execution space resp. its `sycl::queue`. We also discussed on Slack that this is the behavior we want.
This requirement implies that fencing in SYCL cannot just be restricted to the `sycl::queue` stored but might also affect other objects stored in an execution space instance, e.g. `USMObjectMem` members.
Hence, we need to store (pointers to) execution space instances instead of `sycl::queue` objects for the static fence. In the end, this allows unifying the call mechanism for the instance fence and the static fence. I decided to use an empty string in `SYCLInternal::fence()` to still distinguish between the two and to decide if another `Profiling` function must be called.

All these shenanigans can of course be avoided if we just always `memcpy` the functor but it seems that launch latency tests show that this would be significantly slower for large objects. In my opinion, there is independent value in this pull request and I would like to address the question about improving the launch mechanism/launch latencies somewhere else.

### CODE REVIEW

**Comment by nliber** [comment]
Just brainstorming here on `USMObjectMem`:

Like non-placement new, we have two operations:
Manage memory
Manage an object in that memory

Unlike non-placement new, those two operations may not be back-to-back.

It feels like we are trying to shoehorn this into `unique_ptr`, which is really only for doing that kind of management when the operations are back-to-back.  I'm not sure there is any place where `m_data` can go out of scope and it does the right thing (other than trivially doing nothing).

I wonder if we'd be better off with:

```
static void null_deleter(void*) {}
bool is_live() const { return m_deleter != null_deleter; }

void* m_data = nullptr;
void(*m_deleter)(void*) = null_deleter;
```
I think that can simplify the logic, as (I think) we are always calling the deleter explicitly anyway.  It also gives us a way to check if the object is live if we always use the same `null_deleter` function.

We should also remove `m_size`, as I don't believe we are using it anymore (it threw me off when I was trying to review the changes).

**Comment by masterleinad** [comment]
Yes, I thought about just having an extra deleter object but couldn't quite decide if that's better than a std::unique_ptr that stores both a pointer and a deleter. I agree that we always call the deleter ourselves so having them separate might make more sense.
I also agree with removing `m_size`.

In the end, I want to figure out (here or in a follow-up pull request) what we really want to do for launching kernels. There are some problems with #4097 that I don't think we can quickly resolve so we need to use `USMObjectMem` for some more time. I don't think that we need to carry this class around for any other purpose.
I also want to understand (preferably before the next release) why using `memcpy` looks so much worse than the placement new mechanism.

The `Blocks Promotion` tab here really only means that we should something about the missing destructor call. In the end, I would be fine to just use the `memcpy` approach for the release even if it is slower.

**Review by nliber — APPROVED** [review]

**Comment by masterleinad** [comment]
Superseded by #4273. I'd like to keep it open until we have decided which approach to use, though.

**Comment by dalg24** [comment]
> This should fix #4253.

Are you referring to #4251 ?

**Comment by masterleinad** [comment]
> Are you referring to #4251 ?

Ah, of course!

**Comment by masterleinad** [comment]
I mean it's more like #4254 fixes #4251 and this pull request or #4273 makes #4254 pass for `SYCL`.

**Pull request closed without merging**
