### PR TITLE
#5635: CUDA: Add Overloads for parallel_scan with return value for TeamThreadRange

### PR DESCRIPTION
**Pull request by thearusable**
Related to #5635 

~~Depends on https://github.com/kokkos/kokkos/pull/6090~~ (Merged already)

### CODE REVIEW

**Comment by fnrizzi** [comment]
please explicitly state this PR has a hard dependency on https://github.com/kokkos/kokkos/pull/6090 since that has to be merged first

**Comment by thearusable** [comment]
> please explicitly state this PR has a hard dependency on #6090 since that has to be merged first because it has the test in it.
> So this PR should only be merged _after_ the other one was merged.

I added links to dependent PRs. They are not technically hard dependent on each other because I copied the tests to each PR but indeed it would be better to merge them in particular order.

**Review by masterleinad — APPROVED** [review]

**Review by fnrizzi — APPROVED** [review]

**Comment by ajpowelsnl** [comment]
@thearusable - Does this PR need to be retested?  IOW, is the PR otherwise ready to be merged?

**Comment by cz4rs** [comment]
Freshly rebased and good to go. hpx failure is unrelated.

**Review by crtrott — APPROVED** [review]

**Pull request merged**
